mattermost/desktop

src/main.js
The UI feature to auto-hide the menu bar works on Linux as well as
Windows. Don't ignore it if the config value is set.
=> Allow hiding menu bar on Linux

src/main/menus/app.js
I noticed the default app menu on Mac was missing so I added it.
All Mac apps generally have this menu, allows to hide the app with the
default shortcut.
=> Add default Mac application menu

TESTING.md, docs/setup.md, src/browser/settings.jsx
Proposing changes to enable community testing of Mattermost Desktop app: 
- Adding documentation for Windows functionality 
- Adding guide for community members to help test releases
- Rename "menubar" to "Menu Bar" 
Based [on Android App Testing guide](https://github.com/mattermost/android/blob/master/TESTING.md). 
I'd propose if this PR is accepted to in future: 
- Open [Help Wanted] issues for community members to help test Windows 8 and Windows 10
- Document Mac functionality and testing guides, and post [Help Wanted] issues as well
- Decide which Linux platforms are supported and add documentation and testing guides
=> Release Testing Guide proposal

test/browser_test.js
In my guess, test executing is too fast for actual browser behavior at CircleCI.
So I added some waiting.
* `pause()` before `getUrl()`
* `pause()` when switching tabs
=> Stabilize tests

CONTRIBUTING.md, README.md, circle.yml, circle/make_draft.sh, docs/setup.md, gulpfile.js, package.json, src/browser/index.html, src/browser/index.jsx, src/main.js, src/package.json, test/browser_test.js
This PR rename the application at implementation.
* npm package name (package.json: name) is "mattermost-desktop"
* display name (package.json: productName) is "Mattermost"
As the result, configuration directory will be different from `electron-mattermost`. To take over the configuration, users have to copy `config.json`. When releasing the next version, we must announce this point.
=> Rename electron-mattermost to Mattermost at implementation

src/main.js, src/package.json
As per discussion in #56
Tested on Linux 64-bit (Ubuntu 15.10 to be precise).
Mattermost Desktop version 1.07, Mattermost server version 1.4 (with HTTP basic auth)
=> Add simpler httpBasicAuth implementation

docs/setup.md
Using "Extract All..." with the default options will extract the files to the Downloads folder. Many users will do exactly that and end up running Mattermost from there downloads folder. Not a good thing. These instructions tell users where to extract the files.
Perhaps in a future release these instructions can be reduced to run a batch script or installer.
=> Tell users where to place the application directory

src/browser/index.jsx, src/browser/js/badge.js
Like we do for tray icons.
As it's very confusing for windows users, why the trayicon can have a different colored dot, then the taskbar icon.
I also tried to mimic the black boarder around the dot.
One thing that's not matching is the color. Should I use the color you use in the taskbar dots or the material colors, like you used for the red before?
=> Use different colors for unread/mentioned in windows task bar. 

README.md, gulpfile.js, package.json, script/installer.js, src/main.js
Hey,
this might be totally wrong, as I'm a fist time node user. And so far I could only test win.
The installation of the exe seems to work fine, but there is no shortcut anywhere to be found. Uninstall also seems to work fine.
Would be very cool, if other people could build it for osx/linux and let the maintainer know if it works.
Cheers
=> Implement installers via electron-builder

src/browser/index.jsx, src/browser/js/badge.js
Looks like this for unread.
Couldn't test mentions, as I can't mention myself :/
=> Use a fitting border color for the taskbar badge status

src/browser/settings.jsx
The users can now edit their configured teams in settings window. I only tested it on windows. I also did changes on the UI for adding teams, because I think on this way it's much clearer how to add a team and how to edit a team. This related to #3.
`npm test`ran successfully except this `prettify`. I don't know if I got it right, but I called the command `npm run prettify`and I doesn't get an error there.
Cheers
=> Edit teams in settings window

gulpfile.js, package.json
As https://github.com/mattermost/desktop/pull/138#discussion_r63242703 has been fixed, we can reference the head version again.
=> Change package entry for electron-builder.

package.json
The icon seemed to be lost, at least when running it on windows just for dev purpose.
It might probably get injected by the build scripts, but not sure if that's good enough for us.
=> Bump prebuild to 1.2.2

src/browser/settings.jsx, src/main.js, src/package.json
Is this something you would accept as a PR? It's done via https://github.com/Teamwork/node-auto-launch which should work on all three platforms, I only tested windows so far.
However, this has one problem. if you uninstall the app, you will end up with the autostart entry abandoned. (at least on windows)
I wrote code, that should handle it, but it doesn't work and I don't see why.
=> Adds a setting to launch the app on system login

CHANGELOG.md, docs/setup.md, src/browser/settings.jsx, src/common/settings.js, src/main.js, src/main/menus/tray.js, test/specs/browser/settings_test.js
Added an option to hide the Window on minimize/close to the system tray.
if this option is enabled, a click on the system tray would also toggle the window.
This addresses #178 at least partially (just for Windows and OSX currently)
---
- Tested on Windows 10
- Tested on OS X 10.11.6 Beta
=> Hide window to system tray on minimize/close in Windows/OSX

CHANGELOG.md, docs/setup.md, src/browser/settings.jsx, src/main.js, src/main/menus/tray.js, test/specs/browser/settings_test.js
For Linux in #178.
- The feature can be enabled when the tray icon is enabled as similar to OS X.
- Some refactoring for related parts.
I hope that it's tested on all platforms to check degrading.
---
- Ubuntu 14.04/Unity installed libappindicator1
=> Add feature to hide window into system tray in Linux

src/main.js
As mentioned in pull request [#200](https://github.com/mattermost/desktop/pull/200#issuecomment-234721964) flashing the mattermost window only worked right now, when you have the systray icon enabled.
Since the setting (and also logically) the systray has nothing to do with the flashing window, this pull request now fixes this behavior, so that the window will flash as long as the setting is turned on (no matter what the systray setting is).
*PS: Sorry for the typo in the commit message, only saw it after I opened the pull request.*
---
- Archlinux x64
=> Flash Window also without systray icon

CHANGELOG.md, src/browser/index.jsx
Not sure if this is something we want, but I feel like we should speak the same language everywhere we try to let the user know, that he has unread messages.
Tested on Win10
=> Bold unread tabitem if there are unread messages

CHANGELOG.md, docs/setup.md, src/browser/index.jsx, src/browser/settings.jsx, src/common/settings.js, test/specs/browser/settings_test.js
Adds a new setting that shows the red dot indicatior on the task bar for unread messages when activated. Default is false.
We may want to check the wording I've choose, we might be able to come up with something better.
=> Make unread badge configurable

package.json, src/browser/index.jsx, src/package.json
Implements #176 by using the new setBadgeCount API in electron 1.2.6
---
- Ubuntu 16.04 running Unity
=> Ubuntu Unity counter badge

CHANGELOG.md, src/browser/index.jsx
This PR will add a cache invalidating page reload to each webview as a workaround.
Mattermost platform does not send an `Expires`/`Cache-Control` header, therefore the cache is not being re validated upon load in most cases.
If the cache is beeing invalidated depends on heuristics https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.2.2
In a browser session, the user is used to hit the reload button when something does not work. In the mattermost app, reload does not reload the embedded webviews.
I added a call to `webview.reloadIgnoringCache` right after the `did-start-loading` event is being fired to force the webview to re fetch the main page, as this results in a load cancel and therefore in a `did-fail-load` I extended the handler for that, so that no error is shown.
---
- …
=> Workaround: Invalidate cache of the main page on load

CHANGELOG.md, src/main.js, test/specs/app_test.js
- Operating system: Windows 10 64Bit
fixes issue #236
This fix may be problematic, if running multiple instances is required.
=> Force single app instance

CHANGELOG.md, docs/setup.md, src/browser/index.jsx, src/browser/webview/mattermost.js, src/main/menus/app.js
- Operating system: OS X 10.11.6
----
For #229. `Ctrl/CMD+F` puts cursor in the search box and fill `in:[channel_handle] ` to filter with current channel.
This is not related to operating system, so only need testers.
=> CTRL/CMD+F on Desktop app puts cursor in Mattermost search box filtered to channel

CHANGELOG.md, src/main/menus/tray.js
As spotted in #239 
Those accelerators are now gone from the tray menu
=> Remove accelerators from tray menu

.gitignore, CHANGELOG.md, docs/setup.md, src/main/menus/tray.js
Hello,
Here is a small change to allow settings from tray menu. It's really usefull when your using frameless window (coming in another PR) to gain space.
I've tested on Linux Mint 17.
Regards,
=> Add access to settings through tray menu

CHANGELOG.md, src/browser/index.jsx
- OS X 10.11.5
----
For #243.
This PR removes the notification when tabs failed to load the server (Please see #243). Then if the application is offline, the tab reloads automatically when the application becomes online.
=> Remove failed-to-load notification and reload the error tab on online event

CHANGELOG.md, package.json, src/browser/index.jsx
For #231.
`webview.focus()` was used to focus on the `<webview>`, but it's a DOM element function. So only the tag was focused in the host window, and its `webContents` was not focused. As the result, the shortcuts related to Mattermost UI didn't work in some cases.
Electron is upgraded to 1.2.8 because of `webContents.isFocused()`.
Windows 10 and OS X 10.11.6.
- Ctrl+F (provided by the app)
- Ctrl+K (provided by mattermost UI)
- After clicking application window.
- After clicking a tab.
=> Fix webview doesn't get focus correctly

src/browser/index.jsx
- Redid wording of error page
- Also redid the order of the items and did a little organization.
Just an idea how it could look, some graphics would also be nice. So please let's get some feedback, as I'm not really an ui guy.
=> Changed wording of error page

CHANGELOG.md, docs/setup.md, src/browser/index.jsx, src/main/menus/app.js
Tested environment: Windows 10 and OS X 10.11.6
Added two shortcuts to implement browser's back/forward features. And the menu items are located under **History** menu.
- `Alt+Left` (`Command+[` on OS X): Go back to previous web page in the current tab.
- `Alt+Right` (`Command+]` on OS X): Go forward to previous web page in the current tab.
The functionality is almost not related to OS, so I think we need a tester regardless of OS. Testable artifacts are available at https://circleci.com/gh/yuya-oc/desktop/2#artifacts
=> Add back/forward features for the current tab

CHANGELOG.md, src/browser/settings.jsx
For #181.
Tested on Windows 10. The appearance is below.
It's only for the appearance of html, so I think it's enough if we have one tester. Artifacts are available at https://circleci.com/gh/yuya-oc/desktop/7#artifacts
=> Add simple validation for Name and URL in the settings page

CHANGELOG.md, src/browser/index.jsx
---
- Ubuntu Linux
The problem we were hitting should have been resolved on the server side! No workaround needed anymore.
This reverts commit 58dfda760ea933d4708041c0dfe4b50de7b1ea21.
Revert "Fix error handler which showed an error on reload, as the cancel event was triggered after the cacheInvalidated property has been set to true"
This reverts commit 93263aea3a4160b7b0954f5e17e74dce5ba4b42d.
Revert "Workaround for bad cache handling in mattermost platform, fixes #212"
This reverts commit 61bf5344bfac076397a27503ee8153da5c9565fe.
=> Revert pull #219 "Workaround: Invalidate cache of the main page on load"

src/browser/settings.jsx
For #278.
In Bootstrap, when using `navbar-fixed-bottom` footer, the main content needs `padding-bottom`. It was missing in the PR, so [the issue](https://github.com/mattermost/desktop/pull/278#issuecomment-246703583) was found.
https://circleci.com/gh/yuya-oc/desktop/20#artifacts
=> Add missing padding-bottom in Settings UI

src/browser/settings.jsx, src/main.js, src/package.json
This should hopefully address #228
Untested so far, will grab the artifacts from ci, as soon as they are up and test those.
Let's hope https://github.com/Teamwork/node-auto-launch/issues/31 is solved.
=> Hide on autostart

package.json, src/main.js, src/package.json
For #287
To correctly show the application name in toast notifications on latest Windows 10, the shortcut which has "ApplicationUserModelID" is necessary. The application expected `com.squirrel.mattermost.Mattermost` due to electron-winstaller and Squirrel. But probably the package name of `package.json`, `mattermost-desktop` was used when creating the shortcut. Unfortunately I was not sure what was actually used, so I explicitly fixed the ID.
This might affect the internal name of .deb packages. It's not critical for now, but if the server provided .deb packages, they might conflict.
When testing this PR, please use installers. If the problem is not solved, please try uninstalling the existing app.
Tested on Windows 10 RS1
https://circleci.com/gh/yuya-oc/desktop/26#artifacts
=> Fix ApplicationUserModelID in the start menu shortcut

src/main/menus/app.js
- N/A
----
Proposed updates to menu bar:
- Change 'Help > Mattermost Docs' to 'Help > Learn More' and link to newly submitted desktop docs on docs.mattermost.com [to be merged within the next 48 hours]
- Change 'Settings' and 'Learn More' to include '...' as they open a new page. This is standard to other desktop apps
=> Updates to menu bar

src/browser/js/notification.js
In v3.4.0-rc1, clicking notification doesn't open the application. So I fixed the javascript error.
The code is also used in old versions, so probably this was caused by upgrading Electron.
Tested on Windows 10.
Testing:
1. Send a message from other users.
2. The app shows a desktop notification.
3. Click the notification.
4. The app comes back to front and switches to the applicable tab and channel.
https://circleci.com/gh/yuya-oc/desktop/45#artifacts
=> Fix Notification shim not working when clicking

CHANGELOG.md, docs/setup.md, src/main/menus/app.js
Due to #293
Need to revert when DM search works properly.
This just removed the menu, so just confirmation is enough.
=> Disable search in current team `CTRL+SHIFT+S`

src/main.js
So like we talked about, this makes sure the windows registry is kept up to date when upgrading versions.
Fixes/closes: https://github.com/mattermost/desktop/issues/291
=> Make sure our auto launch link is up do date

CHANGELOG.md, src/browser/index.jsx
For #314, Tested on macOS 10.12.
The issue was probably caused by #262. When a new messages is arrived, the PR try to update focus by `componentDidUpdate`. On macOS, somehow the function changes window order.
Possibly it's a bug of electron, but this is important for us. So I made this PR against to `release-3.4` branch to make v3.4.1.
**Test**
https://circleci.com/gh/yuya-oc/desktop/57#artifacts
For testing, we need regression for #262. Please follow [the test for #262](https://github.com/mattermost/desktop/pull/262#issuecomment-244218427).
> TEST 1:
> 
> 1) Have two windows open side-by-side: one for Desktop and another for text editor
> 2) Click on the text editor
> 3) Click on the webview of the Desktop app
> 4) Hit "CTRL+K"
> 
> Expected: Channel picker UI appears
> 5) Hit "CTRL+S"
> …
=> Fix the app window pops up second to foreground when a new message is received

CHANGELOG.md, src/package.json
This should fix the windows copy bug.
I haven't tested it yet, but if upstream/@jnugh did it's job right it should be fine ;)
=> Bump dependency to get rid of windows copy bug

package.json
I've tested this on windows and the installer seems to perform as expected. And I couldn't find anything wrong with the program itself.
We might want to use this changed/new feature for macOS https://github.com/electron-userland/electron-builder/releases/tag/v5.6.0
=> Bump electron builder

src/main.js
---
- OSX 10.12.1
On Mac, a download in desktop app defaulted to Macintosh HD instead of the download folder
=> Issue 302: Download desktop app download folder, instead of defaulting to Macintosh HD

src/browser/index.jsx, src/main/menus/app.js
This is a possible followup to https://github.com/mattermost/desktop/pull/187
The three zoom related menu items are now handled by electron itself.
=> Use default electron implementation for zoomin, zoomout and resetzoom

src/browser/settings.jsx, src/main.js
- Operating system: Linux, xubuntu 16.04.1 LTS (xfce 4.12)
This is a small PR to fix a couple of minor issues with the settings page on Linux.
- The option "Leave app running in notification area when the window is closed" was never enabled, even after restarting the app, because the check in `main.js` that sets `trayWasVisible` was not running.
- Additionally, one of the settings was wrongly named, referring to the "menu bar" when it should have said "notification area", so I've updated this too.
=> Fix linux tray settings

CHANGELOG.md, src/main/menus/app.js
Refers to https://github.com/mattermost/desktop/issues/301.
I haven't updated the `CHANGELOG.md` nor the `doc/*.md` as I saw the `CTRL+SHIFT+PLUS` shortcut isn't documented as well and is more here for user experience consistency.
---
- Ubuntu 16.04 LTS
=> Add CTRL+SHIFT+MINUS as a shortcut for zooming out

CHANGELOG.md, package.json, src/browser/index.jsx, test/specs/browser/settings_test.js
Allow mixed content does not use disableWebSecurity anymore.
We don't use a sledgehammer to crack a nut when this gets merged. Disabling security features is usually a bad idea - in this case we do not need to disable all security features to reach the goal.
As of electron 1.4.5 we can disable only certain security features as we need to.
This also fixes the youtube preview issue which was related to the disabled CORS security feature.
---
- Ubuntu 16.10 Unity
=> disableWebSecurity -> allowDisplayingInsecureContent

CHANGELOG.md
Changelog for 3.5 release
Notes;
- I'm not sure what `Suppressed verbose errors related to certificates` means
- I updated "OS X" references to "Mac". I know we discussed previously of potentially using "macOS" as well, but I didn't it very common for projects other than Electron. Definitely up for feedback though
=> release-3.5 changelog

src/browser/components/SettingsPage.jsx, src/common/settings.js
**Summary**
Fix that "Leave app running in notification area when application window is closed" was not working on macOS.
It seems that the issue was introduced in #371 by mistake.
Tested on macOS 10.12.
**Issue link**
#382 
**Test Cases**
Try to enable/disable the setting. And the behavior should be changed in accordance with the setting.
Artifacts: https://circleci.com/gh/yuya-oc/desktop/105#artifacts
The failed test case is not related to this change.
=> Fix "Leave app running in notification area" checkbox not working on macOS

package.json, resources/linux/README.md
**Summary**
Added a README file for linux. It's included at the top directory of extracted packages. And it focuses on quick instruction for first use.
**Issue link**
#376 
**Test Cases**
N/A
N/A
=> Add simple README for Linux packages

src/main.js
**Summary**
Fix the issue where the mouse cursor is randomly incorrect when DPI is higher than 100% on Windows.
It was introduced by upgrading Electron in #307.
**Issue link**
https://github.com/mattermost/desktop/pull/307#issuecomment-251397637
https://github.com/electron/electron/issues/7655
**Test Cases**
Set DPI higher than 100%, e.g. 150%, 175%. Then move mouse cursor across messages in a channel.
Background should not blink.
Artifacts: https://circleci.com/gh/yuya-oc/desktop/103#artifacts
=> Fix confused cursor in HiDPI

package.json
**Summary**
Electron 1.4.6 (1.4.0-1.4.11) has an issue where some HTTPS connection will start to fail after a certain date (January 14th, 2017 9:00 PM PST).
**Issue link**
http://electron.atom.io/blog/2016/12/09/certificate-transparency-fix
**Test Cases**
Set computer's clock and add https://symbeta.symantec.com/welcome/ as a team URL.
Artifacts: https://circleci.com/gh/yuya-oc/desktop/110#artifacts
=> Update Electron to 1.4.12 for Certificate Transparency Fix

src/browser/components/SettingsPage.jsx, src/main.js
**Summary**
This fixes a regression on the settings page that was introduced by upgrading react bootstrap (upgrading to the new form syntax).
On Linux the user can choose from a dark and a light theme for the tray icon. This setting was a select element which was transformed into a checkbox during react bootstrap upgrade.
The user was therefore not able to choose a different theme, when using the checkbox control a bool value was written to the config file which kept the app from opeining up on the next start.
This fix shows the dropdown again, allows to set sane values for the theme config and has a fallback when an invalid value has already been written to the config file - so that the application starts …
=> Linux tray icon theme settings regression fix

CHANGELOG.md, src/main.js
This fixes an issue where a window could be placed off screen which happend when the display it was previously on has been disconnected before launching the application.
> The application will always be placed on an existing screen.
https://github.com/mattermost/desktop/issues/378
**Test Cases**
* Have 2 monitors
* Place the app on one of them
* Close the app
* Start the app -> It should be exactly were it was when you closed it
* Close the app
* Disable the monitor
* Start the app -> It should be on your main screen
I do not check if the window fits onto the screen , so if you plug in another monitor with a smaller resolution the window might not fit the screen (which I actually didn't test, might as well be covered by …
=> Do not place windows off screen

CHANGELOG.md, docs/release-process.md
Updates for 
1) release process: Replace T-12 checklist with T-20, which incorporates a release date announcement to let contributors and users know about the upcoming release.
2) v3.5 changelog: List of people who provided bug reports benefiting the 3.5 release, [as noted in the v3.5-RC GitHub issue](https://github.com/mattermost/desktop/issues/375#issuecomment-264325604).
=> Updates for release process and v3.5 changelog

CHANGELOG.md, src/browser/webview/mattermost.js
**Summary**
Support unread indications in team sidebar of Mattermost server 3.6
**Issue link**
#409 
**Test Cases**
1. Create multiple teams in the same server.
2. Get messages in a team where you don't see.
Tested on Windows 10. This PR just changes a unread counting only, so the feature should work also on other platforms.
Currently teams are counted as "channels" on Windows.
This should be improved in future refactoring because internal parameters of the app would become very complicated.
=> Count unread teams in team sidebar

package.json, src/browser/components/DestructiveConfirmModal.jsx, src/browser/components/RemoveServerModal.jsx, src/browser/components/TeamList.jsx, test/specs/browser/settings_test.js, webpack.config.renderer.js
**Summary**
The part 5 of #400. This adds "Remove Server" modal.
**Issue link**
#400 
**Test Cases**
1. Open settings page.
2. Click "Remove" on a server list item.
3. The dialog should appear.
4. Close, Cancel, Remove buttons should perform as expected.
N/A
=> Add "Remove Server" modal

src/browser/components/SettingsPage.jsx
**Summary**
The part 1 of #400. 
- Some tweak of labels
- Remain settings page on clicking "x" button when there are no servers in config.
**Issue link**
#400 
**Test Cases**
1. Open settings page.
2. Click "x" on top right of UI.
3. If no servers are saved yet, the settings page remain open.
artifacts: https://circleci.com/gh/yuya-oc/desktop/142#artifacts
=> Tweak for part 1 of #400

docs/release-process.md
Shorten release process and move security updates to T+10, to follow updated Mattermost security process https://about.mattermost.com/security-updates/
=> Shorten release process and move security updates to T+10

CHANGELOG.md, src/browser/components/MainPage.jsx, src/browser/components/NewTeamModal.jsx, src/browser/components/SettingsPage.jsx, src/browser/components/TabBar.jsx, src/browser/components/TeamList.jsx, src/browser/config/AppConfig.js, src/browser/css/index.css, src/browser/index.jsx, src/browser/settings.html, src/main/menus/app.js, src/package.json, test/specs/browser/index_test.js, test/specs/browser/settings_test.js
**Summary**
Adds a button to the Tab Header which allows the user to add a new team without opening the settings page. Use the new Modal in the settings view as well.
**Issue link**
#400, #401 
**Test Cases**
Add a new server from the tab header and the settings page.
I added multiple specs that test if newly added teams are being persisted and if the modal behaves as expected in general.
I'm not sure if the way I do error handling is a good idea, I just saw that #400 defines an area where the error message should be displayed - I think that it's best to have the message next to the input that is incorrect but I could change it (might be a good idea to discuss).
=> Ux manage servers

src/browser/components/SettingsPage.jsx, test/specs/app_test.js, test/specs/browser/settings_test.js
**Summary**
The part 3 of #401.
Open "Add Server" modal...
- when openning the app without saved servers.
- when all servers are removed.
**Issue link**
#401 
**Test Cases**
a. Open the app when no servers are saved.
b. Remove all servers in settings page.
https://circleci.com/gh/yuya-oc/desktop/160#artifacts
=> Show "Add Server" modal when no servers exist in SettingsPage

src/browser/components/SettingsPage.jsx, src/browser/css/settings.css, src/browser/settings.html, src/common/settings.js, src/main.js, test/specs/browser/settings_test.js
**Summary**
Improve messages and options in "App Options" section.
Difference from #398 
- Display secure content only
- Help Text: Enabling allows only secure (HTTPS/SSL) content. Disabling allows the app to display non-secure (HTTP) content such as images.
- Icon theme
- Changed to radio buttons in order to make a little more consistent.
**Issue link**
#398 
**Test Cases**
1. Open the settings page.
2. Change desired options.
N/A
=> Improve messages and options in "App Options" section

src/browser/components/AutoSaveIndicator.jsx, src/browser/components/MainPage.jsx, src/browser/components/SettingsPage.jsx, src/browser/components/TeamList.jsx, src/browser/components/TeamListItem.jsx, src/browser/css/settings.css, src/browser/index.jsx, src/common/settings.js, src/package.json, test/specs/browser/settings_test.js
**Summary**
The part 2 of #400.
Proposal:
To prevent unexpectedly clicking "Edit" or "Remove", a clickable area is limited to server name and URL. (Red squares in the screenshot)
**Issue link**
#400
**Test Cases**
1. Open the settings page.
2. Click a server.
3. The page goes back to the main page and the corresponding tab is opened.
Limitation: Currently the changes in settings page would be lost when this feature performs. There is no way to know whether the changes are already saved.
=> Open the corresponding tab when a server is clicked in settings page

src/browser/components/SettingsPage.jsx
**Summary**
Fix an issue where server select menu was not working in settings page.
In v3.5.0, the behavior of #443 is expected because the config is not saved yet in the settings page.
Now the config is auto-saved, so I added an event listener for menu items.
**Issue link**
#443 
**Test Cases**
1. Open the settings page.
2. Select a server from the tray icon menu or "Window" menu items.
3. The selected server' tab should be shown in the main window.
https://circleci.com/gh/yuya-oc/desktop/167#artifacts
=> Fix an issue where server select menu was not working in settings page

src/browser/components/SettingsPage.jsx, test/specs/browser/settings_test.js
**Summary**
Update settings text for "Flash taskbar icon when..." to "Flash app window and taskbar icon when a new message is received", as the latter is the actual behaviour of the setting.
**Issue link**
https://github.com/mattermost/desktop/issues/447
**Test Cases**
1. Go to File > Settings
2. Confirm the settings text reads `Flash app window and taskbar icon when a new message is received`
3. Confirm the help text reads `If enabled, app window and taskbar icon flashes for a few seconds when a new message is received.`
=> Update settings text for "Flash taskbar icon when..."

src/browser/components/SettingsPage.jsx
**Summary**
On macOS, "Dock" is the correct word.
**Issue link**
N/A
**Test Cases**
1. Open settings page.
2. Check sentences.
https://circleci.com/gh/yuya-oc/desktop/170#artifacts
=> Use "Dock" instead of "taskbar" on macOS

CHANGELOG.md, src/main.js
**Summary**
Set focus to the next top-level window when the main window has been closed.
**Issue link**
#430, #431 
**Test Cases**
#430 
1. Open Mattermost and another application window.
2. Activate Mattermost window.
3. Close Mattermost window.
4. Another window should get focus.
#431 
1. Open Mattermost and another application window.
2. Activate Mattermost window.
3. Close Mattermost.
4. Show the classic Alt+Tab switcher. (See #431)
5. Mattermost should not appear on the switcher.
Testable apps: https://circleci.com/gh/yuya-oc/desktop/187#artifacts
=> Set focus to the next top-level window when close the main window

CHANGELOG.md, src/browser/components/SettingsPage.jsx, test/specs/browser/settings_test.js
**Summary**
Fix an issue where the setting was not saved when changing tray icon theme.
**Issue link**
#456 
**Test Cases**
The test is automated.
1. Start the application.
2. Open settings page.
3. Change tray icon theme.
4. "Saving..." indicator should appear and the selected theme should be written into `config.json`.
Artifacts: https://circleci.com/gh/yuya-oc/desktop/190#artifacts
=> Fix the setting not saved when changing tray icon theme

CHANGELOG.md, src/browser/components/MainPage.jsx, src/browser/components/MattermostView.jsx, src/browser/components/SettingsPage.jsx, src/browser/index.jsx, src/common/settings.js, test/specs/browser/settings_test.js
**Summary**
Remove "Display secure content only" option.
allowDisplayingInsecureContent is removed in Electron 1.6 https://github.com/electron/electron/commit/2e0780308c7ef2258422efd34c968091d7cd5b65. 
And it's no longer necessary to show http contents in https server.
**Issue link**
N/A
**Test Cases**
1. Post a HTTP link or an embedded image (`![image](URL)`) in a channel provided by HTTPS.
2. The image should appear.
Tested on Windows 10 and macOS 10.12.3.
https://circleci.com/gh/yuya-oc/desktop/192#artifacts
=> Remove "Display secure content only" option

src/browser/components/MainPage.jsx, src/browser/components/TabBar.jsx, src/browser/css/index.css
**Summary**
Reduce tab bar height.
It seems that Chrome's tabs have about 28px of height at 100% of scaling.
But 28px looked a little narrow for me. So I used 32px. It always becomes an integer on monitor at all scaling.
- 100% -> 32 dots on monitor
- 125% -> 40 dots on monitor
- 150% -> 48 dots on monitor
**Issue link**
#462 
**Test Cases**
1. Add two servers at least to show the tab bar.
2. Get unread mention to show badges.
Please also check that webapp doesn't looks blurry.
https://circleci.com/gh/yuya-oc/desktop/196#artifacts
=> Reduce tab bar height

CHANGELOG.md, package.json
**Summary**
Fix Quick Look not closing in file upload dialog.
https://github.com/electron/electron/releases/tag/v1.6.2
But still there is a problem where the app craches when the dialog is canceled without closing Quick Look.
**Issue link**
#498 
**Test Cases**
1. Open file upload dialog
2. Use Quick Look to preview a file.
3. Quick Look can be closed via close button or space bar.
https://circleci.com/gh/yuya-oc/desktop/213#artifacts
=> Fix Quick Look not closing in file upload dialog

src/browser/components/ErrorView.jsx, src/browser/components/MainPage.jsx, src/browser/components/MattermostView.jsx, src/browser/css/components/ErrorView.css, src/browser/css/components/MattermostView.css, src/browser/css/index.css, test/specs/browser/index_test.js
**Summary**
Hide webview with the recommended approach.
https://electron.atom.io/docs/api/webview-tag/#css-styling-notes
This fixes the possible issue found in https://github.com/mattermost/desktop/pull/495#issuecomment-289947772 . I met this on Mac.
**Issue link**
#495 
**Test Cases**
1. Add 2 servers to the app.
2. Start the app.
3. All tabs should be loaded correctly.
https://circleci.com/gh/yuya-oc/desktop/216#artifacts
=> Improve hidden webview

src/main.js, src/main/mainWindow.js
Add display-metrics-changed handler to place window on screen when metrics change while the application is running.
**Summary**
I added a listener for `display-metrics-changed` to handle changes while the app is running.
However the event doe snot fire on my OS so I'm not able to test this (+ I can't reproduce the bug on Linux so there is actually no bug to fix in my case).
However this might fix #471 if it works correctly...
**Test Cases**
See #471, place window on a dedicated monitor, remove that monitor. Hope the event fires and the window is moved to an existing screen.
Not really tested, event does not fire on my OS. I hope it does on Window...
=> Add display-metrics-changed handler to place window on screen

CHANGELOG.md, src/browser/components/MattermostView.jsx, src/main.js, src/main/downloadURL.js
**Summary**
Don't show an extra window when clicking a public link for uploaded files.
When clicked link is a public link (`/api/v[34]/public/files`), open a save file dialog.
**Issue link**
#390
**Test Cases**
1. Post a public link for an uploaded file.
2. Click the link.
3. Only save file dialog should appear.
4. The file should be saved correcty.
https://circleci.com/gh/yuya-oc/desktop/234#artifacts
=> Don't show an extra window when clicking public file link

CHANGELOG.md
**Summary**
Update CHANGELOG.md for 3.7
=> Update CHANGELOG.md for 3.7

src/browser/webview/mattermost.js, src/main.js, src/main/SpellChecker.js
**Summary**
Reset misspelled state after changing spelling language.
**Issue link**
#524 
**Test Cases**
See #524. After the step 7, the highlight should be updated a moment later.
https://circleci.com/gh/yuya-oc/desktop/241#artifacts
=> Reset misspelled state after changing spelling language

src/common/settings.js, src/main.js, test/specs/browser/settings_test.js
**Summary**
Enable spellchecker as default setting.
The language should be determined by user's locale. If it's not available in spellchecker, English is used.
**Issue link**
#527 
**Test Cases**
A. First installation.
1. Exit from the app.
2. Rename `config.json` to backup.
3. Start the app.
4. Spellchecker should be enabled as default setting.
B. Upgrading
1. Exit from the app.
2. Remove `useSpellChecker` and `spellCheckerLocale` entries from `config.json`.
3. Start the app.
4. Spellchecker should be enabled.
https://circleci.com/gh/yuya-oc/desktop/244#artifacts
=> Enable spellchecker as default setting

src/browser/components/MainPage.jsx, src/browser/components/TabBar.jsx, src/browser/css/components/TabBar.css, test/specs/browser/index_test.js
**Summary**
Fix alignment for 'Add new server' button. (+)
v3.7.0 on Mac:
PR on Mac:
It looks `Button` component makes the alignment difficult. So I stopped using `Button`. And '+' is a plain text font, so I think it's difficult to layout at "complete center".
Please see the actual alignment.
**Issue link**
https://github.com/mattermost/desktop/pull/540#issuecomment-303734982
**Test Cases**
1. Add two servers at least.
2. Open the main page.
3. See tab bar.
4. The '+' button should work as expected.
https://circleci.com/gh/yuya-oc/desktop/264#artifacts
=> Fix alignment for 'Add new server' button

CHANGELOG.md, package.json, src/main.js
**Summary**
Update Electron to v1.6.10. This is the prior work for #525.
Electron 1.6.7 supports following features for Windows. So this PR should test them.
- Desktop notification for Windows 7
- Per-monior DPI awareness
**Issue link**
#67, #357
**Test Cases**
Notification:
1. Prepare Windows 7, 8 or 8.1
2. Receive any message.
3. Notification should appear instead of a tray balloon.
4. Click the notification.
5. The message should appear in the main window as well as Windows 10.
Per-monitor DPI:
1. Prepare Windows 8.1 or 10
2. Connect two monitors and set different DPI scaling.
3. Move the window across monitors.
4. The window should be rendered in proper DPI. …
=> Update Electron to 1.6.10

CHANGELOG.md, src/browser/components/MainPage.jsx, src/main/mainWindow.js
**Summary**
Keep focus when closing file upload dialog on macOS.
This requires Electron 1.6.8 which is still beta.
**Issue link**
#341 
**Test Cases**
On Mac:
1. Upload file using CMD or CTRL + U
2. Choose file with keyboard + hit enter to select
3. Hit enter to send the message
https://circleci.com/gh/yuya-oc/desktop/240#artifacts
=> Use sheet-end event to handle focus when closing macOS file upload dialog

CHANGELOG.md, src/main/mainWindow.js
Blur webview when the main window loses its focus.
**Summary**
Fix desktop notifications not working when the window is minimized from inactive state.
Explicitly blur webview when the window loses focus. Tested on Windows 10 and server v3.8.
**Issue link**
#522 
**Test Cases**
1. Select any channel for this test (We call it "channel A" for simplicity)
2. Make the app window inactive (ex. by clicking on the other window)
3. Click on the "minimize" button on the title bar of Mattermost window.
4. Send a message to the channel A from the other account.
5. Desktop notifications should appear.
https://circleci.com/gh/yuya-oc/desktop/271#artifacts
=> Fix desktop notifications not working when the window is minimized from inactive state

CHANGELOG.md, src/browser/components/SettingsPage.jsx, test/specs/browser/settings_test.js
**Summary**
Fix close button not working when the number of servers is not zero when it's started from initial config.
**Issue link**
#552 
**Test Cases**
Tested on macOS.
1. Remove `config.json` (please make backup before testing)
2. Launch the app.
3. Add a server to the list in Settings page.
4. Confirm that "X" in top right corner works.
https://circleci.com/gh/yuya-oc/desktop/276#artifacts
=> Fix close button not working when the number of servers is not zero

CHANGELOG.md, LICENSE.txt, package.json, src/package.json
**Summary**
Fix the app publisher was not changed to Mattermost, Inc.
**Issue link**
#542 
**Test Cases**
- Windows:
After installation, open "Apps and Features".
- Mac:
Open "About Mattermost" in the menu bar.
- Linux:
Open deb packages with GDebi Package Installer.
https://circleci.com/gh/yuya-oc/desktop/278#artifacts
=> Change the app publisher to Mattermost, Inc.

.eslintrc.json, CHANGELOG.md, src/main.js, src/main/squirrelStartup.js
**Summary**
Fix Windows uninstaller not removing files correctly
Multiple async tasks were not performed completely when running uninstaller.
So rearranged tasks with sequential order.
i.e. take care startup registry, finally call electron-squirrel-startup.
**Issue link**
#551 
**Test Cases**
1. Install the app with the installer.
2. Enable "Start app on login" option.
3. Uninstall the app.
4. Files under `C:\Users\%USERNAME%\AppData\Local\mattermost` should be removed excepting `.dead` and `Update.exe`.
5. Registry key `\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run\Mattermost` should be removed.
https://circleci.com/gh/yuya-oc/desktop/280#artifacts/containers
=> Fix Windows uninstaller not removing files correctly

CHANGELOG.md, src/browser/webview/mattermost.js
**Summary**
Change the way to take intervals when counting unread channels/mention.
Possible fix for related issues. Unread counter is updated by the function invoked by `setInterval()`. But this function doesn't take care whether the invoked function finished. When the app is minimized, internal Chrome reduces performance by itself. So I think possibly the function might not be able to finish by the next interval.
Eventually we should also improve the function performance though, I use `setTimeout()` instead in order to take proper intervals first.
@jasonblais I haven't met the freezing issue. Would you try the artifact for a few days?
**Issue link**
#494 #520
**Test Cases**
1. Open desired servers.
2. Get …
=> Use setTimeout instead of setInterval to get unread count

CHANGELOG.md, src/main/mainWindow.js
**Summary**
Fix --hidden not working on Linux.
I'm not sure why the problem happens though, it seems that the problem happens by calling `BrowserWindow.loadURL()` after `BrowserWindow.minimize()`. So I changed the order of functions.
Tested on Ubuntu 16.04. To make sure, we need to check about Windows as well.
**Issue link**
#570 
**Test Cases**
1. Enable "Start app on login".
2. Logout from the computer, then login again.
3. Started app should be minimized.
https://circleci.com/gh/mattermost/desktop/985#artifacts
=> Fix --hidden not working on Linux

CHANGELOG.md, src/browser/components/MattermostView.jsx
**Summary**
Fix an extra reloading when an error page is manually reloaded.
This PR cancels the automated reloading when an error page is manually reloaded by `Ctrl+R`.
**Issue link**
#573 
**Test Cases**
1. Unplug ethernet cable or disable Wi-Fi to get error page.
2. Start the application.
3. Make sure that the error is NOT `ERR_INTERNET_DISCONNECTED (-106)`.
4. Repair internet connection then press `Ctrl+R`.
5. Extra reloading should not happen within 30 seconds.
https://circleci.com/gh/yuya-oc/desktop/327#artifacts
=> Fix an extra reloading when an error page is manually reloaded

package.json, src/main.js
**Summary**
Upgrade Electron for security fix of HTTPS.
https://github.com/electron/electron/releases/tag/v1.6.11
This should include #543 to upgrade Electron from 1.6.2 to 1.6.11.
- Desktop notification for Windows 7/8
- Per-monior DPI awareness
**Issue link**
#543
**Test Cases**
Notification:
1. Prepare Windows 7, 8 or 8.1
2. Receive any message.
3. Notification should appear instead of a tray balloon.
4. Click the notification.
5. The message should appear in the main window as well as Windows 10.
Per-monitor DPI:
- Not necessary because already tested at #543.
https://circleci.com/gh/yuya-oc/desktop/332#artifacts
=> Upgrade Electron dependancy

electron-builder.json
To be able to customize icons, they can not be remote. Adding `file://` to the beginning of the relative path will make it work locally.
"iconUrl": "file://resources/icon.ico"
**Test Cases**
Replace `resources/icon.ico` file
Run `npm run package:windows` and make sure it runs properly and generates the files with the correct icon.
=> BASH-10 add local icon reference for squirrel

.gitignore
This PR adds the following folders and files to gitignore:
build/
dist/
package-lock.json
src/package-lock.json
=> BASH-21 Add build files and npm files to gitignore

scripts/manipulate_windows_zip.js
Use value for `productName` from `package.json` inside of the `scripts/manipulate_windows_zip.js` script not to have the hardcoded `mattermost` value.
**Test Cases**
Change `productName` in `package.json`
Run `npm run package:windows` and make sure it runs properly and generates the files with the proper name.
=> BASH-7 make dynamic zip scripts

src/browser/components/SettingsPage.jsx, src/browser/settings.jsx, src/main/squirrelStartup.js
This PR changes all hardcoded product name references to use the productName from the package.json file.
=> BASH-19 Remove hardcoded product name references

package.json
Adds a simple rm command to npm to remove all dynamically generated files to make it easy to reset between builds/branches
**Test Cases**
Run `npm run clean`
=> BASH-23 Add npm clean script

CHANGELOG.md, src/browser/components/SettingsPage.jsx, src/browser/components/TeamList.jsx, src/browser/components/TeamListItem.jsx
Closes #446 
**Summary**
After closing the modal the focus of the clicked link will be removed
**Issue link**
#446
=> Remove focus after cancelling modal

src/common/config/base.json, src/main/menus/app.js
This PR changes the behavior of the Help menu Learn More item to open the link that is defined for the helpLink property in the base.json file (src/common/config/base.json). This property can be overridden by defining the helpLink property in the override.json file (src/common/config/override.json). 
**Test Cases**
Add override values like this:
```json 
// Exampleoverride.js
{
"1": {
"helpLink": “http://test.helplink.com”
}
}
```
**Notes**
includes BASH-20
=> BASH-11 Open help link from config

src/main.js, src/main/mainWindow.js, src/main/menus/app.js
Closes #512
**Summary**
[Mac] Adds `Ctrl+Tab` and `Ctrl+Shift+Tab` keyboard shortcuts as an alternative to `Alt+Cmd+Right` and `Alt+Cmd+Left` to switch between servers.
**Issue link**
#512
=> Add Ctrl(+Shift)+Tab as alternative to switch between servers

src/common/settings.js, src/main.js
This PR allows for a defaultTeam to be defined in the override.json file (src/common/config/override.json). When this value is defined and the config file does not contain any teams in the team’s array, the team defined in the defaultTeam property will be added to the team's array in the config.
**Test Cases**
Add override values like this:
```json 
// Exampleoverride.js
{
"1": {
"defaultTeam": {
“name”: “Test Team”,
“url”: “https://test.team.com” 
}
}
}
```
Remove the application support folder by running rm -rf /Users/{yourusername}/Library/Application Support/Mattermost
When the application starts the login for the defaultTeam will be shown.
**notes**
includes bash-20
=> BASH-14 Set default server/team in settings

src/common/deepmerge.js, src/common/settings.js, test/modules/environment.js, test/specs/settings_test.js
**Summary**
Fix an issue where the combination of deepmerge and webpack breaks tests.
In #586, I had found that the combination of deepmerge and webpack makes a wrong state when requiring. Due to the problem, the application raised the error only in `npm test`. It's the reason why recently CircleCI is failing.
Unfortunately, I could not notice the behavior because #188 hides the error and doesn't quit the application. I will prepare another PR to quit the application when `uncaughtException` and other critical errors have been occurred.
**Issue link**
#586 #188
**Test Cases**
Execute `npm test` (done in CI)
https://circleci.com/gh/yuya-oc/desktop/429
=> Fix an issue where the combination of deepmerge and webpack breaks tests

CHANGELOG.md, src/browser/components/MainPage.jsx, src/main/mainWindow.js
**Summary**
Keep MainWindow's zoom level to zero excepting webview.
This PR makes a workaround for #334. The problem is that the main window and webview tags have zoom level on their own. The issue happens the main window has modified zoom level. A workaround is below.
- Always reset zoom level when launching the app.
- Keep focus on webview tags when clicking tab bar area.
**Issue link**
#334 
**Test Cases**
1. Click the tab bar area where there are no buttons.
2. Use `Ctrl+Plus` or `Ctrl+Minus` to change zoom level.
3. Make sure that #334 doesn't happen.
https://circleci.com/gh/yuya-oc/desktop/454#artifacts
=> Keep MainWindow's zoom level to zero excepting webview

CHANGELOG.md, src/main.js, src/main/CriticalErrorHandler.js
**Summary**
When an uncaught error occurred, the error log is saved to `AppData\Roaming\Mattermost\uncaughtException-*.txt`. Then a dialog would pop up to notice it.
When the user click "Show detail", the file is opened in the default text editor.
```sample.txt
Application: Mattermost 3.7.1
Platform: Windows_NT 10.0.15063 x64
Error: test error
at Timeout.setTimeout [as _onTimeout] (C:\Users\yuya-oc\git\mattermost-desktop\src\main_bundle.js:7781:11)
at ontimeout (timers.js:386:14)
at tryOnTimeout (timers.js:250:5)
at Timer.listOnTimeout (timers.js:214:5)
```
Usually the error is unrecoverable, so the application should finish soon.
https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_co …
=> Show uncaughtException as an internal error and quit the app

src/browser/components/MainPage.jsx, src/browser/components/SettingsPage.jsx, src/browser/components/TabBar.jsx, src/browser/index.jsx, src/common/config/base.json, src/main/menus/app.js
This PR add values `enableMultiTeams` and `enableServerManagement` to show/hide server management and multiteam settings.
**Test Cases**
Add override values like this to override.json (src/common/config/override.json)
After entering the a fist server no others are accepted
```json 
//override.js
{
"1": {
"enableMultiTeams": false,
"enableServerManagement": false
}
}
```
**Notes**
Includes bash-20
=> BASH-18 Add configs to show/hide server management and multiteam settings

src/browser/components/MainPage.jsx, src/browser/components/PermissionRequestDialog.jsx, src/browser/components/TabBar.jsx, src/browser/css/components/PermissionRequestDialog.css, src/browser/css/components/TabBar.css, src/browser/css/components/index.css, src/browser/index.jsx, src/main.js, src/main/permissionRequestHandler.js, test/modules/environment.js, test/specs/permisson_test.js
**Summary**
Use `session.setPermissionRequestHandler()` to confirm permissions when they're requested.
Results of the dialog are saved to `AppData\Roaming\Mattermost\permissions.json`.
This implementation is naive. The dialog pause the application until selecting a choice.
**Issue link**
https://mattermost.atlassian.net/browse/PLT-7458
**Test Cases**
1. Receive any messages in a channel.
2. A dialog should appear to confirm Allow/Deny/Skip the 'notifications' permission.
3. A desktop notification should appear after clicking 'Allow'.
https://circleci.com/gh/yuya-oc/desktop/411#artifacts
=> Dialog to confirm requested permissions

src/browser/components/MainPage.jsx, src/browser/css/components/MainPage.css, src/browser/css/components/TabBar.css
**Summary**
Add PermissionRequestDialog for when the app doesn't show the TabBar.
This is quick fix for #644.
**Issue link**
#644 
**Test Cases**
See #644. The dialog should appear even when the app shows one server.
https://circleci.com/gh/yuya-oc/desktop/493#artifacts
=> Add PermissionRequestDialog for when the app doesn't show the TabBar

src/main.js
**Summary**
Ignore "gpu-process-crashed" event then output the log to console.
This PR changes `throw new Error()` to `console.log`. So the user will not see the event.
As investigated in #646, it doesn't affect the app.
**Issue link**
#646
**Test Cases**
a. Use the app. The app should not crash with the error of GPU process.
b. Kill the GPU process with Process Explorer.
https://circleci.com/gh/yuya-oc/desktop/494#artifacts
=> Ignore "gpu-process-crashed" event then output the log to console

CHANGELOG.md, src/browser/components/SettingsPage.jsx, src/common/config/defaultPreferences.js, src/common/settings.js, src/main.js
Closes #514
**Summary**
With this feature it is be possible to enable the bouncing icon for Mac when receiving a new message. 
**Issue link**
#514
=> Implement Mac bounce feature

README.md, TESTING.md, resources/linux/README.md, src/common/config/buildConfig.js
Instead of hard-coding the help link to https://docs.mattermost.com/help/apps/desktop-guide.html, added a redirect from https://about.mattermost.com/default-desktop-app-documentation/.
This is so that if the help documentation moves, we can just update the redirect at .com page, instead of making a change in the product.
Note: https://about.mattermost.com/default-desktop-app-documentation/ gives a 404 error until the marketing team pushes the change. Should be in the next couple of days.
=> Replace hard-coded doc link with a redirect

src/browser/components/PermissionRequestDialog.jsx, src/browser/components/TabBar.jsx, src/browser/css/components/TabBar.css
**Summary**
Fix lag to show/hide permission dialog.
If the LHS has unread channels, the dialog doesn't correctly appear/hide due to complicated rendering function of TabBar.jsx. Now some `if` statements are removed, so the TabBar correctly render the dialog in any cases.
By the way, I feel `notifications` should be allowed as default. Users might not notice the dialog until they open the tab.
**Issue link**
#643
**Test Cases**
1. Remove `AppData\Roaming\Mattermost\permisson.json`
2. Start the app.
3. Receive new messages or WebRTC concall
https://circleci.com/gh/yuya-oc/desktop/499#artifacts
=> Fix permission dialog lag

src/browser/webview/mattermost.js
https://stackoverflow.com/questions/47203183/missing-data-reactroot-attirbute-in-react-16
**Summary**
In React 16, `data-reactroot` attribute is no longer used. So the desktop app can't know whether a webapp is initialized.
So I added a query selector to detect React app from DOM.
**Issue link**
N/A
**Test Cases**
1. Start the app to show the latest mattermost server (https://pre-release.mattermost.com).
2. The loading icon should disappear within 30 seconds.
https://circleci.com/gh/yuya-oc/desktop/508#artifacts
=> Support React 16 of webapp for loading icon

src/main.js, src/main/PermissionManager.js, src/main/permissionRequestHandler.js, src/utils/util.js, test/specs/permisson_test.js
**Summary**
Show permissions dialog only for untrusted origins.
"Trusted" means that a origin is one of URLs which are saved at `config.json` or `buildConfig.js`.
**Issue link**
#659 
**Test Cases**
1. Remove `AppData\Roaming\Mattermost\permissions.json`.
2. Start the app.
3. The dialog should not appear when receiving new messages or webrtc concall.
https://circleci.com/gh/yuya-oc/desktop/522#artifacts
=> Show permissions dialog only for untrusted origins

src/common/JsonFileManager.js, src/main.js, src/main/AppStateManager.js
**Summary**
Fix cache-purging not working.
I rewrote version detection with AppStateManager class which will be introduced by #582 
The temporary parameter, `lastAppVersion` is stored at `app-state.json` separately from `config.json`.
**Issue link**
N/A
**Test Cases**
1. Quit the app.
2. Create `AppData\Roaming\Mattermost\app-state.json` with following content.
```json
{"lastAppVersion": "9.9.9"}
```
3. Open `AppData\Roaming\Mattermost\Cache` in Explorer.
4. Cache files should be temporarily removed when launching the app next time.
5. If `lastAppVersion` equals to the app version (3.7.1 in this PR), cache files should NOT be removed. …
=> Fix cache-purging not working

src/browser/components/SettingsPage.jsx
**Summary**
Tweak setting help text for Dock icon bounce setting
**Issue link**
https://github.com/mattermost/desktop/issues/677
=> Tweak setting help text for Dock icon bounce setting

electron-builder.json
**Summary**
Locate NOTICE.txt and LICENSE.txt under Content/Resources on Mac.
Please see https://github.com/mattermost/desktop/issues/681#issuecomment-358647921 for detail.
**Issue link**
#681 
**Test Cases**
1. Download .zip or .tar.gz package.
2. NOTICE.txt and LICENSE.txt should be located under:
- Windows, Linux: Top level directory of extracted directory. (Same as before)
- Mac: `Mattermost.app/Content/Resources`
https://circleci.com/gh/yuya-oc/desktop/540#artifacts
=> Locate NOTICE.txt and LICENSE.txt under Content/Resources on Mac

src/browser/components/MattermostView.jsx, src/main.js
**Summary**
Fix deep linking not working when the app is not already opened.
On macOS, deep linking is implemented with `open-url` event. When the app is launched by URL scheme, the event is emitted before `ready` event. In this case, the main windows is not created yet. So there was null reference error and the app was not able to start correctly.
**Issue link**
#678 
**Test Cases**
1. Register 2 servers to the app. https://pre-release.mattermost.com must be the second server.
2. Quit the app.
3. Open mattermost://pre-release.mattermost.com/core/channels/developers in your web browser.
4. App should be launched then the Developers channel of pre-release should be opened. …
=> Fix deep linking not working when the app is not already opened

src/browser/components/MattermostView.jsx
**Summary**
Fixed an issue where clicking on a file:// protocol path does not open windows explorer since version 3.5.0.
**Issue link**
https://github.com/mattermost/desktop/issues/579
**Test Cases**
1. Post a "file://..." path to a channel. (e.g. file://\\\\ComputerName\ShaedFolder)
2. Click on that link.
-> Windows explorer opens.
Tested only on Windows 7 and 10.
Not tested on Linux and Mac. I am not familiar with folder sharing on those operating systems.
=> Fixed an issue where clicking on a file:// protocol path does not open windows explorer since version 3.5.0. #579

src/main.js, test/modules/environment.js, test/specs/browser/settings_test.js
**Summary**
Fix app crashed after toggling tray icon setting.
**Issue link**
#706
**Test Cases**
See #706.
- Go to the Settings page via CMD+COMMA
- Enable "Show Mattermost icon in menu bar" setting. Then disable it.
On Linux, changing theme also made crashes.
https://circleci.com/gh/yuya-oc/desktop/620#artifacts
=> Fix app crached after toggling tray icon settings on Mac and Linux

src/browser/components/MattermostView.jsx
**Summary**
Modal window title is not white-labeled based on app name. It displays when clicking the `Download apps` or `help` links.
=> Whitelabel: Downloads link opens in Mattermost branded window.

src/common/config/defaultPreferences.js, src/common/settings.js, src/main.js, test/specs/spellchecker_test.js
**Summary**
Fix correct spellchecker locale is not selected for non en-US locales.
While launching the app, `app.getLocale()` can't return correct locale until `ready` event is emitted. So default `en-US` was chosen.
In this fix, `defaultPreferences.js` would lose `spellCheckerLocale` parameter because it should be determined by user's system locale.
Tested on macOS 10.12.
**Issue link**
#632
**Test Cases**
Before testing, change computer's locale to non en-US locale such as `de-DE` (Germany).
1. Make sure `config.json` is removed before launching the app.
2. Start the app.
3. The app should use correct locale for spellchecker.
4. `config.json` should have `spellCheckerLocale` parameter with correct locale. …
=> Fix correct spellchecker locale is not selected for non en-US locales

src/browser/components/SettingsPage.jsx, src/common/config/defaultPreferences.js, src/main.js, test/specs/browser/settings_test.js
**Summary**
Add "Enable GPU hardware acceleration" option.
It's enabled by default.
**Issue link**
#713
**Test Cases**
- `config.json` (covered by CI)
-  `enableHardwareAcceleration` key is saved when clicking the option in the settings page.
- Actual process
1. Set `Enable GPU hardware acceleration` to disabled.
2. Restart the app.
3. Check running mattermost-desktop processes.
4. Processes which have an argument `--type=gpu-process` should not exist.
https://circleci.com/gh/yuya-oc/desktop/696#artifacts
=>  Add "Enable GPU hardware acceleration" option

src/browser/components/MattermostView.jsx
**Summary**
Ignore did-fail-load event when trying to use U2F devices.
The guest page should fall back to another option, so the app need to keep the screen even when the error occurred.
**Issue link**
#708 
**Test Cases**
1. Set up U2F devices for 2FA.
2. Add a URL as a server in order to login with U2F devices, such as https://gitlab.com.
3. Try to login.
4. The login form should fall back to PIN code in 2FA.
https://circleci.com/gh/yuya-oc/desktop/680#artifacts
=> Ignore did-fail-load event when trying to use U2F devices

src/main.js
**Summary**
Disable Certificate Transparency verification.
It seems that there is problem in Electron's Certificate Transparency verification.
https://github.com/electron/electron/issues/11997
Some error cases reported at #742 would be solved by disabling the verification. This is issued against to release-4.0. And we need to know whether Electron v1.8.3 actually fixes the issue.
https://github.com/mattermost/desktop/issues/742#issuecomment-376165341
**Issue link**
#742
**Test Cases**
- Case A: Certificate Transparency error
1. Add the URL as a server which have the error appears.
2. The error should not appear.
- Case B: Actually invalid
1. Add the URL as a server which is actually insecure. e.g. …
=> Disable Certificate Transparency verification

src/browser/webview/mattermost.js
**Summary**
Clear webFrame cache at a certain interval.
mattermost-webapp is SPA. So cache is not cleared due to no navigation by assuming this article.
http://seenaburns.com/debugging-electron-memory-usage/
We need to manually clear cache to free memory in long-term-use. Just for now, the interval is set to 1 hour.
**Issue link**
#710
**Test Cases**
Use an artifact for longer than the interval. After that, memory usage should not be highly increased.
For testing purpose, switching channels is a way to temporarily increase memory usage.
https://circleci.com/gh/yuya-oc/desktop/712#artifacts
=> Clear webFrame cache at a certain interval

src/browser/components/HoveringURL.jsx, src/browser/components/MainPage.jsx
**Summary**
We keep getting tickets to hide different links throughout the app, but the root problem seems to be that these are links within the app, so they're not considered important. We still want the full URL to appear on hover for external links so the user can avoid malicious ones, but this should solve it without us making additional changes to the web app.
**Issue link**
https://mattermost.atlassian.net/browse/MM-9922
**Test Cases**
Tested locally using `yarn run watch`. Let me know if there's anywhere else that I should be adding tests
=> MM-9922 Don't show hovered URL for internal links

src/browser/components/TabBar.jsx
**Summary**
Make tabs undraggable.
This would block #478 in the future. But this is an easy workaround for now.
**Issue link**
#667
**Test Cases**
1. Add two servers at least.
2. Try to drag&drop a tab.
3. Anything should not happen.
https://circleci.com/gh/yuya-oc/desktop/754#artifacts
=> Make tabs undraggable

package.json
**Summary**
Fix package.json to use correct package name.
Probably it's regression of #749. The app was installed under `AppData\Local\mattermost-desktop`. It may causes an issue when upgrading the desktop app.
**Issue link**
N/A
**Test Cases**
1. Uninstall all `Mattermost` from the Control Panel.
2. Install the artifact.
3. The app should be installed under `AppData\Local\mattermost`.
https://circleci.com/gh/yuya-oc/desktop/797#artifacts
=> Fix package.json to use correct package name

src/main.js, src/main/squirrelStartup.js
**Summary**
Fix an issue where Windows installer crashed in some cases.
Unfortunately the issue doesn't reproduce on my PC, so I'm not sure whether this PR can solve the problem.
Even though I found an issue in initial setup; a `null` object was being destroyed. So I fixed it and ensure that the initial setup correctly finishes.
**Issue link**
#728 
**Test Cases**
1. Install the desktop app with the installer exe.
2. The crash report dialog should not appear.
https://circleci.com/gh/yuya-oc/desktop/798#artifacts
=> Fix an issue where Windows installer crashed in some cases

CHANGELOG.md, src/browser/components/TabBar.jsx, src/browser/css/components/TabBar.css
- Should resolve https://github.com/mattermost/desktop/issues/518.
- Shows server name in a `title` attribute so that you can still see the full name on hover.
- Unusual placement of CSS changes is to prevent a [flash of unstyled content](https://en.wikipedia.org/wiki/Flash_of_unstyled_content).
Here is a screenshot of how it looks.
If you'd like it to look different, let me know, or if you think we should solve this problem a different way, let me know.
=> Truncate long server names in server tabs

CHANGELOG.md, package.json, src/browser/components/NewTeamModal.jsx, src/package.json
=> Fix for being unable to type in the form fields on the add server dialog when launched from the tab bar

src/browser/components/MainPage.jsx
**Summary**
Unfortunately, the actual behaviour that we want where hovered links in posts always show the URL isn't possible with this behaviour since I haven't found a way to identify what in the WebView has been hovered from these events, so this will have to be handled from the web app.
**Issue link**
https://mattermost.atlassian.net/browse/MM-9922
=> Revert "Merge pull request #745 from mattermost/mm9922"

CHANGELOG.md, src/browser/components/NewTeamModal.jsx
Closes #438
This solution is different than what @jasonblais suggested. @jasonblais suggested not highlighting the field that hasn't been filled out yet, but I think it's a better UX to continue to highlight them all as it currently does, but to clarify the error messages. Also notably, as far as I can tell, the react-bootstrap [forms API](https://react-bootstrap.github.io/components/forms/) does not appear to support selectively highlighting some fields in the form but not others anyway.
=> Improve error messages on add new server dialog

src/main/permissionRequestHandler.js
**Summary**
Add workaround for permissionRequestHandler error on deep linking.
The original problem doesn't happen on my PC. However the call stack indicates the error happened at permissionRequestHandler apart from deep linking.
So it seems there is a timing that the handler failed to get URL. I added try-catch statement for workaround. 
**Issue link**
#771
**Test Cases**
See #771. Quit the desktop app, then click mattermost:// link in web browser.
https://circleci.com/gh/yuya-oc/desktop/816#artifacts
=> Add workaround for permissionRequestHandler error on deep linking

src/browser/components/MattermostView.jsx
**Summary**
Fix an error where the main page gets blank when adding a server.
When adding a server on the main page, it tries to get focus to the new webview. However probably its webContents object is not created yet, so null reference error happened for me.
**Issue link**
N/A
Original report: https://pre-release.mattermost.com/core/pl/53y7wdj3wtye3pnewpfajzuatc
**Test Cases**
Add a server from `+` button of the main page or [File/Mattermost ->Sign in to Another Server] menu item.
https://circleci.com/gh/yuya-oc/desktop/822#artifacts
=> Fix an error where the main page gets blank when adding a server

src/main.js, src/main/cookieManager.js
**Summary**
Make sure that cookies are saved to disk when closing the app.
Somehow cookies are not immediately saved to disk. Possibly https://github.com/electron/electron/issues/8416 is related.
So I manually called [`cookies.flushStore()`](https://electronjs.org/docs/api/cookies#cookiesflushstorecallback) when the app is quitting or the window loses focus. This would cover almost use cases even if application crashed.
**Issue link**
Original report: https://pre-release.mattermost.com/core/pl/m4s6qfjb5f815x4co388pscrfe
**Test Cases**
1. Quit the app.
2. Remove the application data folder
- Windows: `AppData\Roaming\Mattermost`
- Mac: `~/Library/Application Support/Mattermost`
- Linux: …
=> Make sure that cookies are saved to disk when closing the app

src/browser/components/MattermostView.jsx
**Summary**
Fix `MattermostView.focusOnWebview()` if statement.
It's my mistake when fixing #787. Necessary `!` was missing.
**Issue link**
#790 
**Test Cases**
1. Click the dock/taskbar icon to focus on the desktop app
2. Press CMD/CTRL+K to open channel switcher
And test cases of #787
https://circleci.com/gh/yuya-oc/desktop/826#artifacts
=> Fix MattermostView.focusOnWebview() if statement

src/common/config/defaultPreferences.js, test/specs/browser/settings_test.js
**Summary**
Enable GPU hardware acceleration by default.
**Issue link**
#798 
**Test Cases**
See #734. The expected behavior would be opposite.
https://circleci.com/gh/mattermost/desktop/1456#artifacts
=> Enable GPU hardware acceleration by default

resources/linux/create_desktop_file.sh
**Summary**
Add "Categories=Network;InstantMessaging;" to ensure that Mattermost is listed under the appropriate submenu of the application starter.
**Test Cases**
Tested with KDE/Plasma 5.46/5.12.5 and KMenu. With the change, Mattermost is listed under "Internet", without the change Mattermost is listed under "Lost & Found".
=> Update create_desktop_file.sh with categories

package.json, yarn.lock
**Summary**
Upgrade Electron to ~2.0.7~ 2.0.8.
It includes minor bug fixes and improvements for DWM of Windows.
**Issue link**
#753 
**Test Cases**
Use the app on Windows which is disabling DWM. Please refer to #753.
~https://circleci.com/gh/yuya-oc/desktop/959#artifacts~
https://circleci.com/gh/yuya-oc/desktop/962#artifacts
=> Upgrade Electron to 2.0.8

src/browser/components/SettingsPage.jsx, src/browser/js/contextMenu.js
- [-] executed `npm run lint:js` for proper code formatting
**Summary**
Add a '[US]' to the word 'English' in the dictionary, and add Portuguese to settings helps text list 
**Issue link**
https://mattermost.atlassian.net/browse/MM-11910
**Test Cases**
=> MM-11910: Add a '[US]' to the word 'English' in the dictionary, and add Portuguese to settings helps text list 

src/main.js, src/main/utils.js
**Summary**
Hide the main window on Mac auto-start
**Issue link**
#583
**Test Cases**
1. Configure auto-start on Mac: https://support.apple.com/kb/PH25590?viewlocale=en_US
2. Select the "Hide" checkbox next to Mattermost.
3. Logout from Mac.
4. Login to Mac.
5. The app should launch automatically, but the window should not appear.
Artifacts: https://circleci.com/gh/yuya-oc/desktop/966#artifacts
=> Hide the main window on Mac auto-start

.eslintrc.json, src/browser/components/LoginModal.jsx, src/browser/components/MattermostView.jsx, src/browser/components/SettingsPage.jsx
**Summary**
Remove findDOMNode() from components. For that, apply react/no-find-dom-node eslint rule.
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-find-dom-node.md
In most cases, we can avoid using `findDOMNode()` by using a Ref to the node.
https://reactjs.org/docs/react-dom.html#finddomnode
**Issue link**
N/A
**Test Cases**
1. Execute unit tests.
2. Tray icon theme can be configurable on Linux.
Artifacts: https://circleci.com/gh/yuya-oc/desktop/978#artifacts
=> Remove findDOMNode() from components

src/browser/components/MainPage.jsx, src/browser/components/MattermostView.jsx, src/browser/components/TabBar.jsx, src/browser/css/components/TabBar.css, src/browser/index.jsx, src/browser/webview/mattermost.js, src/main.js
**Summary**
Detect when a session has expired and display appropriate badging, as per https://docs.google.com/document/d/1yezizH0-3mi4ZJ8nr5vIOiDKv-aBo52fguG__THpDD0/edit#.
**Issue link**
https://mattermost.atlassian.net/browse/MM-12275
**Test Cases**
* Login, then expire session via another session (Account Settings -> Security -> View and Logout of Active Sessions), verify badging
See https://github.com/mattermost/mattermost-webapp/pull/1751 for corresponding notifications displayed.
=> MM-12205: session expiry notification

src/main/SpellChecker.js, test/specs/spellchecker_test.js
**Summary**
Preserve case of first letter in spell check, fixes #562
**Issue link**
https://github.com/mattermost/desktop/issues/562
**Test Cases**
Implemented as described in yuya-oc's proposal from Jul 12, 2017
=> Preserve case of first letter in spell check, fixes #562

electron-builder.json
**Summary**
Sets a flag in the electron builder that enables AppImage packaging.
This would enable most linux users to simply run the application from the downloaded image and if wanted sets the necessary path variables to launch it from the preferred desktop environment. 
IMO it is better than distributing with a .deb or .rpm package, because it's distribution independent and comes with all needed dependencies, if any. Also it is just a minor change in packaging that enables a lot more users to comfortably install and use the app on their system.
=> Add flag for AppImage packaging

src/browser/components/MattermostView.jsx
We've decided to match the behaviour of most browsers by not allowing these links. They only worked sometimes anyway, so it's easier to not support them in all cases than inconsistently support them.
**Issue link**
https://mattermost.atlassian.net/browse/MM-12800
=> MM-12800 Remove partial ability to use file:// links

package.json, yarn.lock
**Summary**
Upgrade Electron to 2.0.12.
I believe there are no breaking changes from 2.0.8 to 2.0.12 as far as reading their release notes.
And I found Electron v3 and Spectron v5 break almost of our tests. I think it's hard to solve soon, so I used Electron v2.x.
**Issue link**
N/A
**Test Cases**
Automated tests. (`npm test`)
https://circleci.com/gh/yuya-oc/desktop/1016#artifacts
=> Upgrade Electron to 2.0.12

src/main.js, src/main/mainWindow.js
**Summary**
- Improved the wording of the bad certificate dialog to make it scarier and harder to just allow.
- Adding `will-navigate` and `new-window` handling to prevent the bug where the app would navigate to a random page.
- Added context isolation.
**Issue link**
https://mattermost.atlassian.net/browse/MM-13145
=> MM-13145 Some improvments to navigation and messaging.

resources/windows/gpo/en-US/mattermost.adml, resources/windows/gpo/mattermost.admx
This pull request add the GPO functionality to
- configure the server addresses
- control if the + for adding more server is available or not
Target for 4.3, if not we need to change slightly this policy before merge.
=> GPO: Configure server addresses and prevent adding new servers

src/browser/components/MainPage.jsx, src/main/menus/app.js
**Summary**
Add a menu to open dev tools for current webview 
**Issue link**
https://github.com/mattermost/mattermost-server/issues/10131
**Test Cases**
=> add a menu to open dev tools for current webview

electron-builder.json
**Summary**
Enabled MacOS Mojave Dark Mode title bar.
**Issue link**
- https://github.com/mattermost/desktop/issues/848
- https://mattermost.uservoice.com/forums/306457-general/suggestions/36842986-desktop-mac-mojave-dark-titlebar
Tested on MacOS 10.14.3.
=> GH-848 Add flag to enable MacOS dark mode title bar

.eslintrc.json, package-lock.json, package.json, scripts/extract_dict.js, src/browser/components/MainPage.jsx, src/browser/components/MattermostView.jsx, src/browser/components/SettingsPage.jsx, src/main.js, test/specs/settings_test.js, webpack.config.base.js, webpack.config.main.js, webpack.config.renderer.js
**Summary**
Add eslint-plugin-eslint-comments. It prevents abuse of `eslint-disable` directive.
See https://mysticatea.github.io/eslint-plugin-eslint-comments/ for detail.
**Issue link**
N/A
**Test Cases**
Add unwanted `/* eslint-disable */` comments, then execute `npm run lint:js`. It should report errors.
N/A
=> Add eslint-plugin-eslint-comments

src/main/mainWindow.js
**Summary**
On Mac, when the window is closed in fullscreen, this PR first exits fullscreen and then closes the window to prevent a black screen when trying to close the window in fullscreen.
**Issue link**
[MM-14172](https://mattermost.atlassian.net/browse/MM-14172)
=> [MM-14172] Fix black screen when closing window in fullscreen on a Mac

src/main/mainWindow.js
**Summary**
Removes logic that saves fullscreen state when quitting, allowing the app to always open up in windowed mode.
**Issue link**
Github: #863
Jira: [MM-14176](https://mattermost.atlassian.net/browse/MM-14176)
I was unable to replicate the exact issue described in the ticket in Mac OS Mojave, however, there was still some odd behaviour for me (App went fullscreen, but didn't get focus). This fix corrects that odd behaviour and should also correct the High Sierra issue.
=> [MM-14176] Fix restart after quitting in full screen

src/browser/components/MattermostView.jsx
**Summary**
This PR opens the help link below the textbox in the default system browser instead of in the desktop app.
**Issue link**
[MM-14349](https://mattermost.atlassian.net/browse/MM-14349)
**Test Cases**
See issue link.
=> open certain internal paths in default browser

.eslintrc.json, src/browser/components/SettingsPage.jsx, src/browser/index.jsx, src/common/config/RegistryConfig.js, src/common/config/index.js, src/main.js, src/package.json
**Summary**
This PR integrates GPO functionality by retrieving supported values set in the Windows registry and appropriately merging them with the app config.
NOTE: This functionality needs to be tested in a Windows environment configured with the appropriate GPO capabilities.
=> [MM-14740] Integrate GPO functionality

src/common/config/RegistryConfig.js, src/main.js
**Summary**
This PR's primary purpose is to address a potential race condition between the Electron app's `ready` event that creates the app UI etc. and the loading of Windows registry config data needed by the app UI. This is handled using Promise.all – specifically, moving the app `ready` code into a separate function, moving the registryConfig `update` event code into the same function and waiting till both the app is ready and the registry config data has loaded before calling the new function to finish creating the app.
While making these changes, the PR also restructures the `main.js` file to clean it up and group related code together. The intent of this restructuring is to make it easier to see what …
=> [MM-14740] Address potential race condition and cleanup main.js

src/browser/components/LoginModal.jsx
**Summary**
Resolves an issue where username and password were not being passed for HTTP basic authentication.
**Issue link**
Fixes #965
**Test Cases**
=> Move LoginModal username and password into instance properties, remove refs

src/browser/webview/mattermost.js
**Summary**
This PR updates the scraping mechanism that retrieves mentions from the DOM of the webapp for use in the mentions badge on the server tab (when visible). The mechanism now only pulls mentions from the LHS instead of anywhere in the DOM, which was previously causing the count in the tab to double whenever the suggestions drop-down was visible while the quick-switcher was open.
**Issue link**
[MM-15918](https://mattermost.atlassian.net/browse/MM-15918)
=> [MM-15918] Pull reference counts from LHS only.

package-lock.json, package.json
**Summary**
This PR upgrades electron to the lastest 4.x version (4.2.4) to fix the quit menu keyboard shortcut not working in Windows. Seems the shortcut broke with the Electron 4.0.0 upgrade but is fixed in the latest 4.x.
**Issue link**
[MM-15812](https://mattermost.atlassian.net/browse/MM-15812)
=> [MM-15812] Upgrade Electron to latest 4.x version

src/browser/css/components/TabBar.css
**Summary**
This PR adds some CSS tweaks to center mention badge counts and the nomention dot. Also adds some padding to better mimic the badges in the webapp.
**Issue link**
[MM-13267](https://mattermost.atlassian.net/browse/MM-13267)
It is possible that not all combinations of OS's and the Desktop app will work identically for this solution as we are not currently embedding the font we use in the app so the font used on a particular system may not position as well. I have tested on Mac OS 10.14.5 and Windows 10 Pro.
=> [MM-13267] Center badge count text and nomention dot

.eslintrc.json, src/browser/components/MattermostView.jsx, src/browser/js/WebappConnector.js, src/browser/webview/mattermost.js, src/main.js, src/main/UserActivityMonitor.js, test/specs/main/user_activity_monitor_test.js
**Summary**
This PR and related Webapp & Server PR's support maintaining a user's online status while the Desktop app is in the background as well as automatically setting the user to away/online if the screensaver goes on/off, the user locks/unlocks their computer or shuts down their computer.
**PR's**
Desktop: [MM-7970](https://github.com/mattermost/desktop/pull/993) (this PR)
Webapp: [MM-7970](https://github.com/mattermost/mattermost-webapp/pull/2992)
Server: [MM-14582](https://github.com/mattermost/mattermost-server/pull/11312)
**Issue links**
Jira 1: [MM-7970](https://mattermost.atlassian.net/browse/MM-7970)
Jira 2: [MM-14582](https://mattermost.atlassian.net/browse/MM-14582)
Jira 3: [MM-16153](https://mattermost.atlassian.net/browse/MM-16153) …
=> [MM 7970] Maintain online status while the Desktop App is in the background ... and other things.

src/main/menus/app.js
**Summary**
Adds condition to remove accelerator for Window -> Minimize when `process.platform === 'win32'`. 
By setting accelerator to `null` for other platform values, Minimize will use the default shortcut on those platforms.
**Issue link**
Fixes https://github.com/mattermost/mattermost-server/issues/9398
**Test Cases**
I was unable to come up with a good way to test this, and didn't see any comparable tests in the app.  I prefer to have a test here, and would appreciate any guidance to achieve that.
=> [MM-11896] Do not use minimize shortcut on win32

resources/windows/license.rtf, resources/windows/msi_i18n/en_US.wxl, scripts/make_build.ps1, scripts/msi_installer.wxs
This PR includes work for several Jira tickets as follows:
- [MM-15392](https://mattermost.atlassian.net/browse/MM-15392) – kill running app during (un)install
- [MM-15389](https://mattermost.atlassian.net/browse/MM-15389) – prevent 32bit install on 64bit windows
- [MM-15385](https://mattermost.atlassian.net/browse/MM-15385) – always show license button
- [MM-15388](https://mattermost.atlassian.net/browse/MM-15388) – integrate GPO files into installer
- [MM-15713](https://mattermost.atlassian.net/browse/MM-15713) – tie license checkbox's in normal and advanced screens to each other
Merging into branch `release-test-msi` as the current "master" for MSI related functionality. Does not need a final 2-dev code review as the `release-test-msi` branch still needs a final review against actual …
=> Consolidated updates to MSI installer

src/main/mainWindow.js
**Summary**
This PR turns on Context Isolation for increased security between the loaded MM Webapp and the users underlying OS.
**Issue link**
https://mattermost.atlassian.net/browse/MM-13609
**Test Cases**
Mac: A local build (`yarn run build`) on a Mac is sufficient to test this PR.
Windows: A package needs to be generated locally (`yarn run package:windows`) and then installed from the resulting `./releases/squirrel-windows` (64-bit) folder for notifications to work properly.
Once running:
* make sure you are logged into the same mm server with two different users, one within the running Desktop app.
* with the user not running in the Desktop app, at-mention the user running in the Desktop app in a …
=> Enable context isolation for release-4.2.x

builds/pr/Jenkinsfile
removing jenkins, circleci is doing the same for building the PRs
- after we merge this I will remove the jenkins job and set the check to use the one from circleci
=> remove jenkins

src/browser/components/NewTeamModal.jsx, src/main/Validator.js, test/specs/browser/index_test.js
**Summary**
After analyzing the `config.json` file from a client experiencing the disappearing server problem after updating from 4.2.1 to 4.2.2, it seems that in their `config.json` files, the `trayIconTheme` option was set to a blank string instead of the `light` or `dark` options. The Validator was written to expect either `light` or `dark` and so the validation was failing. Digging deeper into the code, it looks like it might actually be possible to have a blank value for that option (it's really only a Linux option), so the Validator has been updated to allow for that.
While the team URL wasn't actually the problem in this case it is still a possibility, so the validator has also been updated to convert any `\` characters to `/` characters and then further checks each updated URL …
=> [MM-17616] v4.2: Update config.json file validation to prevent loosing config settings on upgrade

src/main.js, src/main/mainWindow.js
**Summary**
This PR turns on Context Isolation for increased security between the loaded MM Webapp and the users underlying OS.
**Issue link**
https://mattermost.atlassian.net/browse/MM-13609
**Test Cases**
Mac: A local build (`npm run build`) on a Mac is sufficient to test this PR.
Windows: A package needs to be generated locally (`npm run package:windows`) and then installed from the resulting `*setup*.exe` in the `./releases/` folder for notifications to work properly.
Once running:
* make sure you are logged into the same mm server with two different users, one within the running Desktop app.
* with the user not running in the Desktop app, at-mention the user running in the Desktop app in a team/channel …
=> Enable context isolation

test/modules/environment.js
**Summary**
There was a small bug in the tests from recent pipeline changes that is only apparent on a mac. This PR fixes that bug.
**Issue link**
Piggy backs off of: https://github.com/mattermost/desktop/pull/1029
Related to: https://mattermost.atlassian.net/browse/MM-17955
**Test Cases**
Tests should run on a mac without errors.
=> Bugfix: Initialize `chromeDriverArgs` property before using it

src/main.js, src/main/menus/app.js
**Summary**
This PR comments out the code that was added to implement (auto)updating on v4.3 to remove it from the v4.3 release. Will be added back in in a future release.
**Issue link**
https://mattermost.atlassian.net/browse/MM-18551
=> [MM-18551] Remove (auto)updater from v4.3

src/browser/components/MattermostView.jsx, src/main.js
**Summary**
A security update added in [this commit](https://github.com/mattermost/desktop/commit/6b09eec4c51ffb02422ade4c866581aef30d0953) causes custom authentication paths (OAUTH, SAML) to fail as the 3rd party URLs used in the authentication process are not in the list of trusted domains. This fix detects navigation to any trusted custom authentication paths, grabs the domain of the resulting 3rd party authentication site and uses that to temporarily trust any further navigation changes that occur within the 3rd party domain until navigation is returned to MM, at which point the temporary trust is cleared.
Incidentally also adds a workaround for an electron bug preventing the cursor from showing when navigation occurs in the webview, as reported in [this …
=> [MM 17255] Fix OneLogin and other OAUTH/SAML custom login attempts

src/main.js
**Summary**
The call to `shouldShowTrayIcon()` was not actually a call at all, it was just checking if the function existed. As a result, the tray icon always showed up. This fixes that typo.
**Issue link**
https://mattermost.atlassian.net/browse/MM-18750
**Test Cases**
1. Open the desktop app on Mac
2. In settings, turn off 'Show Mattermost icon in the menu bar'
3. Restart the app
4. See that the menu icon no longer appears.
=> [MM-18750] Fixed a typo that was causing tray icon to constantly show up

resources/windows/gpo/en-US/mattermost.adml, resources/windows/gpo/mattermost.admx
**Summary**
Remove the option to switch GPU Acceleration as a GPO directive. Note that it can still be accessed from the settings page.
**Issue link**
[MM-18906](https://mattermost.atlassian.net/browse/MM-18906)
**Test Cases**
1. Add GPO configuration files to a compatible Windows install (eg. Windows 10 Pro) ala https://docs.mattermost.com/install/desktop-msi-gpo.html#download-group-policy-and-msi-installer-files (It is not necessary to install the Desktop app to verify)
2. Run gpedit from the Start menu's search box (https://docs.mattermost.com/install/desktop-msi-gpo.html#configure-mattermost-using-group-policy-settings)
3. Ensure that there isn't an option for configuring the GPU setting for the Desktop …
=> [MM-18906] remove GPU acceleration option from GPO settings

src/main.js
**Summary**
This PR fixes an issue where entering `https://google.com` as a server url causes the desktop app to crash.
**Issue link**
https://mattermost.atlassian.net/browse/MM-18936
Subsequent crashes occur upon restart, unless you edit the `AppData/Mattermost/config.json` file manually.
=> [MM-18936] Guard against bad server url so app doesn't crash

src/browser/components/MattermostView.jsx
**Summary**
A fix applied in [this PR](https://github.com/mattermost/desktop/pull/1025) to resolve an Electron cursor/focus bug has been messing up focus for the currently active tab when a server defined in an inactive tab is not able to load (offline). The problem is that the desktop app keeps trying to load the offline server and with each attempt, the cursor/focus fix is run again stealing focus from the active tab.
This PR adds a check to make sure a tab is active before running the fix.
**Issue link**
https://mattermost.atlassian.net/browse/MM-19095
=> MM-19095 – Stop cursor bug fix from running in inactive tabs

src/main/menus/app.js
**Summary**
The Desktop app menu has the `History` and `Help` menu items sharing the same shortcut letter. This PR corrects that by assigning the `p` as the shortcut letter for the `Help` menu.
**Issue link**
https://mattermost.atlassian.net/browse/MM-16373
**Test Cases**
1. Install and run the v4.3.0 Windows desktop app with this fix applied
2. Press and release the ALT key.
Expected: The `Help` menu should have the `p` character underlined and subsequently pressing the `p` key should open the `Help` menu.
=> MM-16373: Change `help` menu shortcut on Windows

src/main.js
**Summary**
The new functionality added to support 3rd party custom login mechanisms (SAML, OAUTH) following a security enhancement attempted to determine the 3rd party hostname and temporarily trust it for the duration of the login request. This temporary trust created some challenges during testing and it was subsequently decided that this aspect of the feature was too brittle given we ultimately can't control what an IDP does on their end to validate an authentication request, nor can we control the kinds of linkable resources an end user might be presented with during the login process.
This PR removes the temporary trust aspect of the feature and solely relies on appropriately flagging a custom login is in progress, during which any navigation that needs to occur until the user is …
=> MM-19096 – simplify custom login process

src/browser/css/components/MattermostView.css
**Summary**
Desktop v4.3-rc2 was not updating mention/unread status in inactive tabs - seems Chrome related. This PR changes the mechanism for showing/hiding tabs to allow them to continue updating while inactive.
More details: it seems that setting the width/height on inactive tabs' `webview` to 0px/0px is causing Chrome to stop updating them, preventing the scraping mechanism from updating the count on the tabs.
**Issue link**
https://mattermost.atlassian.net/browse/MM-19208
=> [MM-19208] Allow hidden tabs to still receive unread/mention updates

src/browser/webview/mattermost.js
**Summary**
Team sidebar was not being considered in determining the total number of mentions in the tab for a server. This PR (re)adds the sidebar to the calculation.
**Issue link**
https://mattermost.atlassian.net/browse/MM-19207
=> include team bar in mention counts

src/browser/components/MainPage.jsx
**Summary**
The `BrowserWindow` did not have focus after the server was selected. This PR sets focus to the webView after the server is selected.
**Issue link**
https://mattermost.atlassian.net/browse/MM-19187
=> [MM-19187] Focus the webview on server selection

src/main/UserActivityMonitor.js, test/specs/main/user_activity_monitor_test.js
**Summary**
In this PR:
- re-work of the mechanism for determining user activity status and updating the server via the webapp
- removing system events (login/out screensaveer on/of etc.) to be re-considered for a future release – prompted by stability issues that aren't readily resolvable given the current implementation of status management in MM
**Issue link**
https://mattermost.atlassian.net/browse/MM-19266
https://mattermost.atlassian.net/browse/MM-19302
=> [MM-19266] User activity monitor updates

src/main.js
**Summary**
A security enhancement prevented local URLs from opening in new Desktop app windows. This PR allows trusted URLs to open in new windows again.
**Issue link**
https://mattermost.atlassian.net/browse/MM-19301
=> [MM-19301] Allow trusted urls to open new windows

src/browser/components/MainPage.jsx
**Summary**
Using the menu hotkeys was causing the renderer to somehow loose focus, preventing further hotkeys from working. Refocusing the renderer process just prior to focusing the webview corrects the issue in the linked ticket ... deceptively simple 😛
**Issue link**
https://mattermost.atlassian.net/browse/MM-19340
=> [MM-19340] Re-focus renderer process

scripts/msi_installer.wxs
**Summary**
This PR changes all human readable references of `Mattermost Desktop` to just `Mattermost` in the MSI installer config file.
Needs to be built as release in CI to test (for now).
**Issue link**
https://mattermost.atlassian.net/browse/MM-19329
=> [MM-19329] Change `Mattermost Desktop` to `Mattermost` in MSI

src/main.js
**Summary**
A recent security enhancement to the desktop app was preventing the Jira v2 plugin from authenticating from a popup window when trying to connect it with MM using `/jira connect`.
This PR adds in the ability for a pop-up window triggered from within MM and having a destination URL within the same MM server, to open a controlled Electron BrowserWindow over top of the Desktop App. Further, the resulting BrowserWindow is allowed to navigate outside of the MM server domain for purposes of authentication.
This fix is specifically for Jira v2, but should apply to any plugin that needs to authenticate via SAML/OAUTH and first slingshots though a plugin-specific url on the MM server.
Note that to test this, it is necessary to do so from https://community.mattermost.com. See …
=> [MM 19369] Add controlled support for popup windows.

resources/windows/gpo/en-US/mattermost.adml, resources/windows/gpo/mattermost.admx
**Summary**
This pull request disable the GPO for controlling the AutoUpdate feature as Eric remove it here: 
https://github.com/mattermost/docs/pull/3067/files#diff-dcc9ba198b59be56a71e3af640d71201L47
=> Disable AutoUpdate GPO

.circleci/config.yml, scripts/Makefile.ps1
**Summary**
While electron builder setup executable will eventually go away, we might distribute it if something happens with msi. For that reason it should be signed.
**Issue link**
[MM-19515](https://mattermost.atlassian.net/browse/MM-19515)
**Test Cases**
Use signtool to verify signature
installation should not complain about it not being signed
results from test branch can be found in a previous run: https://circleci.com/gh/mattermost/desktop/3551#artifacts/containers/0
=> [MM-19515] Sign electron builder executable

.circleci/config.yml, electron-builder.json, package-lock.json, package.json, scripts/notarize.js
**Summary**
Added notarization which is a requirement for using software on osx Catalina (v10.15)
**Issue link**
[MM-19569](https://mattermost.atlassian.net/browse/MM-19569)
**Test Cases**
Steps:
on catalina version, running the app shouldn't raise any errors/warnings
Notes:
a release is needed for proper testing, but DM on community me for a version notarized run from this branch
added a dependency to handle notarization
added a signing check on release to ensure it's properly signed (it should fail if it isn't), this is disabled on PRs to prevent failing when not expected to be signed.
official apple procedures for testing signing: https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc …
=> [MM-19569] add notarization to osx app

.circleci/config.yml, scripts/Makefile.ps1, scripts/cp_artifacts.sh, scripts/generate_release_markdown.sh, scripts/release.sh
**Summary**
- Added a release script to handle tick-tock branching and general release process to make sure versions are consistents between builds
- fixed [MM-14180](https://mattermost.atlassian.net/browse/MM-14180). When installing on windows, msi installer would have a weird alfanumeric name.
- push artifacts onto github release. release is generated as draft, so someone has to go to github and finish publishing. This is to prevent publishing in the wrong time and to have time to review what's going to be published.
**Issue link**
- [MM-14180](https://mattermost.atlassian.net/browse/MM-14180)
- [MM-19051](https://mattermost.atlassian.net/browse/MM-19051)
- [MM-19330](https://mattermost.atlassian.net/browse/MM-19330)
there is room for improvement, we can add …
=> [MM-19051] [MM-14180] [MM-19330] Release helpers, push to github and aws, fix weird name on msi at UAC

package-lock.json, package.json, src/browser/components/MainPage.jsx, src/main.js, src/main/menus/app.js, src/package-lock.json, src/package.json
**Summary**
There are a number of menu bar keyboard shortcuts that have not been working properly since 4.3.0. We suspect that this may be related to https://community-daily.mattermost.com/core/pl/b95bi44r4bbnueqzjjxsi46qiw. While we investigate a proper way to handle the issue, this PR manually intercepts and handles several of the malfunctioning keyboard shortcuts including zooming, redo/undo. Copy/cut/paste are included for good measure.
Also bumps minor version of Electron to v5.0.11 and upgrades context menu package to latest stable to resolve https://mattermost.atlassian.net/browse/MM-19324 (needs testing).
**Issue link**
MM-19198
MM-19032
MM-19324
=> Manually handle misbehaving keyboard shortcuts

src/main.js
**Summary**
The changes we made to enforce the use of trusted URLs has shut off the `mailto` protocol. This PR adds an exception for it.
**Issue link**
https://mattermost.atlassian.net/browse/MM-19596
=> Fixed email links being rejected by will-navigate

scripts/Makefile.ps1, scripts/notarize.js, src/main.js
**Summary**
Ensure working directory is set to where the executable is to prevent problems
**Issue link**
[MM-19963](https://mattermost.atlassian.net/browse/MM-19963)
**Test Cases**
run from the command line from a directory different from where it is installed
use procmon or some other process monitoring tool that can provide information of the working directory and check that is properly set.
=> [MM-19963] set working directory on start

src/main.js, src/main/Validator.js, src/main/mainWindow.js
**Summary**
Prior to the upgrade to Electron v5 (from v2), the app would immediately minimize the app window once created. It would then wait for the window's 'ready-to-show' event fired and call the `.show()` method to show the UI in the window while the window remained minimized. Following the upgrade of Electron, calling the `.show()` method un-minimizes the Window, but the UI doesn't get shown resulting in a blank window (I suspect this has something to do with not being told the Window is visible and/or not getting a resize event to re-render the UI). Although the below ticket only refers to Windows, the reality is that it can be repro'd on other OS's by using the supported `--hidden` flag when starting the app from command line.
This PR sets the initial `show` option when creating …
=> [MM 19649] Fix blank window when auto-starting the app on login

src/browser/components/MattermostView.jsx, src/browser/webview/mattermost.js, src/main.js
**Summary**
When the Mac Desktop app is in macOS fullscreen, engaging html fullscreen on an inline Youtube video gets stuck in html fullscreen mode. The `Escape` key, the `f` key shortcut and the fullscreen button don't do anything.
This PR listens for the `Escape` and `f` keys from the main process to manually tell the webview in the renderer process to exit html fullscreen if engaged.
This PR doesn't fix the fullscreen button, as due to `contextIsolation` the desktop app can't control the contents of the Webapp.
**Issue link**
https://mattermost.atlassian.net/browse/MM-19226
=> [MM-19266] Manually exit html fullscreen on macOS when in fullscreen

src/browser/js/contextMenu.js
**Summary**
on [electron-context-menu v0.12](https://github.com/sindresorhus/electron-context-menu/releases/tag/v0.12.0) they released a breaking change, we need to adapt to it to allow the spellchecker to show.
**Issue link**
[MM-20645](https://mattermost.atlassian.net/browse/MM-20645)
**Test Cases**
- on the imput line type "helo my friend"
- "helo" should show with a red underline
- right click on it to correct
Expected:
- suggestion of "hello" appears
- clicking on suggestion substitutes the word.
=> [MM-20645] fix spellchecker

src/browser/index.jsx, src/browser/js/badge.js
**Summary**
When a user has over 99 mentions, the text expands too large to fit the badge, creating a poor UX. This PR forces that over 99 mentions will show as "99+".
**Issue link**
https://mattermost.atlassian.net/browse/MM-20156
=> [MM-20156] Added '99+' message badge for Windows when over 99 mentions are on the badge

src/main.js
**Summary**
When a link to a team is posted and the user has that server on the list of tabs on the desktop app, it should only open in the browser, it shouldn't open a new desktop window with the server
**Issue link**
[MM-21075](https://mattermost.atlassian.net/browse/MM-21075)
**Test Cases**
Repro steps:
1) Add mysql.test.mattermost.com as a server on the desktop app as well as another server
2) On the other server, post a link to https://mysql.test.mattermost.com/
3) Click on that link
Observed: A new desktop app window opens to mysql.test and a browser tab for mysql.test also opens
Expected: Nothing should open another desktop app window. Current expected is that it opens in browser tab.
It is not expected to change tabs within the app
=> [MM-21075] Prevent known teams to open in a new app window

src/main.js, src/main/Validator.js, src/utils/util.js
**Summary**
Allow for negative window position, so the app can be set to a monitor to the left or on top of the primary display
**Issue link**
[MM-14135](https://mattermost.atlassian.net/browse/MM-14135)
**Test Cases**
*** Case 1 ***
On a multimonitor setup, set as main display the rightest monitor (or the bottom one if they are stacked)
open mattermost
move the window to any monitor not on the main display
quit the app
reopen
expected: window position is as we left it. Notice that if we leave the window partially outside of the screen it might reposition on reopen.
*** Case 2 ***
Same as on Case 1, but disconnect the extra display before launching
expected: window goes to main display.
=> [MM-14135] allow negative window app positions

scripts/msi_installer.wxs
**Summary**
Add code for removing any previously installed version, also changed to doing it before installing the new one.
**Issue link**
[MM-20659](https://mattermost.atlassian.net/browse/MM-20659)
[MM-20678](https://mattermost.atlassian.net/browse/MM-20678)
**Test Cases**
on windows, install version 4.3.1 and configure it with a server
run installer based on this version
Expected:
- previows version no longer displays on settings->apps
- if autostart after install is selected, it should open to the server tab (no blank screen)
For testing, this **needs an msi installer**, so either QA has to wait for it (RC/final), or we can create one on demand.
There seems to be problems with 4.3.0, for some reason this version install to a different path (not in `program files` …
=> [MM-20659] fixing upgrade

src/browser/index.jsx, src/main.js
**Summary**
when user selects a new locale, spellchecker should update its suggestions to match
**Issue link**
[MM-20794](https://mattermost.atlassian.net/browse/MM-20794)
**Test Cases**
1. misspell word
1. right click on a misspelled word
1. check suggestions
1. click on Spelling Languages and select a different one.
1. right click on the same misspelled word
1. suggestions should be different
=> [MM-20794] change suggestion on spellchecker locale change

src/common/config/index.js
**Summary**
This PR changes the config to allow newer versions of the config to attempt to use the version of the config currently supported by the version of the app being used (ie. if you have a v2 config, the app will try to treat it as a v1 config)
**Issue link**
https://mattermost.atlassian.net/browse/MM-19205
=> [MM-19205] Allow the use of v2 configs by v1 config desktop apps

src/main.js, src/main/autoUpdater.js, src/main/mainWindow.js
**Summary**
set up a white bg for browser windows so fonts without subpixel aliasing are rendered properly
**Issue link**
[MM-20660](https://mattermost.atlassian.net/browse/MM-20660)
=> [MM-20660] set white background for OSs which have turned off subpixel aliasing

src/browser/components/MattermostView.jsx
**Summary**
When using Ctrl (or Cmd) + Tab to navigate tabs, if you tried to tab through a tab with an error screen, the event would be suppressed, since the `webview` was focused, but still hidden. This PR removes the `visibility: hidden` descriptor from the `webview` when the error page is showing, such that keyboard shortcuts still work as normal.
**Issue link**
https://mattermost.atlassian.net/browse/MM-20796
=> [MM-20796] Removed visibility: hidden from MM view when error page was showing

src/main.js
**Summary**
This PR fixes an issue where Basic Authentication challenges can be fired from the Mattermost app from arbitrary domains. This fix locks down the domains to only trusted URLS (ie. the URLs used by the Mattermost servers you have configured).
**Issue link**
https://mattermost.atlassian.net/browse/MM-20350
=> [MM-20350] Block Basic auth for non trusted URLs

src/main.js
**Summary**
when downloading on windows, we need to add the file extension filter to ensure it uses the same extension so it doesn't overwrite it on name change.
**Issue link**
[MM-21195](https://mattermost.atlassian.net/browse/MM-21195)
**Test Cases**
1. upload a file to a channel
2. on a win machine, download it
3. dialog should show up matching the extension of the file, as well as `*.*`
4. when downloading try to change the name of the file
5. save it
expected: extension is preserved unless we select the filter `*.*`
=> [MM-21195] add file extension on download

.circleci/config.yml, scripts/generate_release_markdown.sh
* update ci files
* remove redundant build step
- npm run package:* also builds
* fix path to temp aws files
* include exe in windows build
* add release notes reference
* tweak ghr draft tag name
* remove test filtering
* ignore tags for build_linux
* don't try to use the tag
Co-authored-by: Guillermo Vayá <guivaya@gmail.com>
Manual cherry pick
=> CircleCI config tweaks (#1116)

src/main.js
**Summary**
electron is moving towards using promises in its api, this caused our downloads to stop working. having an asynchronous download also showed browser's file dialog (thus duplicating it)
this pr adresses those issues by using another mechanism to download.
**Issue link**
[MM-21869](https://mattermost.atlassian.net/browse/MM-21869)
**Test Cases**
1. upload file
2. from the desktop download it
expected:
- only 1 dialog
- extension set to the right one (e.g.: pdf for pdf files)
- file downloads
- app doesn't crash
tested on osx
=> [MM-21869] handle downloading in a new way to adapt to electron v6

src/main/mainWindow.js, test/specs/app_test.js
**Summary**
On macOS, closed window reopens on Cmd+Tab
**Issue link**
Fixes https://github.com/mattermost/desktop/issues/1068
**Test Cases**
Unfortunately, my test case is skipped until Chromedriver on Mac issue is addressed: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3023#c2
Maybe I'm mistaken though, please advise if there's an alternative.
Possibly able to run this kind of test using TestCafe.
For changelog message, do I need conventional commit format? Such as `FEAT:`, `FIX:`?
=> [MM-18007] macOS app reopens closed window on Cmd+Tab

src/browser/components/MainPage.jsx, src/browser/components/MattermostView.jsx, src/utils/util.js
**Summary**
When clicking a link from Server A that links to Server B, even if you have Server B configured, it would open the link in your browser. This PR allows those links to be opened directly in the tab for that server.
**Issue link**
https://mattermost.atlassian.net/browse/MM-19919
=> [MM-19919] Allow links to other servers to go directly to that server in the app

src/browser/components/MainPage.jsx
**Summary**
When using the JIRA plugin connect functionality, the desktop app will open a new window for sign-in. The copy/paste shortcuts weren't working due to the logic grabbing the Mattermost tab that opened the window rather than the window itself.
This PR changes the logic to ensure the Mattermost tab is focused, otherwise it should grab whatever web contents are focused and send the command there.
**Issue link**
https://mattermost.atlassian.net/browse/MM-21341
=> [MM-21341] Changed keyboard shortcut logic to pull focused web contents if an explicitly focused tab is not found

.circleci/config.yml, scripts/generate_release_markdown.sh
**Summary**
- Prevent circle from publishing a new release if it's not an RC or final
- Fix naming on MSI
**Issue link**
[MM-22007](https://mattermost.atlassian.net/browse/MM-22007)
Successfull test for github: https://app.circleci.com/github/mattermost/desktop/pipelines/faaa2eb9-c5b3-4a2b-8272-037a69d1f8b3/workflows/51853392-0006-42bb-b038-0ccfbe6eab82
=> [MM-22007] Fix MSI download from S3, don't run when not an RC/release

src/browser/components/SettingsPage.jsx, src/browser/css/settings.css, src/browser/settings.jsx
**Summary**
When I added the new titlebar, I neglected to add it for the Settings page. It is now added.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22073
**Test Cases**
- On Windows, when you open the settings page, you should see a titlebar.
- Each of the titlebar buttons on Windows in the settings page should function the same as they do on the main view.
- On Mac, you should see the titlebar with the normal titlebar buttons.
This wasn't tested on Mac, though I believe things should be working.
=> [MM-22073] Added new titlebar to Settings page

src/browser/components/MainPage.jsx, src/browser/components/MattermostView.jsx
**Summary**
The fix in this PR: https://github.com/mattermost/desktop/pull/1127
Was overwritten by this PR: https://github.com/mattermost/desktop/pull/1056
This PR puts the fix back.
Also found a bug where tabbing through when you've re-ordered the tabs would tab through in the wrong order, also fixed.
**Issue link**
https://mattermost.atlassian.net/browse/MM-20796
=> [MM-20796] Un-reverted the Ctrl+Tab fix and also made sure the tabs go in the right order

src/main.js
**Summary**
As per this issue: https://github.com/electron/electron/issues/19468
On desktop app v4.4, the app will hang if you are running Windows 10 dark mode.
This PR adds a workaround to fix that hang as per this workaround: https://github.com/electron/electron/issues/19468#issuecomment-549593139
**Issue link**
https://mattermost.atlassian.net/browse/MM-22193
**Test Cases**
See ticket description.
Should ensure that the app does indeed hang on v4.4-rc1 before testing this fix.
=> [MM-22193] Workaround for app hang on Windows 10 dark mode

src/main.js
**Summary**
whenever there is no connection stablished, a new connection retry is launched every few seconds, if that fails a new dialog was being presented to the user, which might end up in a stack of errors. this PR only allows one dialog per instance and error-type.
Also, on electron6 the api for the dialog moved to promises, so I updated the code for that.
**Issue link**
[MM-20832](https://mattermost.atlassian.net/browse/MM-20832)
**Test Cases**
change the date on your machine to a year in the future, connect to community and the dialog should show up. waiting for several minutes shouldn't create new dialogs.
=> [MM-20832] prevent dialog stacking, move to promises

electron-builder.json, scripts/afterpack.js
**Summary**
Linux users can't get links to open due to not having the setuid bit active. This pr changes permissions on chrome so it can send links to the browser
**Issue link**
Github https://github.com/mattermost/desktop/issues/1101
Jira [MM-21400](https://mattermost.atlassian.net/browse/MM-21400)
**Test Cases**
on a linux machine, open the app and try to have a link opened on the browser.
having `tail -f /var/log/syslog` should only show a message about blocking the URL (which is only preventing to open on the same electron window)
I've tested this on Ubuntu, we might want to test on other scenarios.
=> [MM-21400] Enable setuid on linux packaging

scripts/Makefile.ps1, scripts/dependencies.ps1, scripts/msi_installer.wxs, scripts/tools.ps1
**Summary**
Some filenames for windows added a `v` in front of the version name, this is removed now
removed fixed versions from xml file
get release version from package.json instead of tag
**Issue link**
[MM-19636](https://mattermost.atlassian.net/browse/MM-19636)
for -develop versions, it'll add the number of commits to the build version.
=> [MM-19636] make file names consistent

src/main.js
**Summary**
Trusted URL validation when a browser permission request comes through could be bypassed. This PR updates the validation to use the newer isTrustedURL() function to perform the url validation instead.
**Issue link**
[MM-20188](https://mattermost.atlassian.net/browse/MM-20188)
=> Use ‘isTrustedURL’ function to validate url

src/browser/components/MainPage.jsx
**Summary**
When switching the order of the tabs, and using `Ctrl+i` or `Cmd+i`, where `i` is the 1-based order of the tab to switch to, the app was opening the wrong tab if the order of the tabs did not match the storage order.
This PR now makes sure that the hotkey switches to the correct tab.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22585
=> [MM-22585] Ctrl/Cmd+<num> now switches to tabs based on order

src/browser/components/MainPage.jsx, src/browser/index.jsx
**Summary**
On apps using GPO configurations, when launching the app for the first time, or when adding a new team using the + button, GPO teams would sometimes be duplicated. This was caused by running `config.set('teams', <some array>)` with the GPO teams in the array, thus setting them as local teams as well.
This PR ensures that all uses of `config.set('teams', <some array>)` do not include the GPO teams.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22494
https://github.com/mattermost/desktop/issues/1189
=> [MM-22494] Fixed misuse of config.set

src/main.js, src/utils/util.js
**Summary**
custom logins weren't accounting for any path on the server configuration (subpath/team), this PR adds that option.
**Issue link**
[MM-22558](https://mattermost.atlassian.net/browse/MM-22558)
**Test Cases**
on the desktop add servers with either subpath or team configured (e.g.: https://community.mattermost.com/core)
using onelogin SSO should work properly
=> [MM-22558] fix loginurls on subpath and server's with team in the url

src/main/menus/app.js, src/main/menus/tray.js
**Summary**
Window menu items for tabs were not reordering with the tabs. This PR reorders the menu items when tabs are manually reordered.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22618
=> [MM-22618] Reorder tab menu items to match tab order

src/main.js
**Summary**
The recent update to fix support for MM subpaths missed updating the section of code that determines if a 3rd party login process has begun or is ending. This PR updates that section of code to now allow proper 3rd party authentication to work with subpaths.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22558
=> [MM-22558] Fix 3rd party login detection

src/browser/components/SettingsPage.jsx
**Summary**
When clicking on a server on the settings page to open that server's tab, if tabs were manually reordered, the proper incorrect tab can load. This PR takes into account the manual tab order to ensure that clicking on a server on the settings page will load the correct tab.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22618
=> [MM-22618] Clicking on setting team links to proper tab

src/browser/css/settings.css
**Summary**
By default, long strings like URLs containing no breaking spaces will push past the end of their containers instead of breaking. This PR forces long non-breaking strings to wrap at the end of their container.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22617
=> [MM-22617] Force wrap long server urls in setting page

src/browser/components/NewTeamModal.jsx
**Summary**
By changing the autoFocus to an html property it seems to fix the issue!
**Issue link**
https://mattermost.atlassian.net/browse/MM-22082
=> [MM-22082] - Add focus to server name field in new server modal

src/browser/components/MainPage.jsx
**Summary**
When deep linking to the root of a server and the URL doesn't end with a `/`, the URL `pathname` would be `null` and would be converted to a string as such. This PR does a null check returning a blank string if `pathname` is `null`.
**Issue link**
https://mattermost.atlassian.net/browse/MM-20742
**Test Cases**
1. Open Mattermost Desktop and add the Community server
2. Go to your browser and enter `mattermost://community.mattermost.com`
3. Press Enter and allow to open in Mattermost
4. The deep link should pop the community server up, rather than generate a Channel Not Found error.
=> [MM-20742] Null checking on URL pathname when deep linking

src/browser/components/MainPage.jsx
**Summary**
ARIA label added to the 3-dot menu button, so now it will read 'Context menu button' instead of 'Unlabelled 0 button'.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22479
**Test Cases**
1. Open Mattermost Desktop on Windows, and run JAWS screen reader
2. With the Mattermost window focused, press ALT
3. The 3-dot menu should receive focus and JAWS should read 'Context menu button'
=> [MM-22479] Added aria-label to 3-dot menu on Windows

src/main/menus/app.js
**Summary**
This PR stops the crash that happens when you try to navigate back/forward with an OAuth window open, now the back/forward buttons will correctly work with the focused window.
**Issue link**
https://mattermost.atlassian.net/browse/MM-23153
=> [MM-23153] Fixed the issue where back/forward navigation not in the main window causes the app to crash

src/browser/components/MainPage.jsx, src/browser/components/NewTeamModal.jsx
**Summary**
Focus was lost when having the new server modal and switched applications. This patch will return focus to the name input.
**Issue link**
[MM-22677](https://mattermost.atlassian.net/browse/MM-22677)
**Test Cases**
- open new server modal
- check that focus is on the name input
- alt+tab to another app and alt+tab back
- focus should be on the name input
=> [MM022677] fix focus on new server modal

src/browser/css/index.css
**Summary**
When trying to drag the title bar near the title bar buttons on macOS, dragging would not work. This PR enables dragging for that area for macOS.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22004
=> [MM-22004] Add dragability to the title bar buttons area for macOS

src/main/Validator.js, src/main/certificateStore.js, src/package-lock.json, src/package.json
**Summary**
When loading the certificate.json file, it was failing validation, this was due to several parts, one it was missing the protocol on it to validate as uri. also it wasn't loaded as an object, so i couldn't load.
Improved code and upgraded joi to next version.
**Issue link**
[MM-22434](https://mattermost.atlassian.net/browse/MM-22434)
**Test Cases**
with a server with an untrusted certificate, go throught the dialog and save the connection as valid. upon restart, no dialog should appear.
=> [MM-22434] update joi, convert to json before validating

src/main.js
**Summary**
As discussed, this will change user agent when navigating through a popup window to allow for finishing google's oauth
**Issue link**
[MM-23057](https://mattermost.atlassian.net/browse/MM-23057)
**Test Cases**
on a test server with a zoom plugin that supports oauth (ask me for one if you don't want to set it up yourself) try to start a zoom videocall.
tested on osx catalina, win10 and ubuntu 18.04
this is a temporary fix until a proper oauth2 handshake is implemented.
=> [MM-23057] add different useragent for popup windows

src/browser/components/MattermostView.jsx
**Summary**
On Windows, when creating a new server using the + button or the 'Sign into another Server' menu item, a second `webContents` would be created for that server and would cause some events to be received by the wrong `webContents`.
I'm not 100% sure why this is happening, but it would appear that while calling `focusOnWebView()` on the `MattermostView`, a call to `webview.getWebContents()` is made and removing that call causes this issue to disappear. It would appear that focusing is still working without this call, so I have removed it. My thoughts are that `getWebContents` is returning a new `WebContents` object other than the one created, but I cannot confirm for sure. This feels like an …
=> [MM-23784] Removed unnecessary code for focusing the mattermost view

src/common/config/buildConfig.js, src/common/config/index.js
If sort order was not present in buildConfig.js (or previous configuration), we will assume reasonable defaults.
**Summary**
This fixes an issue where enterprises deploying with buildConfig.js or GPO settings were getting a white screen on app startup.  It might have also affected users that upgraded their application from previous releases due to a configuration file format change.
**Issue link**
https://github.com/mattermost/desktop/issues/1224
**Test Cases**
* Define default servers in src/common/config/buildConfig.js, but leave out the order:0 parameter
* Launch application
* Confirm that application loads and displays tab, as expected.
=> [MM-23082] Fixes whitescreen issue on app upgrade / GPO / whitelabeled app deployments

src/common/config/buildConfig.js, src/common/config/index.js
Cherry pick #1246 
* Fixes whitescreen issue on app upgrade / GPO push / whitelabeled app deployments.  If sort order was not present in buildConfig.js (or previous configuration), we will assume reasonable defaults
* Fixing eslint bugs - with my apologies
* Removing order flag from sample configuration, but leaving it in the documentation.
BUGFIX: Accidentally left my custom enableServerManagement flag in place.  Reverted to default
* Making a more educated guess as to the user's desired sort order.
* Update src/common/config/index.js
Use forEach's index instead of an external one.
Co-Authored-By: Guillermo Vayá <guivaya@gmail.com>
* Update src/common/config/index.js
Let me test this, I'm not sure I understand how this logic works.  :)
Co-Authored-By: Guillermo Vayá <guivaya@gmail.com>
* …
=> [MM-23082] cherry pick of #1246

src/browser/components/MattermostView.jsx, src/main.js, src/main/cookieManager.js, src/main/downloadURL.js, src/main/menus/app.js
**Summary**
with the move to electron 6 some functions are now returning promises, this pr addresses that
**Issue link**
[MM-22231](https://mattermost.atlassian.net/browse/MM-22231)
[MM-22229](https://mattermost.atlassian.net/browse/MM-22229)
[MM-22232](https://mattermost.atlassian.net/browse/MM-22232)
**Test Cases**
for download: download a file from the proxy, on error it shouldn't crash.
for cache: use menu for clear cache and reload, after a while it should show the channel again (not get stuck in a white page)
for cookies: not really sure how to make this check, it should handle any error while flushing the cookie store and print an error on console, but I don't know what can make this fail.
=> [MM-22229] migrate some operations to promises

src/main.js
**Summary**
logic for detecting if the window was within a display was backwards. It only happened on restore, not on first launch.
**Issue link**
[MM-23195](https://mattermost.atlassian.net/browse/MM-23195)
**Test Cases**
=> [MM-23195] fix logic to detect if windows is outside of display boundaries

src/browser/components/MainPage.jsx
**Summary**
when clicking on the close button with the new tabbar, on windows (not sure why only this one) it goes through and prevents the app from losing focus, which the webapp interprets as having the window visible
**Issue link**
[MM-23215](https://mattermost.atlassian.net/browse/MM-23215)
**Test Cases**
have two users on the same channel, one on the app and another somewhere else
close the app 
mention the user on the app from the other one
expected: notification appears
=> [MM-23215] prevent mouse event to go through and click on window

src/browser/components/MattermostView.jsx, src/browser/css/components/MattermostView.css
**Summary**
We had removed the `mattermostView-hidden` class from the error state since it was causing issues with the Ctrl+Tab shortcut. Unfortunately, it meant that the `webview` was sitting on top on of the error page, making the error page not usable. This PR forces the `z-index` of the `webview` in the error state to sit below the error page itself, allowing for shortcuts to function while not displaying overtop of the error page.
**Issue link**
https://mattermost.atlassian.net/browse/MM-23663
=> [MM-23663] Fixed z-index ordering of webview vs. error page

src/browser/js/contextMenu.js
**Summary**
The issue is that in the context of the setup here webContents aren't passed to webview. What I did fixes the issue but there might be a better solution. Suggestions? 
**Issue link**
https://mattermost.atlassian.net/browse/MM-24286
Fix versions
v4.5 Desktop App
=> [MM-24286] - Fix save image functionality of context menu

scripts/release.sh
it was bothering me to have to do this every time I make a new patch version.
rc now starts at 1
issuing release patch will create a new micro-version with -rc1 suffix
no QA should be needed as this only affects the release cut process
=> Improve release

scripts/release.sh
release process is creating rc0 for new feature branches, which might be confusing for users.
no qa needed
=> fix branch releasing

src/main.js, src/main/ParseArgs.js, src/main/Validator.js, src/package-lock.json, src/package.json
**Summary**
upgrade dependencies:
- yargs 
- electron-log
Also added `--help` command line argument to find out about the others.
**Issue link**
[MM-25295](https://mattermost.atlassian.net/browse/MM-25295)
**Test Cases**
command line arguments work as expected (feel free to reach me if you need info on how to run the command line arguments)
yargs is throwing a lot of warnings in compilation for using require, I understand that they should disappear once we get babel to the main process compiler (that's happening on #1295 )
=> [MM-25295] upgrade yargs, electron-log deps, reorganized args

src/common/config/index.js
**Summary**
We had a contributor who made a fix for GPO team ordering. An unintended consequence of that change was that the physical order of the teams in `config.json` was changing on every drag and drop.
This PR maintains the ordering logic added, but ensures that the physical order will only change if a GPO team is added on config load/change.
**Issue link**
https://mattermost.atlassian.net/browse/MM-24702
**Test Cases**
=> [MM-24702] Fixed unintentional re-ordering of teams in config file

src/browser/components/NewTeamModal.jsx, src/browser/components/SettingsPage.jsx, src/browser/components/TeamList.jsx
**Summary**
When I did the changes for the New Desktop Tabs, I introduced a change to fix a flaky test here: https://github.com/mattermost/desktop/pull/1056/commits/e8e15e3a3da71b8af0f07ac6de3ef6609928b1e3
Unfortunately, this caused some visual issues when opening the Add Server Modal on the Settings Page. It appears the flaky test has been fixed so I'm reverting this change.
**Issue link**
https://mattermost.atlassian.net/browse/MM-25526
=> [MM-25526] Removed fix for flaky test causing visual issues with Add New Server flow

src/browser/components/MainPage.jsx
**Summary**
When Desktop Tabs were added a fix was made very early in the process to not restore focus to the app after the modal was closed. See here: https://github.com/mattermost/desktop/pull/1056/commits/f09ea8d2cc439b98940e2adaadb4fe1832a8d5fa
I'm not sure why this was done, as there is no PR feedback/no further comment from me, but it appears that this fix is no longer needed as restoring focus seems to work correctly. This PR will restore the ability of the modal to restore focus on close.
**Issue link**
https://mattermost.atlassian.net/browse/MM-25522
=> [MM-25522] Revert unnecessary fix for bad UX causing focus to not be restored correctly

src/browser/components/MattermostView.jsx
**Summary**
there was an uncaught error trying to reload the webcontents too soon. Nothing broke but there was an ugly message on the logs (see ticket)
**Issue link**
[MM-25681](https://mattermost.atlassian.net/browse/MM-25681)
**Test Cases**
`npm restart` doesn't show ticket's log messages.
=> [MM-25681] fix reload

src/utils/util.js
**Summary**
when adding/modifying a server, we weren't making enough tests for the url, making it crash later.
**Issue link**
[MM-25671](https://mattermost.atlassian.net/browse/MM-25671)
**Test Cases**
1. add
- click on `add a new server` (either + or settings)
- add a name for the server
- add an invalid url (like `https://comm]unity.mattermost.com` notice the `]`)
- save
2.modify
- open preferences
- edit a server
- change into an invalid url
- save
expected: raises an error of invalid url on both cases
=> [MM-25671] fix invalid urls

src/browser/css/components/TabBar.css, src/browser/css/index.css
**Summary**
On Electron apps in Windows and Linux, a `--webkit-app-drag` draggable area cannot be used to resize the window, as per this issue: https://github.com/electron/electron/issues/3022
This PR adds a small margin to the draggable area so that the topmost part of the window can facilitate resizing and the rest of the top bar can be used to drag the window.
**Issue link**
https://mattermost.atlassian.net/browse/MM-24587
=> [MM-24587] Added margin at top of draggable tab bar to facilitate resizing

src/main/CriticalErrorHandler.js, src/main/allowProtocolDialog.js, src/main/autoUpdater.js
**Summary**
on electron v6 dialog module changed to promise based functions, so all of them would return a promise.
this fixes that, reenabling trusting protocols
also while working on this, I realised the unhandled exceptions dialog wasn't working properly, so fixed it as well.
**Issue link**
[MM-22230](https://mattermost.atlassian.net/browse/MM-22230)
**Test Cases**
for the protocol question:
1. ensure you don't have spotify in your `<configpath>/Mattermost/allowedProtocols.json` or dont have that file
1. post a link with spotify protocol like: `here is a protocol link [herbie hanckock](spotify:album:5fmIolILp5NAtNYiRPjhzA)`
1. dialog should appear. if hitting save it will add an entry to the above file, …
=> [MM-22230] fix promises, reenable trust protocols, reenable capturing unhandled exceptions

src/browser/components/MainPage.jsx, src/browser/components/SettingsPage.jsx, src/main/mainWindow.js
**Summary**
This PR adds the original window border for non-Mac, non-Windows 10 clients so that the window style more accurately fits the OS being used.
This has been tested on:
- Windows 7 SP1
- Ubuntu 20.04 LTS
- Fedora 31
More testing on other operating systems should happen before this is merged.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22751
=> [MM-22751] Removed Windows 10 style border for non-Windows 10 clients

src/browser/components/MainPage.jsx, src/browser/components/MattermostView.jsx, src/browser/js/contextMenu.js, src/browser/settings.jsx
**Summary**
Provide context menu globally across electron. This means, we now have context menu on:
- add server modal (previously it only had it if it was started from the settings page) [MM-26017](https://mattermost.atlassian.net/browse/MM-26017)
- any other modal
- popup windows [MM-26076](https://mattermost.atlassian.net/browse/MM-26076)
- developer tools
**Issue link**
[MM-26017](https://mattermost.atlassian.net/browse/MM-26017)
[MM-26076](https://mattermost.atlassian.net/browse/MM-26076)
**Test Cases**
see above tickets
Additionally:
1. open webtools
2. go to network tab (or any other)
3. right click on an item, menu should appear (if it appears in chrome as well ;) )
clicking on tabs shouldn't show …
=> [MM-26017] add menu to all windows

.circleci/config.yml, scripts/Makefile.ps1
**Summary**
Builds on CircleCI currently use `npm install` for dependencies, when they should be using `npm ci`. That way `package-lock.json` does not get modified during build and we can be sure of the versions we ship. This PR fixes that.
**Issue link**
**Test Cases**
Not sure if this actually works or if there's some reason we actually have to use `npm install`, but I guess we'll see when the checks run. Also not sure how to test the PowerShell change without cutting a release.
=> Replace npm install with npm ci on CircleCI

src/main/mainWindow.js
I've yet to test on windows and ubuntu 20.20 so I'm setting the wip flag until then. but feel free to review in the meantime, it won't take long 😄 
**Summary**
Fixes a race condition when using the `--hidden` flag in the cli (or from using autolaunch) that was causing it will try to show and hide the window.
**Issue link**
[MM-26832](https://mattermost.atlassian.net/browse/MM-26832)
**Test Cases**
Two possibilities for testing the same
1. Autostart:
- set autostart on login from the preferences
- restart OS
2. Terminal
- launch the app from the command line with the `--hidden` flag
Expected:
- app should show minimized
=> [MM-26832] don't show the window until it is ready

src/browser/components/SettingsPage.jsx
**Summary**
Fixes a minor (but annoying) typo in SettingsPage.jsx. 
Before:
Setting takes **affect** after restarting the app.
After:
Setting takes **effect** after restarting the app.
That is all. Thanks ✌️
=> Fix typo in SettingsPage.jsx

src/main.js
**Summary**
Prevents showing the certificate modal if there is only one option to manage a certificate login. Will still be shown if there is more than one that suits.
Fixes https://github.com/mattermost/desktop/issues/1328
[MM-27331](https://mattermost.atlassian.net/browse/MM-27331)
=> [MM-27331] only show the picker if there is more than 1 cert

electron-builder.json
**Summary**
- Adds the missing web links protocol to desktop. 
**Issue link**
JIRA: https://mattermost.atlassian.net/browse/MM-22411
Github : https://github.com/mattermost/desktop/issues/1273
**Test Cases**
=> Fixes MM-22411 : Have the same default protocols as the server in the autolink plugin #1273

src/browser/components/MattermostView.jsx
**Summary**
Team links were not opening when setting the help link as it was trying to open in a new window and we don't allow new windows for server links unless they are popups 
**Issue link**
[MM-28595](https://mattermost.atlassian.net/browse/MM-28595)
**Test Cases**
Change the help link to a channel or some other page that it is within the server's teams. App should reload to it.
Change the help link to a page not belonging to a team (like https://google.com). A new browser tab with the page is loaded.
=> [MM-28595] Open team links within the app

src/common/config/defaultPreferences.js, src/main.js
**Summary**
Adds the showing of tray icon and minimise icon to tray default options for Linux and Mac OS as well. For the variable `minimizeTray` I only saw that it's used in Linux context that's why I updated the default options directly. But if I missed something let me know.
**Issue link**
https://mattermost.atlassian.net/browse/MM-25789
=> [MM-25789] - Update default settings for new installations

src/browser/components/MattermostView.jsx, src/main.js, src/utils/util.js
**Summary**
Navigate to admin pages when the link clicked tries to open them in a new window.
**Issue link**
[MM-28620](https://mattermost.atlassian.net/browse/MM-28620)
**Test Cases**
Go to admin console, scroll down to `Custom Terms of Service (beta)` and click on `go to Site Configuration > Customization.`
Expected: app loads the page.
since we are stopping window creation and loading a new page, it is expected to have a loading flash.
=> [MM-28620] allow navigating links to admin_console

src/browser/components/MainPage.jsx
**Summary**
fix 4.6-rc1 regression. notification of download complete was not appearing.
bug introduced in https://github.com/mattermost/desktop/pull/1351
**Issue link**
[MM-29677](https://mattermost.atlassian.net/browse/MM-29676)
**Test Cases**
upload a file to a post.
download it
Expected: notification appears announcing that the download is complete
known issue: there is no custom sound for this notification.
=> [MM-29677] fix download complete notification not appearing

src/browser/components/MainPage.jsx, src/browser/components/MattermostView.jsx, src/browser/components/NewTeamModal.jsx, src/browser/components/externalLink.jsx, src/browser/index.jsx, src/browser/js/contextMenu.js, src/browser/updater.jsx, src/common/permissions.js, src/main.js, src/main/Validator.js, src/main/certificateStore.js, src/main/trustedOrigins.js, src/utils/url.js, src/utils/util.js, test/modules/utils.js, test/specs/utils/url_test.js
**Summary**
Use URL instead of the url library throughout the project. Additionally, move all of the URL related helper functions from `src/utils/utils.js` to the new `src/utils/url.js` file and migrate tests.
**Issue link**
Fixes https://github.com/mattermost/desktop/issues/1206
**Test Cases**
This is my first contribution to this repository, so please let me know anything I may have done incorrectly! Thank you :)
=> [MM-21835] Use URL instead of the url library

scripts/msi_installer.wxs
**Summary**
Add setting to disable standard RemoveShortcuts action and keep icon pinned to taskbar on upgrade.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22960
=> [MM-22960] - Keep desktop app pinned to task bar when the app upgrades

src/main/main.js
**Summary**
fix checking server's url param when it is not a team url during attempt to navigate in the main window.
**Issue link**
[MM-31266](https://mattermost.atlassian.net/browse/MM-31266)
**Test Cases**
login via OneLogin or gitlab shouldn't crash the app
=> [MM-31266] fix access url when it's not a mm server

src/main/MattermostView.js, src/main/viewManager.js, src/renderer/components/MainPage.jsx
**Summary**
Change server load, so it reuses browserviews, preventing white pages flashes 
Fixed some errors from the renderer that were turning the tabs white
what's not fixed:
- remove `saving...` label, when changing any settings the label remains. Created ticket [MM-31554](https://mattermost.atlassian.net/browse/MM-31554)
- Sometimes it doesn't update which tab is in focus.
**Issue link**
[MM-31224](https://mattermost.atlassian.net/browse/MM-31224)
=> [MM-31224] fix reloading servers and other tab issues

src/main/main.js, src/main/utils.js, webpack.config.renderer.js
**Summary**
Changing the dev server port to 9001, as using 9000 conflicts running a local `mattermost-server` instance as the `mattermost-minio` container defaults to using port 9000.
=> Change dev server port

package.json, src/common/utils/constants.js, src/common/utils/util.js, src/main/main.js, src/main/utils.js
**Summary**
differentiating between webserver and development is no longer needed and it fixes the url view not being shown when using `npm run watch`
**Test Cases**
- `npm run watch`
- create a post with a non-team related url like `[google](https://google.com)`
- hover the url with the mouse
Expected: on the bottom left you can see the google.com url with a grey background
=> remove dev_web_server

.circleci/config.yml
**Summary**
circle is failing due to some deps having its signing key updated
**Ticket**
[MM-31923](https://mattermost.atlassian.net/browse/MM-31923)
=> [MM-31923] Fix missing key on apt-get

src/main/MattermostView.js, src/main/utils.js, src/main/windows/windowManager.js
**Summary**
There's an issue with auto resizing the `BrowserView` elements, documented here: https://github.com/electron/electron/issues/13468
This PR will resize the active `BrowserView` on the `will-resize`, `maximize`, `unmaximize`, `enter-full-screen` and `leave-full-screen` events such that the BrowserView is always in its correct place.
**Issue link**
https://mattermost.atlassian.net/browse/MM-31261
=> [MM-31261] Use manual resizing of BrowserViews on resize, maximize and full-screen

.circleci/config.yml
**Summary**
Add a workflow for CircleCI that will generate nightly builds for the browser-view branch so people can test the latests changes
**Issue link**
[MM-32108](https://mattermost.atlassian.net/browse/MM-32108)
=> add own branch for testing

src/main/windows/windowManager.js
**Summary**
Looks like the logic to minimize/maximize was reversed. Probably just a typo.
Fun fact: The reversed login worked fine on Windows 10, wonder if `maximize()`/`unmaximize()` are both just toggles in Windows.
**Issue link**
https://mattermost.atlassian.net/browse/MM-31233
=> [MM-31233] Reverse maximize logic typo

src/main/MattermostView.js, src/main/allowProtocolDialog.js, src/main/downloadURL.js, src/main/main.js
**Summary**
Protocol handling wasn't migrated over from the original `MattermostView`, so I've done that and made it work with the `webContents` object rather than `webview`.
=> [MM-31467] Move protocol handling over from original MattermostView into web contents handler

src/main/main.js
**Summary**
Prevent a crash when checking a URL
**Issue link**
[MM-29748](https://mattermost.atlassian.net/browse/MM-32392)
**Test Cases**
upload a file
open preview page and instead of using the download button, use the preview icon
expected: no crash
**Additional notes**
this doesn't fix that the download starts when using the icon.
=> [MM-32392] prevent crash when checking a URL

src/common/communication.js, src/main/main.js, src/main/viewManager.js, src/main/windows/windowManager.js, src/renderer/components/MainPage.jsx, src/renderer/components/SettingsPage.jsx
**Summary**
I've reworked how we notify the front-end wrapper that the tabs have changed externally, and made a few fixes around making sure the right tabs are picked at any given time.
What should be working now:
- Tab navigation via keyboard shortcuts
- Clicking on a server in Settings and loading it correctly
- Seamless tab dragging without reloading any servers
**Issue link**
https://mattermost.atlassian.net/browse/MM-31215
https://mattermost.atlassian.net/browse/MM-31387
=> [MM-31215][MM-31387] Fixes for bad tab navigation and dragging

src/main/windows/windowManager.js
**Summary**
fix to prevent some events being passed as content boundaries. on linux this caused a crash on start
**Issue link**
https://mattermost.atlassian.net/browse/MM-32442
**Test Cases**
resizing the window doesn't crash the app.
=> [MM-32442] Fix event as content bound

src/main/menus/app.js
**Summary**
toggle devtools tries to restore to the last known position of the devtools, so it might end below the browserview, checking and using open with detach mode prevents this from happening. Also removes the option to reattaching the window.
**Issue link**
[MM-32424](https://mattermost.atlassian.net/browse/MM-32424)
=> [MM-32424] fix server devtools being hidden by browserview

src/main/MattermostView.js, src/main/menus/app.js, src/main/windows/mainWindow.js, src/main/windows/windowManager.js
**Summary**
Copying anything from the about window was crashing and the only way to make it work is to use the role instead of a custom function. I tried to use commands while focusing on the renderer but seems I can't copy anything from the tabs or zoom in there (which is the expected and desirable) so I moved some commands to use roles, and removed any click function that was already with a role property (it gets ignored)
additionally it fixes focus issues when starting or alt-tabbing
**Issue link**
[MM-20227](https://mattermost.atlassian.net/browse/MM-20227)
[MM-31388](https://mattermost.atlassian.net/browse/MM-31388)
=> [MM-20227][MM-31388] move to roles and fix focus

src/main/main.js
**Summary**
We were currently handling public links by treating the `/files` route as another team, which was opening images in the BrowserView. This PR switches over to opening public links in the user's default browser so that all files can be handled correctly and the app will not get into a weird state.
**Issue link**
https://mattermost.atlassian.net/browse/MM-32333
=> [MM-32333] Open public links in the user's default browser

src/main/windows/windowManager.js
**Summary**
`will-resize` was not being called when the window moved back to its original monitor on replug on macOS.
`resize` seems to be a lot more reliable and smoother, also takes care of the maximize/minimize case.
**Issue link**
https://mattermost.atlassian.net/browse/MM-32382
=> [MM-32382] Use resize event instead of will-resize for monitoring size of BV

src/renderer/css/components/HoveringURL.css, src/renderer/modals/urlView/urlView.jsx
**Summary**
Most of our app uses the Open Sans font, so this PR brings the URL preview modal in-line with that.
**Issue link**
https://mattermost.atlassian.net/browse/MM-32570
=> [MM-32570] Use OpenSans as the font for the URL preview modal

src/main/windows/windowManager.js, src/renderer/components/SettingsPage.jsx
**Summary**
When updating the config from the settings window, we weren't sending the call to synchronize the config back to the settings window, only the main window. Now we are able to update the config outside of the settings window as well and have those changes reflected in the settings window.
**Issue link**
https://mattermost.atlassian.net/browse/MM-31554
=> [MM-31554] Add listener for config synchronization on the settings window

src/main/allowProtocolDialog.js
**Summary**
Make `No` the default choice when asking if a protocol should be added
**Issue link**
[MM-31383](https://mattermost.atlassian.net/browse/MM-31383
)
=> [MM-31383] Make no the default when asking to add a protocol

package-lock.json, package.json, src/common/config/RegistryConfig.js
**Summary**
I found a modded version of `node-winreg` that actually supports UTF-8 correctly by changing the code page of the console when the call to `reg.exe` is executed. This allows special characters to work correctly with GPO servers.
**Issue link**
https://mattermost.atlassian.net/browse/MM-25122
=> [MM-25122] Use modded version of winreg that supports UTF-8

src/renderer/components/TeamList.jsx
**Summary**
When I migrated over the ESLint configuration from the webapp, I had changed the use of `self` here to `this`. I thought I had tested it, but turns out that the context here wasn't the class, so I've reverted to `self`.
Funny enough, the ESLint warning seems to be gone anyhow...
**Issue link**
https://mattermost.atlassian.net/browse/MM-33141
=> [MM-33141] Fixed use of bad context in TeamList

src/browser/js/contextMenu.js, src/main/SpellChecker.js, test/specs/spellchecker_test.js
**Summary**
Add swedish sv-SE already in simple-spellchecker
=> Add Swedish sv-SE (already in simple-spellchecker)

src/main/notifications/Mention.js, src/main/notifications/index.js
**Summary**
On Windows, when receiving multiple notifications sequentially, the application would show them in order but there would be a delay between each notification and if there was a large number of notifications, the application would spam the user.
This PR stops the spam of notifications by only storing the last notification from each channel id in the Notifications Center and auto-dismissing all previous notifications.
**Issue link**
https://mattermost.atlassian.net/browse/MM-25355
=> [MM-25355] Throttle notifications for Windows by channel id

src/main/MattermostView.js
**Summary**
When switching between tabs, we check if the back bar should be displayed. Unfortunately, we didn't account for the `admin_console` route and you would see the back displayed when switching back to a tab on the `admin_console`.
Now we check for the `admin_console` route specifically.
NOTE: Are there any other routes we should be checking for that don't need the back button?
**Issue link**
https://mattermost.atlassian.net/browse/MM-33238
=> [MM-33238] Check for admin URL when toggling back bar

package-lock.json, package.json
**Summary**
upgrade electron-context-menu so it upgrades electron-dl which was causing the crash.
**Issue link**
[MM-31342](https://mattermost.atlassian.net/browse/MM-31342)
**Test Cases**
click on a profile picture and use `save image` or `save image` as context menu options
=> [MM-31342] fix "save image as" context menu crash

src/main/windows/mainWindow.js
**Summary**
If you have a tab near the center of the tab bar on macOS, and try to click on the top-most portion of it, the tab would not register a click event and thus not respond.
This is due to the way that Electron was insetting the traffic light buttons, causing some kind of overlap over the tabs. This PR changes the `titleBarStyle` to `hidden` and manually sets the inset, which seems to solve the issue.
**Issue link**
https://mattermost.atlassian.net/browse/MM-33032
=> [MM-33032] Use `hidden` titleBarStyle value to fix macOS Catalina click issue

src/common/config/index.js, src/main/main.js, src/main/menus/app.js
**Summary**
@Willyfrog has already done the work to use the native dark mode option provided by Electron, so I'm just cleaning up by removing the menu item for Windows.
EDIT: The toggle wasn't working for non-Windows/macOS machines so I've enabled that as well.
**Issue link**
https://mattermost.atlassian.net/browse/MM-32809
=> [MM-32809] Remove Toggle Dark Mode menu item for Windows, enable toggling on Linux

src/main/menus/app.js
**Summary**
When we moved a bunch of the menu shortcuts over to roles, some of the keyboard shortcuts disappeared. This PR restores them.
**Issue link**
https://mattermost.atlassian.net/browse/MM-33334
=> [MM-33334] Restore keyboard shortcuts for menu items moved to roles

src/renderer/modals/finder/finder.jsx
**Summary**
The Finder used to perform its cleanup on `componentWillUnmount`, which will not run when destroying a `BrowserView`. This PR moves the cleanup to the `close()` function that runs on pressing Escape or clicking the 'x' button.
**Issue link**
https://mattermost.atlassian.net/browse/MM-33542
=> [MM-33542] Trigger finder cleanup on pressing close or Escape

src/main/main.js, src/main/menus/app.js, src/renderer/components/MainPage.jsx, src/renderer/components/TabBar.jsx, src/renderer/index.jsx
**Summary**
This PR fixes a few things:
- Some old dead badge updating code in the renderer process was causing some console errors, those have been cleaned up.
- The unread dot that would normally appear wasn't appear due to some conflicts in the object type of `unreadCounts`. We're now using `object` for both unreads and mentions and this has been fixed in all components.
- A couple lint issues :P
**Issue link**
https://mattermost.atlassian.net/browse/MM-33607
=> [MM-33607] Remove old badge code, update unreads code

src/main/views/webContentEvents.js
**Summary**
Previously, we had a `webview` handler deal with linking between different servers, but since that's gone, we were only using the `webContents` handler, which was missing any way of linking between servers.
This PR leverages the deeplinking mechanism (which is similar to what we were doing previously) to allow inter-server links to be opened within the app.
**Issue link**
https://mattermost.atlassian.net/browse/MM-33247
=> [MM-33247] Have the app handle links to other teams as a deep link

src/main/badge.js, src/main/windows/windowManager.js
**Summary**
We were missing using the smaller font for when the mention count was over 99, which is needed to make the badge look nice. This PR restores that in `browser-view`.
**Issue link**
https://mattermost.atlassian.net/browse/MM-33373
=> [MM-33373] Trigger the smaller font for 99+ mentions

src/main/tray/tray.js
**Summary**
on Mac OS switching theme causes the read/mention state to be lost. this pr fixes that problem
**Issue link**
[MM-33551](https://mattermost.atlassian.net/browse/MM-33551)
=> [MM-33551] Keep tray state

src/main/preload/mainWindow.js, src/main/views/MattermostView.js, src/main/views/webContentEvents.js, src/main/windows/mainWindow.js, src/main/windows/settingsWindow.js, src/renderer/components/MainPage.jsx, src/renderer/components/SettingsPage.jsx, src/renderer/components/TabBar.jsx, src/renderer/index.html, src/renderer/index.jsx, src/renderer/settings.jsx, src/renderer/updater.jsx, webpack.config.main.js
**Summary**
Some security fixes:
- Defined a Content Security Policy for all BrowserWindows created (using index.html, which they all should be using). Currently enables `unsafe-inline` for styles, which was required for either `react-smooth-dnd` or `react-bootstrap`. Follow-up ticket: https://mattermost.atlassian.net/browse/MM-34152
- Enabled `contextIsolation` and disabled `nodeIntegration` for the main and settings windows, so that neither of them can access Node modules. Done for security. Added a preload script that uses `contextBridge` to expose ONLY the required functionality for the renderer process to work (ie. ipcRenderer, some platform information). We could probably go a step further and lock this down to only our functions so that there's even less ways arbitrary calls could …
=> [MM-33828] Define CSP for all BrowserWindows, enable contextIsolation for main/settings window, other fixes

src/main/views/MattermostView.js, src/main/views/modalView.js, src/main/views/viewManager.js
**Summary**
When we upgraded to Electron v11, `BrowserView.destroy()` was removed, with Electron electing to have Node manage the objects once removed. However, as indicated by this post: https://github.com/electron/electron/pull/23578#issuecomment-742150830, if you don't explicitly destroy the `webContents` object inside, a zombie will persist.
This was causing issues when hovering links or opening modals, as we would create the BrowserView and then simply set its reference to null. Doing this multiple times would result in a lot of zombies.
This PR explicitly destroys the `webContents` object on each `BrowserView` destroy to avoid this issue.
**Issue link**
https://mattermost.atlassian.net/browse/MM-34067
=> [MM-34067] Explicitly destroy web contents in non-permanent BrowserViews

src/main/views/webContentEvents.js
**Summary**
If a url doesn't parse it shouldn't crash the app
**Issue link**
[MM-34201](https://mattermost.atlassian.net/browse/MM-34201)
**Test Cases**
create a group link (like `@appsteam`) and click on it
=> [MM-34201] fix non-links crashing the app

src/main/menus/app.js, src/main/windows/windowManager.js
**Summary**
When we switched over to the new method for finding messages in the desktop app, we removed the menu item.
This PR restores the menu item and forwards the keyboard shortcut to the webapp.
**Issue link**
https://mattermost.atlassian.net/browse/MM-34461
=> [MM-34461] Restore Find menu item

src/main/windows/windowManager.js
**Summary**
This is a workaround for the maximizing issue on Linux, by using `setTimeout` to run the resize code for BrowserViews a short time after the initial maximize event has run.
**Issue link**
https://mattermost.atlassian.net/browse/MM-33577
=> [MM-33577] Workaround for Linux minimizing/maximizing issue

src/common/utils/util.js, src/main/views/MattermostView.js, src/main/views/webContentEvents.js, src/renderer/css/components/TabBar.css, src/renderer/css/settings.css
**Summary**
Pages were reloading after loading for the first time due to an exception being raised, which was treated as a load failure.
Also fixed long names getting in the way in several places.
**Issue link**
[MM-34527](https://mattermost.atlassian.net/browse/MM-34527)
**Screenshots**
=> [MM-34527] fix reload and long names

src/main/menus/app.js
**Summary**
During the refactor the key to learn more url was inadvertently edited which prevented showing the menu item. This pr corrects the key.
**Issue link**
[MM-34459](https://mattermost.atlassian.net/browse/MM-34459)
**Screenshots**
=> [MM-34459] Fix config key to show 'learn more'

.circleci/config.yml
**Summary**
grep -v seems to be using a regex to filter, this should prevent treating `.` as a wildcard
=> prevent eager filtering

src/renderer/css/components/TabBar.css
**Summary**
Set `max-width` on the server tabs to 224px, using the entire wrapped `div` instead of the inner label `span`
**Issue link**
https://mattermost.atlassian.net/browse/MM-34564
=> [MM-34564] Set max-width on the server tabs to 224px

src/renderer/components/SettingsPage.jsx, src/renderer/css/settings.css
**Summary**
On the Settings page, if the window is large enough the first setting would sit next to the header and save indicator.
This was caused by setting `float: left` on those elements.
This PR changes the elements to use `display: inline-block` so that the header and save indicator are next to each other while each subsequent `div` is correctly stacked.
**Issue link**
https://mattermost.atlassian.net/browse/MM-34645
=> [MM-34645] Align App Options header and save indicator using display: inline-block instead of float: left

src/main/contextMenu.js, src/main/views/MattermostView.js, src/main/views/modalView.js, src/main/views/viewManager.js, src/main/windows/mainWindow.js, src/main/windows/settingsWindow.js
**Summary**
Instead of using one context menu object and re-assigning it based on active view, we now create a new `electronContextMenu` object for each view so that the views are able to manage their own menus and each one will have one.
**Issue link**
https://mattermost.atlassian.net/browse/MM-34494
=> [MM-34494] Encapsulate context menu in a class object and add it to each view as necessary

src/common/communication.js, src/main/windows/mainWindow.js, src/main/windows/settingsWindow.js, src/renderer/components/MainPage.jsx
**Summary**
Fix 2 full-screen issues:
- Fullscreen status wouldn't restore when the app was restarted
- When opening the settings window in fullscreen mode, the window would get stuck in fullscreen and there was no way of getting out of it, so I've prevented the window from full-screening at all on opening.
**Issue link**
https://mattermost.atlassian.net/browse/MM-34890
https://mattermost.atlassian.net/browse/MM-34897
=> [MM-34890][MM-34897] Fix some fullscreen issues

src/main/appState.js, src/main/badge.js, src/main/main.js
**Summary**
The `showUnreadBadge` setting was not being observed when setting the badge. This PR adds a variable for the setting and an updater such that the badge will turn on and off when the setting is toggled.
**Issue link**
https://mattermost.atlassian.net/browse/MM-34594
=> [MM-34594] Only show dock badge when the setting is enabled

src/main/tray/tray.js
**Summary**
Since we are now using templates on macOS, we dont need to set pressed images
**Issue link**
[MM-35007](https://mattermost.atlassian.net/browse/MM-35007)
=> [MM-35007] don't try to use pressed images with templates

src/main/windows/windowManager.js
**Summary**
When calling `show()` on a BrowserWindow, the app, if tiled, would revert to an untiled state. This PR only calls `focus()` if the BrowserWindow is already visible and only calls `show()` if the window is not visible to the user.
**Issue link**
https://mattermost.atlassian.net/browse/MM-34884
=> [MM-34884] Only call `show()` on an existing mainWindow if the window is actually closed or hidden

src/main/windows/windowManager.js
Cherry-pick of #1552 to `release-4.7`
=> [MM-34884] Only call `show()` on an existing mainWindow if the window is actually closed or hidden (#1552) - cherry-pick

electron-builder.json
**Summary**
added quarantine to files downloaded from mattermost
this is added as part of the info.plist so the OS is responsible to enforce it
**Issue link**
[MM-20677](https://mattermost.atlassian.net/browse/MM-20677)
**Test Cases**
Download a .terminal file created from the terminal app (menu->
**Screenshot**
=> [MM-20677] Quarantine files downloaded from electron

.github/PULL_REQUEST_TEMPLATE.md
Add a release not section in the PR template to facilitate the release note process.
After this PR get approval, I will setup the webhook
JIRA: https://mattermost.atlassian.net/browse/DOPS-371
This PR was tested on: N/A
N/A
```release-note
NONE
```
=> add PR/Issue template and release notes section in the PR template

scripts/cp_artifacts.sh
see original https://github.com/mattermost/desktop/pull/1559
```release-note
NONE
```
=> [MM-35010] Fix m1 release pipeline (cherry-pick v4.7)

src/common/utils/url.js, src/main/views/webContentEvents.js, test/unit/index.js, test/unit/url_test.js
When working with URLs that have multiple slashes in the pathname, if we tried to match them using one of our `is___URL` functions they wouldn't match due to the extra slashes.
This PR adds some code to cleanse the extra slashes out of URLs (since apparently the URL library doesn't do that on parsing), and explicitly defines the image proxy case such that those links will open in a browser.
https://mattermost.atlassian.net/browse/MM-34836
```release-note
NONE
```
=> [MM-34836] Cleanse URLs of extra slashes on parsing, and add the image proxy case

.circleci/config.yml
In order to help rainforest testing, we need to provide the same link for every daily build, so we rename the files removing its version and adding daily so they can be easily recognized
```release-note
NONE
```
=> Make daily links in s3 look always the same to help with rainforest

electron-builder.json
remove libappnotify1 as a dependency as it is being deprecated in newer debian  versions.
fixes #1570 
[MM-35278](https://mattermost.atlassian.net/browse/MM-35278)
```release-note
Removed libappnotify1 as a dependency requirement in deb installers as it is no longer shipped in Debian's Bullseye. It is still recommeded to install where available.
```
=> [MM-35278] Remove dependency libappindicator1

electron-builder.json
Cherry-pick of #1572 
```release-note
Removed libappnotify1 as a dependency requirement in deb installers as it is no longer shipped in Debian's Bullseye. It is still recommeded to install where available.
```
=>  [MM-35278] Remove dependency libappindicator1 (cherry-pick v4.7)

src/main/main.js
`electron-context-menu` uses the default downloads path provided by the app when saving stuff. Turns out that we can actually override that, so I've done that.
https://mattermost.atlassian.net/browse/MM-35131
```release-note
NONE
```
=> [MM-35131] Set default app downloads path to specified path in config

.circleci/config.yml
fix path names for renaming to daily builds so rainforest doesn't need to figure it out.
follow up to https://github.com/mattermost/desktop/pull/1568
```release-note
NONE
```
=> fix wrong folder name for s3_daily

src/common/config/defaultPreferences.js, src/main/main.js
When I had forced the entire app to use the downloads path we use in our config, it revealed that we were defaulting to a path used only by Mac. So now we support Windows and Linux (and don't set a default for other OSes) and will only set the path if it exists at all.
https://mattermost.atlassian.net/browse/MM-35454
```release-note
NONE
```
=> [MM-35454] Fix default downloads path for Windows and Linux, only set for the app if the path is not blank

src/common/config/defaultPreferences.js, src/main/main.js
Cherry-pick of #1583 to `release-4.7`
=> [MM-35454] Fix default downloads path for Windows and Linux, only set for the app if the path is not blank (#1583) - cherry-pick

src/main/preload/mattermost.js
When a Mattermost server wasn't loaded, the preload script can sometimes generate an `undefined` error. So we now check that the object exists before running `toUpperCase`.
https://mattermost.atlassian.net/browse/MM-35245
```release-note
NONE
```
=> [MM-35245] Null check to prevent console error in preload script on unloaded server

src/main/views/MattermostView.js
The value of `window.innerWidth` was being calculated as 0 when the Mattermost app was first loaded inside of BrowserView. This is because we didn't set the bounds of the view until much later, so we now set the bounds on successful loading of the URL.
https://mattermost.atlassian.net/browse/MM-35249
```release-note
NONE
```
=> [MM-35249] Set window bounds on initial load success

.circleci/config.yml, scripts/msi_installer.wxs
The shortcut produced by the MSI installer was malformed and was causing an issue when clicking on a notification that wouldn't open the application. I've removed the offending line that doesn't need to be there.
Thanks a bunch to @zpersichetti for finding this for us! :)
https://mattermost.atlassian.net/browse/MM-19510
https://mattermost.atlassian.net/browse/MM-19511
https://github.com/mattermost/desktop/issues/1523
```release-note
Fixed an issue with the MSI build that caused notifications when clicked, to not open the application and navigate to the correct channel.
```
=> [MM-19510][MM-19511] Remove ToastActivatorCLSID from Start Menu shortcut on Windows

scripts/msi_installer.wxs
Cherry-pick of #1590 to `release-4.7`
=> [MM-19510][MM-19511] Remove ToastActivatorCLSID from Start Menu shortcut on Windows (#1590)

src/renderer/components/SettingsPage.jsx
When pressing Cancel on the download location dialog, it would set the download location in the config to undefined. This was because we weren't checking for an undefined response from the dialog, so now we do.
https://mattermost.atlassian.net/browse/MM-35131
```release-note
NONE
```
=> [MM-35131] Don't set the download location in config if we hit Cancel

src/main/windows/windowManager.js
Apparently the fix I added for Linux resizing wasn't enough, as the outer window doesn't seem to resize properly. So we have to add a `setTimeout` as a workaround. See comments for the bugs that are affecting this.
https://mattermost.atlassian.net/browse/MM-35781
```release-note
NONE
```
=> [MM-35781] Another workaround for Linux resizing

electron-builder.json
adds an option to also build rpm packages for deployment in RPM based distros like Fedora and RHEL
we should probably mark this as unoffical or something like that for now.
But tested and working on Fedora 34 with latest master.
=> add rpm build option to electron builder

src/renderer/index.html
When trying to play notification sounds from the desktop app, the CSP in our app wrapper was stopping the sounds from playing. This PR allows those `data:` URIs to play correctly.
https://mattermost.atlassian.net/browse/MM-35662
```release-note
NONE
```
=> [MM-35662] Added media-src tag to CSP to allow data blobs to play for notification sounds

src/main/main.js, src/renderer/components/SettingsPage.jsx
Cherrypick of #1613 to `release-4.7`
=> [MM-35984] Make sure Select Downloads Folder dialog always uses the default location if none is selected (#1613) - cherrypick

package-lock.json, package.json
Update to electron v12.0.10
fixes #1080 and fixes  #1399 as well as some other issues (see [release notes of electron v12.0.10 and v12.0.9](https://www.electronjs.org/releases/stable?version=12))
tested `alt+shift` doesn't trigger menu, `alt` by itself does trigger it.
OS ubuntu 21.04
[MM-19601](https://mattermost.atlassian.net/browse/MM-19601)
```release-note
update to v12.0.10, fixed alt+shift problem on Linux.
```
=> [MM-19601] Update to v12.0.10, fix alt issue in linux

.circleci/config.yml
Renames distributable Mac files from arm64 to m1
It downloads rename directly instead of using brew as CircleCI is [having some trouble with brew](https://discuss.circleci.com/t/macos-image-users-homebrew-brownout-2021-04-26/39872) at the moment.
[MM-35581](https://mattermost.atlassian.net/browse/MM-35581)
```release-note
rename package from arm64 to m1 on CI
```
=> [MM-35581] Rename arm64 to m1

.circleci/config.yml
Rename arm64 builds to m1 so people can find them. See #1620 
```release-note
arm64 mac builds are now named m1 so people can easily spot them
```
=> [MM-35581] Rename arm64 to m1 (Cherry-pic #1620)

src/main/tray/tray.js
#1595 changed the comparison to use equal which is not an operation of a string
[MM-36340](https://mattermost.atlassian.net/browse/MM-36340)
This PR was tested on: Ubuntu 21.04
```release-note
NONE
```
=> [MM-36340] fix linux  theme comparison

src/common/config/index.js, src/main/views/viewManager.js
When adding a server with a different name but the same URL, the app would crash due to differences between what the config was reporting as the server list, and what views actually exists. Now the config will filter on both the server name and URL, effectively allowing users to access the same server with multiple different names,
NOTE: You can still add the same server (ie. same name and URL) twice, it just won't cause a crash. We should be adding some validation on server creation to remedy this in a future ticket.
https://mattermost.atlassian.net/browse/MM-36030
```release-note
NONE
```
=> [MM-36030] Allow for duplicate servers with different names to behave normally

.circleci/config.yml, scripts/generate_release_markdown.sh
Rename was occurring after persisting the workspace, so changes were lost when circle job ended
Also, add rpm to the list of files in the release.
Follow up to #1620 and #1611 
```release-note
NONE
```
=> [MM-35581] fix m1 rename not being persisted, add rpm to release

src/main/certificateManager.js
When there is more than one client certificates that fits to authenticate, we show a modal for choosing the right one. currently this was failing as it was using an old method for detecting were to get the preload info, updating to the new one seems to fix the issue.
[MM-30147](https://mattermost.atlassian.net/browse/MM-30147)
[MM-30146](https://mattermost.atlassian.net/browse/MM-30146)
```release-note
NONE
```
=> [MM-30147] [MM-30146] fix loading path for cert modal

src/main/views/MattermostView.js
When removing a tab, we destroy the webcontents object to ensure we don't end up with zombies processes. However, our retry timer still exists and we need to make sure that we don't load anything if the tab has been removed. So we simply check to see if webcontents still exists before trying to load anything into it.
https://mattermost.atlassian.net/browse/MM-36543
```release-note
NONE
```
=> [MM-36543] Check for webcontents before trying to load url in case tab was removed

src/common/config/index.js, src/main/main.js
Disabling the gpu once the app is ready had some unexpected results (see #1645 ) this will trigger reading the config file and applying the change before the app is ready and before it finishes reading the registry (which is really slow in windows)
After merging this, we'll need to reimplement it in master as TS, so don't cherry pick.
Fixes #1645 
Jira: [MM-36938](https://mattermost.atlassian.net/browse/MM-36938)
This PR was tested on: windows 10 with and without GPO policies
```release-note
Fixed GUI missbehaviour by disabling GPU after app initialization.
```
=> [MM-36938] Disable gpu before reading the registry

src/common/config/defaultPreferences.js, src/main/main.js
If the path is not absolute, the app crashes. Also removed custom function that was assuming user's home dir was in `C:/` drive by a node api call.
Once merged, we'll need to recreate this in master.
[MM-37117](https://mattermost.atlassian.net/browse/MM-37117)
```release-note
Prevented crash on malformed default download location.
```
=> [MM-37117] Prevent crashing if the download path is not set correctly

src/common/config/defaultPreferences.ts, src/main/main.ts
Cherry pick from #1659 
[MM-37117](https://mattermost.atlassian.net/browse/MM-37117)
```release-note
Prevented crash on malformed default download location.
```
=> fix crash on invalid download paths

src/renderer/components/MainPage.tsx
In certain circumstances, for example, if there are no current servers, the server key in the renderer process was calculating to -1 or NaN. This PR ensures that it's always a number and must be at least 0 (ie. a valid array index)
https://mattermost.atlassian.net/browse/MM-36998
=> [MM-36998] Ensure server key must be at least 0

src/common/config/index.js, src/main/Validator.js, src/main/main.js, src/main/views/MattermostView.js, src/renderer/components/SettingsPage.jsx
This PR allows people who would prefer not to download dictionary definitions from chromium's CDN to use an alternate url.
This requires a separate PR for documenting the process.
This requires a separate PR for cherry-picking into master as we moved towards TS
Testing this is complicated, I've detailed the steps in the jira ticket, but feel free to DM me if you need any help
Fixes #1642 
[MM-36747](https://mattermost.atlassian.net/browse/MM-36747)
This PR was tested on: windows and linux
```release-note
Allow users to specify a different download location for hunspell dictionaries
```
=> [MM-36747] Allow users to specify spellchecker url for downloading dictionaries

package-lock.json, package.json
A breaking change was introduced into Electron v12.0.2 that causes the top part of our BrowserViews for Mattermost to become draggable, matching the draggable area added to the main window. This PR reverts us back to v12.0.1 where this issue does not exist.
I will be filing a bug with Electron to point out the issue.
https://mattermost.atlassian.net/browse/MM-36753
```release-note
NONE
```
=> [MM-36753] Revert to Electron v12.0.1

src/main/views/MattermostView.js
Remove memoization as a possible cause for not removing the unread/mention mark
Also this can't be cherry-picked directly, so once we merge this we'll need to do a separate PR to master replicating.
[MM-35946](https://mattermost.atlassian.net/browse/MM-35946)
This PR was tested on: windows 10, MacOS X
I haven't been able to reproduce with this build, but this doesn't mean it might still happen if there are other causes, so I'd like to have as much feedback as possible on this one.
```release-note
Fix badge not updating properly on some setups
```
=> [MM-35946] Remove memoization to prevent errors on detecting unread/mention state

package-lock.json, package.json
Cherrypick of #1665 to `release-4.7`
=> [MM-36753] Revert to Electron v12.0.1 (#1665) - cherrypick

webpack.config.base.js
I was having trouble building from master, and seems we [couldn't resolve .json files](https://github.com/MarshallOfSound/electron-devtools-installer/pull/60#issuecomment-320229210). this should fix it.
This PR was tested on: compiles on macOS big sur
```release-note
NONE
```
=> allow webpack to resolve .json

src/main/preload/mattermost.js
Seems electron-log requires os when compiled for the preload script (probably due to it being compiled for the main process instead of the renderer one). I've [filed an issue for it](https://github.com/megahertz/electron-log/issues/267), so if it gets resolved we can go back to use electron-log.
this might need to be manually cherry-picked to 4.7 before rc, I'll check the branch and do the PR there if needed.
This PR was tested on: MacOs BigSur
```release-note
NONE
```
=> remove electron-log from preload

src/common/config/index.js
make handlers available before finishing reading the registry
[MM-37480](https://mattermost.atlassian.net/browse/MM-37480)
```release-note
fixed crash on windows due to configuration handlers not being ready
```
=> [MM-37480]Fix no handler

package-lock.json, package.json, scripts/cp_artifacts.sh
`npm run package:X` was failing due to a problem of our version of electron-builder with node v16. upgrading fixes the problem.
This PR was tested on: macOS Big Sur
```release-note
NONE
```
=> make electron builder compatible with node v16

.circleci/config.yml
We upgraded `electron-builder` to v22.11.x, which should be using Node v14+. Unfortunately, the `mac_installer` uses Node 12 by default, so we have to upgrade it on build.
```release-note
NONE
```
=> Fix mac installer

src/renderer/css/dropdown.scss
This PR fixes a style issue where a long server name would cause wrapping within the dropdown menu.
https://mattermost.atlassian.net/browse/MM-37646
```release-note
NONE
```
=> [MM-37646] Fixed long server name style issue

package.json
In some cases, the old `src/node_modules` folder that existed in v4.6 and earlier causes problems when running webpack. More recently it was compiling an older version of `react-bootstrap` which causes the app not to function correctly.
Now we will make sure to blow it away on `npm run clean` so that if its there causing issues again it will get deleted and fix that issue.
```release-note
NONE
```
=> Remove old `src/node_modules` on `clean` if it exists

src/common/utils/url.ts
We were explicitly checking for `null` when calling `isValidURL`, when it now returns `undefined`. So the check has been fixed to check for falsy instead.
https://mattermost.atlassian.net/browse/MM-37743
```release-note
NONE
```
=> [MM-37743] Fix URL validation when editing/adding a server

src/main/windows/windowManager.ts, src/renderer/components/SettingsPage.tsx
The setting determining whether the window should flash or not on Windows/Linux when a new mention arrives was not being checked before flashing the window, so we've re-added the check.
https://mattermost.atlassian.net/browse/MM-37797
```release-note
Fixed an issue where the window would flash on Windows/Linux when a new mention arrives regardless of the setting to turn it on/off.
```
=> [MM-37797] Re-added the check for flashing the window

src/main/views/webContentEvents.ts
Some login providers like GitLab require a CloudFlare check before hitting the login page, which will trigger a redirect. This PR allows us to stay in 'custom login' mode until we return back to the application.
https://mattermost.atlassian.net/browse/MM-36923
```release-note
NONE
```
=> [MM-36923] Wait to return to the application before turning off the custom login setting

src/main/main.ts, src/main/notifications/index.ts, src/main/preload/mattermost.js
Clicking on a notification that regards a reply to a thread,
and when the user has CRT set to ON, should open the corresponding thread.
This is done by passing the URL to push to the browser along side the
notification.
Webapp: If a `url` is passed it will be used, otherwise the URL pushed to
history would be the corresponding channel (as is right now).
https://mattermost.atlassian.net/browse/MM-36234
This PR was tested on: MacBook Pro, Version 11.2.3
```release-note
NONE
```
=> MM-36234: CRT, handle click on notification

electron-builder.json
`electron-builder.json` had the wrong path for some of the linux assets, this PR fixes that.
https://mattermost.atlassian.net/browse/MM-36577
```release-note
NONE
```
=> [MM-36577] Fix electron-builder path for linux files

src/renderer/components/SettingsPage.jsx
Invert the logic so the check can be actioned
fix over [MM-37797](https://mattermost.atlassian.net/browse/MM-37797)
```release-note
NONE
```
=> [MM-37797] Invert check logic

.circleci/config.yml
we saw some time out while building the MAC app https://app.circleci.com/pipelines/github/mattermost/desktop/2783/workflows/1553e084-09d6-4de4-a705-4fe562113240/jobs/12710
increasing to 30m without no output, but might be an issue in the apple signing service as well
n/a
```release-note
NONE
```
=> add no_output_timeout to 30m (default 10m)

src/main/windows/windowManager.ts
When resizing, we weren't checking if the URL could have been an admin link, so now we are so that the space for the back bar doesn't show up when it doesn't need to.
https://mattermost.atlassian.net/browse/MM-38301
```release-note
Fixed an issue where resizing the app while in the System Console causes a white bar to appear at the top.
```
=> [MM-38301] Check for admin URL when adding space for back bar

src/main/main.ts, src/main/windows/windowManager.ts
The menubar isn't needed on Linux/Windows since we define our own dropdown menu, so I've completely removed it for both.
https://mattermost.atlassian.net/browse/MM-36309
```release-note
Fixed an issue where pressing `Alt+<somekey>` could cause the menubar to disable and overlap the top bar on Linux.
```
=> [MM-36309] Completely remove menu bar from Linux/Windows

src/common/communication.ts, src/common/tabs/BaseTabView.ts, src/common/tabs/MessagingTabView.ts, src/common/tabs/TabView.ts, src/main/main.ts, src/main/notifications/index.ts, src/main/preload/mattermost.js, src/main/views/MattermostView.ts, src/main/views/viewManager.ts, src/main/windows/windowManager.ts, src/renderer/components/MainPage.tsx, src/renderer/components/TabBar.tsx
Fixed a few issues with multiple tabs:
- Tab tooltips were showing the tab type instead of the display name
- Notifications were being sent from all 3 tabs instead of just the Channels tab
- Notifications were showing the view name instead of the server name
- Notifications were not navigating to the correct tab
- Last active tab was not being remembered
https://mattermost.atlassian.net/browse/MM-38310
https://mattermost.atlassian.net/browse/MM-38313
https://mattermost.atlassian.net/browse/MM-38315
```release-note
NONE
```
=> [MM-38310][MM-38313][MM-38315] Fixed some issues caused by having multiple tabs

src/main/menus/app.ts
The Mattermost desktop app's Window menu on macOS is highly non-standard.
A typical macOS app's Window menu contains, in order:
- Minimize
- Zoom
- Tile Window (or Move Window, depending on window type) to Left of Screen
- Tile Window (or Move Window, depending on window type) to Right of Screen
- Separator
- Move to [name of next display] (when multiple displays are connected)
- Separator
- [Other app-specific window options]
- Separator
- Bring All to Front
- Separator
- [List of current windows for the app]
Example, for the Finder app:
Mattermost is missing most of these items. In fact, the only standard item it has is Minimize. (Close Window is normally in the File menu, not the Window menu.)
Here's a current screenshot from master:
However, most of the missing items can been added …
=> Make the Window menu on macOS more standard

src/renderer/components/MainPage.tsx, src/renderer/components/TabBar.tsx, src/renderer/components/TeamDropdownButton.tsx
When no servers are configured, the Add Server modal pops up. However if you close that, on Windows, you will just end up with a blank screen that you can't interact with. This PR makes sure the top bar always shows regardless of how many servers you have.
```release-note
NONE
```
=> Show topbar regardless of whether there are servers or not

src/common/communication.ts, src/common/config/upgradePreferences.ts, src/main/Validator.ts, src/main/main.ts, src/main/views/viewManager.ts, src/main/windows/windowManager.ts, src/renderer/components/MainPage.tsx, src/renderer/index.tsx, src/types/config.ts
Two fixes that needed to be rolled together:
- Ensure when restarting the app that the last used server and tab opens
- Ensure that `handleConfigUpdate` runs as it was affecting autostart.
https://mattermost.atlassian.net/browse/MM-23452
https://mattermost.atlassian.net/browse/MM-36861
```release-note
NONE
```
=> [MM-23452][MM-36861] Fixed some configuration issues

src/main/server/serverAPI.ts
In some cases, if you entered a bad server URL and the returned data was not in JSON format, it would crash the app. I've added some error checking to fail gracefully and log it if this happens.
https://mattermost.atlassian.net/browse/MM-38433
```release-note
NONE
```
=> [MM-38433] Error checking when a bad server URL is entered

src/main/views/MattermostView.ts, src/main/views/viewManager.ts
Since we now have functionality to have the desktop app update the webapp's current URL without reloading it, we can now leverage that functionality when deep-linking and clicking links in other tabs so that the page doesn't reload.
https://mattermost.atlassian.net/browse/MM-38275
```release-note
NONE
```
=> [MM-38275] Use browser history push for deeplinking and other inter-tab navigation when using a v6.0 server

src/main/main.ts, src/main/windows/windowManager.ts
My original method of removing the menu from the window caused all the keyboard shortcuts to stop working. So now instead, on Linux, I will simply suppress the shortcuts that cause the issue to happen in the first place.
https://mattermost.atlassian.net/browse/MM-36309
```release-note
NONE
```
=> [MM-36309] Restore window menu, override shortcuts for window menu so they don't interfere

src/common/communication.ts, src/common/tabs/TabView.ts, src/common/utils/util.ts, src/main/Validator.ts, src/main/main.ts, src/main/preload/mattermost.js, src/main/views/viewManager.ts, src/main/windows/windowManager.ts, src/renderer/components/MainPage.tsx, src/renderer/components/SettingsPage.tsx, src/renderer/components/TabBar.tsx, src/types/config.ts
I've changed around some of the closed tab logic to allow us to be explicit if the tab should be open or closed, and if there's no value we can open it. We will also open the Boards and Playbooks tabs for servers that support them instead of have them open by default and close them if not needed.
This should solve a couple issues with creating servers in which you would not see the loading screen for the new tab, and with removing servers in which you wouldn't be redirected to an active tab.
I've also added a tap into the logic functionality so that the desktop tabs will reload correctly when logging in on one of them.
```release-note
NONE
```
=> [MM-38524] Rework the closing and opening tab logic, fixed login issue

src/renderer/components/MainPage.tsx, src/renderer/components/TabBar.tsx, src/renderer/css/components/TabBar.css
When the menu is open, the drag region was eating all click events include the event that is supposed to close the menu. This PR add an overlay `span` over top of the drag region when the menu is open so that when you click on the top bar, the menu should close like normal.
https://mattermost.atlassian.net/browse/MM-38535
```release-note
NONE
```
=> [MM-38535] Overlay drag region with clickable area when menu is open

src/main/menus/app.ts, src/main/windows/windowManager.ts
When some of the tabs for a server were closed, the keyboard shortcuts and menu items did not reflect the ordering and visibility of the tabs. This PR fixes that by only showing the tabs that are visible in the menu.
https://mattermost.atlassian.net/browse/MM-38570
```release-note
NONE
```
=> [MM-38570] Fixed the keyboard shortcuts for switching tabs when some tabs are closed

resources/windows/gpo/en-US/mattermost.adml
Fix typo in mattermost.adml as discovered [here](https://community-daily.mattermost.com/core/pl/6zsmpbtzqpnbzktn4b3bqbamwo) by @mark.piermarini
```release-note
NONE
```
=> Fix typo in mattermost.adml

src/main/views/webContentEvents.ts
`electron-context-menu` was missing from popup windows. This PR adds it in.
https://mattermost.atlassian.net/browse/MM-36032
```release-note
Fixed the missing context menu for popup windows
```
=> [MM-36032] Add electron-context-menu to popup windows

src/renderer/css/components/TeamDropdownButton.scss, src/renderer/css/dropdown.scss
Set a max-width of 400px on the dropdown button and 600px on the menu to avoid it being ridiculously long with really long server names.
https://mattermost.atlassian.net/browse/MM-38642
```release-note
NONE
```
=> [MM-38642] Set a max-width for the dropdown button and menu

src/main/windows/windowManager.ts, src/renderer/components/MainPage.tsx
When pressing F11 on Windows, the app would enter full screen mode and there would be no clear indication to the user how to get out. This PR adds the full screen toggle functionality to the restore button such that the same action as unmaximizing will get the app out of fullscreen mode.
https://mattermost.atlassian.net/browse/MM-38577
```release-note
Fixed an issue where the app could get stuck in full screen mode without the users knowledge.
```
=> [MM-38577] Allow exit of full screen mode using the restore button on Windows

src/main/main.ts, src/main/notifications/Download.ts, src/main/notifications/index.ts
The download notification title was using the raw view name instead of just the server name for the download notification title on Windows 10. Now it will use just the server name, like before.
https://mattermost.atlassian.net/browse/MM-38679
```release-note
NONE
```
=> [MM-38679] Fix download notification title on Windows

src/main/menus/app.ts, src/main/utils.ts, src/main/views/teamDropdownView.ts, src/main/views/viewManager.ts, src/main/windows/mainWindow.ts, src/main/windows/windowManager.ts
There's a very annoying Electron bug causing issues on macOS in which the top 40px of our app isn't as interactable, as the framework is popping a draggable area there. Bug report here: https://github.com/electron/electron/issues/31052
As a workaround, I've put the entire top bar in a BrowserView in order to circumvent this issue. In the past there was problems with doing this, but I think the changes in infrastructure has made this easier to do.
https://mattermost.atlassian.net/browse/MM-38649
```release-note
Fixed the top bar dragging issue on macOS by placing the top bar in its own BrowserView
```
=> [MM-38649] Put top bar in a BrowserView

src/main/views/viewManager.ts
In some cases, on initial load of the app, the first server/view opened would refresh multiple times unnecessarily.
This was caused by extra calls to `reloadViewIfNecessary` when the view wasn't completely ready. This PR makes sure we're always working with the webContents for the view, other than the window.
```release-note
NONE
```
=> Fixed multiple reloads happening on launch

src/renderer/components/SettingsPage.tsx
This PR fixes the 'minimize to tray' setting on Linux, as it was not changeable. This enables a user to uncheck the setting if they don't have a system tray to work with, thus allowing the window to minimize to the GNOME app bar if needed.
https://mattermost.atlassian.net/browse/MM-38695
```release-note
NONE
```
=> [MM-38695] Fixed minimize to tray setting on Linux

src/main/Validator.ts
This PR fixes the regex used for validating spell checker locales. It was previously expecting locales with a dash, which not all of them have.
Closes #1754.
https://mattermost.atlassian.net/browse/MM-38857
```release-note
NONE
```
=> [MM-38857] Fix spellcheck locales regex

src/renderer/css/components/TeamDropdownButton.scss
Adding `user-select: none` to the dropdown button to fix this issue: https://community-daily.mattermost.com/core/pl/baf16oczmirjfna7dt91bk7rpc
```release-note
NONE
```
=> Fix for user selection on the dropdown menu button

.circleci/config.yml
`update-image` job was breaking on getting packages because the certificates were out of date. Fixed by manually updating the certificates as per this: https://github.com/nodesource/distributions/issues/1266#issuecomment-931467582
```release-note
NONE
```
=> Fix update image

scripts/generate_release_markdown.sh
Adding the Mac universal binary changed the way we write the release description. This PR fixes that.
```release-note
NONE
```
=> Fix GitHub release markdown for mac universal change

src/main/views/MattermostView.ts
When removing a server, mentions and unreads that were on that server would remain visible in the global count and wouldn't go away until restart. This PR removes those when the view is destroyed so that they don't persist when the view doesn't exist.
https://mattermost.atlassian.net/browse/MM-38991
```release-note
NONE
```
=> [MM-38991] Remove mentions and unreads when unloading a view

src/main/views/modalView.ts, src/main/views/teamDropdownView.ts, src/main/views/viewManager.ts
Found a workaround for forcing `BrowserViews` to be transparent anyways. It's not supported by Electron, so a fix is still likely to be needed, but this will work for the time being.
https://mattermost.atlassian.net/browse/MM-39139
```release-note
NONE
```
=> [MM-39139] Workaround for transparency issue for BrowserViews on Electron v14.1.0+

test/specs/browser/modal_test.js
E2E test checking to make sure the first input is focused in the Add Server modal
https://mattermost.atlassian.net/browse/MM-39737
```release-note
NONE
```
=> [MM-39737] E2E test checking for focused input in Add Server Modal

src/common/config/index.ts, src/main/main.ts
Some situations can cause the config file to be locked while trying to write to it. This PR adds retry logic to avoid this issue, and also adds logging if any other file related issues happen.
https://mattermost.atlassian.net/browse/MM-39428
Closes https://github.com/mattermost/desktop/issues/1840
Closes https://github.com/mattermost/desktop/issues/1825
```release-note
Fixed an issue where the app would crash trying to write to the config
```
=> [MM-39428] Check for EBUSY, add retry logic and logging for writing to config

src/common/communication.ts, src/main/preload/mattermost.js, src/main/views/MattermostView.ts, src/main/windows/windowManager.ts
In some cases due to the redirect logic, the app think it needs to redirect to another tab immediately after signin. When this happens, the app tries to call a logged-in route and our webapp emits a logged out event when this happens. This creates a race condition potentially logging out the user simply when they try to log in.
This PR stops any redirection to a tab that is not currently logged in, stopping the weird login issues.
Closes https://github.com/mattermost/desktop/issues/1861
https://mattermost.atlassian.net/browse/MM-40025
```release-note
Fixed an issue where a user might an erroneous "Your session has expired" error and be unable to login.
```
=> [MM-40025] Stop app from redirecting to tabs when not logged in

src/main/preload/mattermost.js
Calls plugin makes use of the [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) to allow users to share their screen. However, while the browser implements [`getDisplayMedia()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia), Electron only provides [`getUserMedia()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia). This has worked so far but the limitation is that only the main screen source (full desktop) can be shared. This has also led to some weird issues with multiple monitor setups. 
To improve on this I did some quick research and figured out we may need some help from the Electron side itself through the use of …
=> Expose native API call to get desktop screen sources

src/main/views/MattermostView.ts
Sometimes, if you press Ctrl/Cmd+R while the app is still loading, the `did-finish-load` event will fire for the first load while the page is reloading. Since we can't send messages down to a page that isn't loaded, the app will crash.
This PR checks to make sure the page isn't loading when sending the message down, and will avoid a crash if the send fails.
https://mattermost.atlassian.net/browse/MM-40192
Closes #1888
```release-note
Fixed an issue where the app could crash while trying to reload a page that is currently loading.
```
=> [MM-40192] Don't send message until server is finished reloading

src/main/views/webContentEvents.test.js, src/main/views/webContentEvents.ts
With this change, URLs with custom protocols won't be validated any longer. This allows usage of technically invalid URLs for custom protocols 
Fixes https://github.com/mattermost/desktop/issues/1635
This PR was tested on: Windows 10
```release-note
NONE
```
=> [GH-1635] don't validate custom protocol URLs

src/common/utils/url.ts, src/main/views/MattermostView.test.js, src/main/views/MattermostView.ts, src/main/views/webContentEvents.test.js, src/main/views/webContentEvents.ts
When I added tests for `MattermostView`, I introduced an issue where we force the URL to turn into a URL object.
This PR makes sure that whatever URL we create is valid before we do so.
Also added a fix to allow parsed, but technically invalid URIs to open in the browser.
https://mattermost.atlassian.net/browse/MM-32946
https://mattermost.atlassian.net/browse/MM-40602
Closes https://github.com/mattermost/desktop/issues/1474
```release-note
Allow parsed, but technically invalid URIs to open in the browser.
```
=> [MM-32946][MM-40602] Ensure URL is valid before showing tooltip link, allow parsed URLs that aren't valid to open in browser

src/main/views/MattermostView.ts
Sometimes when using an Alt shortcut on your OS while the MM Desktop App was focused, the app would not register any future key presses until the app was refocused. This would happen when switching workspaces using the Alt key for example.
This PR adds a timeout to clear the `altLastPressed` value so that it only will trigger the 3-dot focus if the key was lifted within 500ms of being held.
https://mattermost.atlassian.net/browse/MM-40603
Closes https://github.com/mattermost/desktop/issues/1297
```release-note
Fixed an issue where OS-level shortcuts could cause unexpected focus behaviour in the app.
```
=> [MM-40603] Add timeout for alt press to make sure it doesn't interfere with OS shortcuts

src/main/views/MattermostView.test.js, src/main/views/MattermostView.ts
If you are on a channel that begins with an asterisk, even if the server had no unreads it would show unreads.
This was caused by the regex we used to parse out the title for unreads/mentions. 
This PR stops that process from being used by versions newer than 5.28, and at least ensures you must have a space when searching for the asterisk on older versions.
https://mattermost.atlassian.net/browse/MM-40573
Closes https://github.com/mattermost/desktop/issues/1690
```release-note
Fixed an issue where being on a channel with an asterisk at the front would cause unreads to return a false positive.
```
=> [MM-40573] Stop asterisk detection on versions newer than 5.28, force space for the others

src/renderer/components/SettingsPage.tsx
Since the window flashing behaviour doesn't work correctly on all Linux window managers, we've added a disclaimer for those which it does not work.
https://mattermost.atlassian.net/browse/MM-26018
```release-note
Added a disclaimer for the window flashing behaviour on Linux
```
=> [MM-26018] Added disclaimer for window flashing on Linux

src/main/views/MattermostView.ts
Cherry pick of #1932 on release-5.0.
```release-note
NONE
```
=> Automated cherry pick of #1932

src/main/menus/app.ts, src/main/preload/dropdown.js, src/main/windows/mainWindow.ts, src/renderer/css/dropdown.scss, src/renderer/dropdown.tsx
We were missing a menu item for the Servers menu and instead used a globalShortcut. This PR adds the menu item and the correct keyboard shortcut, as well as a reference to the shortcut in the menu itself.
https://mattermost.atlassian.net/browse/MM-40009
```release-note
Added menu item to open the dropdown menu called 'Show Servers' under 'Window'
```
=> [MM-40009] Add servers dropdown shortcut to menu

src/main/menus/app.ts
Small change to make the `menu > help > version` copy the full version string to the clipboard on click to address the help wanted a ticket. 
This information is also available in `menu > mattermost > about mattermost`, which was not changed in this PR.
Fixes https://github.com/mattermost/desktop/issues/1868
```release-note
Click Menu > Help > Version to copy version string into clipboard.
```
=> Menu > Help > version copied to clipboard on click

src/common/communication.ts, src/main/menus/app.ts, src/main/preload/mattermost.js, src/main/views/MattermostView.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts
This PR adds some communication logic to facilitate message passing for history information, so that the webapp is aware when the page can actually go back or forward.
Related Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/9614
https://mattermost.atlassian.net/browse/MM-32371
```release-note
NONE
```
=> [MM-32371] Communicate history information to webapp for disable/enabling Back/Forward buttons

src/main/menus/app.ts
Since we recently changed the layout of the desktop app and moved the server tabs into a drop down I think it makes more sense to change the wording for this to refer to the "Server" instead of "Tab". Another one I considered was "View" instead of "Tab". I'd be good with either one.
The changes refer to this menu: 
```release-note
Changed wording in "File -> View" Menu from "Tab" to "Server" to reflect recent changes in UI.
```
=> change "tab" to "server" in developer tools menu

src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts
When opening the app from the tray icon, for some reason we were showing the dock as well on macOS. This was odd behaviour as if the dock was auto-hidden, it would remain stuck open afterwards.
This PR removes that call.
https://mattermost.atlassian.net/browse/MM-40822
Closes #1938 
```release-note
Fixed an issue where the macOS dock would stay open after clicking the tray icon
```
=> [MM-40822] Remove app.dock.show from restoreMain

webpack.config.renderer.js, webpack.config.test.js
The PR https://github.com/mattermost/desktop/pull/1437 changed the default port from 9000 to 9001 to solve an issue with minio port on https://github.com/mattermost/mattermost-server. The port 9001 is now used by the container "inbucket" since the PR https://github.com/mattermost/mattermost-server/pull/18145. So if you have an instance of mattermost-server running, you cannot start the desktop project.
This PR introduces an environment variable `WEBSERVER_PORT` to change the port on-demand:
```shell
$ WEBSERVER_PORT=9005 npm run watch
ℹ ｢wds｣: Project is running at http://localhost:9005/
``` 
This PR **does NOT** change the default port, so it does not have any impact for somebody who changed their ports elsewhere. If you guys want me to change the default port, I'm happy to add a new …
=> Make WEBSERVER_PORT configurable with env variable

scripts/release.sh
Whenever we do a release we need to update the links that point to the latests mattermost release
this should live in a release playbook, but since we don't have one yet, this would serve as a reminder of the process.
```release-note
NONE
```
=> add a reminder on how to proceed with releases

src/main/menus/app.ts
This PR changes the zoom in shortcut to match the expected behavior known from other apps like Chrome, Firefox, etc.
The 'new' shortcut would be `ctrl/cmd`+`=` instead of `ctrl/cmd`+`shift`+`=`
```release-note
The app now uses 'ctrl+=' or 'cmd+=' to zoom in to match the behavior known from other apps like Chrome or Firefox.
```
=> Change zoom in shortcut to match expected behavior known from other apps

e2e/specs/server_management/long_server_name.test.js, src/renderer/css/components/TeamDropdownButton.scss
Adds e2e tests for long server names.
Fixes https://mattermost.atlassian.net/browse/MM-39799
This PR was tested on:  MacBook Pro, MacOS 12.1
```release-note
NONE
```
=> [MM-39799] E2E Test: MM-T4050 Long server name

src/common/utils/url.ts, src/main/views/webContentEvents.test.js, src/main/views/webContentEvents.ts
This PR adds a function to allow trusted plugin routes. This is designed to be easily expanded in the future for other routes but, for now, it only allows the `/api/v1/export` endpoint from the channel export plugin.
By allowing that specific endpoint here, we fix [the bug](https://mattermost.atlassian.net/browse/MM-41042) that prevented the channel log from being downloaded.
https://mattermost.atlassian.net/browse/MM-41042
This PR was tested on: laptop, Linux
https://user-images.githubusercontent.com/3924815/150202926-519882d9-fb34-42f9-a0c1-013e39e733bc.mp4
```release-note
Fixed a bug that prevented the channel log from being downloaded from Playbooks.
```
=> MM-41042: Allow trusted plugin routes

e2e/specs/menu_bar/file_menu.test.js
e2e test:Preferences in the Menu Bar opens the Settings page
Fixes https://github.com/mattermost/desktop/issues/1893
```release-note
NONE
```
=> test:Preferences in the Menu Bar opens the Settings page

e2e/specs/linux_dark_mode.test.js
End to end test to check if toggle dark mode works
https://github.com/mattermost/desktop/issues/1911
Linux
None
```release-note
none
```
=> test : MM-T2465 Linux Dark Mode Toggle

e2e/specs/relative_url/relative_url.test.js
test:MM-T1308 Check that external links dont open in the app
Fixes https://github.com/mattermost/desktop/issues/1906
```release-note
NONE
```
=> test:MM-T1308 Check that external links dont open in the app

src/common/communication.ts, src/main/preload/urlView.js, src/main/views/viewManager.ts, src/renderer/components/urlDescription.tsx, webpack.config.main.js
When you hover over a URL near the bottom of the page (eg. OneLogin links) they will be covered by the URL view browser view. This PR adds dynamic sizing to the URL view that will stop this from happening.
https://mattermost.atlassian.net/browse/MM-41559
```release-note
Fixed an issue where external links at the bottom of the page were not clickable.
```
=> [MM-41559] Dynamically size URL view to avoid overlapping bottom links

src/main/windows/windowManager.ts
When navigating on a server with a subpath, the path name of the server URL would be included when sending URLs back and would be append to the pathname (eg. for a server with site URL: `http://myserver.com/subpath`, urls would end up being `http://myserver.com/subpath/subpath/<rest of url>`)
This PR cleanses out the subpath from the pushed URL and pushes back the pathname without the server URL subpath.
https://mattermost.atlassian.net/browse/MM-41392
```release-note
NONE
```
=> [MM-41392] Clean path name on browser pushes for subpaths

src/main/windows/windowManager.ts
An issue was caused by the changes made for subpath navigation, in which servers without a subpath did not receive the correct path names on returns.
Closes https://github.com/mattermost/focalboard/issues/2270
```release-note
NONE
```
=> [MM-41392] Ensure pathname starts with `/`

src/common/config/defaultPreferences.ts, src/common/config/index.ts, src/main/Validator.ts, src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts, src/renderer/components/SettingsPage.tsx, src/types/config.ts
Many Linux users have reported that the app doesn't obey closing rules as they would normally expect, so we've refined the way the app closes on Linux and added some dialog boxes to inform the user of what happens when they close the main window:
- Upon pressing X, if the 'Leave app running in notification area when application window is closed' is checked, a dialog box will pop up telling the user that the app will still be running even if the window is closed. If 'Don't show again' is checked (it is by default) then the user will not see that message again.
- If the above setting is NOT checked, the user will see a dialog box asking them whether they really want to close the app permanently. If they reply 'Yes', the app is quit. If they reply 'No', nothing happens. If the 'Don't ask …
=> [MM-30713] Stop Linux and Windows app from minimizing/hiding without user warning

.circleci/config.yml, .gitignore, package-lock.json, package.json
Since the E2E tests are kind of flaky, we're electing to turn off the CircleCI check to ensure that the tests pass.
We will run them manually from now on.
https://mattermost.atlassian.net/browse/MM-42010
```release-note
NONE
```
=> [MM-42010] Remove CircleCI check for E2E tests

src/main/views/MattermostView.ts, src/main/views/viewManager.test.js, src/main/views/viewManager.ts, src/renderer/components/LoadingAnimation/LoadingAnimation.tsx
The loading screen had some issues sending the request back to the app since the end of the animation was unreliable and wasn't always resetting itself.
There was also some issues with the app calling `showByName` too many times and causing the screen to be in a very odd state.
This PR fixes up the loading screen by adding clear state and some debouncing, as well removing unnecessary calls.
https://mattermost.atlassian.net/browse/MM-42072
```release-note
Fixes to the loading screen to make it more reliable.
```
=> [MM-42072] Fix issues with loading screen animations

package.json, src/main/app/initialize.ts, src/main/preload/mattermost.js, webpack.config.base.js
For the `nightly` branch we will turn on React Developer Tools so that people on an 'unstable' branch can debug various React issues if necessary.
https://mattermost.atlassian.net/browse/MM-42024
```release-note
NONE
```
=> [MM-42024] Enable React Developer Tools for nightly builds

src/common/communication.ts, src/main/preload/mattermost.js, src/main/views/MattermostView.test.js, src/main/views/MattermostView.ts, src/main/views/viewManager.ts, src/main/windows/windowManager.ts, src/renderer/components/ErrorView.tsx, src/renderer/components/MainPage.tsx
This PR extends the retry logic for tabs that are unable to load (likely due to network conditions) to retry indefinitely.
Now, the app will still show an error screen after a small amount of retries (prompting users to double check the URL) but will continue to retry in the background at the same interval in case network conditions change and the URL is now accessible as a result. This should improve the reliability a bit such that users that need to login to a VPN, or connect to a different WiFi network will have their tabs automatically loaded for them once the network conditions change.
Also a couple small fixes were made to improve the error screen behaviour.
https://mattermost.atlassian.net/browse/MM-41891
Closes #2002
```release-note
Support retrying to load tabs indefinitely …
```
=> [MM-41891] Improve error and reload states

src/main/preload/mattermost.js
There was a typo in the preload code that checked for unreads in the team sidebar when you were on a different team, this PR fixes that typo so that the unreads should work correctly now.
https://mattermost.atlassian.net/browse/MM-42587
```release-note
Fixed an issue where unreads on a different team wouldn't trigger an unread badge in the Desktop App.
```
=> [MM-42587] Fix typo in unread checking code

fastlane/Fastfile
Turn on the `skip_waiting_for_build_processing` option for MAS so that the build finishes before the cutoff time.
```release-note
NONE
```
=> Add `skip_waiting_for_build_processing` to CI build

.circleci/config.yml
This PR fixes the daily upload to the AWS bucket for Rainforest tests, since it was blown out when the new nightly job was created.
```release-note
NONE
```
=> Fix daily upload for Rainforest builds

src/renderer/components/SettingsPage.tsx
When in the Settings page, the "Tray icon theme" toggle would be visible when the icon itself wasn't enabled on Linux, which could be confusing to some users.
This PR removes that toggle when the icon is disabled.
https://mattermost.atlassian.net/browse/MM-26016
```release-note
Hid the tray icon theme toggle when the icon itself wasn't enabled
```
=> [MM-26016] Hide tray icon theme colour when tray icon not enabled

package-lock.json, package.json
An issue with Electron v18.0.1 was including a deprecated Chromium API. Our app was rejected from MAS because of this.
This PR upgrades to Electron v18.0.3 which has this API removed.
```release-note
NONE
```
=> Upgrade to Electron v18.0.3 to fix MAS rejection

src/main/views/viewManager.ts, src/renderer/css/components/HoveringURL.css
When trying to click a button directly above the URL View component, the button would be blocked by the BrowserView containing the URL View. This is due to the fact that URL View was too tall.
This PR corrects the height to 20px, the same height of the URL View.
https://mattermost.atlassian.net/browse/MM-43185
```release-note
Fixed an issue where the URL View stopped users from clicking a button directly above it
```
=> [MM-43185] Fix size of BrowserView for URLView

src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts
When using the Global Header (or some other non `target=_blank` link) to open a new tab, the original tab would also navigate to the new location. This was due to the check for `isLoggedIn` on the new view, which of course won't be set until the view has finished loading.
This PR stops the rest of the `handleBrowserHistoryPush` flow from happening after the tab is opened, as when we open a tab we always go directly to where the push link told us to go.
```release-note
Fixed an issue where opening a new view causes the original view to go to the requested link as well
```
=> Fix issue where opening a new view causes the original view still to push

src/main/views/MattermostView.test.js, src/main/views/MattermostView.ts
When the user hovers over an external URL, we show a URL preview display at the bottom. When the user moves their mouse away, the app was supposed to remove the view, but it wasn't doing that, since we were checking that the URL exists on removing hover (which it wouldn't). So I've updated the login to make sure we're sending the event even when the URL is blank.
https://mattermost.atlassian.net/browse/MM-43632
```release-note
Fixed an issue where the URL view would persist once the user had moved their moved off of an external URL
```
=> [MM-43632] Ensure handleURLView is called when removing the target URL

src/main/views/MattermostView.test.js, src/main/views/MattermostView.ts
Cherry pick of #2074 on release-5.1.
```release-note
NONE
```
=> Automated cherry pick of #2074

.circleci/config.yml, scripts/generate_release_markdown.sh
@JulienTant pointed out a couple issues with the release markdown, so I've made the changes here
- Fix the renaming of `arm64` to `m1` for macOS builds
- Removed Windows ZIP files from release (since we don't build them anymore)
- Renamed RPM build for `i386` to `i686` (those poor 486 users :P)
```release-note
NONE
```
=> Fix release markdown

src/main/views/viewManager.ts
When the Mattermost window is maximized on Windows 10/11, the URL hover view was not showing correctly. This was due to window bounds being incorrect for the entire window when maximized.
This PR changes to use the current Mattermost view for bounds since those report correctly even when maximized.
https://mattermost.atlassian.net/browse/MM-44022
Closes #2086
```release-note
NONE
```
=> [MM-44022] Switch to using current BrowserView for determining window bounds for URL view

src/main/menus/tray.ts
The server name was overflowing on the tray menu, causing bad UX (specifically on Ubuntu). This PR truncates the server name to 50 characters so that it doesn't cause any issues.
https://mattermost.atlassian.net/browse/MM-44066
```release-note
Fixed bad UX for the system tray menu with long server names
```
=> [MM-44066] Truncate server names in the system tray to 50 characters

src/main/ParseArgs.test.js, src/main/ParseArgs.ts, src/main/app/initialize.test.js, src/main/app/initialize.ts
yargs, the command line parsing library, was unable to read the app's version automatically from `package.json`.
Fix by passing the app's version as electron sees it.
I was able to identify yargs was behaving improperly by polyfilling `console.log` and `process.exit` and making them throw on call, then cross-checking with yargs' source code.
It is also possible to disable yargs exiting. I opted for allowing yargs to handle it. It is possibly unwanted for an external process to call `process.exit` for us as it results in truly mysterious behaviour in edge cases such as this. This is exacerbated by yargs being overengineered for its relatively trivial task.
Fixes https://github.com/mattermost/desktop/issues/1422
This PR was tested on: Debian sid, 5.17.3-1.
```release-note
Fixed improper …
```
=> fix version flags displaying bad version on linux (#1422)

src/main/app/utils.ts
There seems to be a case on some Linux installs where the `restore` event will be emitted every time the window is resized. In the `resizeScreen` function, this was causing a stack overflow. This PR stops the handler from being called more than once unless explicitly needed.
https://mattermost.atlassian.net/browse/MM-44117
Fixes #2098 
```release-note
NONE
```
=> [MM-44117] Fix stack overflow where window resize would constantly emit the restore event

src/renderer/components/NewTeamModal.tsx
When adding a new server, if both the Name and URL fields are invalid, the user will see a message that says 'Name and URL are required'. This can be misleading if they've entered something for both, and doesn't give them a good indication as to what is wrong with their entry.
This PR changes the modal to show both messages so that the user understands better what is wrong.
https://mattermost.atlassian.net/browse/MM-44161
```release-note
NONE
```
=> [MM-44161] Show both validation messages when adding new server if both fields are invalid

.circleci/config.yml
`ghr` only looks at immediate descendents of the path it is provided, so we need to ensure that `ghr-dist/` is flattened.
Fixes: #2113
```release-note
NONE
```
=> Fix GitHub release asset upload

src/main/windows/mainWindow.ts, src/main/windows/windowManager.ts
When the app starts, we had a few extra calls made to show the main window. These weren't being caught by the `hideOnStart` setting meaning that it wasn't working, so I've removed those extra calls.
https://mattermost.atlassian.net/browse/MM-44339
Closes https://github.com/mattermost/desktop/issues/2109
```release-note
Fixed an issue where the `hideOnStart` setting wasn't working
```
=> [MM-44339] Remove unnecessary calls to show the main window

electron-builder.json, scripts/afterbuild.js, scripts/generate_release_markdown.sh, src/common/config/index.ts
We chose to remove the ZIP build for Windows since we did not believe it was relevant, and the auto-updater caused some odd issues with it. We have decided after a few people have mentioned it to restore it with the auto-updater removed.
https://mattermost.atlassian.net/browse/MM-44344
Closes https://github.com/mattermost/desktop/issues/2112
```release-note
Restore Windows ZIP build
```
=> [MM-44344] Restore zip build for Windows and remove auto-updater from it

src/common/utils/url.test.js, src/common/utils/url.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts
When switching to a channel that matches (or starts with) the name of the server subpath (eg. server url `http://server.com/mattermost` and channel name `mattermosty`), navigation would not happen. This was caused by an issue with the replacement function that removes the subpath when switching tabs.
This PR fixes the function to only remove the subpath if its at the beginning of the path that's being cleansed.
https://mattermost.atlassian.net/browse/MM-44607
Closes https://github.com/mattermost/desktop/issues/2125
```release-note
Fixed an issue where a channel name matching the server subpath would not be navigable
```
=> [MM-44607] Only cleanse subpath if it occurs at the beginning

.config/notice-file/Readme.md, .config/notice-file/config.yaml
We are working to automate Notice.txt file generation and some of the properties need to be managed by developers.
To support that feature, we created a configuration file in the repo under build folder. 
https://mattermost.atlassian.net/browse/DOPS-448
```release-note
NONE
```
=> Create configuration folder for notice.txt generation

src/main/app/intercom.ts, src/main/app/utils.test.js, src/main/app/utils.ts, src/main/server/serverInfo.ts, src/types/server.ts
Whenever the server is configured not using the `SiteURL` that is configured on the server, a lot of unexpected issues can occur. This most recently manifested itself when we started redirecting `community-daily` to `community`. 
This PR uses the same API the app uses to check for installed plugins and server version to grab the SiteURL and update the configured server URL with it.
This does appear to work with GPO configurations as well!
https://mattermost.atlassian.net/browse/MM-44644
```release-note
Force servers to update their configuration using the configured SiteURL if available
```
=> [MM-44644] Update configured server URL from SiteURL if available

package.json
Once a version is released, MAS doesn't allow subsequent releases of the same version to be uploaded to TestFlight, so I've updated the version in package.json to v5.2
```release-note
NONE
```
=> Fix MAS/TestFlight nightly build

src/renderer/modals/certificate/certificateModal.tsx
Due to an issue caused during the TS migration, the first certificate in the client certificate list was unable to be selected.
This PR fixes that issue.
https://mattermost.atlassian.net/browse/MM-44071
```release-note
Fixed an issue where the first client certificate could not be selected
```
=> [MM-44071] Fixed an issue where the first client certificate could not be selected

e2e/specs/menu_bar/view_menu.test.js, src/main/menus/app.ts
Add hidden MenuItems that add keyboard shortcuts for Zoom In/Out when Shift is pressed.
I tried using the default role for `zoomIn` and `zoomOut` that electron provides, but it didn't work on Windows, so I followed this approach.
Fixes https://mattermost.atlassian.net/browse/MM-44931
This PR was tested on:
- macbook pro, Macos Monterey 12.4 
- pc, Windows 11
- pc, Ubuntu 22
```release-note
Fix zoom in/out not working when Shift is pressed.
```
=> [MM-44931] Allow zoom in/out when Shift is pressed

i18n/en.json, src/renderer/modals/permission/permissionModal.tsx
One of the `permissionModal` translations had a concatenation issue making translating it difficult. I've resolved it by using the same rich text pattern I used for the other ones.
```release-note
NONE
```
=> Fixed an issue with a permission modal translation

src/main/app/initialize.test.js, src/main/app/initialize.ts
When downloading a file, the user is allowed to save the file as any name they want. However, when the notification displays that the file is done, it would always show the original name, which can be confusing.
This PR makes a change to always show the saved file name instead.
https://mattermost.atlassian.net/browse/MM-45646
```release-note
Fixed an issue where the download notification would show the wrong file name
```
=> [MM-45646] Change download notification text to display saved filename instead of original

entitlements.mas.plist
There's an issue with Electron currently blocking users from replacing files if there are using the MAS build. This PR mitigates the issue by explicitly adding the entitlements for available folders (Downloads, Pictures, Movies, Music) that will allow file replacement.
Partial resolution:
https://mattermost.atlassian.net/browse/MM-45980
https://github.com/mattermost/desktop/issues/2199
```release-note
Fixed an issue where the user could not replace files in the Downloads folder
```
=> [MM-45980] Add entitlements for read/write to a few key user directories

src/main/windows/windowManager.ts
A recent change to the resize logic causes issues on Windows. This PR fixes that.
```release-note
NONE
```
=> Fix windows resize

src/main/windows/windowManager.ts
A couple extra Windows resize fixes:
- Fixed an issue where maximize was causing the BrowserView to overlap outside the window
- Removed unnecessary calls to `handleResizeMainWindow()` when on Windows
https://mattermost.atlassian.net/browse/MM-46114
```release-note
NONE
```
=> [MM-46114] More fixes for Windows resizing

electron-builder.json
MAS build was failing due to the addition of native modules that were conflicting.
=> Fix MAS build

e2e/modules/environment.js
Sometimes, test servers like to switch back to the Loading screen after the login screen has shown. This change asks the tester to expect that so that it doesn't miss the login prompt.
```release-note
NONE
```
=> Fix for some flaky E2E tests

src/main/notifications/index.test.js
Unit tests were failing on macOS due to missing mocks for notification libraries. Thanks to @saturninoabril for pointing this out :)
```release-note
NONE
```
=> Fix for mac unit tests

.circleci/config.yml, package-lock.json, package.json, scripts/Makefile.ps1
The issue with the Windows node-gyp build seems to be related to the headers not being properly downloaded/populated. This PR pre-populates them which seems to fix the issue.
```release-note
NONE
```
=> Fix node-gyp build on Windows

.circleci/config.yml, src/common/config/buildConfig.ts, src/common/config/defaultPreferences.ts, src/common/config/index.ts, src/main/Validator.test.js, src/main/Validator.ts, src/main/app/intercom.ts, src/types/config.ts
Implemented a way to bypass the onboarding screens for nightly run builds.
https://mattermost.atlassian.net/browse/MM-46445
This PR was tested on: macOs Big Sur 11.6.6
```release-note
NONE
```
=> MM-46445_Add a way to bypass Desktop App onboarding to `buildConfig`

.circleci/config.yml
This patch isn't needed right now and is breaking the build. Removing it for now and will add the changes for Rainforest in a separate PR.
```release-note
NONE
```
=> Remove buildConfig patch

.circleci/config.yml, package.json, scripts/Makefile.ps1, src/common/config/buildConfig.ts, src/common/config/defaultPreferences.ts, src/common/config/index.ts, src/main/Validator.test.js, src/main/Validator.ts, src/main/app/initialize.ts, src/main/app/intercom.ts, src/types/config.ts, webpack.config.base.js
We are in need of a special build of the Desktop App for Rainforest to fix 2 issues:
- The onboarding screens are causing issues with the existing tests, so we'll be disabling it
- GPU acceleration causes macOS to crash in RF, so we are disabling that as well
https://mattermost.atlassian.net/browse/MM-46553
```release-note
NONE
```
=> [MM-46533] Remove buildConfig item and add webpack flags for onboarding screens and GPU acceleration

src/main/windows/windowManager.ts
If `localStorage` sends the `__login__` signal more than once, we end up with an infinite redirect. This PR makes sure not to reload the view if we already know the view is logged in. It will now only reset if the `__logout__` signal is sent.
https://mattermost.atlassian.net/browse/MM-45003
```release-note
Fixed an issue where tabs will infinitely redirect to each other on multiple `__login__` signals.
```
=> [MM-45003] Fix the infinite redirect caused by MFA sending the login signal repeatedly

src/main/views/MattermostView.test.js, src/main/views/MattermostView.ts
Old version of Mattermost (<5.28) used an asterisk in the page title to show whether they had unread messages or not. Later versions uses the favicon, which is what the Desktop App prefers.
The asterisk is still used for session expiry, and we ran into a strange issue where the view would get stuck in the asterisk mode if the session expired, thus stopping notifications from happening.
Since v5.28 and earlier have been out of support for almost 2 years now, it seems to make sense to drop support for this since it's causing issues with newer versions.
https://mattermost.atlassian.net/browse/MM-46405
```release-note
Drop support for asterisk-based unreads in Mattermost versions <5.28
```
=> [MM-46405] Drop support for asterisk-based unreads

src/main/notifications/index.ts
Notifications are currently being `info` level logged, which is overkill and a bit of a security concern. Changing those over to `debug`.
```release-note
NONE
```
=> Remove notification logging from info

src/main/views/modalManager.test.js, src/main/views/modalManager.ts, src/main/views/viewManager.ts, src/main/views/webContentEvents.test.js, src/main/views/webContentEvents.ts
I noticed that our modals don't handle external links at all, since we've never had them before. However, now that we might want to do that, it would make sense to have similar handling around our links.
```release-note
NONE
```
=> Add webContents listeners to modals

src/common/JsonFileManager.ts
Make `JsonFileManager.writeToFile()` return a Promise instead of void. 
```release-note
NONE
```
=> Make writeToFile return a Promise in JsonFileManager

src/renderer/components/NewTeamModal.tsx
In order to be consistent with mobile v2, the add server modal fields order is changed (asking for server URL first and display name after).
Improvement: https://mattermost.atlassian.net/browse/MM-45058
This PR was tested on: Laptop running Linux (Ubuntu)
The new UI after the change:
```release-note
NONE
```
=> Change order of fields in add server modal to match the one in mobile v2

e2e/modules/environment.js, e2e/specs/popup.test.js, e2e/specs/settings.test.js, webpack.config.base.js
A bunch of E2E test fixes listed here:
- Add an environment variable `MM_TEST_SERVER_URL` to specify where the test Mattermost server is located
- Fixed the auto updater test where the `app-update.yml` file didn't exist
- Force Electron processes to stop on all OSes after each test
```release-note
NONE
```
=> E2E omnibus fixes

.vscode/launch.json, .vscode/tasks.json
Fix vscode debugger for E2E tests. The issue was the it didn't use `electron-mocha` and the correct entrypoint
```release-note
NONE
```
=> [chore] Fix vscode debugger for E2E tests

e2e/specs/settings.test.js, src/renderer/components/MainPage.tsx
There was a misleading error about tab status that was coming up when no servers were configured. This was a relic of older BrowserView/WebView architecture stuff where it was possible that we were missing tab statuses for certain tabs, which doesn't happen anymore. So we've removed that log entry.
Also fixed a couple lint headaches.
https://mattermost.atlassian.net/browse/MM-46857
```release-note
NONE
```
=> [MM-46857] Remove misleading console error about tab status when servers don't exist

package-lock.json, package.json
In lieu of the issues with upgrading to Electron v20+ (see here: https://github.com/mattermost/desktop/pull/2270), for now I've elected to upgrade to the latest Electron v19 patch and upgraded some of its dependencies as well.
https://mattermost.atlassian.net/browse/MM-47279
```release-note
Upgrade to Electron v19.1.1
```
=> [MM-47279] Upgrade to Electron v19.1.1 and other Electron dependency upgrades

src/main/views/downloadsDropdownMenuView.ts
I noticed this on ubuntu.
If you clicked a file from the downloads list it would open the downloads folder twice. On mac it would not open a second Finder window, that's why I missed it
```release-note
NONE
```
=> Downloads - Remove duplicate handler for showing file in folder

package-lock.json, package.json, src/renderer/components/LoadingAnimation/LoadingIcon.tsx
Upgrading to Electron v21
https://mattermost.atlassian.net/browse/MM-47279
```release-note
Upgrade to Electron v21.0.1
```
=> [MM-47279] Upgrade to Electron v21

.circleci/config.yml
Had to fix a couple build issues before we cut the next RC:
- Fixed the MSI build failing on the MSI (something about the installer service not running). Upgraded to the newest circleCI windows image
- Fixed the github uploading by upgrading the Go version
https://mattermost.atlassian.net/browse/MM-47463
```release-note
NONE
```
=> [MM-47463] Fix build issues

scripts/Makefile.ps1
Due to an issue with the MSI installer that @tboulis found, it looks like the changelog variable that we set could have actually been causing the Windows Installer issue we found. Since it doesn't look like we use it in the first place, this PR removes it.
https://mattermost.atlassian.net/browse/MM-47463
```release-note
NONE
```
=> Fix MSI build by removing changelog requirement

src/main/menus/app.test.js, src/main/menus/app.ts
When no servers exist, you can still pop the Add Server Modal when the Getting Started screen is there. This causes some confusion as it pops after the screen is finished, and you can't dismiss it since it thinks when it is queued that there's no servers.
This PR just removes the menu item to show it so that it can't be added while the Getting Started screen exists.
https://mattermost.atlassian.net/browse/MM-47778
```release-note
NONE
```
=> [MM-47778] Remove Sign into another Server menu item when no servers exist

src/main/views/viewManager.ts
There's a potential race condition that can crash the app when the app reloads. If a URL view was supposed to disappear as the computer was being locked, on wake the window may not yet be fully re-rendered causing a crash.
This PR just catches that so that the app doesn't crash.
https://mattermost.atlassian.net/browse/MM-47779
```release-note
Fixed an issue where the app could crash when logging back in.
```
=> [MM-47779] Prevent crash when either URL view or main window was destroyed first

src/main/app/initialize.test.js, src/main/app/initialize.ts, src/main/downloadsManager.ts, src/main/views/downloadsDropdownView.ts, src/main/webRequest/webRequestHandler.test.js, src/main/webRequest/webRequestHandler.ts, src/main/webRequest/webRequestManager.test.js, src/main/webRequest/webRequestManager.ts
In order to support URL rewriting from many different listeners, we need a manager that will allow us to bind as many listeners to the web requests as possible. This PR adds a manage for the WebRequest handlers and allows the app to bind as many listeners as we want.
https://mattermost.atlassian.net/browse/MM-47682
```release-note
NONE
```
=> [MM-47682] Implement WebRequestManager

src/main/downloadsManager.test.js, src/main/downloadsManager.ts
The save as dialog does not open and the file would be downloaded right away in the default download location. 
The fix is to detect if the download was initiated by user gesture or not.
This happens because we use `electron-context-menu` to show the right click menu, which when you click "Save as" uses `electron-dl` to trigger the download.
I would recommend we remove the `electron-context-menu` and use electron's Menu on the renderer process instead, which will give us the option to use our `downloadManager` when clicking "Save as" instead of the hard-coded `electron-dl`
https://mattermost.atlassian.net/browse/MM-47842
```release-note
NONE
```
=> [MM-47842] Make "save as" in context menu show the save dialog

e2e/specs/server_management/add_server_modal.test.js, src/renderer/components/ConfigureServer.tsx, src/renderer/components/NewTeamModal.tsx
Reverse order of server input fields in welcome screens
https://mattermost.atlassian.net/browse/MM-47776
```release-note
NONE
```
=> [MM-47776] Reverse order of input fields in server welcome screen

.circleci/config.yml
We've been pushing to TestFlight on every commit for the release branches, this generates a lot of noise and doesn't help us version well. This PR should stop that from happening.
=> Stop unnecessary TestFlight builds

src/main/downloadsManager.test.js, src/main/downloadsManager.ts, src/main/views/downloadsDropdownView.ts, src/main/webRequest/webRequestHandler.test.js, src/main/webRequest/webRequestHandler.ts, src/main/webRequest/webRequestManager.test.js, src/main/webRequest/webRequestManager.ts, src/types/webRequest.ts
The main features we'll need out of the new WebRequestManager will be to faciliate URL rewrite and header replacement. I've since locked down the access to the other handlers and I'm letting the manager be in charge of adding those listeners.
https://mattermost.atlassian.net/browse/MM-47682
```release-note
NONE
```
=> [MM-47682] Add helpers for URL rewriting, header replacement

src/common/JsonFileManager.ts, src/common/constants.ts, src/main/autoUpdater.ts, src/main/downloadsManager.ts, src/renderer/components/DownloadsDropdown/FileSizeAndStatus.tsx, src/renderer/downloadsDropdown.tsx
- Use downloads location as default when clicking "Save as".
- Remove update from downloads after upgrade when application starts
- Fix issue where "addedAt" was extracted from undefined object
- https://mattermost.atlassian.net/browse/MM-47754
- https://mattermost.atlassian.net/browse/MM-47970
```release-note
NONE
```
=> [MM-47970] + [MM-47754] Downloads fixes

e2e/modules/utils.js
One of the util methods was hanging the tests if a directory already existed.
```release-note
NONE
```
=> FIx E2E test util method

src/common/communication.ts, src/common/utils/constants.ts, src/main/preload/callsWidget.js, src/main/preload/mattermost.js, src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts, src/types/calls.ts
PR fixes some outstanding issues with the call state in the main window, namely:
- Channel toast should not show in the channel after joining the call.
- Leave button should render in the post card.
- Leaving the call from the post card should be allowed, as well as through slash command.
- Switching calls from the post card should work as in web version.
https://mattermost.atlassian.net/browse/MM-48142
https://github.com/mattermost/mattermost-plugin-calls/pull/235
```release-note
NONE
```
=> [MM-48142] Fix remaining call state issues in main window

src/main/downloadsManager.ts
When right-clicking a file and choosing Save As, if the filename had more than one `.`, the dialog would pick up each string seperated by a `.` and add it to the file extension list. Commonly reproducible when sharing macOS screenshots.
This PR ensures that we always get the actual file extension (ie. the last one) and use it for the dialog.
https://mattermost.atlassian.net/browse/MM-48167
```release-note
NONE
```
=> [MM-48167] Only grab the last extension from a filename during Save As

src/common/utils/constants.ts, src/main/downloadsManager.test.js, src/main/downloadsManager.ts, src/main/server/serverAPI.test.js, src/main/server/serverAPI.ts, src/main/server/serverInfo.ts, src/main/utils.test.js, src/main/utils.ts, src/main/views/MattermostView.ts, src/main/views/viewManager.test.js, src/main/views/viewManager.ts, src/main/webRequest/webRequestManager.ts, src/renderer/index.html, src/types/server.ts, src/types/webRequest.ts, webpack.config.renderer.js
This PR adds the logic to insert the correct CSP header when the app is loaded. It takes information from the web app's CSP header and adds in a few fields to allow for Desktop App modules to run.
https://mattermost.atlassian.net/browse/MM-47710
```release-note
NONE
```
=> [MM-47710] Override CSP header including allowances for the Web App and Desktop App

src/common/communication.ts, src/main/preload/mainWindow.js, src/main/utils.ts, src/main/views/MattermostView.ts, src/renderer/index.tsx, src/types/window.ts, webpack.config.renderer.js
This PR includes the handler for the cookie manager. This involves a system in which we strip the cookie out of the response headers and store it internally, then make sure that it's passed up with every request where it's necessary.
We also override the locally provided `document.cookie` property to make sure the local webapp has access to the cookie as needed (since it won't be allowed otherwise being on a locally hosted app).
https://mattermost.atlassian.net/browse/MM-47709
```release-note
NONE
```
=> [MM-47709] Implement cookie handling

src/main/views/MattermostView.ts
Since Boards uses it's own web request module that resolves differently that the web app one does, we had to add an extra override specifically for Boards to make sure that it can access its API.
```release-note
NONE
```
=> Fixed URL rewrite for Boards

src/main/views/MattermostView.ts, src/renderer/index.tsx, src/types/window.ts
This implements an override for the `getSiteURL` module, and overrides the origin when connecting to the websocket. These two changes allow the websocket to connect and pass information as normal without any issue.
Relevant webapp change: https://github.com/mattermost/mattermost-webapp/pull/11383/commits/d2699127df051cc22f680e81c4c996bf26acd415
https://mattermost.atlassian.net/browse/MM-48083
```release-note
NONE
```
=> [MM-48083] Add websocket overrides

electron-builder.json
We were rejected from the Mac App Store for having a deprecated API. I believe this was being caused by the inclusion of a bunch of unnecessary binaries from the native modules. I've restricted `electron-builder` from including these in the future.
https://mattermost.atlassian.net/browse/MM-48404
Closes https://github.com/mattermost/desktop/issues/2374
```release-note
NONE
```
=> [MM-48404] Exclude unnecessary binaries for native modules

electron-builder.json
Apparently we never fixed the AppImage shortcuts once the fix to `electron-builder` was merged. The issue with the `--no-sandbox` flag causing the app to crash is resolved by this fix.
https://mattermost.atlassian.net/browse/MM-48557
```release-note
Fixed an issue where the Applmage when added with the AppImageLauncher would not allow the app to launch correctly
```
=> [MM-48557] Fix AppImage shortcut

package-lock.json, package.json
This PR upgrades compass-icons to its latest version (0.1.32 from 0.1.21), fixing also the reported issue https://github.com/mattermost/desktop/issues/2366 (xmldom outdated version with a CVE fixed in version 0.5.0). The latest compass-icons depends on xmldom 0.6, which is the source of this dependency (ie xmldom is not a direct dependency of the desktop app).
https://mattermost.atlassian.net/browse/MM-48383
```release-note
NONE
```
=> [MM-48383] Upgrade compass-icons

src/main/app/intercom.test.js, src/main/menus/app.ts
When the Getting Started modal is open, a user can open the servers dropdown using the menu or a keyboard shortcut and trigger the Add Server Modal to open after the Getting Started one does, causing them to get stuck and require a second server be added.
This PR stops users from opening the servers dropdown until a server has been added.
Also fixed a bad unit test.
https://mattermost.atlassian.net/browse/MM-48682
```release-note
Fixed an issue where users could get stuck after finished the Getting Started flow
```
=> [MM-48682] Stop user from opening the servers menu when no servers are configured

.circleci/config.yml
The mac_installer build is taking a lot longer than expected, likely due to some issues with Apple during notarization.
I've extended the time to 60 minutes to hopefully cover this.
```release-note
NONE
```
=> Extend npm run package:* context deadline to 60m

package-lock.json, package.json
Was able to shave off about 10-15 MB from the package size by moving a bunch of our dependencies to the `devDependencies` section. I believe what this is doing is making sure we don't drop the source code into the app package that we provide, as that was happening before.
Thanks to @selfisekai for the suggestion.
Closes https://github.com/mattermost/desktop/issues/2342
```release-note
NONE
```
=> Reduced package size by moving most depedencies to devDependencies

src/main/windows/callsWidgetWindow.ts
There's a side effect in calling [`window.setVisibleOnAllWorkspaces`](https://www.electronjs.org/docs/latest/api/browser-window#winsetvisibleonallworkspacesvisible-options-macos-linux) on macOS which makes the main window (Mattermost) disappear. Setting the `skipTransformProcessType` prevents this behaviour as suggested in https://github.com/electron/electron/issues/25368#issuecomment-914960930.
I am open to more suggestions as there could be better ways to handle this case but so far it seems this is the quickest fix.
@Willyfrog Would be nice if you could run this locally and let me know if the issues you were encountering are gone.
https://mattermost.atlassian.net/browse/MM-49049
```release-note
NONE
```
=> [MM-49049] Fix main window disappering on call join

.circleci/config.yml
I've noticed deviations in how some OSes run the lint/type/tests, so I think it makes sense to run those checks per OS to make sure we don't end up with failures locally that won't repro on the remote.
```release-note
NONE
```
=> Remove check job and perform check on each build

src/main/diagnostics/steps/internal/utils.test.js
There was a flaky unit test that was dependent on `Date.now()` and arbitrary timing to run. It usually ran fine locally, but would fail in CI frequently. I've updated it to base itself on mocking `Date.now()`.
```release-note
NONE
```
=> Fix flaky unit test

src/main/views/MattermostView.ts
Found this when running E2E tests on my local VM. When we start the app and specify a deep linking URL, the first thing we do is start all the views and have them load their default URLs. On some machines, what would happen is that the initial URL wouldn't be finished loading and the app would throw an `ERR_ABORTED` error on the initial URL and start the retry logic.
The deeplink URL would then finish loading, but it would then try to retry the original URL after 5 seconds and forward you back to the original URL, which isn't ideal. This wouldn't reproduce on my local Windows machine, but my Windows VM was a bit slower and showed this behaviour, causing the E2E test to fail pretty reliably.
This PR catches the `ERR_ABORTED` error and ignores the retry logic, since an `ERR_ABORTED` is …
=> Fixed an issue where opening the app with a deeplink may cause the app not to redirect to the correct URL

e2e/specs/linux_dark_mode.test.js
The Linux Dark Mode test seems to be failing quite regularly in which instead of the dark mode toggle being hit, we hit the full screen one.
To try and fix this, I've added an await to wait for the next keystroke to be pushed, hopefully should fix things.
```release-note
NONE
```
=> Add await to the dark mode toggle test for Linux

src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts
PR brings back the title bar to the calls popout window (when global widget is enabled, Desktop >= 5.3) which was originally removed to avoid showing the menu bar. 
At the time I wasn't aware that there was a simple way to customize a window opened from the renderer side but using [`webContents.setWindowOpenHandler()`](https://www.electronjs.org/docs/latest/api/web-contents#contentssetwindowopenhandlerhandler) is working nicely and allows us to hide the menu bar while retaining the title bar which is useful for easily resizing, closing and dragging the window.
https://mattermost.atlassian.net/browse/MM-49082
https://github.com/mattermost/mattermost-plugin-calls/pull/282
```release-note
NONE
```
=> [MM-49082] Hide menu bar in calls popout window

src/main/views/viewManager.ts
When reloading the configuration, if we have deleted a server and thus a view, we need to make sure that we unset the value of `currentView` so that other tasks working with the views aren't expecting a view to be visible. We were clearing the value using `delete`, which apparently sets the `string` to `null`, which of course evaluates to `true`.
This PR changes the operation to explicitly set the value to `undefined`.
https://mattermost.atlassian.net/browse/MM-49690
```release-note
NONE
```
=> [MM-49690] Set currentView to `undefined` instead of using `delete`

src/main/downloadsManager.ts, src/main/views/webContentEvents.test.js, src/main/views/webContentEvents.ts
With the changing over to using the `mm-desktop` protocol, we end up a cross-origin request when trying to download files from the server. Thus, it will try to open all files in a new window, which isn't ideal.
This PR forces them through the `DownloadsManager` manually, by denying the `new-window` request and manually calling `downloadURL` on the corresponding `webContents`.
@tboulis I'm honestly not totally happy with the way I've done this, but it's the best I could come up with for now. Feel free to provide suggestions to improve.
https://mattermost.atlassian.net/browse/MM-49689
```release-note
NONE
```
=> [MM-49689] Force `/api/v4/files` links to not open a new window and download correctly

electron-builder.json
This will basically prevent the creation of symlinks in /usr/lib/.build_id to avoid conflicts with other electron applications
https://mattermost.atlassian.net/browse/MM-50220
and
https://github.com/mattermost/desktop/issues/2461
```release-note
Fix RPM conflict with other electron based applications
```
=> [MM-50220] Fix issue with rpm build conflicting with other electron applications

src/main/server/serverAPI.test.js, src/main/server/serverAPI.ts, src/main/server/serverInfo.ts, src/types/server.ts
With the changes to allow Boards to function as a product, newer server versions won't have the Boards plugins installed anymore, thus when the server is added to the Desktop App the Boards tab wouldn't be automatically added.
This PR changes the logic to check for the `BuildBoards` flag in the `ClientConfig` object. If it set to `true` then we show the Boards tab.
Also, made a fix to the API to allow for chunked responses, since `community.mattermost.com` was sending those.
https://mattermost.atlassian.net/browse/MM-50042
```release-note
Fixed an issue where sometimes the Boards/Playbooks tabs wouldn't appear automatically when a server was added.
```
=> [MM-50042] Detect Boards using the BuildBoards flag in the client config

src/common/communication.ts, src/main/preload/callsWidget.js, src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts
Setting the parent seems to do the trick and now the expanded view should be focused and brought on top when clicking on the icon.
@tboulis It would be great if you could give it a quick try and let me know if it works as expected now. Thanks!
https://mattermost.atlassian.net/browse/MM-49739
```release-note
NONE
```
=> [MM-49739] Set parent window on calls expanded popout view

src/main/views/webContentEvents.test.js, src/main/views/webContentEvents.ts
With my recent changes [here](https://github.com/mattermost/desktop/pull/2544), I neglected to account for the case in which the URL doesn't match any of our specifically handled cases, which also happened to be the default external links case. Our previous method specifically checked if the URL matched an active view, but since the new one does not, we can just allow it to fall through and open uncaught cases in the browser.
https://mattermost.atlassian.net/browse/MM-50410
```release-note
NONE
```
=> [MM-50410] Allow any unhandled target=_blank links to open in the browser

src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts
With changes in https://github.com/mattermost/desktop/pull/2544, `WindowManager.getServerURLFromWebContentsId()` wasn't taking into account the Calls widget window which doesn't really have a view so it would return undefined and eventually fail during a permission check for media in `setPermissionRequestHandler()`.
PR adds a check to make sure that we also match against the web contents id for the calls window, if present.
@cpoile Could you give this a quick try on your system as well?
https://mattermost.atlassian.net/browse/MM-50411
```release-note
NONE
```
=> [MM-50411] Fix media permissions failure on Calls window

package-lock.json, package.json
This PR upgrades Electron to v23. This will drop support for Windows 7/8/8.1 explicitly, as the version of Chromium will not working on versions before 10.
https://mattermost.atlassian.net/browse/MM-50433
```release-note
Upgrade to Electron v23.0.0. This will drop support for Windows 7/8/8.1.
```
=> [MM-50433] Upgrade to Electron v23.0.0

src/main/preload/callsWidget.js, src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts, src/types/calls.ts
PR implements some missing logic which is needed to surface clients errors (e.g. connection failure) from global widget to main window.
https://user-images.githubusercontent.com/1832946/219517628-49503970-a862-4cbc-ae52-2f1a864e7ff2.mov
https://user-images.githubusercontent.com/1832946/219517633-412ff76c-c4ea-40ee-980f-beb116944ae0.mov
https://user-images.githubusercontent.com/1832946/219517636-e898bd50-10a9-4e94-8027-ea7366eca94a.mov
https://github.com/mattermost/mattermost-plugin-calls/pull/339
https://mattermost.atlassian.net/browse/MM-49089
```release-note
NONE
```
=> [MM-49089] Propagate calls client errors

src/common/communication.ts, src/main/preload/callsWidget.js, src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts, src/types/calls.ts
- This allows the Calls popout to:
- Send internal links to the Desktop to be processed as any other link would
- Capture link clicks that would open a separate window, and process them as those clicks would normally be processed.
- More detail as to what that looked like here: https://github.com/mattermost/mattermost-plugin-calls/pull/340
- https://mattermost.atlassian.net/browse/MM-49079
macOS 12.5 Monterey
```release-note
Calls: Handle call thread links correctly
```
=> MM-49079 - Calls: process link clicks from Calls popout

src/main/preload/callsWidget.js, src/main/preload/mattermost.js, src/main/utils.ts, src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts, src/types/calls.ts
PR addresses a couple of outstanding issues with screen sharing:
1. After https://github.com/mattermost/desktop/pull/2554 there was still an issue preventing the error message from surfacing up again if dismissed and permissions were missing after the first attempt to share.
2. Since macOS 10.15 Catalina screen permissions need to be explicitly (and manually) granted to an app through the system settings. This has caused a lot of confusion for users on why screen sharing isn't working (see ticket below). On top of that the system isn't really helping since permissions require an app restart to take effect and the prompt to fix them is only showed once per app execution. To help with this we reset permissions on a share request if missing and also open the related system setting pane in an …
=> [MM-46980] Improve screensharing permissions flow

src/main/diagnostics/steps/internal/loggerHooks.test.js, src/main/diagnostics/steps/internal/obfuscators.ts
We had a function that would allow an untrusted input to override the type of the object that was inputted via local prototype pollution. This PR explicitly disallows for an object with the key `__proto__` to be included in the obfuscated output.
https://mattermost.atlassian.net/browse/MM-50712
```release-note
NONE
```
=> [MM-50712] Fix local prototype pollution flaw

src/common/constants.ts
We were using a vulnerable regex that could have resulting in a DoS attack. This PR replaces the regex with a safer one.
Checked using https://devina.io/redos-checker
https://mattermost.atlassian.net/browse/MM-50569
```release-note
NONE
```
=> [MM-50569] Fix insecure win32 path regex

src/main/preload/callsWidget.js, src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts, src/types/calls.ts
PR implements some stricter checks to make sure Calls events are coming from the expected sources (either server's main view or calls widget window).
@amyblais These fixes would probably need to go in 5.3
https://mattermost.atlassian.net/browse/MM-50995
https://mattermost.atlassian.net/browse/MM-50975
https://mattermost.atlassian.net/browse/MM-50982
https://mattermost.atlassian.net/browse/MM-50994
```release-note
NONE
```
=> [MM-50995] Harden Calls events handling

src/main/app/initialize.ts, src/main/windows/callsWidgetWindow.ts
When upgrading to Electron v23, it seems that a new permission was added to check if we were allowed to write to the clipboard using the Clipboard API. I think the permission has existed for a while (since it didn't come up in the Breaking Changes) but it must have been recently enforced (or a bug was fixed)
This PR makes sure that we allowed that permission when coming from a trusted source. I've also added the calls widget window as a trusted source since it asks to play media sometimes.
https://mattermost.atlassian.net/browse/MM-50527
```release-note
NONE
```
=> [MM-50527] Explicitly allow the Mattermost views access to write to the clipboard using Copy Link

src/common/utils/url.test.js, src/common/utils/url.ts, src/main/views/viewManager.ts, src/main/views/webContentEvents.ts, src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts, src/main/windows/windowManager.ts
PR adds some stricter checks on what can be opened/navigated from calls widget and popout windows.
- widget window should only navigate to the widget url and open the popout url.
- popout window should only navigate/open to allowed sources (using `webContentsEventManager.addWebContentsEventListeners`).
@amyblais Similarly to the previous one it would be good to include this in 5.3 as well.
@cpoile Could you give this a pass to make sure I didn't break anything link clicking related?
https://mattermost.atlassian.net/browse/MM-50973
https://mattermost.atlassian.net/browse/MM-50974
```release-note
NONE
```
=> [MM-50973] Harden Calls windows URL navigation checks

package-lock.json, package.json
There was a bug in Electron v23 that was causing the calls widget not to be draggable on the MAS build. This PR upgrades to Electron v23.1.2 which includes a fix for this issue: https://github.com/electron/electron/pull/37466
https://mattermost.atlassian.net/browse/MM-50537
```release-note
NONE
```
=> [MM-50537] Upgrade to Electron v23.1.2

src/main/views/webContentEvents.ts
There was a case where a user could click on a link that was able to trick the application into navigating to an arbitrary URL by having it prefixed with the path: `/plugins/..%2F`. From there any internal URL would open in the popup window which has some looser restrictions around navigating to external URLs. This was caused because our URL checker would note that the URL was a plugin URL, but Chrome would not evaluate it as such.
This PR adds a listener on the `will-redirect` event to ensure that those URLs cannot be exploited by making sure that any redirects to internal URLs need to go to the matching plugin/managed resource that is allowed by the application.
https://mattermost.atlassian.net/browse/MM-50948
```release-note
Fixed an issue where a certain URL form would allow the popup …
```
=> [MM-50948] Prevent popup windows from redirecting to internal URLs outside of the plugin/managed resource URLs

src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts
PR fixes a race condition when switching from one call to another (or starting a new call when already in one). Having two Calls clients active at the same time even for just a few moments led to a permission error when accessing the microphone. I am not exactly sure why Electron would prevent that but it's a not a strong issue at the moment since we don't want to allow a user to be in more than one call at the same time. 
The fix here is to wait until the widget window is properly closed and only then proceed with creating a new one.
https://mattermost.atlassian.net/browse/MM-51222
```release-note
Fixed a race condition leading to a permissions error when switching calls.
```
=> [MM-51222] Fix race condition on switching calls

scripts/patch_mas_version.sh
The old patcher was based on CircleCI and wasn't grabbing a unique ID for GitHub Actions. This PR should make sure it always has a unique id.
```release-note
NONE
```
=> Allow MAS build to be repeated more easily

.github/workflows/nightly-browser-view.yml, .github/workflows/nightly-rainforest.yml
We missed an environment variable for making sure we build and push the Windows installers as well.
```release-note
NONE
```
=> Add MM_WIN_INSTALLERS for nightly builds

.github/ISSUE_TEMPLATE/config.yml
Some users have erroneously been creating issues in the Desktop App repository that should belong to webapp, or might be a feature request. We have issue templates that handle pointing users towards the places they need to go to do that, but some choose to use a blank issue which doesn't allow us to control how issues are created.
This PR will disable blank issue creation in the Desktop App repo, as users should be using one of the created templates.
```release-note
NONE
```
=> Disable creation of blank issues

src/main/views/webContentEvents.ts
When I removed the use of `getView()` from the `webContentsEvents` module I neglected to check for the case where other servers would need to be switched to via permalinks.
This PR restores the use of the `getViewByUrl()` function as a last check before we try to open a URL in a browser window. This should still mean minimal performance hits since it won't need to be called very often.
https://mattermost.atlassian.net/browse/MM-51406
```release-note
NONE
```
=> [MM-51406] Check for other server URLs when trying to navigate

src/common/config/defaultPreferences.ts
On Linux machines that are using a desktop env which conforms to the FreeDesktop spec, users should have the XDG_DOWNLOAD_DIR variable set to specify their default download directory.
This patch ensures that this directory is used if the variable is present.
Hoping this will fix the following issue in the Mattermost snap: https://github.com/snapcrafters/mattermost-desktop/issues/65
It's not super clear to me where best to add a test for this, but I'm happy to do so if someone can give a quick pointer on where might be most appropriate.
This PR was tested on: my desktop machine, Linux/ubuntu
```release-note
Ensure that default download location respects `XDG_DOWNLOAD_DIR` where it is set.
```
=> fix: use XDG_DOWNLOAD_DIR as default download dir

package-lock.json, package.json, src/renderer/components/ConfigureServer.tsx, src/renderer/components/NewTeamModal.tsx
When I upgraded Electron, I missed checking the E2E tests (and my automated job had apparently stalled out and not updated) so they weren't running on the latest code. In order to run, we needed to update to the latest `node-abi` so that we could build modules on the latest Electron.
Once the tests were run, some modal bugs were uncovered, caused by the migration away from `window.postMessage`. Some error handling was not properly coded in, so I've fixed that too. All tests should be passing now :)
https://mattermost.atlassian.net/browse/MM-51406
```release-note
NONE
```
=> [MM-51406] Update node-abi, fix some server modal bugs

src/common/config/index.ts, src/main/app/config.ts, src/main/app/initialize.test.js, src/main/app/initialize.ts, src/main/app/intercom.ts
A while back, there was an issue in which the new server modal or the Welcome modal would show up when the user had GPO teams configured. At the time, it was fixed by checking for the teams to be added later on and not popping the modal until then. What was neglected was that we could just await the call before the rest of the app even loaded, which seems to be the right call and was removed at some point during v4.7.
This PR goes back to doing it the correct way and should be cleaner in general.
```release-note
Fix the issue where we sometimes need to wait for GPO teams properly.
```
=> Fix the issue where we sometimes need to wait for GPO teams properly

.github/ISSUE_TEMPLATE/bug_report.yml
Adding a checkbox to make sure users are submitting issues for the latest version of the Desktop App, instead of older ones.
```release-note
NONE
```
=> Add a checkbox asking users to reproduce on the latest version of the Desktop App

src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts
- If the user opens the calls popout and then closes it (without leaving the call), any click on the webapp will cause a crash. We need to manually set the popout to null so that the null/undefined guards will work. (Otherwise, the var will be pointing to a non-empty object after the popout is closed.)
- https://mattermost.atlassian.net/browse/MM-51850
```release-note
Calls: fixed a bug where, after opening the calls popout then closing it (without leaving the call), subsequent clicks will cause a crash.
```
=> MM-51850 - Calls: Fix for crash after closing popout

src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts
(cherry picked from commit 4fe66b298deae51a4c83113579f0834feec5924f)
- #2647 
```release-note
Calls: fixed a bug where, after opening the calls popout then closing it (without leaving the call), subsequent clicks will cause a crash.
```
=> cherry-pick: MM-51850 - Calls: Fix for crash after closing popout (#2647)

entitlements.mas.plist
We had a rejection from Apple in which they told us a bunch of entitlements were unnecessary, so I've removed them.
NONE
```release-note
NONE
```
=> Remove unneeded entitlements for MAS

.github/workflows/release-mas-only.yaml
=> Fixed a typo in MAS workflow

src/main/views/downloadsDropdownMenuView.test.js, src/main/views/downloadsDropdownMenuView.ts, src/main/views/downloadsDropdownView.test.js, src/main/views/downloadsDropdownView.ts, src/main/windows/windowManager.test.js, src/main/windows/windowManager.ts
This PR moves the last two objects (the downloads dropdown menus) out of the `WindowManager`  and into their own singletons.
```release-note
NONE
```
=> Migrate downloads dropdown menus to singletons

src/main/views/teamDropdownView.ts
One of the changes I made to the team dropdown causes the mentions to accumulate and never reset.
This PR makes sure the maps are cleared before trying to re-fill them.
```release-note
NONE
```
=> Fixed bad mention counts in the dropdown menu

src/main/preload/desktopAPI.js, src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
Something I refactored caused the auto snap function in Windows 11 to stop resizing the window correctly.
This PR adds a check on another listener to make sure once the window is moved that the size of the elements are correct, which seems to have fixed the issue.
```release-note
NONE
```
=> Fixed Snap issue with resizing on Windows 11

.github/workflows/build-for-pr.yml, .github/workflows/ci.yaml, .github/workflows/nightly-main.yml, .github/workflows/release.yaml
The GPG key for Wine (used to build cross-platform) is out of date. I've updated to latest LTS.
```release-note
NONE
```
=> Update wine key to 22.04

src/main/app/initialize.ts, src/main/app/utils.ts
There's a case for some reason when we update to a new version that the application will crash when trying to ensure we update the browser cache for the main window. We force a reload on the main window, which fails saying that the object is destroyed. It's possible that this is just a check to make sure the page is reloaded afterwards, but it might be doing it itself.
I've done 2 things to mitigate any issues:
- Move the app cache call down a bit to hopefully make sure the window exists
- Add a catch to ensure the crash doesn't happen (we just need to log it if the object is already reloading)
https://mattermost.atlassian.net/browse/MM-52380
```release-note
NONE
```
=> [MM-52380] Fix unhandled rejection when clearing app cache

package-lock.json, package.json
There was a weird, inconsistent bug where sometimes spellchecker highlighting would persist even after text was deleted. This is likely related to an Electron thing, so I've upgraded us to v23.0.0, and also made sure the context-menu wasn't the culprit either.
This may not be the exact fix, but it's the most likely one. We'll see if it comes back again.
https://mattermost.atlassian.net/browse/MM-52285
```release-note
Fixed an issue where spellcheck highlighting might persist after text is deleted.
```
=> [MM-52285] Upgrade to Electron v23.3.0, electron-context-menu to v3.6.0

src/main/windows/callsWidgetWindow.ts
PR sets the `hasShadow` option to `false` for the calls widget window. The native macOS shadow is not playing nicely and causing some weird artifacts and inconsistencies in sizing as we already have some shadow in place at the CSS level.
The only concern with this change is that it makes it a little more difficult to figure out whether the widget window is focused but not sure how important that is. @tanmay-des Maybe we could work on improving that at the widget level through some clever styling
Before:
After:
```release-note
NONE
```
=> Prevent calls widget window from showing native shadow

i18n/en.json, src/main/app/initialize.ts, src/main/app/intercom.ts, src/main/downloadsManager.ts
When the application is upgraded, it loses access to the folders it was previously granted entitlements to, including whatever the configured default downloads directory is. Since we still keep the configuration between upgrades however, it confuses the app when it doesn't have access.
This PR will force the user to reset the default downloads directory when the folder becomes inaccessible, allowing the app to download normally to whatever folder was chosen.
https://mattermost.atlassian.net/browse/MM-52139
```release-note
Fixed an issue for the MAS build where the default downloads directory would be invalid after upgrade.
```
=> [MM-52139] Force user to reset default downloads directory when the app is not allowed to access it

src/common/Validator.ts, src/common/communication.ts, src/common/servers/MattermostServer.ts, src/common/servers/serverManager.test.js, src/common/servers/serverManager.ts, src/common/utils/url.test.js, src/common/utils/url.ts, src/main/app/app.test.js, src/main/app/app.ts, src/main/app/initialize.test.js, src/main/app/initialize.ts, src/main/app/utils.ts, src/main/authManager.test.js, src/main/authManager.ts, src/main/certificateStore.test.js, src/main/certificateStore.ts, src/main/contextMenu.ts, src/main/trustedOrigins.test.js, src/main/trustedOrigins.ts, src/main/utils.test.js, src/main/utils.ts, src/main/views/MattermostView.ts, src/main/views/viewManager.ts, src/main/views/webContentEvents.test.js, src/main/views/webContentEvents.ts, src/main/windows/callsWidgetWindow.ts, src/renderer/components/ConfigureServer.tsx, src/renderer/components/NewTeamModal.tsx, src/renderer/modals/login/loginModal.tsx, src/renderer/modals/permission/permissionModal.tsx
A community member reported that subpaths were causing issues when clicking links and attempting to navigate incorrectly. This led me to do some refactoring of the URL utils while fixing the bug.
Here are the highlights:
- Removed the default import and a few redundant functions
- Converted over everything checking for internal URLs to use `isInternalURL` (this fixed the bug)
- Reworked the tests a bit
https://mattermost.atlassian.net/browse/MM-52587
Closes https://github.com/mattermost/desktop/issues/2692
```release-note
Fixed an issue where servers on subpaths would not navigate to external URLs on the same domain properly
```
=> [MM-52587] Clean up URL utils, use isInternalURL when possible

src/main/preload/desktopAPI.js, src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
A few of the weird resizing cases showed up again after the refactor, I've made fixes for them:
- macOS; Fixed the issue where rapidly resizing cues up a bunch of changes to the BrowserViews and keeps it bouncing back and forth
- Linux: Fixed the issue where maximizing/full-screening doesn't resize the window properly
- Windows: Ensured that users with 'Show window contents while dragging" is off will still be able to resize.
```release-note
NONE
```
=> Fixed a few resizing issues

src/common/communication.ts, src/main/app/app.ts, src/main/app/config.ts, src/main/app/initialize.test.js, src/main/app/initialize.ts, src/main/app/utils.ts, src/main/tray/tray.test.js, src/main/tray/tray.ts, src/main/views/viewManager.ts, src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
We had some feedback from community members about the tray icon misbehaving, so I've done some work to improve it.
The behaviour should be as follows:
Windows:
- Left-clicking on the icon will bring the app to the foreground (and restore or unhide if it is minimized)
- Right-clicking should bring up the context menu
macOS:
- Both right and left click should bring up the context menu, should never show the app
Linux:
- In most cases, the behaviour should be the same as Windows, HOWEVER, some OSes may not support the tray icon, or may support an older version that has a bug with the click event, so it's possible the context menu will be shown with either left or right click.
https://mattermost.atlassian.net/browse/MM-52625
```release-note
Improved the tray icon click behaviour across OSes …
```
=> [MM-52625] Rework tray icon code into a class, make the behaviour of the tray icon consistent with the OS it's running on

src/main/windows/mainWindow.ts
My addition of `setAutoHideMenuBar` actually caused a different issue on Linux when you press Alt. This fix should now make sure the menu bar never shows up as it should be forced hidden everytime we emit bounds.
```release-note
NONE
```
=> Fix issue where Linux menubar pops up when it's not supposed to

src/main/windows/settingsWindow.ts
For some reason, closing the Settings window is causing my app to crash on nightly on macOS.
The culprit seems to be calling `view.focus()` on a BrowserView too quickly after the window closes (not sure why).
To fix it, I just added an arbitrary delay on the focus call, which seems to have solved the issue for now.
```release-note
NONE
```
=> Fix weird macOS crash that occurs when closing the settings window

entitlements.mas.plist
App Sandbox requires an entitlement for USB devices, which was blocking YubiKeys from being used to authenticate.
This PR adds the USB entitlement.
https://mattermost.atlassian.net/browse/MM-52581
```release-note
Fix YubiKeys not working on the MAS build
```
=> [MM-52581] Add USB entitlement for MAS build

src/main/app/app.ts
I missed adding a call to `MainWindow.show()` when updating the deep linking/second instance call, so I've re-added that.
```release-note
NONE
```
=> Fixed issue where launching the app a second time wouldn't show the main window if it was hidden

src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts
- The popout didn't have the `Mattermost/version` userAgent. The only way to set this (that works) is through the `browserWindow.loadURL` fn, but we don't use that for the popout, we use the `window.open` from the calls side. It's not possible to set the userAgent directly with `window.open` or in the `windowOpenHandler` return options. The best way I could come up with is to just reload the calls popout using the `loadURL`. Through trial and error I found a place to do that, which doesn't cause the screen to flicker or load and reload, luckily. We can do it even earlier in the process (e.g., the `dom-ready` event) but that returns an error (but, oddly, everything works and the userAgent does get correctly set). The `did-frame-finish-load` event is the earliest that doesn't return an …
=> MM-51956 - Fix for: Calls popout generating duplicate notifications

src/main/views/webContentEvents.ts, src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts, src/main/windows/settingsWindow.ts
Some navigation code changes, as well as https://github.com/mattermost/desktop/pull/2713 revealed an issue with how we check for the calls widget/popout. We should be getting the root server URL to check against instead of the calls widget URL, whatever that may be, so I've fixed that.
This was causing a white screen for users of nightly.
https://mattermost.atlassian.net/browse/MM-52879
```release-note
NONE
```
=> [MM-52879] Fixed calls popout URL checking

src/common/servers/serverManager.ts, src/main/app/intercom.ts
This PR fixes two server manager issues:
- If the last server is deleted, re-adding a server causes the app to crash. This was caused by not resetting the `currentServerId` when no servers were left.
- When adding the first server on launch, the app would add it twice. This was caused by us calling the Welcome Screen twice.
```release-note
NONE
```
=> Fix two server manager issues

electron-builder.json
This PR removes the inclusion of `elevate.exe`, an application used for scripting elevated permissions when installing our app in a per-machine fashion instead of per-user. Since we don't explicitly support per-machine for the EXE installer, this is no longer necessary.
```release-note
NONE
```
=> Remove elevate.exe from the NSIS installer

src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
This PR fixes two issues with window sizing:
- On Windows 10/11, changing servers would cause the window to unsnap if snapped, due to [this bug](https://github.com/electron/electron/issues/25359). I've made an exception for Windows to fix this for our purposes.
- Restoring the saved window bounds for the `MainWindow` was failing due to calling the screen size before the app was ready, which wasn't working, so I've moved it over to the `init()` call.
```release-note
NONE
```
=> Fix window issues

package-lock.json, package.json
This PR upgrades the Desktop App to Electron v24, which includes the latest Chromium and Node fixes.
```release-note
Upgrade to Electron v24.3.1
```
=> Upgrade to Electron v24.3.1

.github/workflows/release.yaml, scripts/generate_release_post.sh
For some reason, the script running in GitHub Actions grabbed the same tag that we just made. So I fixed up the script to explicitly exclude it.
```release-note
NONE
```
=> Fix release post script

src/main/notifications/index.test.js, src/main/notifications/index.ts
When clicking on a notification, we weren't calling `MainWindow.show()` in the handler to make sure the window showed itself. This PR changes so that we make sure to do that.
https://mattermost.atlassian.net/browse/MM-52984
```release-note
NONE
```
=> [MM-52984] Fix minimized window not showing when clicking the notification

src/common/servers/serverManager.test.js, src/common/servers/serverManager.ts, src/main/views/viewManager.test.js, src/main/views/viewManager.ts
When clicking on a deep link, for links that don't include a pathname (eg. [mattermost://community.mattermost.com](mattermost://community.mattermost.com)), the app would fail to open them with an error message.
This PR forces a pathname so that matching works correctly.
https://mattermost.atlassian.net/browse/MM-53056
```release-note
NONE
```
=> [MM-53056] Force a pathname when checking for deep links

scripts/generate_release_post.sh
Fixing an issue with the release post generation script in which some of the pipe calls don't run in order, so we need to separate them out.
https://mattermost.atlassian.net/browse/MM-53201
```release-note
NONE
```
=> [MM-53201] Fix piping concurrency issues with release post generation script

package-lock.json, package.json, scripts/notarize.js
We've been using a legacy method to notarize our app, and apparently a newer and much faster one exists called `notarytool`. I've updated the dependency, and enabled `notarytool`, so now macOS builds should be a LOT faster :)
https://mattermost.atlassian.net/browse/MM-53199
```release-note
NONE
```
=> [MM-53199] Update to use `notarytool`

src/app/serverViewState.test.js, src/app/serverViewState.ts, src/main/server/serverInfo.ts
When a user tries to enter a server URL that has plugins disabled, the app will tell the user that their server isn't valid, even though it is.
This PR changes the logic to not require the user of the plugins API to get the server status.
https://mattermost.atlassian.net/browse/MM-53294
Closes https://github.com/mattermost/desktop/issues/2766
```release-note
Fix bad user feedback on server URL validation when plugins are disabled
```
=> [MM-53294] Fix bad user feedback on server URL validation when plugins are disabled

src/main/diagnostics/steps/internal/utils.ts, src/main/diagnostics/steps/step3.serverConnectivity.ts, src/main/server/serverInfo.ts
When running diagnostics, we check the current configured servers to ensure reachability. Unfortunately, there was a bug introduced when refactoring for the `ServerManager` in which the wrong URL was provided and would always crash. This revealed a further bug where if the server was unreachable, diagnostics would always crash.
This PR fixes the issue with the wrong URL, as well as catches the potential crash that could happen.
https://mattermost.atlassian.net/browse/MM-53295
Closes https://github.com/mattermost/desktop/issues/2769
```release-note
Fix crash in diagnostics when server is unreachable
```
=> [MM-53295] Fix crash in diagnostics when server is unreachable

e2e/utils/artifacts.js
This PR fixes a bug in the E2E test report upload script, which caused the report to be inaccessible for Windows E2E tests.
https://mattermost.atlassian.net/browse/CLD-5909
```release-note
NONE
```
=> Fix E2E test report upload URL

src/main/views/MattermostBrowserView.ts
Some reports were happening of developers having trouble opening the Dev Tools on macOS, requiring them to restart the Desktop App to make it work. After some investigating, I noticed that the `devtools-closed` event wasn't firing and the `isDevToolsOpened()` call was returning true. This was happening everytime I would open a Dev Tools window for one server, then open a second window for a different, close the original one and then try to re-open the original one.
I unfortunately wasn't able to find the root cause of this, since nothing had been reported to Electron and I wasn't able to reproduce on a Fiddle, so what I've done is create a workaround in which we check if the Dev Tools was successfully opened after the call was made, and if not we manually call `closeDevTools()` and then …
=> [MM-50536] Add workaround for Dev Tools not opening correctly on Mac

webpack.config.base.js
When we migrated to GitHub Actions, I neglected to fix the flag for the nightly build to turn on the React Developer Tools. This PR fixes that by checking for the right workflow.
```release-note
NONE
```
=> Re-add React Developer Tools to nightly builds

package-lock.json, package.json
Upgrading to the latest release of Electron v24 to fix an issue with screen sharing in Calls on Linux.
Closes https://github.com/mattermost/desktop/issues/2694
```release-note
Upgrade to Electron v24.6.3
```
=> [GH-2694] Upgrade to Electron v24.6.3

e2e/specs/menu_bar/full_screen.test.js, src/common/utils/constants.ts
Dropping the minimum width of the Desktop App down to 600px to accommodate for users wanting to have the app in a smaller window.
Closes https://github.com/mattermost/desktop/issues/2786
https://mattermost.atlassian.net/browse/MM-53490
```release-note
Set minimum window width to 600px
```
=> [MM-53490] Reduce min window width to 600px

src/main/downloadsManager.test.js, src/main/downloadsManager.ts
Disabling automatic updates will not automatically dismiss the notification if it's already been saved to the Downloads dropdown. This PR makes sure to clear that out on startup if auto-updates were disabled to avoid any confusion.
https://mattermost.atlassian.net/browse/MM-53841
```release-note
Fixed an issue where auto updating wouldn't be properly disabled
```
=> [MM-53841] Remove upgrade notification if auto updates were switched off

package-lock.json, package.json, src/main/authManager.ts, src/main/certificateManager.ts, src/main/views/viewManager.ts, src/main/views/webContentEvents.ts, src/main/windows/callsWidgetWindow.ts
This PR upgrades the Desktop App to Electron v26, which includes the latest Chromium and Node fixes.
Closes https://github.com/mattermost/desktop/issues/2694
```release-note
Upgrade to Electron v26.1.0
```
=> Upgrade to Electron v26.1.0

src/common/JsonFileManager.ts, src/main/downloadsManager.ts
There was a report of users having the app crash when restarting due to missing files that were downloaded, deleted from the file system, but not cleared from the Downloads dropdown.
I wasn't able to reproduce the exact issue, but I found and fixed 2 issues that were likely contributing:
- The initial crash report was due to an `ENOENT` error (file not found) which I've wrapped in a `try/catch` to make sure that the app won't crash in the same way again.
- The reason that this was hard to reproduce was being caused by the saved downloads list not saving correctly (it was being corrupted by multiple async saves), so I've added a queue of promises that need to happen subsequently in order to save correctly.
Between these two fixes this should help alleviate the linked ticket. I also noticed …
=> [MM-54279] Fix issues around working with saved downloads

src/renderer/components/ConfigureServer.tsx
On the Welcome Screen while we are validating a URL, we would always populate the returned validated URL from the main process after it was returned, regardless of whether the URL was changed in the meantime.
This PR removes the extra call that was doing that.
https://mattermost.atlassian.net/browse/MM-54276
Closes https://github.com/mattermost/desktop/issues/2809
```release-note
NONE
```
=> [MM-54276] Stop URL from being populated on validation regardless of change/timeout

src/common/config/defaultPreferences.ts, src/common/log.test.js, src/common/log.ts
New installations did not have a default logging level set, so `electron-log` was defaulting to `silly` which was logging all keystrokes and a lot of other noise, which could fill up a user's hard drive.
This PR makes sure to set the default config item to `info` and to set the log level to `info` when the app starts by default in case the user (or some other source) removes the config item.
https://mattermost.atlassian.net/browse/MM-54170
```release-note
Fixed an issue where the default logging level was `silly` for all new installs
```
=> [MM-54170] Automatically set the logging level to info if not specified

src/renderer/components/MainPage.tsx
We were storing the darkmode in a state, instead of using what we got from the props. The change just uses whatever information we get from the props.
https://mattermost.atlassian.net/browse/MM-54005
```release-note
Fix bug where changes in the OS dark/light mode did not reflect immediately in the window top bar
```
=> Fix top bar theme when changing the system settings

src/common/Validator.ts, src/common/utils/url.test.js, src/common/utils/url.ts, src/main/windows/callsWidgetWindow.test.js
When we were checking if two URLs were equal, we were assuming that like the URL's origin, the pathname was also not case-sensitive. This is not the case so it was possible that two URLs with different URLs could be considered equal.
This PR removed the call to `toLowerCase()` to make sure we respect case sensitivity for path names.
https://mattermost.atlassian.net/browse/MM-54465
```release-note
Fixed an issue where two different URLs could be considered the same.
```
=> [MM-54465] Remove lowercase call when checking path names

src/common/log.ts
While fixing [this issue](https://github.com/mattermost/desktop/pull/2811) I neglected to take into account that the `Logger` class would be reinstantiated multiple times, thus keeping the app stuck on `info` level logging.
This PR moves the call to default to `info` right under the call to start logging so that it's only ever called once.
```release-note
Fix issue where logging will be stuck on `info` level
```
=> Fix issue where logging will be stuck on `info` level

src/common/communication.ts, src/main/app/initialize.ts, src/main/app/intercom.ts, src/main/preload/mattermost.js
When a user types a password, there is a risk that another process on the user's computer could read the keyboard input and retrieve sensitive information from the user. On macOS, there is an API designed to prevent this.
This PR adds a call to that API that fires whenever the user has a password box focused.
https://mattermost.atlassian.net/browse/MM-54463
```release-note
NONE
```
=> [MM-54463] Enforce secure keyboard entry on macOS when a password box is focused

package-lock.json, package.json
Upgrade to Electron v26.2.1 for the latest security and bug fixes.
https://mattermost.atlassian.net/browse/MM-54509
Closes #2833
```release-note
Upgrade to Electron v26.2.1
```
=> [MM-54509] Upgrade to Electron v26.2.1

.github/workflows/release.yaml
The release script wasn't pulling all commits when finishing the notification, missing commits.
```release-note
NONE
```
=> Force end notification to pull all commits

src/main/permissionsManager.test.js, src/main/permissionsManager.ts
Fixed an issue I found in the permissions manager where if you received multiple permissions checks before the dialog finished, you would see all the additional dialogs even if you explicitly allowed.
```release-note
NONE
```
=> Fix multiple permission dialogs displaying for the same permission check

src/common/servers/serverManager.ts
Our URL lookup check was using regular expressions to check if URLs were part of a certain server, instead of just using `startsWith`, which is much simpler. This PR switches us to just using `startsWith`.
https://mattermost.atlassian.net/browse/MM-54517
```release-note
NONE
```
=> [MM-54617] Remove regex matching for URL lookups

electron-builder.json
As per https://github.com/electron/electron/issues/2727 and a slew of other issues, `gconf` has long been deprecated, and is no longer needed by Electron. This PR removes the dependency from the Debian package. 
Closes #2853 
```release-note
Removed gconf dependency for Debian/Ubuntu
```
=> Remove gconf dependencies for debian as no longer needed by Electron.

src/main/app/intercom.ts
It would appear that the `app.setSecureKeyboardEntryEnabled` function is undefined for Windows and Linux, instead of escaped for those OSes since it doesn't affect them.
This PR ensures that we only call this function for macOS.
Closes #2857
```release-note
NONE
```
=> [GH-2857] Allow only macOS to call setSecureKeyboardEntryEnabled

src/main/preload/desktopAPI.js, src/renderer/components/DownloadsDropdown/DownloadsDropdownItem.tsx, src/renderer/components/DownloadsDropdown/DownloadsDropdownItemFile.tsx, src/renderer/components/DownloadsDropdown/Update/UpdateAvailable.tsx, src/renderer/components/DownloadsDropdown/Update/UpdateDownloaded.tsx, src/renderer/components/DownloadsDropdown/Update/UpdateWrapper.tsx, src/renderer/downloadsDropdown.tsx, src/types/window.ts
For some reason `app` wasn't initialized in the preload script at the right time, causing issues that were breaking the downloads dropdown. This PR pushes us back to using the old endpoint of `getAppVersion` that provides both the version and app name when the dropdown initializes.
https://mattermost.atlassian.net/browse/MM-54591
```release-note
Fixed an issue where the downloads dropdown would not open on auto update notification.
```
=> [MM-54591] Use getVersion endpoint to report app name

src/main/allowProtocolDialog.test.js, src/main/allowProtocolDialog.ts
When calling `shell.openExternal` on macOS, it returns a `Promise`. If the protocol used in the URL provided is not registered, the Promise will reject.
We were not properly handling this rejection, and due to the changes in v5.4 that included unhandled promise rejections, the app was simply crashing even though it should just fail silently.
This PR adds the handler to catch the error, log in, and then fail silently like we would expect.
https://mattermost.atlassian.net/browse/MM-54584
```release-note
Fixed an issue where clicking on a link to an unregistered protocol on macOS would cause the app to crash.
```
=> [MM-54584] Fixed an issue where clicking on a link to an unregistered protocol on macOS would cause the app to crash

.github/ISSUE_TEMPLATE/bug_report.yml
We've received a very large volume of issues to the Desktop App repository that are actually Web App issues. It would appear that users are missing/misinterpreting the prompt to try and reproduce in the Web App first.
This PR adds a much large prompt in the issue template to hopefully ensure reporter will know where the issues should go.
```release-note
NONE
```
=> Include more obvious prompt to reproduce issues in the Web App first

src/common/config/migrationPreferences.test.js, src/common/config/migrationPreferences.ts, src/common/servers/serverManager.test.js, src/common/servers/serverManager.ts, src/types/config.ts
To improve overall memory usage, we are electing to stop opening the Boards and Playbooks tabs automatically when a new server is added. These tabs are often left running unnecessarily and take up memory.
Additionally, I've added a migration to close the tabs for everyone who currently has them open. This would be a good memory improvement for those who aren't using the tabs, but will be a bit jarring for those who do. They can re-open them afterwards and shouldn't see any further effects. cc @abhijit-singh on what you think of this approach/if you have any better ideas.
https://mattermost.atlassian.net/browse/MM-54979
```release-note
Stop auto opening Boards/Playbooks tabs
```
=> [MM-54979] Stop auto opening Boards/Playbooks tabs, close existing open tabs once for users that might have them open

package-lock.json, package.json
This PR upgrades our app to Electron v27.0.2, which includes a fix in Chromium that was causing a memory leak in cases of lazy loading images.
https://mattermost.atlassian.net/browse/MM-55132
```release-note
Upgrade to Electron v27.0.2
```
=> [MM-55132] Upgrade to Electron v27.0.2

src/assets/linux/create_desktop_file.sh
Apparently as shown [here](https://github.com/mattermost/desktop/issues/2895#issuecomment-1779381109) our desktop file creation script was missing the argument passing bit, which was throwing off some users, especially with the new authentication changes.
This PR fixes the script so that it does include the `%U` placeholder.
```release-note
NONE
```
=> Add argument passing to the desktop file script

i18n/i18n.ts
Adding Hebrew as beta language
https://github.com/mattermost/desktop/pull/2889 needs to be merged first
```release-note
Adding Hebrew as a beta language
```
=> adding Hebrew as a new beta language

src/main/permissionsManager.test.js, src/main/permissionsManager.ts
With the new permission changes, we were stopping servers with subpaths from being able to grant the `media` permission, due to being too strict about which URLs we were considering trusted.
The `media` permission generally populates the `securityOrigin` field when doing a permission check, so when checking for that permission if the URL can be trusted, we just need to match the two origins.
This PR makes that exception in the permissions handler.
https://mattermost.atlassian.net/browse/MM-55054
Closes https://github.com/mattermost/desktop/issues/2881
```release-note
Fixed an issue where servers on a subpath could not grant the `media` permission
```
=> [MM-55054] Consider a matching origin for a media request as a trusted URL when checking permissions

src/main/permissionsManager.ts
When adding per-server permissions, I neglected to test for YouTube and other embedded videos that will want to fullscreen the app. Those requests always come from the video's source and would get auto-denied otherwise.
This PR adds an exception for the `fullscreen` permission to allow the user to decide whether to allow/deny the full screen permission, which allows these embedded videos to work again.
https://mattermost.atlassian.net/browse/MM-55261
```release-note
Fix an issue where user's could not fullscreen embedded videos.
```
=> [MM-55261] Allow embedded video links to go fullscreen after a permission check

src/main/views/viewManager.ts
When deep linking, we were re-writing the path incorrect by not removing the trailing slash for servers with subpaths. This was causing issues with the Desktop App's auth flow.
This PR fixes the deep linking flow to make sure to clean the subpath properly.
https://mattermost.atlassian.net/browse/MM-55317
Closes #2906
```release-note
Fixed a deep linking issue for servers with subpaths
```
=> [MM-55317] Force deep linking to use formatted path names when rewriting the URL

src/common/appState.ts
The session expired badge would not show up due to updating the wrong map in `appState`.
```release-note
Fixed an issue where the session expired badge wouldn't show.
```
=> Fix session expired issue

src/main/views/MattermostBrowserView.ts
When creating a view, we were calling `AppState.updateExpired` on `load` to reset the expired flag. But this only needs to be called on `reload` in case that flag is no longer valid. The original implementation was causing a crash when the first server was added, moving the call to `reload` ensures that won't happen.
```release-note
NONE
```
=> Fixed a crash when the view loads for the first time

i18n/en.json, src/main/menus/app.test.js, src/main/menus/app.ts, src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts
PR adds a dynamic menu item to open developers tools for the Call widget window (see screenshot).
UPDATE: after the below conversation we are adding a dedicated `Developer Tools` submenu to keep things tidy.
https://mattermost.atlassian.net/browse/MM-55720
```release-note
Added a new View > Developer Tools submenu that contains items to access the developer tools for all desktop created windows.
Added a new menu item to open the developers tools for the Call widget window
```
=> [MM-55720] Add menu item to open developer tools for Call Widget window

package-lock.json, package.json
Version 24.12.0 of electron-builder contains [this fix](https://github.com/electron-userland/electron-builder/pull/7978), which changes the version string's pre-release separator from `-` to `~` for Debian as well.
I tried building the packages locally and verified that they use the correct separator, with the new electron-builder version:
```
$ rpm -q -p --queryformat '%{VERSION}' release/5.7.0-develop.1/mattermost-desktop-5.7.0-develop.1-linux-x86_64.rpm 
5.7.0~develop.1
$ dpkg-deb -W --showformat '${version}' mattermost-desktop_5.7.0-develop.1-1_amd64.deb 
5.7.0~develop.1
```
We can also cherry-pick this to the `release-5.6` branch if we want, but it'd be best to do so in lockstep with a patch version increase.
Fixes https://github.com/mattermost/desktop/issues/2458
Internal ticket: …
=> CLD-4665 Bump electron-builder version

src/app/serverViewState.test.js, src/app/serverViewState.ts
As part of server validation, we are checking against the Site URL on the configured server. However, when the URL wasn't configured we weren't doing any further validation, but we were assuming that there was a Site URL there, which would blank out the URL for users.
This PR assumes that if the user's URL is okay and there's no Site URL configured, to use the user's provided URL.
Closes https://github.com/mattermost/desktop/issues/2891
https://mattermost.atlassian.net/browse/MM-55134
```release-note
Fixed an issue where the user's URL would be cleared after being entered in the Add Server modal
```
=> [MM-55134] Don't blank the Site URL when it's not properly configured on an otherwise working server

src/common/servers/serverManager.test.js, src/common/servers/serverManager.ts
If you tried to add a server on a subpath, where the domains were the same and the second server's subpath was a substring of the first server's subpath, the app would erroneously claim it was the same server. This is because we weren't comparing the server subpaths as though they were the last in the chain.
This PR adds the `getFormattedPathName` call around the original subpath as well as the first to ensure we're comparing them correctly.
https://mattermost.atlassian.net/browse/MM-54872
Closes https://github.com/mattermost/mattermost/issues/24891
```release-note
Fixed an issue where you couldn't add a second server with a similar subpath as a configured server
```
=> [MM-54872] Ensure matched subpaths are exact and not substrings of each other

src/main/diagnostics/steps/internal/utils.ts
A server URL that does point to a Mattermost server, or if the diagnostics do not receive a valid JSON response, running the diagnostics will cause the app to crash.
This PR adds the proper error handling to stop that from happening.
https://mattermost.atlassian.net/browse/MM-56882
```release-note
Fix a potential crash in diagnostics
```
=> [MM-56882] Fix a potential crash in diagnostics

src/main/views/webContentEvents.test.js, src/main/views/webContentEvents.ts
This PR adds the `console-message` hook to each `WebContents` object, logging all of the messages that would hit the Chrome Dev Tools console in the log file and in the Electron process job.
This should make debugging easier in cases where the front-end code or the Mattermost Web App is misbehaving or causing issues otherwise.
https://mattermost.atlassian.net/browse/MM-48518
```release-note
NONE
```
=> [MM-48518] Include renderer process logs in main process log and log file

webpack.config.base.js
When we migrated to GitHub Actions, the hash got stuck in release builds, because we were still checking for the old CircleCI env variables. This PR switches over to the GitHub Actions one.
```release-note
NONE
```
=> Remove build hash from release builds

.github/workflows/build-for-pr.yml, .github/workflows/nightly-main.yml, .github/workflows/nightly-rainforest.yml, .github/workflows/release.yaml, electron-builder.json, entitlements.mac.inherit.plist, entitlements.mac.plist, entitlements.mas.plist, package-lock.json, package.json, src/main/notifications/index.test.ts, src/main/notifications/index.ts
The DND status was being blocked for MAS users and users on Ventura (macOS 13) or higher. This was caused by Apple's change in the way they communicate their notification status to apps. There is now an API called Communication Notifications that controls this, and it needed to be enabled in Apple Developer to work.
This change does the following things:
- Upgrades us to `macos-notification-state` 3.0, which supports the new API
- Adds entitlements for both DMG and MAS builds to be able to request focus status.
- Adds a provisioning profile for the DMG build to allow it to access the focus status.
https://mattermost.atlassian.net/browse/MM-45780
```release-note
Fixed an issue for macOS 13+ users on the MAS build where the OS-level DND status was not respected
```
=> [MM-45780] Update to macos-notification-state 3.0, update entitlements and provisioning profile to allow Communication Notification access

package-lock.json, package.json, src/main/diagnostics/index.ts, src/main/diagnostics/steps/internal/loggerHooks.ts, src/main/diagnostics/steps/internal/utils.ts, src/main/diagnostics/steps/step.template.ts, src/main/diagnostics/steps/step0.logLevel.ts, src/main/diagnostics/steps/step1.internetConnection.ts, src/main/diagnostics/steps/step10.crashReports.ts, src/main/diagnostics/steps/step11.auth.ts, src/main/diagnostics/steps/step2.configValidation.ts, src/main/diagnostics/steps/step3.serverConnectivity.ts, src/main/diagnostics/steps/step4.sessionDataValidation.ts, src/main/diagnostics/steps/step5.browserWindows.ts, src/main/diagnostics/steps/step6.permissions.ts, src/main/diagnostics/steps/step7.performance.ts, src/main/diagnostics/steps/step8.logHeuristics.ts, src/main/diagnostics/steps/step9.config.ts, src/types/diagnostics.ts
Upgrade `electron-log` to v5.1.1. This also includes a bunch of type changes (mostly just a rename of `ElectronLog` to `MainLogger`)
```release-note
NONE
```
=> Upgrade electron-log to v5.1.1

electron-builder.json
With the recent changes to use the communication entitlement, Apple wants us to state our intent for sending notifications, so I've added that here to the MAS build.
```release-note
NONE
```
=> Add NSUserActivityTypes to Info.plist

src/main/server/serverAPI.test.js, src/main/server/serverAPI.ts, src/main/server/serverInfo.test.js, src/main/server/serverInfo.ts, src/main/views/MattermostBrowserView.ts
For servers that might be offline, we had some retry logic that would constantly reload the whole Chrome page to try and reconnect to the server when it came back.
This was a bit heavy handed, and with recent changes it's now gumming up the logs. So I've changed the retry logic to just ping the server using the backend Fetch API and when it returns a success we can then try and reload the server correctly.
```release-note
NONE
```
=> Stop constant reloading of BrowserViews for servers that are not available

scripts/release.sh
Thought I fixed this last time around - `release.sh` expects that on the final release day we need to patch the version number again, but since we do that for the MAS approval first, we don't need to force it anymore.
This PR addresses that.
```release-note
NONE
```
=> release.sh patch

src/main/views/MattermostBrowserView.test.js, src/main/views/MattermostBrowserView.ts, src/main/views/modalView.test.js, src/main/views/modalView.ts, src/main/views/viewManager.ts
Electron now provides a proper public method `.close()` on `WebContents` to destroy the `WebContents` object. So we can use that now.
```release-note
NONE
```
=> Use `.close()` instead of the private `.destroy()` to stop leaking WebContents

src/main/notifications/index.ts
With the check for DND being bound to Apple's focus center API and `macos-notification-state` choosing to only use that API, in Dev Mode Apple will force-close any app that doesn't have its entitlements set correctly, which Electron doesn't.
So for dev mode, we just disable the check.
```release-note
NONE
```
=> Stop Apple from killing the Electron dev process when a notification is received

.eslintignore, api-types/index.ts, api-types/lib/index.d.ts, api-types/lib/index.js, api-types/package.json, api-types/tsconfig.json, src/main/app/initialize.ts, src/main/app/intercom.ts, src/main/notifications/index.ts, src/main/preload/externalAPI.ts
This PR enables the Desktop App to return data around whether a notification was successful or not. It relays that data back to the web clients that support it, and the web client will push that data through the websocket as needed.
https://mattermost.atlassian.net/browse/MM-57348
```release-note
NONE
```
=> [MM-57348] Support notification metrics from the Desktop App client

.eslintrc.json, api-types/index.ts, api-types/lib/index.d.ts, api-types/package.json, e2e/specs/menu_bar/view_menu.test.js, e2e/utils/analyze-flaky-test.js, package-lock.json, package.json, src/app/serverViewState.test.js, src/app/serverViewState.ts, src/common/appState.ts, src/main/app/initialize.ts, src/main/app/utils.ts, src/main/preload/externalAPI.ts, src/main/views/viewManager.test.js, src/main/views/viewManager.ts, src/main/views/webContentEvents.test.js, src/main/views/webContentEvents.ts, src/renderer/components/MainPage.tsx, src/renderer/index.tsx, webpack.config.base.js
A slew of fixes for the Desktop App:
- Fixed an issue where removing a server would not clear mentions: https://mattermost.atlassian.net/browse/MM-57690
- Added the login/logout signal back for the external API - to allow for servers to tell the app when login/logout occurs, better automating cookie storage and mention counts (NOTE: A small breakage may occur in older servers where cookies may not be flushed easily, but we want to push for this new method anyways)
- Fixed an issue where Save Image right-clicking would crash the app (bad package)
- Reduced the amount of noise the renderer process would dump into the logs, we didn't want to show every `console.log` outside of debugging
- Fixed an issue where typing in your local server followed by a port would trip up the URL validation. …
=> Various QoL fixes for Desktop App

api-types/index.ts, api-types/lib/index.d.ts, api-types/package-lock.json, api-types/package.json, package-lock.json, src/main/notifications/index.ts, src/main/windows/mainWindow.ts
For consistency, and overall better naming, I'm changing the field name for the notification status to `status` instead of result. This keeps it in line with the server descriptors/constants.
```release-note
NONE
```
=> [MM-57348] Change `result` to `status` as a better descriptor of the notification status

src/main/app/app.ts, src/main/app/utils.test.js, src/main/app/utils.ts, src/main/windows/settingsWindow.ts
On macOS, if you drag the settings window to another monitor, it will disappear and you cannot get it back without restarting the application. This is due to a bug in Electron with parent windows: https://github.com/electron/electron/issues/38760
As a workaround, I am setting the settings window to no longer be the parent of the main window, which means that the window is not forced always on top, or to the same screen as the main window. To remedy this, I've added some code to force all new browser windows to render on top of the main window initially.
```release-note
Fix the settings window disappearing on macOS when dragged to another monitor
```
=> Fix settings window disappearing on macOS when dragged to another monitor

scripts/afterpack.js
`--inspect` can be used for permissions escalation, so we're disabling it on the built application.
https://mattermost.atlassian.net/browse/MM-57912
```release-note
Disabled `--inspect` tag
```
=> [MM-57912] Disable `--inspect` on built application

src/main/notifications/index.ts
I erroneously set the `shouldNotify` check to `error` which it isn't, this should only happen when the Playbooks tab (or some other tab) receives the notification and it shouldn't be sent. The main tab will send it, so this is just something else to track as not sent.
```release-note
NONE
```
=> Fix shouldNotify notification reason

.github/workflows/nightly-main.yml, .github/workflows/nightly-rainforest.yml, .github/workflows/release.yaml
upload-artifact v4 contains a breaking change that prevents workflows that upload homonymous artifacts from working: https://github.com/actions/upload-artifact/issues/478
For now we can revert it on problem workflows, but later we should version bump while fixing the jobs.
https://mattermost.atlassian.net/browse/CLD-7560
```release-note
NONE
```
=> Revert upload-artifact where homonymous jobs are used

.github/workflows/nightly-main.yml, .github/workflows/nightly-rainforest.yml, .github/workflows/release.yaml
Twin PR to https://github.com/mattermost/desktop/pull/3011 , but for download-artifacts instead of upload-artifacts.
https://mattermost.atlassian.net/browse/CLD-7560
```release-note
NONE
```
=> Revert download-artifact for problematic jobs

electron-builder.json, scripts/beforepack.js
An issue I introduced when cleaning up the `package.json` is that `fpm` (the packager for .deb packages) was complaining if the directory it needs to store the .deb file doesn't exist. This wasn't happening before because we had to run the .tar.gz packager first, which we don't need to do anymore. However, now what we have to do is manually create that sub-directory in the release folder so that this doesn't complain.
https://mattermost.atlassian.net/browse/MM-58065
```release-note
NONE
```
=> [MM-58065] Force the packager to create the version directory before packing

scripts/cp_artifacts.sh
Changes in the build process seem to constantly be breaking this script, which I believe was there to make sure we didn't include extra files. However, we now drop all of our artifacts into the same folder (tagged with the release version) so it's easier to just copy the folder.
https://mattermost.atlassian.net/browse/MM-58286
Closes #3036
```release-note
NONE
```
=> [MM-58286] Fix cp_artifacts to avoid weird naming changes

electron-builder.json, patches/app-builder-lib+24.13.3.patch
I found two issues with the MSI installer that I've been able to remedy:
- At times, the MSI install when trying to remove the NSIS installation would just delete `Mattermost.exe` and appear to install successfully, but not actually. This was caused by the NSIS uninstallation running asynchronously with the MSI installer, so I've moved that to run synchronously instead.
- If the application is running the MSI installer is supposed to prompt you to close it, which it does, but it's doing so using the `WM_CLOSE` message which only (sometimes) closes the window and will not close the whole app. This can cause the installer to fail since the existing executable is still running, so I've added a custom prompt that tells the user to close the app manually (like the EXE installer used to do) …
=> Fixes for the MSI installer

src/common/Validator.ts, src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
When we create the main window of the app using saved bounds from the disk, if the screen that we are putting the window is scaled to a higher value than 100%, the window will try to render outside the boundaries of the screen in a multi-monitor environment.
This is due to a bug in Electron (https://github.com/electron/electron/issues/10862) where the `setBounds()` function of the `BrowserWindow` seems to ignore scale factor altogether. This PR contains a workaround that will manually resize the saved bounds using the scale factor of the target monitor to put the window back correctly, avoiding any multi-monitor overlap.
https://mattermost.atlassian.net/browse/MM-58357
Closes https://github.com/mattermost/desktop/issues/3039
```release-note
Fixed an issue where scaled monitors in a …
```
=> [MM-58357] Account for monitor scale factor when creating the window from saved bounds

.config/notice-file/config.yaml
This PR adapts the notice-file-generator config to the new schema. It should be merged only after [the corresponding changes are themselves merged](https://github.com/mattermost/notice-file-generator/pull/17).
https://mattermost.atlassian.net/browse/CLD-7792
```release-note
NONE
```
=> Support new notice-file-generator version

src/main/notifications/index.test.ts, src/main/notifications/index.ts
When the webapp is focused, we make a call to mark the current channel as read. When a notification is clicked, we make a call to both focus the window and navigate to the new route if needed. This introduces a race condition in which the channel the user was on before switching to the one where the notification was triggered from would be marked read instead, causing the perception that an unread was missed.
This doesn't really happen much on the web side, as the calls are all run as part of a single thread and the `push()` action will likely update the `currentChannel` value before the focus handle can get in the way, but on Desktop App the focus action is called much earlier and done as a result of Electron telling the renderer process to focus. Then afterwards an IPC messages takes …
=> [MM-46634] Force window to be focused after navigation on notification click

src/main/app/initialize.test.js, src/main/app/initialize.ts, src/main/notifications/index.test.ts, src/main/notifications/index.ts
A recent change that allowed the macOS app to correctly use the `FocusStatus` to prevent notifications under DND was completely stopping notifications if permission wasn't given. This was caused by the app not performing any error handling from the DND check, which would throw an error if the app wasn't authorized to check the status.
This PR adds that error handling, and logs a warning in the logs to denote that the check failed.
Closes https://github.com/mattermost/desktop/issues/3052
https://mattermost.atlassian.net/browse/MM-58455
```release-note
Fixed an issue where notifications would not show on macOS in certain cases.
```
=> [MM-58455] Add error handling when FocusStatus is not authorized on macOS

src/main/notifications/index.test.ts, src/main/notifications/index.ts
Cherry pick of #3051 on release-5.8.
```release-note
NONE
```
=> Automated cherry pick of #3051

src/main/notifications/dnd-windows.test.js, src/main/notifications/dnd-windows.ts, src/main/notifications/index.ts
Found a few issues with reporting notifications on Windows and a small bug that I wanted to fix:
- Sometimes Windows will fire both the `show` and `failed` events when a notification fails to show due to permissions not being enabled for Mattermost in Windows. This was then always being reported as a `success` when it should be `not_sent`, so I had to add a timeout to have the `show` callback wait for the `failed` one to potentially run (not an elegant solution)
- Windows would return `failed` when the notification fails the permission check. This should now be reported as `not_sent` as it is a user choice not to send the notification
- Our DND check for priority was returning the opposite of what it should, so I've swapped the flag.
https://mattermost.atlassian.net/browse/MM-58693 …
=> [MM-58693] Fix some issues with Windows notifications

src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
When I fixed the window scaling issue on Windows causing the `setSize` call to size the window strangely, on Mac some displays were misreporting the `scaleFactor` based on other factors (ie. the Retina Display technically having a higher pixel density, setting the `scaleFactor` to 2). This would cause some mini windows to popup that were 1/4 the size they should be.
To fix this, I just limited the window scaling fix to Windows since it seems to report just based on the user's scale factor.
https://mattermost.atlassian.net/browse/MM-58357
```release-note
NONE
```
=> [MM-58357] Disable window scaling for OSes that aren't Windows

src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
Cherry pick of #3063 on release-5.8.
```release-note
NONE
```
=> Automated cherry pick of #3063

src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
Further to the fix I did for the Electron bug here: https://github.com/electron/electron/issues/10862
The primary monitor on Windows doesn't need to care about the scale factor, and will respect it when resetting its window bounds. This PR checks to see if the primary monitor is the matching screen and won't use the `scaleFactor` if the windows bounds aren't set.
https://mattermost.atlassian.net/browse/MM-58780
Closes https://github.com/mattermost/desktop/issues/3067
```release-note
Fixed an issue where the window size will get smaller on Windows after a restart if the primary monitor is used and is scaled
```
=> [MM-58780] Don't account for scaleFactor on Windows when resizing if the matching screen is the primary monitor

src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts
PR adds the expected context menu upon right-clicking inside the Calls pop-out window.
https://mattermost.atlassian.net/browse/MM-58291
```release-note
Fixed missing context menu upon right-click in calls popout window
```
=> [MM-58291] Show context menu in Calls popout

src/main/app/intercom.ts, src/main/notifications/index.ts
We were still the title of notifications in DEBUG logging mode, and `handleMentionNotification` was still logging the body, which could be a privacy concern. This PR removes those fields from the log since they aren't generally necessary for debugging anything with the Desktop App.
https://mattermost.atlassian.net/browse/MM-59490
```release-note
NONE
```
=> [MM-59480] Remove logging of the title/body of notifications

src/main/utils.test.js, src/main/utils.ts, src/main/windows/mainWindow.ts
There was a case as described in the ticket below where a user could get the window to display off the screen. This was due to a flaw in `isInsideRectangle` where we weren't checking the bounds correctly (we were only checking that it was inside from the top-left corner, which is fine in single-monitor setups, but not multi-monitor). Additionally, I had expected `getMatchingScreen` to return `false` if it doesn't find one, but it always just gets the primary screen in the worse case.
This PR fixes and adds tests for `isInsideRectangle`, as well removes the null check for `getMatchingScreen`
https://mattermost.atlassian.net/browse/MM-59492
Closes https://github.com/mattermost/desktop/issues/3087
```release-note
Fixed an issue where the window might be rendered off-screen in multi-monitor …
```
=> [MM-59492] Fixed `isInsideRectangle`, and removed null check for matchingScreen since it will always return something

scripts/afterpack.js
This PR flips a few more fuses in our app to disable certain functionality that can cause vulnerabilities. The fuses and their descriptions are detailed in this document: https://www.electronjs.org/docs/latest/tutorial/fuses.
One note is that the ASAR integrity fuse cannot be flipped on for anything but macOS currently. It's supported on Windows as of Electron v30, but `electron-builder` does not support it yet, so we can only turn it on for macOS right now.
I have yet to flip the `GrantFileProtocolExtraPrivileges` fuse, since it required a LOT more changes that I think are too risky to release right away, that change is [here](https://github.com/mattermost/desktop/pull/3095)
These cannot be tested outside of the built application as a note. …
=> [MM-59046] Flip fuses for cookie encryption, node options and ASAR integrity

src/main/windows/mainWindow.ts
On Windows, removing the window from snapped to unsnapped using the Windows+Arrow Keys, or when moving between screens using Shift+Windows+Arrow Keys, the BrowserViews inside would not resize correctly.
This PR brings back the `onResize` handler for Windows (which I believe was removed to try and improve performance) but includes an exception that if `onWillResize` is being called simultaneously it won't resize the window twice.
https://mattermost.atlassian.net/browse/MM-59412
```release-note
Fixed an issue where snapping the window on Windows would sometimes cause the inner BrowserView not to resize
```
=> [MM-59412] Reinstate the resize listener for Windows and the exception for willResize

.github/workflows/release.yaml
I missed adding the Windows ZIPs to the `release` pipeline. This PR adds those.
```release-note
NONE
```
=> Build all windows targets on release

src/main/windows/mainWindow.ts
With the upgrade to Electron v30, they seem to have quietly taken away the default window frame for Linux clients, or something else has broken in the configuration. However, they have given us a way to add native window buttons to Linux apps now, so this PR adds that overlay in the same way used by macOS.
This will require some follow-up for the next release to re-work how we do these window buttons for macOS and Windows, but this will fix the immediate issue for Linux users.
Closes https://github.com/mattermost/desktop/issues/3102
https://mattermost.atlassian.net/browse/MM-59840
```release-note
Changed the window buttons on the Linux client to use the native ones provided by Electron, removed the frame
```
=> [MM-59840] Add Linux title bar buttons using `titleBarOverlay` field of `BrowserWindow`

api-types/index.ts, api-types/lib/index.d.ts, api-types/package-lock.json, api-types/package.json, src/common/communication.ts, src/main/preload/externalAPI.ts, src/main/windows/callsWidgetWindow.ts, src/types/externalAPI.ts
As we are implementing persistent Calls preferences and settings, we'd like a way to open the modal from within a call. PR implements a new `openCallsUserSettings` method to allow triggering this functionality from the global widget window.
https://github.com/user-attachments/assets/c3521aac-69de-4daf-8b06-d8d7d7bbdff1
https://mattermost.atlassian.net/browse/MM-51514
```release-note
NONE
```
=> [MM-51514] Allow Calls widget to open user settings

src/main/windows/mainWindow.ts
Adding the `titleBarOverlay` for just Linux crashes Windows when the app tries to load (apparently calling the `set` function will crash if it's not enabled :(). This PR makes sure we're on Linux and that it's enabled before we try to set it.
```release-note
NONE
```
=> [MM-59480] Fix crash on Windows caused by titlebar overlay

src/common/communication.ts, src/main/preload/externalAPI.ts, src/main/views/viewManager.ts
One of the changes to the Desktop API was that individual tabs report their login change directly to the Desktop App instead of relying on local storage to do so. At some point it appears that `localStorage` was not syncing to inactive tabs, which makes sense given that that doesn't happen on Chrome either unless the tab is focused. This caused no issue on web app, but the navigation code on Desktop App was effected in that if you logged out of another tab, logged back in on the main tab and tried to navigate to the other tab using a link of some kind, the other tab would try to load and not be logged in correctly before it tried to navigate, causing a session expiry.
This PR fixes the log in tracking code for the new API, forcing each individual tab to reload if necessary (like the old …
=> [MM-59489] Change logged in tracking code for new API, check for `/` when navigating tabs

src/main/preload/internalAPI.js, src/renderer/components/WelcomeScreen/WelcomeScreen.tsx, src/renderer/css/components/LoadingScreen.css, src/types/window.ts
When you resize the window on the welcome screen, if you make the height too small the Get Started button disappears. This PR just forces the flex items to align to the bottom so that it will always show at the bottom no matter how small. A follow-up here might be to find a way to scale the contents properly when resizing.
Additionally, I fixed a longstanding issue for macOS where the welcome screen couldn't be resized at all.
https://mattermost.atlassian.net/browse/MM-59252
```release-note
Fix resizing app when welcome screen is open on macOS, force button to always appear on welcome screen
```
=> [MM-59252] Fix resizing app when welcome screen is open on macOS, force button to always appear on welcome screen

src/renderer/components/SettingsPage.tsx
Fixed the dark-mode style for the download location box in settings.
Fixes https://github.com/mattermost/desktop/issues/2977
- [ x read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
This PR was tested on: `Fedora 40`
```release-note
Fixed dark-mode style for download location in settings
```
=> Fixed #2977 - Fixed the dark-mode style for the download location box in settings

src/main/downloadsManager.ts
When we made the fix to disallow the `file:` protocol, we started using `createThumbnailFromPath` to process images. Unfortunately, this function is simply not defined on Linux, causing a crash.
This PR falls back to using the `createFromPath` function for Linux only, which creates a full version of the image. I've capped the image size to use at 1MB so that we don't inflate the memory usage of the downloads dropdown too much.
https://mattermost.atlassian.net/browse/MM-60232
Closes #3129
```release-note
Fix a crash in Linux when trying to create a thumbnail from an image
```
=> [MM-60232] Fix a crash in Linux when trying to create a thumbnail from an image

src/app/serverViewState.ts
Wasn't able to reproduce the exact crash, other than this possible case where it's possible that the current server ID isn't set before the menu regenerates, causing a crash where the app menu might be re-rendered before the last server is removed. This PR just reverses those statements so that it's less likely that the `currentServerId` isn't set.
Closes https://github.com/mattermost/desktop/issues/3122
https://mattermost.atlassian.net/browse/MM-60201
```release-note
Fix a potential crash where the app menu might regenerate when `currentServerId` isn't set.
```
=> [MM-60201] Fixed a potential crash on removing server

src/main/menus/app.ts, src/main/windows/mainWindow.ts, src/renderer/components/SettingsPage.tsx
We have made the decision to disable full screen mode on Linux, for a number of reasons:
- Most notably, the buttons for minimize/maximize/restore/close are not able to be hidden on Linux, as per this Electron issue: https://github.com/electron/electron/issues/43030. Under full screen mode on Windows, these are hidden automatically, but under Linux they remain. This behaviour would continue under native Linux titlebars.
- Use of the above buttons consistently puts the window in a really weird state where the window is not in full screen mode, but it thinks it is and is stuck and not able to be moved or resized.
- Every window manager handles the sizing and abilities of this window while it's in full screen mode, causing some inconsistencies that are impossible to account for.
- When …
=> Disable full screen mode on Linux

src/main/views/pluginsPopUps.test.js, src/main/views/pluginsPopUps.ts, src/main/views/webContentEvents.ts, src/main/views/webContentEventsCommon.ts
Unfortunately, I am reminded once more that not all operating systems are created equal.
PR adds the additional check for custom URL protocols for new windows created by plugin popouts. These will be handled via `allowProtocolDialog`.
https://mattermost.atlassian.net/browse/MM-61040
```release-note
NONE
```
=> [MM-61040] Handle custom protocols in plugins popouts

src/app/serverViewState.test.js, src/common/config/defaultPreferences.ts, src/common/config/index.test.js, src/common/config/upgradePreferences.test.js, src/main/app/config.test.js, src/main/downloadsManager.test.js, src/main/tray/tray.test.js, src/main/views/MattermostBrowserView.test.js, src/main/views/downloadsDropdownMenuView.test.js, src/main/views/downloadsDropdownView.test.js, src/main/views/serverDropdownView.test.js, src/main/views/viewManager.test.js
During the definition of the default config values, we were hardcoding the download directory and not letting the app to find it by itself. With this change, we make sure to load the default download directory set via the OS.
https://mattermost.atlassian.net/browse/MM-60782
```release-note
NONE
```
=> MM-60782 - use default download directory on windows

package-lock.json, package.json, src/common/log.ts
This PR turns on async logging for the Desktop App, as the default behaviour of `electron-log` is to write synchronously and wait on the main thread. Also I have upgraded `electron-log` to the latest released version.
This should address issues for those with endpoint security/AV software running, or users on a weaker/slower disk that are experiencing slowness in the app, especially while on a higher logging level.
https://mattermost.atlassian.net/browse/MM-61058
```release-note
Upgrade `electron-log`, turn on async logging
```
=> [MM-61058] Upgrade `electron-log`, turn on async logging

src/app/serverViewState.ts, src/renderer/components/NewServerModal.tsx, src/renderer/dropdown.tsx
Pre-defined servers, such as those defined by Group Policy on Windows, were not able to access the Edit Server Modal since there was nothing to edit for those servers. However, when we introduced the [permissions UI](https://github.com/mattermost/desktop/pull/3059) we didn't account for these pre-defined servers which still might need to be able to trigger the permissions.
This PR makes changes so that in the server dropdown, for pre-defined server you can now click the pencil icon to access the permissions switches. I've also made a change to not hide badges that show up for said servers. 
https://mattermost.atlassian.net/browse/MM-60704
https://mattermost.atlassian.net/browse/MM-61144
```release-note
Fixed an issue where pre-defined couldn't edit permissions, and the dropdown would not …
```
=> [MM-61144][MM-60704] Show badges and allow Edit Server modal for permissions for pre-defined servers

e2e/package-lock.json, e2e/package.json, e2e/patches/nan+2.22.0.patch, package-lock.json, package.json, patches/electron+33.0.2.patch, src/main/menus/app.ts, src/main/views/MattermostBrowserView.test.js, src/main/views/MattermostBrowserView.ts
Upgrade to Electron v33.0.2. Some deprecations were addressed, but otherwise nothing major should be changed.
https://mattermost.atlassian.net/browse/MM-61271
```release-note
Upgrade to Electron v33.0.2
```
=> [MM-61271] Upgrade to Electron v33.0.2

e2e/package-lock.json, e2e/package.json, e2e/patches/nan+2.22.0.patch, package-lock.json, package.json, patches/electron+33.0.2.patch, src/main/menus/app.ts, src/main/views/MattermostBrowserView.test.js, src/main/views/MattermostBrowserView.ts
Cherry pick of #3181 on release-5.10.
```release-note
NONE
```
=> Automated cherry pick of #3181

package-lock.json, package.json
An issue I missed with Windows build when upgrading to Electron v33 caused the release to fail. This was caused by `windows-focus-assist`. This upgrade fixes the build issue.
```release-note
NONE
```
=> Upgrade`windows-focus-assist` to 1.4.0

src/main/utils.ts, src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
MM-60233: Fix window minimizing issue on KDE/KWin environments. The app window was immediately being focus after being minimized, and it caused it to restore instead of stay minimized. This happened because the onFocus event was being  triggered after minimizing, and then the actions within the onFocus handler was causing the window to re obtain the focus.
This PR resolves this by modifying the onFocus event handler by checking if the application was running on KDE/KWin (plasma) and if the window is also minimized. If both of the conditions are present, then the handler will return early and will not execute further actions avoiding the window to obtain focus unwanted.
https://mattermost.atlassian.net/browse/MM-60233
Closes #3130
Kubuntu:
Operating System: Kubuntu …
=> MM-60233 - fix issue in kde of focus after minimize

src/common/utils/constants.ts, src/renderer/css/downloadsDropdownMenu.scss
- Updated the styling of `.DownloadsDropdownMenu__MenuItem` to improve text fitting and prevent text overlap.
- Changed `height` to `fit-content(25%)` to ensure the menu items dynamically adjust to content size.
- Added `flex-grow: 1` to allow the items to expand and occupy available space within the menu.
- Added padding-right: 20px to ensure text does not touch the right edge of the menu.
This PR was tested on: Ubuntu 22.04
I have tested it in 3 different languages (English, Russian, French). Some of them had problems with text overlapping in the download menu tab. Other languages with long translations also have overlapping text.
<details>
<summary>English</summary>
</details>
<details>
<summary>French</summary>
</details>
<details>
<summary>Russian</summary>
</details>
<details> …
=> Fix: Adjust dropdown menu item layout for better text fitting

src/main/app/app.ts, src/main/app/utils.ts, src/main/views/viewManager.ts
While working on https://github.com/mattermost/desktop/pull/3200 I found an issue with deep linking when booting the app from cold. The application would fail to load the initial server, and the dropdown menu would also not load. This was caused by the main window creation call happening too early, before a bunch of other setup code could be run.
This PR fixes the issue by having the application wait for the main window to be created normally, before attempting to deep link.
```release-note
Fixed issues with loading the app from cold when deep linking
```
=> Fixed issues with loading the app from cold when deep linking

src/app/serverViewState.test.js, src/app/serverViewState.ts
In circumstances where the user stopped typing, or was slow typing the beginning of their server URL, the URL validation would kick in and erroneously mistake the beginning of a URL (ie. any substring of `https://`) as a hostname, and try to add `https://` for the user. This would cause some confusion and frustration for users trying to type.
This PR fixes the validation to recognize any leading substring of `https://` as an invalid URL before it tries to call it a hostname. This stops the user from having to backspace and correct themselves while typing, and should still server to help people typing without the leading `https://`. Additionally, I added a QoL fix to stop the trailing `/` from appearing while you were typing a host name, so that if you do stop, you don't have to backspace …
=> [MM-53799] Stop autocompleting while the user is typing `https://`

resources/mac/entitlements.mac.inherit.plist, resources/mac/entitlements.mac.plist, resources/mac/entitlements.mas.plist
These entitlements are not necessary for the app to function under macOS anymore, as they are from older Electron versions. This PR removes these entitlements.
https://mattermost.atlassian.net/browse/MM-61725
```release-note
NONE
```
=> [MM-61725] Remove unnecessary macOS entitlements

src/main/app/app.ts, src/main/app/initialize.ts
After fixing https://github.com/mattermost/desktop/pull/3201, I introduced a bug where the app would not restore its window when booting a second instance, due to the removal of `MainWindow.show()`, which was removed since it interfered with the normal app boot process from cold. I also noticed that from cold, Linux would ignore deep links.
This PR fixes both of the above issues.
https://mattermost.atlassian.net/browse/MM-61864
```release-note
Fix issue where the app will not restore when opened again from cold
Fix issue where deep linking from cold didn't work on Linux
```
=> [MM-61864] Fix issue where the app will not restore when opened again from cold, fix issue where deep linking from cold didn't work on Linux

src/main/downloadsManager.ts
There seems to be a Windows-only crash case where calling `createThumbnailFromPath` would throw an error failing to get the thumbnail from a local cache (see https://github.com/electron/electron/blob/main/shell/common/api/electron_api_native_image_win.cc#L69). I'm not certain but I'm guessing it has something to do with files that do not have thumbnails pre-generated by the OS, and Electron expects that they are always there. This causes a hard crash since that method throws an error.
This PR simply adds an error boundary to fallback to `createFromPath` in those situations where a thumbnail cannot be retrieved, to avoid having the app crash hard.
https://mattermost.atlassian.net/browse/MM-61919
Closes https://github.com/mattermost/desktop/issues/3140
```release-note
Fixed an issue where …
```
=> [MM-61919] Wrap potential crash in try/catch for thumbnails, fall back to `createFromPath`

package-lock.json, package.json, patches/electron+33.2.0.patch
An issue was occurring where the application wouldn't focus the browser when opening an external link. This was caused by an Electron bug, fixed here: https://github.com/electron/electron/pull/44468
This PR updates our app to use the newer fixed Electron version.
https://mattermost.atlassian.net/browse/MM-61406
Closes https://github.com/mattermost/desktop/issues/3227
```release-note
Upgrade to Electron v33.2.0
Fixed an issue where the application would not focus your browser window when opening an external link
```
=> [MM-61406] Upgrade to Electron v33.2.0

src/main/permissionsManager.test.js, src/main/permissionsManager.ts
This is a small QoL improvement for enterprise users who have their Desktop App configured for them by their system administrator. Normally the application will ask for permission to send notifications, access the camera/microphone, and other system related permissions on a per-server basis. However, if the server is configured using Group Policy on Windows, we can make an assumption that the server is trusted since it is configured at the registry level.
This PR just removes the permission check for those servers.
https://mattermost.atlassian.net/browse/MM-61821
```release-note
Skip per-server permission checks for GPO-configured servers on Windows
```
=> [MM-61821] Automatically allow permission checks for supported permission types through for GPO configured servers

electron-builder.json, patches/app-builder-lib+24.13.3.patch
An issue with the newer MSI installer (present since v5.9) was that it would not uninstall previous versions installed by the old MSI installer. This was due to a change in the `UpgradeCode`, which was manually created for the old MSI, and automatically generated by `electron-builder` for the new one. `electron-builder` did support a way to prescribe it, but I had missed adding that.
This PR both adds the original `UpgradeCode` that we used from the old MSI, as well as adds another step to the new installer that will uninstall versions v5.9 and v5.10 that used the auto-generated `UpgradeCode`. This alongside the script that uninstalls the EXE should make sure the app uninstalls all other versions of the Desktop App before proceeding to install the new one. …
=> [MM-61994] Fix UpgradeCode to use the old one, allow MSI to uninstall both

patches/app-builder-lib+24.13.3.patch
Once of the features of the new MSI installer is to basically replace the EXE one, despite the fact that they use different installation methods and thus different ids, making them able to be installed side by side. What we did was to force the uninstallation of the EXE installer if we install via MSI. However, this was throwing an error (which seemed to be ignored most of the time) when the uninstaller was missing for those using a deployment system.
This PR adds a check for the uninstaller before we try to run it, which avoids the error altogether.
https://mattermost.atlassian.net/browse/MM-60416
```release-note
Fixed a potential error thrown by the MSI when trying to uninstall the EXE
```
=> [MM-60416] Check for the presence of the EXE uninstaller before trying to run it

src/main/utils.ts, src/main/windows/mainWindow.test.js, src/main/windows/mainWindow.ts
Cherry pick of #3157 on release-5.9.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #3157

electron-builder.json, patches/app-builder-lib+24.13.3.patch
Manual cherry-pick of #3237, #3238, #3239 to `release-5.9`
Done manually to avoid `patch-package` issues.
```release-note
NONE
```
=> Cherry-pick of #3237, #3238, #3239 to `release-5.9`

patches/app-builder-lib+24.13.3.patch
An issue was noted while testing the MSI and trying to install an older version over top. An error would be thrown and the MSI would technically install, but would miss the main EXE file causing the app to not work at all.
This PR makes a couple template changes to actually support downgrading properly (as of the installer that this is released in) and fixes the error and missing EXE.
https://mattermost.atlassian.net/browse/MM-62196
```release-note
Add support for downgrading using the MSI installer
```
=> [MM-62196] Add support for downgrades using the MSI

src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts
For calls widget actions requiring focus on the main channel view (e.g., channel link click, showing screen sharing selection modal), we were not handling the possibility that the tab was something other than messaging. We fix this by switching to the expected tab.
https://mattermost.atlassian.net/browse/MM-62001
```release-note
Fixed an issue preventing the screen sharing selection modal to show when the app was focused on a different tab (e.g. Playbooks, Boards)
```
=> [MM-62001] Calls: switch tab on actions requiring focus

.github/workflows/snyk-sbom.yml
Change SBOM file from `sbom.json` to `sbom-desktop-vX.Y.Z.json`
https://mattermost.atlassian.net/browse/SEC-7235
```release-note
NONE
```
=> Bump SBOM version so the file output is sbom-desktop-vX.Y.Z.json

src/main/windows/callsWidgetWindow.test.js, src/main/windows/callsWidgetWindow.ts
PR adds some logic to dynamically change the global Calls widget visibility when the popout window is open. This is to address the inconvenience of having this window always on top even when focusing on the popout.
Hiding the widget completely is also possible, but I still feel it's a more impactful change in behavior. My hope is that the proposed changes are enough to address the reported issue. That said, let me know if you feel strongly about this.
The previous conversation for extra context is at https://hub.mattermost.com/private-core/pl/wbf4jd67g7fnpmon8fafwnxmuy
https://github.com/user-attachments/assets/c58e7dee-36a4-4b6c-a043-0acfd4b7da92
https://mattermost.atlassian.net/browse/MM-62205
```release-note
Calls: while the popout window is open, the widget window's visibility will …
```
=> [MM-62205] Dynamically toggle widget window visibility when popout opens/closes

.github/workflows/build-for-pr.yml, .github/workflows/ci.yaml, .github/workflows/nightly-main.yml, .github/workflows/nightly-rainforest.yml, .github/workflows/release-mas.yaml, .github/workflows/release.yaml
Apparently GitHub has shifted the Xcode image to 16.2, which broke our workflow again. For some reason there doesn't seem to be a static place to select the Xcode SDK, so we're stuck manually upgrading it everytime they do...
Perhaps they will have an answer for me [here](https://github.com/actions/runner-images/issues/11021#issuecomment-2573225187) but for now we'll use this to get us back up and running.
```release-note
NONE
```
=> Switch to Xcode 16.2 for CI

src/main/views/modalView.ts
When modals are removed from the window, we unset the attached window property. This caused an issue with our resizing code for modals on Linux (which is required to run a little after the window changes since the values seem to be delayed) where the window bounds were not available as the window had been detached, causing a crash.
This PR checks to see if the window is still attached before trying to call set bounds.
https://mattermost.atlassian.net/browse/MM-62395
```release-note
Fixed an issue for Linux users where the app could crash when trying to add the first server.
```
=> [MM-62395] Don't attempt to set boundaries for a window that is no longer attached

scripts/patch_updater_yml.sh, scripts/release.sh
We ran into an issue with our ESR releases where if we ran the patch release process after another newer version had gone out, we would end up overwriting the latest YML file pointing to the newest updated version, meaning that people would end up upgrading backwards/users on the newest minor version wouldn't get updates.
This PR changes the release script to add a `.esr` file on the branch of ESR releases, which forces some changes in the script that patches the YML file. If we're working with the ESR branch and doing a patch release, we remove the YML file so it doesn't mess up the auto-updating.
I've also taken some time to change up the release script a bit, and add some help functionality in case anyone else needs to use it.
https://mattermost.atlassian.net/browse/MM-61890 …
=> [MM-61890] Add support for marking as ESR for release script, add help, remove update YML for ESR patch releases

package-lock.json, package.json, src/main/developerMode.test.js, src/main/developerMode.ts, src/main/menus/app.test.js, src/renderer/components/DeveloperModeIndicator.tsx, src/renderer/components/WithTooltip/index.tsx, src/renderer/components/WithTooltip/tooltip_content.tsx, src/renderer/components/WithTooltip/with_tooltip.scss, src/renderer/constants.ts, src/renderer/css/_variables.scss, src/renderer/css/components/DeveloperModeIndicator.scss, src/renderer/index.html
Removing the original `OverlayTrigger` usage from `react-bootstrap` and replacing the tooltip with `floating-ui`, as we do in the webapp. I re-used a modified version of the `WithTooltip` component from the web app, that can be replaced if that one is ever exported as a separate package.
Also realized it might make sense to have developer mode on, while in development, so I've set that.
https://mattermost.atlassian.net/browse/MM-62649
```release-note
NONE
```
=> [MM-62649] Switch DeveloperModeIndicator over to floating-ui

src/main/views/loadingScreen.ts
An issue caused either by the migration to WebContentsView, or by the branding changes brought back a bug where the loading screen flashes white between transitions, which isn't a great UX. This seems to be caused by the removal of `transparent: true` from the `webPreferences` object, which shouldn't need to be there as it's set to `true` by default according to the docs.
This PR adds that back anyways and leaves a comment explaining why it's there.
https://mattermost.atlassian.net/browse/MM-62741
```release-note
NONE
```
=> [MM-62741] Fix loading screen flash between transitions

src/renderer/components/DownloadsDropdown/Update/UpdateAvailable.tsx, src/renderer/components/DownloadsDropdown/Update/UpdateDownloaded.tsx
At one point I think we were a bit overzealous with our use of `react-bootstrap`, as this simply required replacing `Button` with `button` and seems to work the same.
https://mattermost.atlassian.net/browse/MM-62652
```release-note
NONE
```
=> [MM-62652] Replace `Button` from `react-bootstrap` with `button`

src/renderer/components/ErrorView.tsx, src/renderer/components/MainPage.tsx, src/renderer/components/TabBar.tsx, src/renderer/css/components/ServerDropdownButton.scss, src/renderer/css/components/TabBar.css, src/renderer/index.tsx
This change removes `react-bootstrap` components and `bootstrap` from the `MainPage` and `TabBar` components. There was not much to change here, just a few style fixes.
A note was left leaving `bootstrap` and `react-bootstrap` elements in the ErrorPage, to be cleaned up later.
https://mattermost.atlassian.net/browse/MM-62650
https://mattermost.atlassian.net/browse/MM-62651
```release-note
NONE
```
=> [MM-62650][MM-62651] Remove bootstrap/react-bootstrap from TabBar, MainPage

src/renderer/css/components/Input.scss
Quick fix to a colour that was using a variable that no longer exists/isn't needed anymore.
https://mattermost.atlassian.net/browse/MM-62787
Before:
After:
```release-note
NONE
```
=> [MM-62787] Fix warning state colour on welcome screen URL input

src/main/views/viewManager.ts
When we migrated to `WebContentsView`, all calls to `addChildView` which is called to put the correct view on top or add a new view, would also give focus to whatever view was added/put on top. This causes an accessibility issue in the Desktop App where tabbing through the application and highlighting an external link would trap focus into the URL view that is created and shown.
Unfortunately there is no way currently to prevent this from happening, see: https://github.com/electron/electron/issues/42339
This PR prevents the URL view from ever taking focus by always returning focus to the current Mattermost server view anytime the URL view takes focus, which allowing tabbing to continue to work freely.
https://mattermost.atlassian.net/browse/MM-62581
```release-note
Fixed an issue where …
```
=> [MM-62581] Prevent URL view from ever taking focus by always returning focus to the current server view

patches/electron-context-menu+4.0.4.patch
An issue with `electron-context-menu` where it assumes `isDestroyed` is on a window (its not) crashes the app.
This PR patches the library to check the webContents object for `isDestroyed` instead.
https://mattermost.atlassian.net/browse/MM-62846
```release-note
NONE
```
=> [MM-62846] Fix crash caused by `electron-context-menu`

scripts/release.sh
To avoid having to cherry-pick Electron upgrades, and also to avoid me forgetting to bump the nightly version, I've added a couple checks/reminders to the release script.
```release-note
NONE
```
=> Reminding myself to upgrade Electron and bump the release version for future releases

src/renderer/dropdown.tsx
A change made in https://github.com/mattermost/desktop/pull/3120 has caused a potential race condition in the server dropdown menu, where the dropdown info to populate the server dropdown would arrive before the component was able to be rendered because of a missing nonce. This would mean that the size value would still be effectively 0x0 and would not get refreshed until the component was updated by something else (either a new server or just blurring the window)
This PR forces an ordering in which the component must have the nonce and be renderable before trying to get the dropdown info, so that we can assume the size sent up from the component to accurately size the WebContentsView is correct.
https://mattermost.atlassian.net/browse/MM-62781
```release-note
Fixed an issue where the …
```
=> [MM-62781] Wait for nonce before requesting info that will update the server dropdown component

e2e/modules/environment.js
Bringing back the env variable here so that I can configure my E2E tests to run locally during development.
```release-note
NONE
```
=> Allow for env variable to set the username for E2E tests

src/main/views/MattermostWebContentsView.test.js, src/main/views/MattermostWebContentsView.ts
For the incompatible view, if your server is unavailable when the app loads, after you reload it will show the incompatible screen until you switch back from another server. This PR stops that.
```release-note
NONE
```
=> Reload server info on retry

src/app/serverViewState.ts, src/common/constants.ts, src/main/app/intercom.ts, src/main/authManager.test.js, src/main/authManager.ts, src/main/certificateManager.ts, src/main/menus/app.ts, src/main/menus/tray.ts
Convert all the modal keys to use constants instead.
https://mattermost.atlassian.net/browse/MM-63265
```release-note
NONE
```
=> [MM-63265] Use constants for modal keys

src/main/views/MattermostWebContentsView.ts
The incompatible server version check assumed that compatible servers should be able to respond to the API request that checks for server version, however this is not always working.
As a short term fix, we will default to not show the screen if the server version is not present.
Closes https://github.com/mattermost/desktop/issues/3363
```release-note
Fix an issue where the incompatible server screen shows by default when the server info is not present.
```
=> Fix an issue where the incompatible server check defaults to show the screen when the server info is not present

i18n/en.json, src/common/communication.ts, src/common/constants.ts, src/main/preload/internalAPI.js, src/main/views/viewManager.ts, src/renderer/components/DownloadsDropdown/Update/UpdateAvailable.tsx, src/renderer/css/downloadsDropdown.scss, src/types/window.ts
This PR adds a link to the changelog when the user is prompted for an auto-update.
https://mattermost.atlassian.net/browse/MM-63399
NOTE: The screenshots says Electron in dev mode, they will say Mattermost in production
```release-note
Add a changelog link for when the app auto updates
```
=> [MM-63399] Add a changelog link for when the app auto updates

src/main/permissionsManager.test.js, src/main/permissionsManager.ts
Fixes persistence of microphone and camera access on Linux by checking the platform before calling `systemPreferences.getMediaAccessStatus`, which is only implemented on Windows and macOS (https://www.electronjs.org/docs/latest/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-windows-macos)
This PR was tested on:  Ubuntu 22.04
```release-note
NONE
```
=> Fix issue with media permissions on Linux

.github/workflows/ci.yaml
this PR https://github.com/mattermost/desktop/pull/3393 had the Macos build job failing. 
I had added a temprory Fix to skip check. 
The error we were seeing:
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" cannot be located.
This is because the active developer path is set to the Command Line Tools, which don’t include full SDKs like MacOSX.sdk.
With this fix the full SDK is used
```release-note
NONE
```
=> Fix: Build Mac no dmg job failing due to MACOS_NOTIFICATION_STATE_NO_SDK_CHECK

.github/workflows/snyk-sbom.yml
- Fix SBOM filename (the name came out as `sbom-desktop-.RELEASE_TAG.json ` instead of `sbom-desktop-v5.11.2.json`)
NA
```release-note
NONE
```
=> Fix SBOM file name

scripts/generate_release_post.sh
When building v5.12.0-rc.1, we ran into an issue where the text was too long. This was caused by the notification script going too far back in history, due to the script only checking for versions of the form `vx.x.x`, which didn't account for multiple digits.
This PR accounts for multiple digits.
This should be backported to v5.11 as well in case we need to release from there.
https://mattermost.atlassian.net/browse/MM-63849
```release-note
NONE
```
=> [MM-63849] Account for minor versions >= 10

src/main/views/viewManager.ts
Our fix for focus trapping on the URL view on Desktop App wasn't sufficient, it wouldn't work on Windows/Linux due to the timing of the actual focusing. This PR switches to an undocumented `ready-to-show` event that fires before the web contents are shown, long after focus is taken. However this all happens very quickly, so now the event always fires after focus is taken but before the window shows, so focus won't be disrupted for long.
https://mattermost.atlassian.net/browse/MM-62005
```release-note
Fix focus loss when tabbing to an external URL for Windows/Linux
```
=> [MM-62005] Use `ready-to-show` event for focus workaround for URL view

scripts/patch_updater_yml.sh
The ESR CI build fails on Linux if the update file doesn't exist.
```release-note
NONE
```
=> Don't require the update file to exist

patches/electron-context-menu+4.0.4.patch
A conflict in how we were passing window context to the `electron-context-menu` caused crashes in our app, since some pass the `webContents` and others pass the window object. There is a handler in `electron-context-menu` for this, but we weren't using it.
This PR switches to use that handle so that either windows or `webContents` will work fine.
https://mattermost.atlassian.net/browse/MM-64399
Fixes #3440 
```release-note
NONE
```
=> [MM-64399] Fix crash in electron-context-menu

src/common/communication.ts, src/main/preload/internalAPI.js, src/main/views/viewManager.ts, src/renderer/components/urlDescription.tsx, src/renderer/modals/urlView/urlView.tsx, src/types/window.ts
Unfortunately, the previous fix isn't enough to stop all cases where the UrlView steals focus when it's added by hovering a link. Instead of doing that though, let's just keep it mounted all of the time and only make it visible when needed.
From my testing in Parallels, it seems to fix the issue on both Windows and Ubuntu
MM-62005
Closes https://github.com/mattermost/desktop/issues/3377
This PR was tested on: Windows 11 21H2, Ubuntu 24.04 LTS
Comparisons of before/after:
https://github.com/user-attachments/assets/102baa89-15ec-4b47-b2c0-2500888c0042
https://github.com/user-attachments/assets/5f53fb45-79ec-4ceb-bd55-237e6822edc5
```release-note
Fixed URL preview stealing focus from app
```
=> MM-62005 Change UrlView to always stay mounted

src/main/views/webContentEvents.ts, src/main/views/webContentEventsCommon.ts
Enhances mattermost:// protocol handling for in-app links in channel bookmarks. When users click bookmarks with mattermost:// URLs, they now open within the desktop app using internal deep linking instead of triggering external protocol dialogs.
- Add isMattermostProtocol() helper function to identify mattermost:// URLs
- Update webContentEvents to handle mattermost:// links through internal deep linking
- Ensure mattermost:// links in bookmarks open within the app instead of external dialog
- Maintain existing custom protocol dialog for other non-http/https protocols
This improves the user experience by allowing mattermost:// bookmarks to navigate directly within the desktop app without prompting external application dialogs.
Related to [server-side …
=> In-App Links in Channel's Bookmarks

src/app/mainWindow/mainWindow.ts, src/app/serverHub.ts, src/common/servers/serverManager.ts, src/common/views/viewManager.test.js, src/common/views/viewManager.ts
I introduced a bug in #3509 that causes an issue on server removal. I made a change that required the server to still exist when the event was emitted, but I didn't take into account that other listeners assume the server would not exist.
To fix this, I just emit the entire server object on removal so that any data one of the listeners needs is still there when the listener is called.
```release-note
NONE
```
=> Fix server removal bug

electron-builder.json, resources/mac/entitlements.mas.inherit.plist
Our MAS build was missing the hardened runtime, which is needed to avoid certain exploits. This PR turns that runtime on and fixes an entitlement issue causing the app to not work.
https://mattermost.atlassian.net/browse/MM-64732
```release-note
macOS: Enable hardened runtime on MAS build
```
=> [MM-64732] Enable hardened runtime on MAS build
