mattermost/desktop

- README.md
- docs/setup.md
- Propose starting step-by-step guide to help less technical users install
- Also minor typo correction in README
Wonderful work with 1.0 release!
> Propose adding step-by-step install guide

- src/browser/index.jsx
- src/browser/webview/mattermost.js
Show mention count badge and unread * badge like Slack app.
I tested only on Mac OSX.
> Show mention count badge and unread * badge.

- src/browser/index.jsx
- src/browser/webview/mattermost.js
I found 2 bugs.
bug1.
Mention count does not disappear on active CHANNEL.
bug2.
Mention count and Unread badge does not appear on active DM.
Tested OS: OSX El Capitan
Tested Mattermost version: 1.4
Test case: 
Post to channel/DM when window isn't focused, unread badge(if DM, count badge) appear. and dissapear when it focused.
Post to channel/DM with mention when window isnt focused, count badge appear. and dissapear when it focused.
> fix 2 bugs. see #12 and #18.

- README.md
I accidentally linked it to the branch in the first PR :p
> Fixing link to GIF in README

- CHANGELOG.md
- src/browser/settings.jsx
- src/common/settings.js
> Update text for allowing http content, allow mixed content by default

- src/browser/index.jsx
- src/main.js
> Change tooltip text on mentions/unread

- src/browser/settings.jsx
- src/common/settings.js
- src/main.js
Here is the blink notification in the taskbar after being mentioned by someone.
I only tested it on windows, since I doesn't own a macOS or linux distribution.
More information see #39
> Blink notification in taskbar

- ISSUE_TEMPLATE.md
A similar template to this one has been successfully used in the \platform repo and can help increase quality of submissions
> Proposed update to issue template

- CHANGELOG.md
- docs/setup.md
- src/main/menus/app.js
Closes #177
I can't build at the workplace where I'm right now, but I will grab the circleci build and verify it as soon as it's up.
> Added a "Mattermost docs" link to the Help section

- CHANGELOG.md
- src/main.js
- src/main/menus/app.js
- src/main/menus/tray.js
- [ x ] Complete [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [ x ] Execute `npm run prettify` to format codes
- [ x ] Write about environment which you tested
- Tested with windows 10, works fine
Also aligned the changelog, but could not find anything in the docs folder about it.
Looks like this:
> Improve tray menu

- src/browser/settings.jsx
As mentioned in
https://github.com/mattermost/desktop/issues/193#issuecomment-231553779
> Fixed typo in settings (task icon)

- CHANGELOG.md
- src/browser/settings.jsx
- src/main.js
- test/specs/browser/settings_test.js
This enables the *window flashing in the taskbar on messages* feature for linux.
---
- Ubuntu 16.04 running unity
> Urgent hint on linux

- CHANGELOG.md
> Add "UNDER DEVELOPMENT" note for v1.4 changelog

- package.json
- src/browser/menus/context.js
- src/main.js
- src/main/menus/app.js
- src/main/menus/tray.js
Just updated to the newest version of electron and used some of the new features, to streamline our menus.
See each commit for details.
Tested on windows 10 so far.
> Improve menus due to improvements in electron

- ISSUE_TEMPLATE.md
- N/A
- N/A
Update description of Mattermost Menu in issue_template.md.
Also update location of the desktop app version, given it's now under **Help**.
> Update description of Mattermost Menu in issue_template.md

- package.json
Not tested yet, as my windows crashes when I execute the tests. Let's see if circleci can handle it.
> Bump mocha

- CHANGELOG.md
- src/browser/webview/mattermost.js
- src/main.js
- src/main/menus/tray.js
As stated in #249 the window handling was off under some circumstances.
This tries to improve it and is working fine with win10 x64.
There might be cases I missed, where this also needs to be done. Just let me know.
> Improved window state handling

- src/main.js
Probably an oversight of my previous window handling refactor.
Especially the toogle window on tray icon click option was borked.
> Fix for window toggle on tray click

- src/main/menus/app.js
> Enable zoom-in on CommandOrctrl +

- CHANGELOG.md
- docs/setup.md
- src/browser/index.jsx
- src/browser/webview/mattermost.js
- src/main/menus/app.js
This addresses #270 
Tested and working on win10
> Move current search in channel function to Shift+CTRL+S

- CHANGELOG.md
This is just a text change for an .md file, so fine to add to `v3.4-release` branch.
It'll be included in RC2 (if cut) or the final build.
> Update changelog for v1.4

- CHANGELOG.md
Reverts mattermost/desktop#286
> Revert "Update changelog for v1.4"

- src/browser/settings.jsx
- Added the cross icon in the header.
- Adjusted the padding for the settings grid and removed an unnecessary hr.
> plt-4174 - Improvements to the Settings UI

- circle.yml
- docker/package_in_docker.sh
This makes the test faster than current. The purpose of PR is just for notice.
Before merging, we have to change the setting in CircleCI.
After merging, further commits for existing PRs must rebase in order to pass the test.
> Stop using Docker and using Ubuntu 14.04 for this in CircleCI

- src/package.json
See builds here: https://circleci.com/gh/Razzeee/desktop/28#artifacts/containers/0
> Bump auto launch

- src/browser/index.jsx
---
- OS X 10.12.1
Should fix #299
> "Cannot connect to Mattermost" is now on top of the page

- CHANGELOG.md
- src/common/settings.js
- src/main.js
First of all, please read [`CONTRIBUTING.md`](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
---
- Ubuntu 16.10
> Purge cache on app update

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
Update issue and pull request templates, feedback more than welcome
> Update issue and pull request templates

- TESTING.md
- [N/A] executed `npm run lint:js` for proper code formatting
**Summary**
Update TESTING.md instructions
> Update TESTING.md instructions

- docs/release-process.md
Proposed release process for desktop app, a subset of what's used by the Mattermost core team for server releases.
This will help smooth out the release process, and help everyone monitor how the release is progressing (each checklist will be posted in the Desktop App channel on their respective dates)
> Proposed release process for desktop app

- src/main.js
**Summary**
Update default window dimensions to 1000x700
**Issue link**
#353
> Update default window dimensions to 1000x700

- src/browser/components/TabBar.jsx
- src/browser/css/index.css
**Summary**
PLT-5448 - Updating styling of server tabs
**Issue link**
https://mattermost.atlassian.net/browse/PLT-5448
> PLT-5448 - Updating styling of server tabs

- CHANGELOG.md
**Summary**
Update changelog for 3.6, currently a work-in-progress
> Update changelog for 3.6

- CHANGELOG.md
Just re-submitting #441 to the 3.6 branch
> Updating changelog in 3.6 branch

- src/browser/components/MattermostView.jsx
**Summary**
Fix `window.open()` function looks not working.
When a new window was opened, it was hidden because the main window's `{show:false}` option was inherited to the new window. So the new window was not visible.
**Issue link**
#450 
**Test Cases**
1. Click "Help" below message box.
2. A new window show appear.
https://circleci.com/gh/yuya-oc/desktop/168#artifacts
> Fix window.open() looks not working

- src/browser/components/TabBar.jsx
Reiterate the new team modal PR. This simply aligns the plus button correctly (by moving it down).
> Align add server button in the tab bar vertically, fixes #460

- src/main.js
- src/main/mainWindow.js
**Summary**
Refactor main window code.
Now the main window is managed by `src/main/mainWindow.js`.
**Issue link**
N/A
**Test Cases**
All cases.
https://circleci.com/gh/yuya-oc/desktop/195#artifacts
> Refactor main window code

- LICENSE
Propose using `2015-present` format so we don't have to worry about updating the year in the future :)
> Update current year for license file

- package.json
- test/modules/environment.js
- test/specs/app_test.js
- test/specs/browser/index_test.js
- test/specs/browser/settings_test.js
- test/specs/security_test.js
**Summary**
Stop using chai-as-promised due to its license.
**Issue link**
#488
**Test Cases**
Execute `npm test` ([CircleCI results](https://circleci.com/gh/yuya-oc/desktop/202))
N/A
> Stop using chai-as-promised

- src/main/menus/app.js
**Summary**
Change "team" references to "server"
Looks like this was missed earlier
> Change "team" references to "server"

- CHANGELOG.md
- NOTICE.txt
- electron-builder.json
- package.json
- scripts/7zip-cli.js
- src/browser/components/MainPage.jsx
- src/browser/components/MattermostView.jsx
- src/browser/components/SettingsPage.jsx
- src/browser/index.jsx
- src/browser/js/contextMenu.js
- src/browser/settings.jsx
- src/browser/webview/mattermost.js
- src/common/settings.js
- src/main.js
- src/main/SpellChecker.js
- src/package.json
- test/.eslintrc.json
- test/specs/browser/settings_test.js
- test/specs/spellchecker_test.js
For #225, I tried using [`simple-spellchecker`](https://github.com/jfmdev/simple-spellchecker) suggested in the issue. As the result, it doesn't work in my side.
- As far as reading `npm run build`, somehow `webpack` try to parse markdown file. I feel it's strange.
- In `npm start`, the app could not find `stream`. `stream` is a standard API in Node.js, so I'm not sure why it's not found.
```
> mattermost-desktop@1.4.0 build /Users/airwalker/git/mattermost-desktop
> gulp build
[20:24:28] Using gulpfile ~/git/mattermost-desktop/gulpfile.js
[20:24:28] Starting 'sync-meta'...
[20:24:28] Finished 'sync-meta' after 1.33 ms
[20:24:28] Starting 'webpack:main'...
[20:24:28] Starting 'webpack:browser'...
[20:24:28] Starting 'webpack:webview'...
[20:24:28] Starting 'copy:resources'...
[20:24:28] …
```
> Add spellchecker

- CHANGELOG.md
- [N/A] executed `npm run lint:js` for proper code formatting
**Summary**
Add bug reporter for 3.7
> Add bug reporter for 3.7 changelog

- docs/release-process.md
- [N/A] executed `npm run lint:js` for proper code formatting
**Summary**
Update dot release checklist
> Update dot release checklist

- CHANGELOG.md
- [-] executed `npm run lint:js` for proper code formatting
**Summary**
Update master branch changelog for 3.7.1
> Update master branch changelog for 3.7.1

- package.json
- src/package.json
**Summary**
Merge all changes for v3.7.1.
**Issue link**
N/A
**Test Cases**
N/A
https://circleci.com/gh/yuya-oc/desktop/353#artifacts
> Merge release-3.7 branch

- package.json
**Summary**
Upgrade Electron 1.7.6 -> 1.7.8
I could not find significant changes excepting minor bug or security fixes.
**Issue link**
N/A
**Test Cases**
General use cases
https://circleci.com/gh/yuya-oc/desktop/406#artifacts
> Upgrade Electron to 1.7.8

- src/browser/components/SettingsPage.jsx
- src/browser/css/settings.css
Closes #439
**Summary**
Added hover color on settings page close button.
**Issue link**
#439
> Implement settings close button hover

- package.json
- yarn.lock
**Summary**
Upgrade Electron 1.7.8 -> 1.7.9
I could not find significant changes excepting minor bug or security fixes.
**Issue link**
N/A
**Test Cases**
General use cases
https://circleci.com/gh/yuya-oc/desktop/417#artifacts
> Upgrade Electron to 1.7.9

- src/browser/components/AutoSaveIndicator.jsx
- src/browser/components/SettingsPage.jsx
- src/browser/css/settings.css
- src/main.js
- test/specs/browser/settings_test.js
**Summary**
Changes the "Saved" indicator to show up next to the section titles, instead of one generic "Saved" indicator.
**Issue link**
#500 
Also includes a small fix for an `property of undefined`-error when the spellcheck is disabled.
> Change "Saved" indicator

- src/browser/components/ErrorView.jsx
- src/browser/components/SettingsPage.jsx
This PR changes new hardcoded app name references to use the appName from the package.json file.
via @dmeza
> White label setting and error pages

- README.md
**Summary**
Proposing to change banner in the README file.
> Update README.md - change banner

- package.json
- yarn.lock
**Summary**
Upgrade Electron to introduce latest bug fixes for our v4.0.0.
**Issue link**
N/A
**Test Cases**
General usecases.
https://circleci.com/gh/yuya-oc/desktop/555#artifacts
> Upgrade Electron to 1.7.11

- ISSUE_TEMPLATE.md
**Summary**
Tweak ISSUE_TEMPLATE.md to get more detailed feedback.
Some features are depending on server's features. So if server version is missing in such case, one more feedback is needed before researching the problem.
> Tweak ISSUE_TEMPLATE.md

- circle.yml
- docs/development.md
- test/specs/app_test.js
- test/specs/browser/index_test.js
- test/specs/browser/settings_test.js
**Summary**
Rewrite tests with async/await keywords. They improve readability/writability of asynchronous tests by avoiding complex `Promise` chain.
**Issue link**
N/A
**Test Cases**
Execute `npm test` in CI.
https://circleci.com/gh/yuya-oc/desktop/634
> Rewrite tests with async/await

- package.json
- yarn.lock
**Summary**
Upgrade Electron to 1.7.13
**Issue link**
N/A
**Test Cases**
General usecases.
https://circleci.com/gh/yuya-oc/desktop/700#artifacts
> Upgrade Electron to 1.7.13

- CHANGELOG.md
**Summary**
Update CHANGELOG.md for v4.0.1
**Issue link**
N/A
**Test Cases**
N/A
N/A
> Update CHANGELOG.md for v4.0.1

- package.json
- yarn.lock
**Summary**
Upgrade Electron to 1.8.4.
As far as looking changelogs, important changes not found in functionality.
- https://electronjs.org/releases#1.8.4
- https://electronjs.org/releases#1.8.3
**Issue link**
#739 
**Test Cases**
General usecases.
https://circleci.com/gh/yuya-oc/desktop/704#artifacts
> Upgrade Electron to 1.8.4

- src/browser/components/SettingsPage.jsx
- src/common/config/defaultPreferences.js
**Summary**
Switch default GPU acceleration to false
**Issue link**
Discussed on pre-release: https://pre-release.mattermost.com/core/pl/onub7k6jhbn4uj7qq9ojwfy15w
> Switch default GPU acceleration to false

- builds/pr/Jenkinsfile
Basic Jenkinsfile to get PR's building
> basic jenkinsfile for pull requests

- src/browser/components/LoginModal.jsx
**Summary**
Fix authentication dialog not working.
**Issue link**
#809 
**Test Cases**
There are two ways to test the feature. Either one is sufficient.
a. Use the app with proxy server which requires authentication.
b. Add a server which requires HTTP Authentication.
https://circleci.com/gh/yuya-oc/desktop/847#artifacts
> Fix authentication dialog not working

- src/browser/components/LoginModal.jsx
**Summary**
Backport #812 to release-4.1: Fix authentication dialog not working.
I just cherry-picked 4280154cb876e53b5a19cfe0e31d55ab2ff9ceed against to release-4.1 branch.
**Issue link**
#809
**Test Cases**
As well as #812
N/A
> Backport #812 to release-4.1

- electron-builder.json
**Summary**
Update categories of deb packages.
Inspired by #816: This PR also uses `Network;InstantMessaging` as app category.
**Issue link**
#816
**Test Cases**
Install deb packages, then check its category in the submenu of the application starter.
https://circleci.com/gh/yuya-oc/desktop/873#artifacts
> Update categories of deb packages

- package.json
- test/specs/browser/settings_test.js
- webpack.config.base.js
- webpack.config.main.js
- yarn.lock
**Summary**
Upgrade build tools, webpack and babel. This also has some tweak to use webpack 4.
**Issue link**
#805
**Test Cases**
1. General usecases
2. CI
https://circleci.com/gh/mattermost/desktop/1552#artifacts
> Upgrade build tools

- package.json
- src/package.json
**Summary**
Apply new versioning scheme.
- `X.X.X-develop`: While under development (If possible, use git hash in CI instead)
- `X.X.X-rcX`: RCs
- `X.X.X`: Final release
- `X.Y.0-develop`: Increment version number after new minor release
**Issue link**
Original post: https://pre-release.mattermost.com/core/pl/3qten5ndjpyambf9gzdee9q7gh
**Test Cases**
a. Check artifact names
b. Check version which is displayed in the application menu, `Help -> Version`.
https://circleci.com/gh/yuya-oc/desktop/913#artifacts
> Apply new versioning scheme

- src/browser/js/contextMenu.js
- src/main/SpellChecker.js
- src/package.json
- src/yarn.lock
- test/specs/spellchecker_test.js
**Summary**
Upgrade `simple-spellchecker` and add entry in menu to support pt-BR spell-checker
**Issue link**
**Test Cases**
> Add pt-BR spell checker

- .eslintrc.json
- src/browser/components/LoginModal.jsx
- src/browser/components/MainPage.jsx
- src/browser/components/MattermostView.jsx
- src/browser/components/SettingsPage.jsx
- src/browser/components/TeamList.jsx
- src/browser/webview/mattermost.js
- src/common/config/upgradePreferences.js
- src/common/osVersion.js
- src/common/settings.js
- src/main.js
- src/main/allowProtocolDialog.js
- src/main/certificateStore.js
- src/main/mainWindow.js
- src/main/menus/app.js
- src/main/menus/tray.js
**Summary**
Apply no-var eslint rule. This prevents us from mistake of variable scope.
https://eslint.org/docs/rules/no-var
**Issue link**
N/A
**Test Cases**
General usecases of desktop app. Generally, this change would not make significant changes because source codes are already analyzed by eslint.
N/A
> Apply no-var eslint rule

- .eslintrc.json
- NOTICE.txt
- src/browser/components/MainPage.jsx
- src/browser/components/MattermostView.jsx
- src/browser/components/SettingsPage.jsx
- src/browser/components/TeamList.jsx
- src/package.json
- src/yarn.lock
**Summary**
Use ES6 class for React components. Now it's the replacement of createReactClass().
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-es6-class.md
**Issue link**
N/A
**Test Cases**
a. Page loading.
b. Keyboard shortcuts.
https://circleci.com/gh/yuya-oc/desktop/976#artifacts
> Use ES6 class for React components

- src/browser/js/contextMenu.js
**Summary**
Add en-GB and es-MX to spellchecker
**Issue link**
https://pre-release.mattermost.com/core/pl/pnsthgz4s7bimbksk4qmd6asxr
> Add en-GB and es-MX to spellchecker

- src/browser/components/TabBar.jsx
- src/browser/css/components/TabBar.css
**Summary**
Improving the styling of the mention badge in tab bar
**Issue link**
https://mattermost.atlassian.net/browse/MM-13487
**Test Cases**
> MM-13487 - Updating mention badge in tab bar

- src/main/mainWindow.js
**Summary**
Makes the app not to restart in full-screen mode
**Issue link**
https://github.com/mattermost/desktop/issues/538
> Fix #538: makes the app not to restart in full-screen mode

- src/package-lock.json
- src/package.json
fixes: https://github.com/mattermost/docs/issues/2535
> update simple-spellchecker for new dict files

- resources/windows/gpo/en-US/mattermost.adml
- resources/windows/gpo/mattermost.admx
This pull request enhance the GPO by adding the control of GPU usage.
I added also Desktop Version 4.4 as this is - i guess - a minor GPO that can be added in a later release.
I will create a docs PR next week.
> Add GPO for controlling GPU

- resources/windows/gpo/en-US/mattermost.adml
- resources/windows/gpo/mattermost.admx
This pull request is a proposal for more user friendly list of servers.
> GPO Server address proposal

- .vscode/extensions.json
- .vscode/launch.json
- .vscode/tasks.json
**Summary**
Add VSCode configuration. It would make easier to debug the app.
**Issue link**
N/A
**Test Cases**
Develop/Debug with VSCode.
N/A
> Add VSCode configuration

- src/browser/css/components/TabBar.css
**Summary**
Centering the dot correctly on nomentions badge
**Issue link**
[MM-13690](https://mattermost.atlassian.net/browse/MM-13690)
> MM-13690: Centering the dot correctly on nomentions badge

- src/main.js
Changed code to match Wix and moved after app.ready
> Updates to internal appUserModelID code

- CHANGELOG.md
- package.json
- src/package.json
**Summary**
This PR prepares the 4.2 branch for the 4.2.2 release that contains multiple security enhancement.
> Preparation for 4.2.2 Release

- package.json
- src/package.json
**Summary**
Bump version of desktop app to 4.2.3
> Bump version to v4.2.3

- resources/windows/gpo/en-US/mattermost.adml
**Summary**
During the tests i put the values vice versa. This is a proposal for adding a hint how to fill it correctly.
> Update GPO DefaultServerList Description

- scripts/Makefile.ps1
> [MM-19515] signing electronbuilder exe

- src/browser/components/SettingsPage.jsx
**Issue link**
Closes https://github.com/mattermost/desktop/issues/1071
Closes https://mattermost.atlassian.net/browse/MM-19368
> Update add new server icon on the settings page

- src/browser/components/LoginModal.jsx
- src/browser/components/MainPage.jsx
- src/browser/components/MattermostView.jsx
- src/browser/components/NewTeamModal.jsx
- src/browser/components/TeamList.jsx
- src/browser/components/TeamListItem.jsx
**Summary**
Deleted all instances of .bind()  to use arrow function. 
**Issue link**
https://mattermost.atlassian.net/browse/MM-18754
Fixes https://github.com/mattermost/mattermost-server/issues/13355
**Test Cases**
> MM-18754:  Desktop: Convert binding functions to arrow functions

- src/browser/components/NewTeamModal.jsx
**Summary**
Added auto focus on "Server Display Name" input field.
**Issue link**
https://mattermost.atlassian.net/browse/MM-20795
Fixes https://github.com/mattermost/desktop/issues/1134
> [MM-20795] Added auto focus on Server Display Name input field

- src/browser/js/contextMenu.js
- src/main/SpellChecker.js
- test/specs/spellchecker_test.js
**Summary**
Add entry in menu to support it-IT spell-checker
**Issue link**
**Test Cases**
> Add it-IT spell checker

- src/browser/js/contextMenu.js
- src/main/SpellChecker.js
- test/specs/spellchecker_test.js
This pull request adds pl-PL as available spellchecker within the DesktopApp. I am to stupid to update my branch. Therefore new Pullrequest on new master
> Add pl-PL as spellchecker

- src/browser/components/MainPage.jsx
- src/browser/components/MattermostView.jsx
- src/utils/util.js
**Summary**
Cherry pick for #1165.
> [MM-19919] Allow links to other servers to go directly to that server in the app (#1165)

- src/main.js
**Summary**
Cancel dismisses the certificate selection dialog, but doesn't do anything else like previously
**Issue link**
[MM-21934](https://mattermost.atlassian.net/browse/MM-21934)
> [MM-21934] don't do anything on cancel

- src/browser/components/SelectCertificateModal.jsx
**Summary**
there are two aliases for the fields, we'll try to get the one that is filled.
**Issue link**
[MM-22006](https://mattermost.atlassian.net/browse/MM-22006)
> [MM-22006] fix name mapping

- src/browser/components/SettingsPage.jsx
- src/browser/css/settings.css
- src/browser/settings.jsx
> [MM-22073] Added new titlebar to Settings page (#1171)

- src/browser/components/MainPage.jsx
- src/browser/components/MattermostView.jsx
> [MM-20796] Cherrypick

- src/browser/components/SelectCertificateModal.jsx
- src/browser/components/showCertificateModal.jsx
- src/browser/css/components/CertificateModal.css
**Summary**
Current CSS for selecting the certificate and showing the info is not looking good. this attempts to fix it.
**Issue link**
[MM-21974](https://mattermost.atlassian.net/browse/MM-21974)
> [MM-21974] improve CSS for client certificate screens

- src/main.js
> [MM-22193] Workaround for app hang on Windows 10 dark mode (#1180)

- src/main/menus/app.js
**Summary**
Added shortcuts for some default actions.
**Issue link**
[MM-22150](https://mattermost.atlassian.net/browse/MM-22150)
should be tested on the 3 platforms
> [MM-22150] Add default accelerators

- src/browser/components/MainPage.jsx
> [MM-22585] Cherry-pick of #1193

- src/browser/components/MainPage.jsx
- src/browser/index.jsx
> [MM-22494] Cherrypick (#1191)

- src/common/config/defaultPreferences.js
**Summary**
- Set default preferences to 'Flash app window and taskbar icon when a new message is received'.
This is still a WIP PR because I want to test the changes with the CI artifacts as well.
**Issue link**
https://mattermost.atlassian.net/browse/MM-22361
> [MM-22361] - Set default preferences to flash app window

- src/main.js
**Summary**
cherrypick for #1247
> [MM-23057] add different useragent for popup windows (#1247)

- src/browser/components/MattermostView.jsx
> [MM-23784] Cherry-pick of #1258

- src/main/menus/app.js
> [MM-23153] Cherry pick of #1248

- .circleci/config.yml
- scripts/Makefile.ps1
- test/specs/browser/settings_test.js
**Summary**
change how to describe the signed package into its propper order
add notifications for releases
**Issue link**
**Test Cases**
on UAC should display the right version
waiting for circle to be able to get npm from the registry
> [MM-22495] fix uac name

- src/common/config/index.js
**Summary**
Cherry-pick of #1300
> [MM-24702] Fixed unintentional re-ordering of teams in config file (#1300)

- src/browser/components/NewTeamModal.jsx
- src/browser/components/SettingsPage.jsx
- src/browser/components/TeamList.jsx
**Summary**
Cherry-pick of #1302
> [MM-25526] Removed fix for flaky test causing visual issues with Add New Server flow (#1302)

- src/browser/components/MainPage.jsx
**Summary**
Cherry-pick of #1303
> [MM-25522] Revert unnecessary fix for bad UX causing focus to not be restored correctly (#1303)

- .circleci/config.yml
**Summary**
Fix invalid link to GitHub releases 
**Issue link**
https://community.mattermost.com/core/pl/gdax99o7xf8p9etdr8pn316ahw
> Fix typo in release message

- src/main/CriticalErrorHandler.js
- src/main/allowProtocolDialog.js
- src/main/autoUpdater.js
**Summary**
Cherry-pick of https://github.com/mattermost/desktop/pull/1315 into release-4.5
> [MM-22230] cherry pick #1315

- src/browser/components/MainPage.jsx
- src/main.js
**Summary**
focus event can be raised by multiple elements and search bar might not yet be present.
**Issue link**
[MM-25980](https://mattermost.atlassian.net/browse/MM-25980)
**Test Cases**
see ticket
> [MM-25980] no menu for popups

- package-lock.json
- package.json
- src/package-lock.json
- src/package.json
**Summary**
upgrade minimist and kind-of deps for security issues
**Issue link**
[MM-26665](https://mattermost.atlassian.net/browse/MM-26665)
> [MM-26665] fix security issues from dependabot

- package.json
**Summary**
Bumping Electron to v7.3.2
**Issue link**
https://mattermost.atlassian.net/browse/MM-26752
> Bump electron to v7.3.2

- package-lock.json
**Summary**
Commit package-lock.json for electron version bump
**Issue link**
https://mattermost.atlassian.net/browse/MM-26752
> [MM-26752] Commit package-lock.json for electron version bump

- src/browser/components/SettingsPage.jsx
- src/browser/js/contextMenu.js
- src/main/SpellChecker.js
- src/package-lock.json
- src/package.json
- test/specs/spellchecker_test.js
**Summary**
Adding Russian language in the list available for spellchecking
> add Russian language in the list available for spellchecking

- src/browser/components/SettingsPage.jsx
- src/main.js
- src/main/ParseArgs.js
- src/main/autoLaunch.js
- src/main/mainWindow.js
**Summary**
on autostart don't minimize the window
**Issue link**
[MM-27332](https://mattermost.atlassian.net/browse/MM-27332)
**Test Cases**
Case 1
on windows/linux
- open preferences and tick the autostart on login
Expected:
upon restart, the app open with visible window
Case 2
on windows/linux
- open prefereces and untick same option
Expected
upon restart, the app doesn't start automatically
> [MM-27332] show window at autolaunch

- src/browser/js/notification.js
**Summary**
fix missing sound detection when connecting to a server that doesn't allow for custom sounds
**Issue link**
[MM-29702](https://mattermost.atlassian.net/browse/MM-29702)
**Test Cases**
see ticket
> [MM-29702] fix soundname not existing

- src/browser/js/notification.js
**Summary**
Fix notifications not playing custom sounds
**Issue link**
fixes #1395 
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-29921)
**Test Cases**
- ensure the webapp is not loaded with the same user in a browser tab
- go to account settings, notifications and choose a custom sound
- from another user, send an at-mention
Expected: custom sound is played
> [MM-29921] fix custom sound not playing when receiving a notification

- package-lock.json
- package.json
- src/common/config/index.js
- src/main/main.js
**Summary**
There were several race conditions regarding the config that weren't showing in previous PRs. This should fix them.
> [BrowserView] fix different errors when loading config

- src/common/config/index.js
- src/renderer/components/MainPage.jsx
- src/renderer/components/TabBar.jsx
- src/renderer/index.jsx
**Summary**
Fixes to get tab switching and drag and drop to work correctly in the BrowserView ecosystem.
**Issue link**
https://mattermost.atlassian.net/browse/MM-23078
> [MM-23078] TabBar fixes for BrowserView

- .circleci/config.yml
**Summary**
Cherry pick from #1440
> [browserview] Fix missing key on apt-get (#1440)

- .circleci/config.yml
**Summary**
**Issue link**
**Test Cases**
> Bv pipeline elisabeth

- src/common/communication.js
- src/common/utils/url.js
- src/main/authManager.js
- src/main/certificateManager.js
- src/main/main.js
- src/main/modalView.js
- src/main/preload/modalPreload.js
- src/renderer/components/MainPage.jsx
- src/renderer/css/modals.css
- src/renderer/modals/certificate/certificate.jsx
- src/renderer/modals/certificate/certificateModal.jsx
- src/renderer/modals/login/login.jsx
- src/renderer/modals/login/loginModal.jsx
- src/renderer/modals/permission/permission.jsx
- src/renderer/modals/permission/permissionModal.jsx
- webpack.config.renderer.js
**Summary**
Using a BrowserView to render the auth and certificate check modals
**Issue link**
https://mattermost.atlassian.net/browse/MM-30144
https://mattermost.atlassian.net/browse/MM-30145
https://mattermost.atlassian.net/browse/MM-30146
https://mattermost.atlassian.net/browse/MM-30147
Currently based on @Willyfrog's `BV_modals` branch, will rebase once that's merged.
> [MM-30144][MM-30145][MM-30146][MM-30147] Migrate auth and certificate modals to BrowserView

- .circleci/config.yml
- docs/release-process.md
- package-lock.json
- package.json
- scripts/cleanCache.command
- scripts/cp_artifacts.sh
- scripts/manipulate_windows_zip.js
- scripts/release.sh
- src/main/CriticalErrorHandler.js
- src/main/menus/app.js
- src/renderer/index.jsx
- webpack.config.base.js
**Summary**
- update version to 5.0.0-development
- remove cache from src/package-lock.json, also other references to that file
- enable copying exe files to artifacts
**Issue link**
[MM-32277](https://mattermost.atlassian.net/browse/MM-32277)
> [browser view] MM-32277 bump version, exe, cache errrors

- src/main/viewManager.js
**Summary**
moving through links was triggering the urlview in the footer with no content
**Issue link**
[MM-31232](https://mattermost.atlassian.net/browse/MM-31232)
> [MM-31232] fix urlview present with no content

- src/common/utils/url.js
- src/main/MattermostView.js
- src/main/main.js
- src/main/viewManager.js
- src/main/windows/mainWindow.js
- src/main/windows/windowManager.js
- src/renderer/components/externalLink.jsx
**Summary**
Allow app to handle deeplinking
fixed a couple of errors due to different casing for the word URL
changed how MattermostView notifies it has successfully loaded the requested page
**Issue link**
[MM-28541](https://mattermost.atlassian.net/browse/MM-28541)
> [MM-28541] restore deeplinking

- src/main/MattermostView.js
**Summary**
prevent unwanted crashes when checking for updates
**Issue link**
[MM-32765](https://mattermost.atlassian.net/browse/MM-32765)
**Test Cases**
I couldn't make it crash before this, but given the error this should be enough.
> MM-32765_prevent crash on checking unread state

- src/main/notifications/Download.js
- src/main/notifications/Mention.js
**Summary**
fix path used to setup win/linux icon for notifications
**Test Cases**
mention the user
> [MM-21716] fix appicon path resolution

- src/main/appState.js
- src/main/main.js
- src/renderer/components/MainPage.jsx
**Summary**
make the renderer aware that the state has changed and that it needs to re-render
**Issue link**
[MM-33231](https://mattermost.atlassian.net/browse/MM-33231)
**Test Cases**
have another user mention you in a channel, badge should update almost instantly
> [MM-33231] update jewel on new mentions/when read

- src/main/views/MattermostView.js
**Summary**
there seems to be a race condition when at some point the server is not there when trying to access it. this should probably fix it. but without repro steps is hard to tell
**Issue link**
[MM-34088](https://mattermost.atlassian.net/browse/MM-34088)
> [MM-34088] remove listeners before destroy

- .circleci/config.yml
**Summary**
Fix dailybuild so it correctly generates the message in daily build channel. Improve message.
Results in: https://community-daily.mattermost.com/core/pl/yk4npxfsatgj5nuqtsm4piryec
> Improve daily build ci

- src/main/windows/settingsWindow.js
**Summary**
Remove menu bar in the settings window for windows and linux
**Issue link**
[MM-34528](https://mattermost.atlassian.net/browse/MM-34528)
> [MM-34528] hide menu bar

- src/common/communication.js
- src/common/utils/constants.js
- src/main/views/MattermostView.js
- src/main/views/viewManager.js
- src/renderer/components/MainPage.jsx
**Summary**
- fix loading screen problem when there is a non-mattermost server or an error connecting
- fix mainpage not re-rendering on tab status change
**Issue link**
[MM-33902](https://mattermost.atlassian.net/browse/MM-33902)
Closing https://github.com/mattermost/desktop/pull/1529 in favor of this one
> [MM-33903] fix loading screen

- src/renderer/components/SettingsPage.jsx
**Summary**
languages are no longer selectable, also toggling the spellchecker requires a restart
**Issue link**
[MM-34820](https://mattermost.atlassian.net/browse/MM-34820)
**Screenshot**
> [MM-34820] Improve spell check's option help text

- src/common/communication.js
- src/main/windows/mainWindow.js
- src/main/windows/settingsWindow.js
- src/renderer/components/MainPage.jsx
**Summary**
Cherry-pick of #1546 to `release-4.7`
> [MM-34890][MM-34897] Fix some fullscreen issues (#1546) - cherry-pick

- scripts/Makefile.ps1
- scripts/msi_installer.wxs
cherry pick of https://github.com/mattermost/desktop/pull/1548
> Fix msi [cherry-pick v4.7]

- src/main/tray/tray.js
see https://github.com/mattermost/desktop/pull/1549
>  [MM-35007] don't try to use pressed images with templates - cherry-pick v4.7

- package.json
- scripts/generate_release_markdown.sh
**Summary**
by providing both flags, we can generate builds for both architectures
**Issue link**
[MM-35010](https://mattermost.atlassian.net/browse/MM-35010)
> [MM-35010] add m1 architecture support

- package.json
- scripts/generate_release_markdown.sh
see https://github.com/mattermost/desktop/pull/1550
> [MM-35010] add m1 architecture support (cherry-pick v4.7)

- src/main/appState.js
- src/main/badge.js
- src/main/main.js
see https://github.com/mattermost/desktop/pull/1538
> [MM-34594] Only show dock badge when the setting is enabled (cherry-pick v4.7)

- .circleci/config.yml
- scripts/cp_artifacts.sh
**Summary**
Add results from m1 build so they are available. I misread .* as a regex instead of a shell wildcard 🤦 
**Issue link**
https://github.com/mattermost/desktop/pull/1555
we might want to do a new RC so we can test the build on M1 before release
> [MM-35010] Fix m1 release pipeline

- .github/ISSUE_TEMPLATE/beta_report.md
**Summary**
Add template for beta reports
**Release Notes**
```release-notes
NONE
```
> add beta template

- src/common/utils/url.js
- src/main/views/webContentEvents.js
- test/unit/index.js
- test/unit/url_test.js
Cherry-pick of #1560 to `release-4.7`
> [MM-34836] Cleanse URLs of extra slashes on parsing, and add the image proxy case (#1560)

- src/renderer/components/SettingsPage.jsx
minor spacing problem
small fix to https://github.com/mattermost/desktop/pull/1543
```release-note
NONE
```
> fix help message spacing

- src/renderer/components/SettingsPage.jsx
cherry pick of #1564 
```release-note
NONE
```
> Fix help message spacing (cherry-pick v4.7)

- src/main/utils.js
- src/main/views/MattermostView.js
- src/main/views/webContentEvents.js
I've reverted to using the default base user agent string, with a modification that will put the Mattermost UA at the end of the string instead of in the middle.
https://mattermost.atlassian.net/browse/MM-35171
```release-note
NONE
```
> [MM-35171] Use modified default user agent string instead of hardcoded

- src/main/utils.js
- src/main/views/MattermostView.js
- src/main/views/webContentEvents.js
Cherry-pick of #1571 to `release-4.7`
> [MM-35171] Use modified default user agent string instead of hardcoded (#1571) - cherry-pick

- NOTICE.txt
> Update NOTICE.txt (#1573) (cherry-pick v4.7

- src/main/main.js
Cherry-pick of #1574 to `release-4.7`
> [MM-35131] Set default app downloads path to specified path in config (#1574)

- package-lock.json
- package.json
Upgrade electron to prevent latest vulnerabilities as well as a crash
[MM-35386](https://mattermost.atlassian.net/browse/MM-35386)
```release-note
upgrade to electron 11.4.4
```
> [MM-35386] Upgrade electron

- package-lock.json
- package.json
cherry-pick of #1580 
```release-note
upgrade to electron 11.4.4
```
> [MM-35386] Upgrade electron (cherry-pick v4.7)

- src/main/views/MattermostView.js
Cherry-pick of #1587 to `release-4.7`
> [MM-35249] Set window bounds on initial load success (#1587) - cherry-pick

- src/main/windows/windowManager.js
Cherry-pick of #1598 to `release-4.7`
> [MM-35588] Ensure that the window exists before calling minimize/maximize/reload (#1598)

- src/renderer/components/SettingsPage.jsx
Cherry-pick of #1600 to `release-4.7`
> [MM-35131] Don't set the download location in config if we hit Cancel (#1600) - cherrypick

- package-lock.json
- package.json
- scripts/msi_installer.wxs
- src/main/preload/mainWindow.js
- src/main/windows/windowManager.js
Upgrade the desktop app to Electron 12.
https://mattermost.atlassian.net/browse/MM-35811
```release-note
NONE
```
> [MM-35811][MM-35386] Upgrade to Electron 12

- package-lock.json
- package.json
- src/main/preload/mainWindow.js
- src/main/windows/windowManager.js
cherry pick of #1604 
```release-note
upgrade electron to v12
```
> [MM-35811][MM-35386] Upgrade to Electron 12 (#1604) (cherry-pick v4.7)

- src/main/windows/windowManager.js
Cherry-pick of #1604 to `release-4.7`
> [MM-35781] Another workaround for Linux resizing (#1608)

- src/renderer/index.html
Cherry-pick of #1612 to `release-4.7`
> [MM-35662] Added media-src tag to CSP to allow data blobs to play for notification sounds (#1612) - cherrypick

- package-lock.json
- package.json
see #1619 
```release-note
update to v12.0.10, fixed alt+shift problem on Linux.
```
> Cherry-pick update to v12.0.10 (#1619)

- src/main/certificateManager.js
cherry pick of #1630 
fixes loading path for modal
```release-note
NONE
```
> [MM-30147] [MM-30146] fix loading path for cert modal (#1630)

- src/common/config/index.ts
- src/main/main.ts
Cherry pick of #1653 
[MM-36938](https://mattermost.atlassian.net/browse/MM-36938)
```release-note
Fixed GUI missbehaviour by disabling GPU after app initialization.
```
> [MM-36938] disable gpu before app inits (cherry pick to master)

- src/common/config/index.ts
- src/main/main.ts
- src/main/preload/mainWindow.js
- src/main/views/webContentEvents.ts
- src/renderer/components/MainPage.tsx
- src/renderer/index.tsx
- src/types/config.ts
- src/types/window.ts
Global sandboxing is enabled.
once this is merged, I'll do a separate PR for 4.7
[MM-37198](https://mattermost.atlassian.net/browse/MM-37198)
This PR was tested on: windows 10 & macos big sur
```release-note
global sandbox enabled
```
> [Mm 37198] enable global sandboxing to increase security

- src/common/config/index.ts
- src/main/Validator.ts
- src/main/main.ts
- src/renderer/components/SettingsPage.tsx
- src/types/config.ts
cherry pick of #1666 
[MM-36747](https://mattermost.atlassian.net/browse/MM-36747)
```release-note
NONE
```
> [MM-36747] Spellchecker custom urls (cherrypick to TS)

- src/common/config/index.js
- src/main/main.js
- src/main/preload/mainWindow.js
- src/main/views/webContentEvents.js
- src/renderer/components/MainPage.jsx
- src/renderer/index.jsx
Conversion to JS & Cherry-pick of #1667 into release 4.7
[MM-37198](https://mattermost.atlassian.net/browse/MM-37198)
This PR was tested on: macos bigsur & windows 10
```release-note
global sandbox enabled
```
>  [MM-37198] enable global sandboxing to increase security (cherry-pick #1667)

- src/main/preload/mattermost.js
manu cherry pick for #1673 
This PR was tested on: macOS BigSur
```release-note
NONE
```
> Remove electron-log from preload (cherry pick for #1673)

- src/common/config/index.ts
Cherry-pick of #1676 to `master`
> enable handlers earlier (#1676) - cherry-pick

- src/main/main.js
- src/main/notifications/index.js
- src/main/preload/mattermost.js
Backported fix from: #1699
This PR was tested on: macOS BigSur
```release-note
NONE
```
> MM-36234: CRT, handle click on notification

- src/main/windows/windowManager.js
- src/renderer/components/SettingsPage.jsx
Cherry-pick of #1696 to `release-4.7`
> [MM-37797] Re-added the check for flashing the window (#1696) - cherrypick

- src/main/main.js
Backporting MM-37863 to `release-4.7`
> [MM-37863] Backport of MM-37863 to release-4.7

- package-lock.json
- package.json
Upgrading Electron to latest v12 to fix another weird dragging issue. The old one went away, and upgrading fixes the new one :S.
https://mattermost.atlassian.net/browse/MM-37954
```release-note
Upgrade to Electron v12.0.16
```
> [MM-37954] Fix dragging scrollbar issue

- src/common/utils/constants.ts
- src/main/preload/dropdown.js
- src/main/views/teamDropdownView.ts
- src/main/windows/mainWindow.ts
- src/main/windows/windowManager.ts
- src/renderer/css/components/TeamDropdownButton.scss
- src/renderer/css/dropdown.scss
- src/renderer/dropdown.tsx
This PR forces a minimum window width of 700px, and includes fixes to make sure that those minimum sizes work with all UI elements.
https://mattermost.atlassian.net/browse/MM-36437
```release-note
NONE
```
> [MM-36347] Force min window width of 700px

- src/renderer/components/MainPage.tsx
Removing the mention and unread counts for the current server from the dropdown button to avoid confusion that other servers you may have might have mentions.
https://mattermost.atlassian.net/browse/MM-38316
```release-note
NONE
```
> [MM-38316] Remove mention and unread counts for current server from the dropdown button

- src/renderer/css/components/TabBar.css
- src/renderer/css/components/TeamDropdownButton.scss
- src/renderer/css/dropdown.scss
Fixed up some of the UI elements as a few things were misaligned or needed some colours changed.
https://mattermost.atlassian.net/browse/MM-38325
```release-note
NONE
```
> [MM-38325] Polished up some of the UI elements

- src/main/views/teamDropdownView.ts
This PR changes the way we hide and show the menu, relying purely on changing the size of the browser view rather than adding and removing it from the window. The latter caused some issues on Big Sur and this seems to work on all platforms.
https://mattermost.atlassian.net/browse/MM-38459
```release-note
NONE
```
> [MM-38459] Resize the menu instead of removing the browser view altogether

- package-lock.json
- package.json
- src/main/views/MattermostView.ts
- src/main/views/modalView.ts
- src/main/views/teamDropdownView.ts
- src/main/views/viewManager.ts
- src/main/views/webContentEvents.ts
- src/main/windows/mainWindow.ts
- src/main/windows/settingsWindow.ts
- src/renderer/updater.tsx
- test/specs/app_test.js
- test/specs/browser/index_test.js
Upgrading to Electron v14 as it is stable now. Should fix some bugs.
https://mattermost.atlassian.net/browse/MM-36727
https://mattermost.atlassian.net/browse/MM-38503
```release-note
Upgraded to Electron v14
```
> [MM-38503] Upgrade to Electron v14

- src/main/main.ts
- src/main/views/viewManager.ts
- src/main/windows/windowManager.ts
- src/renderer/components/MainPage.tsx
This PR re-adds the functionality to switch automatically to a newly added server.
https://mattermost.atlassian.net/browse/MM-38532
```release-note
NONE
```
> [MM-38532] Force new server to display when added

- src/main/views/webContentEvents.ts
Cherrypick of #1746 to `release-5.0`
```release-note
NONE
```
> [MM-36032] Add electron-context-menu to popup windows (#1746) - cherrypick

- src/main/CriticalErrorHandler.ts
- src/main/menus/app.ts
- src/renderer/index.tsx
- webpack.config.base.js
We don't want our final releases to contain a commit hash as it could be a bit confusing, so we're removing them from our release builds.
https://mattermost.atlassian.net/browse/MM-37055
```release-note
NONE
```
> [MM-37055] Remove commit hash from release builds generated by CircleCI

- src/renderer/css/components/TeamDropdownButton.scss
- src/renderer/css/dropdown.scss
Cherry-pick of #1751 to `release-5.0`
```release-note
NONE
```
> [MM-38642] Set a max-width for the dropdown button and menu (#1751)

- src/main/windows/windowManager.ts
- src/renderer/components/MainPage.tsx
Cherry-pick of #1744 to `release-5.0`
```release-note
NONE
```
> [MM-38577] Allow exit of full screen mode using the restore button on Windows (#1744) - cherrypick

- src/main/main.ts
- src/main/notifications/Download.ts
- src/main/notifications/index.ts
Cherry pick of #1752 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1752

- src/main/CriticalErrorHandler.ts
- src/main/menus/app.ts
- src/renderer/index.tsx
- webpack.config.base.js
Cherry pick of #1750 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1750

- src/main/main.ts
- src/main/windows/mainWindow.ts
Cherry pick of #1740 on release-5.0.
/cc  @Willyfrog
```release-note
NONE
```
> Automated cherry pick of #1740

- src/main/server/serverInfo.ts
The plugin id for playbooks has changed: update the heuristic in the desktop app used to detect same.
None.
This PR was tested on: N/A
N/A
```release-note
NONE
```
> Fix tab opening behaviour for playbooks

- src/main/server/serverInfo.ts
Cherry pick of #1763 on release-5.0.
/cc  @lieut-data
```release-note
NONE
```
> Automated cherry pick of #1763

- src/main/menus/app.ts
- src/main/utils.ts
- src/main/views/teamDropdownView.ts
- src/main/views/viewManager.ts
- src/main/windows/mainWindow.ts
- src/main/windows/windowManager.ts
Cherry pick of #1758 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1758

- src/main/views/viewManager.ts
Cherry pick of #1761 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1761

- src/renderer/components/SettingsPage.tsx
Cherry pick of #1767 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1767

- src/main/windows/mainWindow.ts
In some cases, the app would render outside of the bounds of one of the users monitors if they changed monitor setups while the app was closed. This was caused by us saving the past user's window size in a file. This PR makes sure that the saved bounds are still valid when the app launches, otherwise it will default to default window bounds.
https://mattermost.atlassian.net/browse/MM-38607
Closes #1736 
```release-note
Fixed an issue where the app would render off screen and the user would have trouble getting the window in view.
```
> [MM-38607] Ensure window is inside one of the screen bounds before rendering

- src/main/Validator.ts
Cherry pick of #1764 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1764

- src/main/windows/mainWindow.ts
Cherry pick of #1769 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1769

- src/renderer/css/components/TeamDropdownButton.scss
Cherry pick of #1773 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1773

- package-lock.json
- package.json
- src/main/menus/app.ts
- src/main/utils.ts
- src/main/views/teamDropdownView.ts
- src/main/views/viewManager.ts
- src/main/windows/mainWindow.ts
- src/main/windows/windowManager.ts
The dragging issue on macOS was fixed in Electron, so I've reverted my original workaround and upgraded us to the latest patch. Also fixes the strange dragging experience seem by some on macOS.
https://mattermost.atlassian.net/browse/MM-38936
```release-note
NONE
```
> [MM-38936] Revert #1758, upgrade to Electron 14.1.0

- package-lock.json
- package.json
- src/main/menus/app.ts
- src/main/utils.ts
- src/main/views/teamDropdownView.ts
- src/main/views/viewManager.ts
- src/main/windows/mainWindow.ts
- src/main/windows/windowManager.ts
Cherry pick of #1779 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1779

- .circleci/config.yml
Cherry pick of #1781 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1781

- scripts/generate_release_markdown.sh
Cherry pick of #1775 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1775

- src/main/views/MattermostView.ts
Cherry pick of #1780 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1780

- src/main/views/modalView.ts
- src/main/views/teamDropdownView.ts
- src/main/views/viewManager.ts
Cherry pick of #1792 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1792

- src/common/config/index.ts
- src/main/main.ts
Cherry pick of #1845 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1845

- src/main/main.ts
Cherry pick of #1848 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1848

- e2e/specs/server_management/add_server_modal.test.js
Duplicate test case no longer needed.
```release-note
NONE
```
> Remove unnecessary test case

- package.json
- src/main/main.ts
- src/main/menus/app.test.js
- src/main/menus/app.ts
- src/main/menus/tray.test.js
- src/main/menus/tray.ts
Unit tests for `main/menus`
https://mattermost.atlassian.net/browse/MM-40316
```release-note
NONE
```
> [MM-40316] Unit tests for main/menus

- src/main/notifications/index.test.js
- src/main/notifications/index.ts
Unit tests for `main/notifications`
https://mattermost.atlassian.net/browse/MM-40327
```release-note
NONE
```
> [MM-40327] Unit tests for main/notifications

- package.json
- src/main/authManager.test.js
- src/main/authManager.ts
- src/main/certificateManager.test.js
- src/main/certificateManager.ts
Unit tests for `main/authManager` and `main/certificateManager`.
https://mattermost.atlassian.net/browse/MM-40146
https://mattermost.atlassian.net/browse/MM-40147
```release-note
NONE
```
> [MM-40146][MM-40147] Unit tests for authManager and certificateManager

- package.json
- src/main/allowProtocolDialog.test.js
- src/main/allowProtocolDialog.ts
Had to refactor `allowProtocolDialog` into a class to make testing make more sense. Might have to do the same for a few people files. Added unit tests as well.
https://mattermost.atlassian.net/browse/MM-40266
```release-note
NONE
```
> [MM-40266] Refactor and tests for main/allowProtocolDialog

- package.json
- src/main/server/serverAPI.test.js
Unit tests for main/server
https://mattermost.atlassian.net/browse/MM-40328
```release-note
NONE
```
> [MM-40328] Unit tests for main/server

- e2e/specs/server_management/edit_server_modal.test.js
> Disable flaky test

- src/main/appState.ts
- src/main/views/MattermostView.ts
When refactoring some things for testing, I broke notification and badges. This PR fixes those.
https://mattermost.atlassian.net/browse/MM-40635
```release-note
NONE
```
> [MM-40635] Fix notifications and badges broken during test changes

- src/main/views/MattermostView.ts
Cherry pick of #1886 on release-5.0.
```release-note
NONE
```
> Automated cherry pick of #1886

- src/common/config/defaultPreferences.ts
- src/common/config/index.test.js
- src/common/config/index.ts
- src/common/config/migrationPreferences.test.js
- src/common/config/migrationPreferences.ts
- src/main/Validator.test.js
- src/main/Validator.ts
- src/main/constants.ts
- src/main/tray/tray.ts
- src/renderer/components/SettingsPage.tsx
- src/types/config.ts
A few tray related fixes for Windows:
- Added the option to override the tray icon colour
- Re-added 'Minimize to tray'
Also added a mechanism we can use to migrate config items to different values when things change in the app.
https://mattermost.atlassian.net/browse/MM-36058
https://mattermost.atlassian.net/browse/MM-40572
Closes https://github.com/mattermost/desktop/issues/1601
Closes https://github.com/mattermost/desktop/issues/1687
```release-note
Restored 'Minimize to tray' option for Windows, added ability to override tray icon colour
```
> [MM-36058][MM-40572] Tray fixes

- .circleci/config.yml
- e2e/modules/environment.js
- e2e/specs/menu_bar/dropdown.test.js
- e2e/specs/menu_bar/view_menu.test.js
- e2e/specs/server_management/edit_server_modal.test.js
- e2e/specs/server_management/remove_server_modal.test.js
- e2e/specs/settings.test.js
- e2e/specs/startup/config.test.js
- package-lock.json
- package.json
- scripts/setup_e2e_docker.js
This PR adds configuration for the CI to run a version of Mattermost in Docker for the E2E tests to run against.
Also I've enabled a test to check that.
https://mattermost.atlassian.net/browse/MM-39852
```release-note
NONE
```
> [MM-39852] Setup docker image to run in CI for E2E

- e2e/specs/menu_bar/file_menu.test.js
feat: Added e2e test for opening settings modal for shortcut
Fixes https://github.com/mattermost/desktop/issues/1907
```release-note
```
> [MM-39738] E2E test for Open Settings modal using keyboard shortcuts

- e2e/specs/mattermost/copy_link.test.js
Fixes https://github.com/mattermost/desktop/issues/1891
```release-note
NONE
```
> test:MM-T125 Copy Link can be used from channel LHS

- e2e/specs/menu_bar/history_menu.test.js
Fixes https://github.com/mattermost/desktop/issues/1892
```release-note
NONE
```
> test: Added test for back and forward in history menu

- e2e/specs/menu_bar/file_menu.test.js
test:Signin to another server open using menu bar
Fixes https://github.com/mattermost/desktop/issues/1894
```release-note
NONE
```
> test:Signin to another server open using menu bar

- e2e/specs/menu_bar/edit_menu.test.js
test: Undo in the menu bar
Fixes https://github.com/mattermost/desktop/issues/1896
- [x ] Added or updated unit tests (required for all new features)
```release-note
NONE
```
> test: Undo in the menu bar

- e2e/specs/menu_bar/file_menu.test.js
End to end test to check for closing the app from the menu
https://github.com/mattermost/desktop/issues/1895
MacOS, Ubuntu, Windows
None
```release-note
NONE
```
> test: MM-T806 Exit in the Menu Bar

- e2e/specs/menu_bar/edit_menu.test.js
test:MM-T812 Select All in the Menu Bar
Fixes https://github.com/mattermost/desktop/issues/1899
```release-note
NONE
```
> test:MM-T812 Select All in the Menu Bar

- e2e/specs/menu_bar/window_menu.test.js
MM-T824/MM-T825 Minimize/Close in the Menu Bar
Fixes https://github.com/mattermost/desktop/issues/1903
```release-note
NONE
```
> test:MM-T824/MM-T825 Minimize/Close in the Menu Bar

- e2e/specs/menu_bar/edit_menu.test.js
test:MM-T808 Redo in the Menu Bar
Fixes https://github.com/mattermost/desktop/issues/1897
```release-note
NONE
```
> test:MM-T808 Redo in the Menu Bar

- e2e/specs/menu_bar/view_menu.test.js
test:MM-T816 Toggle Full Screen in the Menu Bar
Fixes https://github.com/mattermost/desktop/issues/1900
```release-note
NONE
```
> test:MM-T816 Toggle Full Screen in the Menu Bar

- e2e/specs/menu_bar/view_menu.test.js
Fixes https://github.com/mattermost/desktop/issues/1901
```release-note
NONE
```
> test:MM-T817/MM-T818/MM-T819 Zooming in the Menu Bar

- e2e/specs/server_management/header.test.js
e2e test to check minimize/maximize of app when double clicking on header
Fixes https://github.com/mattermost/desktop/issues/1914
This PR was tested on: Ubuntu 20.04.3
```release-note
NONE
```
> [MM-T2637] Double-Clicking on the header should minimize/maximize the app

- e2e/specs/menu_bar/view_menu.test.js
e2e test to check if the Developer tools are toggled on successfully through the Menu Bar and using keyboard shortcuts.
Fixes #1902
- macOS Big Sur v11.6.2
- Windows 10 
```release-note
NONE
```
> [MM-T820][MM-T821] Toggle developer Tools in the Menu Bar

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/troubleshooting-question.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
- SECURITY.md
- package.json
- scripts/generate_release_markdown.sh
- src/common/config/buildConfig.ts
> Legacy domain URL updates

- .circleci/config.yml
Add MSI installer to nightly build
Fix issue with upload to S3
```release-note
NONE
```
> Update nightly job

- .circleci/config.yml
- scripts/Makefile.ps1
- scripts/cp_artifacts.sh
- Fix paths for MSI build
- Change the artifacts copy script
```release-note
NONE
```
> Changes for MSI build for autoupdater

- .circleci/config.yml
One more CircleCI fix:
- Disable nightly for `build_and_test`
- Turn off `mac_installer`
> CircleCI fix

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/troubleshooting-question.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
- SECURITY.md
- package.json
- scripts/generate_release_markdown.sh
- src/assets/linux/README.md
- src/common/config/buildConfig.ts
Updated in-product links to legacy domain about.mattermost.com.
```release-note
Updated in-product links to legacy domain about.mattermost.com
```
> MM-41988 Updated links to legacy domain about.mm.com

- package.json
Adding separate builds for .deb and .rpm for CI.
```release-note
NONE
```
> Add separate deb and rpm builds for CI

- .circleci/config.yml
> Fix a typo in the nightly build

- .circleci/config.yml
- package-lock.json
- package.json
> Fix nightly build again

- e2e/specs/settings/keyboard_shortcuts.test.js
- src/renderer/components/SettingsPage.tsx
E2E tests for the Settings page, specifically Keyboard Shortcuts.
https://mattermost.atlassian.net/browse/MM-39673
Closes #1905
```release-note
NONE
```
> [MM-39673][MM-T1288] E2E Test: Keyboard Shortcuts in Settings Page

- e2e/specs/mattermost/back_button.test.js
- package-lock.json
- package.json
- src/common/utils/url.ts
- src/main/utils.test.js
- src/main/utils.ts
- src/main/views/MattermostView.test.js
- src/main/views/MattermostView.ts
- src/main/windows/windowManager.test.js
- src/main/windows/windowManager.ts
E2E test for the Back Button. Also some fixes since the Back button wasn't working as expected by the test case.
https://mattermost.atlassian.net/browse/MM-39793
Closes https://github.com/mattermost/desktop/issues/1912
```release-note
NONE
```
> [MM-39793][MM-T2633] E2E Test: Use back button to return to the desktop app login - and fixes

- e2e/specs/server_management/drag_and_drop.test.js
E2E test for dragging and dropping servers and tabs.
https://mattermost.atlassian.net/browse/MM-39794
Closes https://github.com/mattermost/desktop/issues/1913
```release-note
NONE
```
> [MM-39794] E2E Test: Drag and Drop

- e2e/specs/focus.test.js
E2E tests for checking return to focus when windows/modals are closed, and when servers are switched.
https://mattermost.atlassian.net/browse/MM-39747
Closes https://github.com/mattermost/desktop/issues/1908
```release-note
NONE
```
> [MM-39747][MM-T1315][MM-T1316][MM-T1317] E2E Test: Ensure focus is returned to Mattermost view

- e2e/specs/popup.test.js
- e2e/specs/settings/keyboard_shortcuts.test.js
E2E tests for popup windows:
- Cut/Copy/Paste/Select All in the window
- Stop the window from going Back/Forward in history
https://mattermost.atlassian.net/browse/MM-39796
https://mattermost.atlassian.net/browse/MM-39782
Closes #1915
Closes #1910
```release-note
NONE
```
> [MM-39796][MM-39872][MM-T1659][MM-T2827] E2E Tests for Popups

- .circleci/config.yml
> Add MAS to release pipeline

- .circleci/config.yml
- scripts/generate_release_markdown.sh
> Fixes to the release script

- NOTICE.txt
Cherry pick of #2060 on release-5.1.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #2060

- src/common/config/defaultPreferences.ts
> Fix download folder for MAS

- package.json
> Fix version numbers

- package.json
Cherry pick of #2064 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2064

- src/common/config/defaultPreferences.ts
Cherry pick of #2063 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2063

- .circleci/config.yml
- scripts/generate_release_markdown.sh
Cherry pick of #2059 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2059

- src/common/config/defaultPreferences.ts
- src/main/app/initialize.ts
- src/types/config.ts
As per MAS guidelines, we're not allowed to prescribe the default download location for users, so we've removed it for that build.
https://mattermost.atlassian.net/browse/MM-43657
```release-note
NONE
```
> MAS: remove default download location

- .gitlab-ci.yml
- Makefile
Cherry pick of #2068 on release-5.1.
/cc  @pfltdv
```release-note
NONE
```
> Automated cherry pick of #2068

- src/common/config/defaultPreferences.ts
- src/main/app/initialize.ts
- src/types/config.ts
Cherry pick of #2070 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2070

- package-lock.json
- package.json
Updating to electron-builder v23.0.8, where the issue with bad permission in the tar releases has been fixed.
https://mattermost.atlassian.net/browse/MM-30272
```release-note
NONE
```
> [MM-30272] Update to electron builder v23.0.8

- package-lock.json
- package.json
Cherry pick of #2073 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2073

- .circleci/config.yml
- scripts/generate_release_markdown.sh
Cherry pick of #2075 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2075

- src/renderer/components/MainPage.tsx
- src/renderer/css/components/UpgradeButton.scss
Cherry pick of #2080 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2080

- src/main/windows/windowManager.test.js
- src/main/windows/windowManager.ts
- src/renderer/components/SettingsPage.tsx
Cherry pick of #2088 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2088

- src/common/config/index.ts
Cherry pick of #2093 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2093

- src/main/app/utils.ts
Cherry pick of #2099 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2099

- src/main/app/utils.test.js
> Broke a test

- src/main/app/utils.test.js
Cherry pick of #2101 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2101

- src/renderer/components/NewTeamModal.tsx
Cherry pick of #2104 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2104

- .circleci/config.yml
Cherry pick of #2114 on release-5.1.
/cc  @elyscape
```release-note
NONE
```
> Automated cherry pick of #2114

- resources/windows/gpo/en-US/mattermost.adml
- resources/windows/gpo/mattermost.admx
Update Version within GPO to the correct Desktop App version.
```release-note
NONE
```
> Update GPO to reflect right version

- resources/windows/gpo/en-US/mattermost.adml
- resources/windows/gpo/mattermost.admx
Cherry pick of #2110 on release-5.1.
/cc  @JtheBAB
```release-note
NONE
```
> Automated cherry pick of #2110

- src/common/tabs/BaseTabView.ts
- src/main/views/MattermostView.ts
- src/main/views/viewManager.test.js
- src/main/views/viewManager.ts
A recent PR caused an issue with changing servers and tabs, effectively making it impossible to do so. This PR makes a few fixes to ensure that we can still do that.
Reported here: https://community-daily.mattermost.com/core/pl/98do1n9ey38k9cp83owxqspbwe
https://mattermost.atlassian.net/browse/MM-44541
```release-note
NONE
```
> [MM-44541] Fix issue with changing servers and tabs

- src/main/windows/mainWindow.ts
- src/main/windows/windowManager.ts
Cherry pick of #2134 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2134

- electron-builder.json
- scripts/afterbuild.js
- scripts/generate_release_markdown.sh
- src/common/config/index.ts
Cherry pick of #2132 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2132

- src/main/app/app.test.js
- src/main/app/app.ts
- src/main/views/MattermostView.test.js
- src/main/views/MattermostView.ts
Cherry pick of #2153 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2153

- src/renderer/modals/certificate/certificateModal.tsx
Cherry pick of #2162 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2162

- e2e/modules/environment.js
- e2e/specs/focus.test.js
- e2e/specs/mattermost/back_button.test.js
Cherry pick of #2169 on release-5.1.
```release-note
NONE
```
> Automated cherry pick of #2169

- src/main/views/viewManager.test.js
- src/main/views/viewManager.ts
When removing a server, the app should always switch to another server or show the new server modal. This wasn't happening correctly due to the use of an old config, so I've switch it around to make sure it's using the updated config.
https://mattermost.atlassian.net/browse/MM-44932
```release-note
NONE
```
> [MM-44932] Fixed issue where deleting a server doesn't switch to another server (or show the new server modal)

- scripts/patch_updater_yml.sh
Made a change that broke the patch script for auto-updater files, fix is here.
https://mattermost.atlassian.net/browse/MM-45519
```release-note
NONE
```
> [MM-45519] Fix auto updater file patch script

- .circleci/config.yml
- package-lock.json
- package.json
The mac nightly build is having issues after installing `mmjstool`. Looks like it needed an update.
```release-note
NONE
```
> Fix mac nightly build

- e2e/modules/environment.js
- src/common/utils/util.ts
- src/main/app/utils.test.js
- src/main/app/utils.ts
- src/renderer/modals/login/login.tsx
- src/renderer/modals/login/loginModal.tsx
- src/renderer/modals/permission/permission.tsx
- src/renderer/modals/permission/permissionModal.tsx
A couple of the modals were not working correctly with the i18n changes, so I've made a couple fixes.
```release-note
NONE
```
> Fix some issues caused by i18n addition

- e2e/specs/mattermost/back_button.test.js
- e2e/specs/menu_bar/dropdown.test.js
- e2e/specs/menu_bar/view_menu.test.js
- e2e/specs/menu_bar/window_menu.test.js
- e2e/specs/server_management/add_server_modal.test.js
- e2e/specs/server_management/drag_and_drop.test.js
- e2e/specs/server_management/header.test.js
- e2e/specs/server_management/long_server_name.test.js
- e2e/specs/settings.test.js
Some of the test cases in our E2E environment did not match the amount of steps in Zephyr Scale. I have corrected some of the tests in Zephyr Scale, and the rest I have modified here so that everything matches and reporting should now be correct.
https://mattermost.atlassian.net/browse/MM-46535
```release-note
NONE
```
> [MM-46535] Fix E2E tests for reporting purposes

- .editorconfig
- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- src/renderer/index.html
Added recommended VSCode extensions:
- Code Spell check (for indicating spellcheck issues)
- i18n-ally for translations (see accepted words in `.vscode/settings.json`)
- EditorConfig
Also added 
```
"editor.codeActionsOnSave": {
"source.fixAll.eslint": true
},
```
to format the files onSave based on the eslint rules
```release-note
NONE
```
> Add recommended VSCode extensions

- .vscode/settings.json
- src/main/windows/windowManager.ts
> Fix issue with downloads position after window (un)maximize

- package-lock.json
- package.json
- src/renderer/components/LoadingAnimation/LoadingIcon.tsx
Cherry pick of #2270 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2270

- .circleci/config.yml
Cherry pick of #2277 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2277

- scripts/Makefile.ps1
Cherry pick of #2280 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2280

- scripts/Makefile.ps1
Cherry pick of #2284 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2284

- src/main/downloadsManager.ts
> Fix issue where update progress was not displayed

- src/main/downloadsManager.ts
Cherry pick of #2286 on release-5.2.
/cc  @tboulis
```release-note
NONE
```
> Automated cherry pick of #2286

- src/main/preload/mainWindow.js
- src/renderer/components/MainPage.tsx
Cherry pick of #2293 on release-5.2.
/cc  @tboulis
```release-note
NONE
```
> Automated cherry pick of #2293

- src/main/menus/app.test.js
- src/main/menus/app.ts
Cherry pick of #2301 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2301

- src/main/downloadsManager.test.js
- src/main/downloadsManager.ts
Cherry pick of #2311 on release-5.2.
/cc  @tboulis
```release-note
NONE
```
> Automated cherry pick of #2311

- .circleci/config.yml
Cherry pick of #2323 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2323

- src/common/JsonFileManager.ts
- src/common/constants.ts
- src/main/autoUpdater.ts
- src/main/downloadsManager.ts
- src/renderer/components/DownloadsDropdown/FileSizeAndStatus.tsx
- src/renderer/downloadsDropdown.tsx
Cherry pick of #2326 on release-5.2.
/cc  @tboulis
```release-note
NONE
```
> Automated cherry pick of #2326

- e2e/modules/utils.js
Cherry pick of #2329 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2329

- src/main/downloadsManager.ts
- src/main/windows/windowManager.ts
2 fixes to downloads, see tickets.
https://mattermost.atlassian.net/browse/MM-48017
https://mattermost.atlassian.net/browse/MM-45980
```release-note
NONE
```
> Downloads fixes

- src/main/downloadsManager.ts
- src/main/windows/windowManager.ts
Cherry pick of #2331 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2331

- resources/windows/gpo/README.md
Add Readme file with instructions on how to use GPO for development on Windows
```release-note
NONE
```
> Add readme file for GPO

- src/main/downloadsManager.ts
Cherry pick of #2357 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2357

- electron-builder.json
Cherry pick of #2380 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2380

- src/main/views/MattermostView.ts
When the remote entry script is loaded, since it can't have a unique id attached to it for predictability reasons, it will be cached by the browser, and anytime the app is rebuilt there will be chunk loading errors since it's trying to load the old app.
This PR forces the `Cache-Control` header for the remote entry script to be `no-cache` so that the Chromium process won't ever cache that script and it will always know when to load a fresh version of the app.
https://mattermost.atlassian.net/browse/MM-48289
```release-note
NONE
```
> [MM-48289] Disable caching on the remote_entry script once it's loaded

- package-lock.json
- package.json
Bumping master to v5.3.0
```release-note
NONE
```
> Bump version to v5.3.0

- src/main/app/intercom.ts
Cherry pick of #2408 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2408

- electron-builder.json
Cherry pick of #2413 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2413

- package-lock.json
- package.json
In the context of upgrading dependencies of the desktop app, this PR upgrades playwright to its latest version.
https://mattermost.atlassian.net/browse/MM-48733
```release-note
NONE
```
> [MM-48733] upgrade playwright

- e2e/specs/downloads/downloads_dropdown_items.test.js
- src/renderer/css/downloadsDropdown.scss
This PR fixes e2e tests for downloads dropdown item, fixing a changed selector.
https://mattermost.atlassian.net/browse/MM-48685
```release-note
NONE
```
> [MM-48685] Fix failing downloads dropdown items tests

- src/main/app/intercom.test.js
- src/main/menus/app.ts
Cherry pick of #2434 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2434

- .circleci/config.yml
Cherry pick of #2437 on release-5.2.
```release-note
NONE
```
> Automated cherry pick of #2437

- e2e/specs/downloads/downloads_dropdown_items.test.js
- src/renderer/css/downloadsDropdown.scss
Cherry pick of #2431 on release-5.2.
/cc  @m1lt0n
```release-note
NONE
```
> Automated cherry pick of #2431

- .circleci/config.yml
- e2e/specs/downloads/downloads_manager.test.js
- e2e/specs/startup/app.test.js
- src/main/diagnostics/steps/internal/loggerHooks.test.js
- src/main/diagnostics/steps/internal/obfuscators.ts
- src/main/windows/windowManager.test.js
Some of the unit tests had been failing on Windows, even though they were passing on CI (running Linux).
Because of this, it made sense to me to add a test step to the Windows and Mac builds as well, just to make sure we catch any weirdness between OSes.
I've also fixed what I could based on what failed locally for me.
```release-note
NONE
```
> Fixed some unit tests and add test step to run on Windows/Mac builds

- .circleci/config.yml
- scripts/Makefile.ps1
> Proper MSI fix

- src/main/server/serverAPI.ts
- src/main/views/MattermostView.ts
- src/main/webRequest/webRequestHandler.ts
- src/main/webRequest/webRequestManager.ts
- src/main/windows/windowManager.ts
One thing we require to do CORS changes for the changed origin is to allow us to change the status line.
This PR makes that change.
```release-note
NONE
```
> Allow for changing of status lint, fix lint issues

- src/common/communication.ts
- src/main/preload/downloadsDropdown.js
- src/main/views/downloadsDropdownView.ts
- src/renderer/components/DownloadsDropdown/DownloadsDropdownItemFile.tsx
When clicking on a downloaded file, postMessage with `DOWNLOADS_DROPDOWN_OPEN_FILE` type instead of `DOWNLOADS_DROPDOWN_SHOW_FILE_IN_FOLDER` type.
Fixes https://github.com/mattermost/mattermost-server/issues/21645
Jira: https://mattermost.atlassian.net/browse/MM-48363
```release-note
Default to opening a file when it is clicked from the download list
```
> [MM-48363] Default to opening a file when it is clicked from the download list

- scripts/msi_installer.wxs
Update Display Name to Mattermost Desktop to reflect the real name. Sorry don't know where to change the exe builder :/
```release-note
NONE
```
> Update Display Name for MSI

- package-lock.json
> Run npm i to save exact version of jest

- src/common/communication.ts
- src/main/preload/callsWidget.js
- src/main/windows/callsWidgetWindow.test.js
- src/main/windows/callsWidgetWindow.ts
- src/main/windows/windowManager.test.js
- src/main/windows/windowManager.ts
- src/types/calls.ts
Cherry pick of #2558 on release-5.3.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #2558

- src/main/preload/callsWidget.js
- src/main/preload/mattermost.js
- src/main/utils.ts
- src/main/windows/callsWidgetWindow.test.js
- src/main/windows/callsWidgetWindow.ts
- src/main/windows/windowManager.test.js
- src/main/windows/windowManager.ts
- src/types/calls.ts
Cherry pick of #2556 on release-5.3.
/cc  @streamer45
```release-note
NONE
```
> Automated cherry pick of #2556

- src/main/views/MattermostView.ts
stumbled upon that while debugging a problem with a community user
```release-note
```
> Fix wording in error message

- .github/workflows/nightly-browser-view.yml
- .github/workflows/nightly-rainforest.yml
- Add missing `npm ci` step
- Removed dependency
```release-note
```
> fix nightly builds

- .github/actions/patch-nightly-version/action.yaml
- .github/workflows/nightly-browser-view.yml
- .github/workflows/nightly-rainforest.yml
- Added missing patch version
- Fix patch action for windows by using the env var
```release-note
```
> Nightly builds fix

- .github/workflows/nightly-browser-view.yml
- .github/workflows/nightly-rainforest.yml
Added missing yq package 
```release-note
```
> Add missing yq for windows builds on nightly

- .github/workflows/release.yaml
We do not want to run the release pipeline on branches .
We only run when a tag is created
```release-note
```
> Run pipeline on tags only

- package-lock.json
- package.json
> Bump version to v5.4.0

- .github/workflows/nightly-rainforest.yml
- Add missing checkout step for upload jobs
- Fixed folder name upon rename 
```release-note
```
> Add missing checkout/patch . Fixed folder name

- .github/workflows/nightly-browser-view.yml
- .github/workflows/nightly-rainforest.yml
- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
Fix release creation with gh cli . 
Tested locally with command: 
```
gh release create --draft --prerelease --verify-tag -F release-notes.md --target fa2c9d8f7ed6abbd2dfa506482f4fa8e69a93d6d --title "v5.3.0-rc.5 (2023-03-13)" v5.3.0-rc.5 ./ghr-dist/*
```
Relevant release : https://github.com/mattermost/desktop/releases/tag/untagged-b4278592cf2a2068f69a
```release-note
```
> Replace release creation with gh CLI

- .github/workflows/nightly-builds.yaml
Fix secrets inheritance for within the company 
```release-note
```
> fix secret inheritance and naming convention for consistency

- .github/workflows/release.yaml
> Add MM_WIN_INSTALLERS to release pipeline

- src/main/views/webContentEvents.ts
Cherry pick of #2616 on release-5.3.
```release-note
NONE
```
> Automated cherry pick of #2616

- package-lock.json
- package.json
- src/renderer/components/ConfigureServer.tsx
- src/renderer/components/NewTeamModal.tsx
Cherry pick of #2617 on release-5.3.
```release-note
NONE
```
> Automated cherry pick of #2617

- .github/workflows/nightly-browser-view.yml
- .github/workflows/nightly-main.yml
- .github/workflows/nightly-rainforest.yml
- We need clear separation of the packages not to override one another since reusable workflows were using the same artifact name
Tested [here](https://github.com/toninis/test-actions/actions/runs/4423779890)
```release-note
```
> Separate artifact names since we merged the nightly builds for consistency

- .github/workflows/nightly-builds.yaml
> HOTFIX nightly workflow name

- scripts/release.sh
Cherry pick of #2624 on release-5.3.
```release-note
NONE
```
> Automated cherry pick of #2624

- src/main/windows/callsWidgetWindow.test.js
- src/main/windows/callsWidgetWindow.ts
- src/main/windows/windowManager.ts
- src/types/calls.ts
Cherry pick of #2630 on release-5.3.
/cc  @streamer45
```release-note
NONE
```
> Automated cherry pick of #2630

- src/common/utils/url.test.js
- src/common/utils/url.ts
Manual cherry-picking #2629 to `release-5.3` branch.
```release-note
NONE
```
> [MM-51527] Cherrypick to  `release-5.3`

- src/main/windows/callsWidgetWindow.test.js
- src/main/windows/callsWidgetWindow.ts
- Cherrypick of #2635 
- https://mattermost.atlassian.net/browse/MM-51535
```release-note
Calls: Fixed an issue where a certain URL form would allow the call's widget to open a popup window that could navigate to an arbitrary URL
```
> MM-51535 - Calls: Fix unrestricted redirect from calls widget (#2635)

- package-lock.json
- package.json
This fixes the E2E test problem. 
```release-note
```
> Upgrade node-abi

- src/main/windows/mainWindow.ts
One more resize issue: snapping to the side on Linux. Most of these have been the result of the wrong window bounds being emitted on resize, so I've just forced a timeout for it every time.
```release-note
NONE
```
> Fixed Linux snapping, performance stuff

- package-lock.json
- package.json
> Bump master to v5.5.0

- .github/workflows/release.yaml
- scripts/generate_release_post.sh
Cherry pick of #2736 on release-5.4.
```release-note
NONE
```
> Automated cherry pick of #2736

- src/main/notifications/index.test.js
- src/main/notifications/index.ts
Cherry pick of #2745 on release-5.4.
```release-note
NONE
```
> Automated cherry pick of #2745

- src/common/servers/serverManager.test.js
- src/common/servers/serverManager.ts
- src/main/views/viewManager.test.js
- src/main/views/viewManager.ts
Cherry pick of #2748 on release-5.4.
```release-note
NONE
```
> Automated cherry pick of #2748

- scripts/generate_release_post.sh
Cherry pick of #2752 on release-5.4.
```release-note
NONE
```
> Automated cherry pick of #2752

- .github/workflows/build-for-pr.yml
- .github/workflows/ci.yaml
- .github/workflows/nightly-main.yml
- .github/workflows/nightly-rainforest.yml
- .github/workflows/release.yaml
- scripts/Makefile.ps1
Trying to fix a Windows CI issue.
```release-note
NONE
```
> Force install of ARM64 Electron headers

- webpack.config.base.js
> Have all nightly branches include React Developer Tools

- package-lock.json
- package.json
- src/main/app/initialize.test.js
- src/main/app/initialize.ts
Some errors are popping up causing issues with React Developer Tools. This PR switches over to a different package to load them that seems to solve the issue.
```release-note
NONE
```
> Fix React Developer Tools for some users

- package-lock.json
- package.json
> Bump to version 5.6

- src/renderer/components/MainPage.tsx
Cherry pick of #2821 on release-5.5.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #2821

- src/common/Validator.ts
- src/common/utils/url.test.js
- src/common/utils/url.ts
- src/main/windows/callsWidgetWindow.test.js
Cherry pick of #2831 on release-5.5.
```release-note
NONE
```
> Automated cherry pick of #2831

- src/common/log.ts
Cherry pick of #2830 on release-5.5.
```release-note
NONE
```
> Automated cherry pick of #2830

- src/common/communication.ts
- src/main/app/initialize.ts
- src/main/app/intercom.ts
- src/main/preload/mattermost.js
Cherry pick of #2829 on release-5.5.
```release-note
NONE
```
> Automated cherry pick of #2829

- package-lock.json
- package.json
Manual cherry-pick of #2837 
```release-note
NONE
```
> [MM-54509] Upgrade to Electron v26.2.1 (#2837)

- .github/workflows/release.yaml
- scripts/generate_release_post.sh
Adding debugging for the notification script ahead of v5.5.1-rc.1 to see if we can figure out why it's not working.
```release-note
NONE
```
> Add debugging for notification script

- .github/workflows/release.yaml
- scripts/generate_release_post.sh
Cherry pick of #2840 on release-5.5.
```release-note
NONE
```
> Automated cherry pick of #2840

- .github/workflows/release.yaml
- scripts/generate_release_post.sh
This reverts commit 55fe6ecec99e9fa2cdfd0c077769c8f54c7e8a39.
```release-note
NONE
```
> Revert "Add debugging for notification script (#2840)"

- .github/workflows/release.yaml
- scripts/generate_release_post.sh
Cherry pick of #2842 on release-5.5.
```release-note
NONE
```
> Automated cherry pick of #2842

- .github/workflows/release.yaml
Cherry pick of #2846 on release-5.5.
```release-note
NONE
```
> Automated cherry pick of #2846

- i18n/de.json
- i18n/pl.json
- i18n/ru.json
- i18n/tr.json
> Cherrypick translations (#2844)

- src/main/permissionsManager.test.js
- src/main/permissionsManager.ts
Cherry pick of #2849 on release-5.5.
```release-note
NONE
```
> Automated cherry pick of #2849

- src/common/servers/serverManager.ts
Cherry pick of #2851 on release-5.5.
```release-note
NONE
```
> Automated cherry pick of #2851

- package.json
- src/main/app/intercom.ts
- src/main/autoUpdater.test.ts
- src/main/autoUpdater.ts
- src/main/downloadsManager.ts
- src/main/notifications/Download.ts
- src/main/notifications/Mention.ts
- src/main/notifications/index.test.js
- src/main/notifications/index.test.ts
- src/main/notifications/index.ts
Notifications are created, but not stored anywhere. That makes the GC to go through them before the notifications get clicked. Therefore, the notification is not listened by anyone.
This PR makes sure the mention is always referenced until the notification disappears.
Fix https://mattermost.atlassian.net/browse/MM-54410
```release-note
Fix some notifications no navigating to the channel
```
> Fix notifications not working

- i18n/i18n.ts
Adding Vietnamese as beta
Related to https://github.com/mattermost/mattermost/pull/24074/ and https://github.com/mattermost/mattermost-mobile/pull/7462
```release-note
Adding Vietnamese as a beta language
```
> adding Vietnamese language as beta

- package-lock.json
- package.json
Update `node-gyp` to v10 to patch this issue in CI: https://github.com/nodejs/node-gyp/issues/2869
https://mattermost.atlassian.net/browse/MM-55466
```release-note
NONE
```
> [MM-55466] Update to node-gyp v10 to fix Python script error

- package-lock.json
- package.json
Cherry pick of #2909 on release-5.6.
```release-note
NONE
```
> Automated cherry pick of #2909

- package-lock.json
- package.json
Bump to version v5.7
```release-note
NONE
```
> Bump to version v5.7

- NOTICE.txt
Cherry pick of #2912 on release-5.6.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #2912

- src/common/appState.ts
Cherry pick of #2921 on release-5.6.
```release-note
NONE
```
> Automated cherry pick of #2921

- .github/workflows/e2e-functional.yml
- package.json
> Test macos e2e

- .github/workflows/e2e-functional.yml
> Draft: test

- .github/workflows/build-for-pr.yml
Currently when we added the label `Build Apps for PR` mattermod picked this up and created the related branches .  
Related core [here](https://github.com/mattermost/mattermost-mattermod/blob/master/server/build_apps.go) . 
We will remove the related code which was used for mobile and desktop repositories in favor of the labeled pull request event. 
- Check status will be generated as before on the PR level
https://mattermost.atlassian.net/browse/CLD-5751
```release-note
NONE
```
> fix: Use labeled event from pull request to trigger apps build

- .github/workflows/e2e-functional.yml
fix a typo to refer the master branch
> Fix push trigger to refer master branch

- package-lock.json
- package.json
Upgrading to Electron v28 for security and performance fixes for v5.7
https://mattermost.atlassian.net/browse/MM-56803
```release-note
Upgrade to Electron v28
```
> [MM-56803] Upgrade to Electron v28.2.2

- package-lock.json
- package.json
> Bump to version 5.8

- package-lock.json
- package.json
Upgrading to Electron v29 to fix an issue with performance profiling.
https://mattermost.atlassian.net/browse/MM-56806
```release-note
Upgrade to Electron v29.0.0
```
> [MM-56806] Upgrade to Electron v29.0.0

- .github/workflows/nightly-main.yml
- .github/workflows/release-mas.yaml
- electron-builder.json
- package.json
> Fix MAS build

- .editorconfig
- .github/workflows/e2e-functional-template.yml
- .github/workflows/e2e-functional.yml
- .github/workflows/nightly-builds.yaml
- e2e/utils/analyze-flaky-test.js
- Refactor E2E functional for readability and reusability
- Introduce new Workflows to be triggered for compatibility matrix testing
https://mattermost.atlassian.net/browse/CLD-7346
```release-note
Introduce Compatibility Matrix Testing
```
> feat: Refactor E2E functional for readability and reusability

- .editorconfig
- .github/workflows/build-for-pr.yml
- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-functional-template.yml
- .github/workflows/e2e-performance.yml
- .github/workflows/nightly-builds.yaml
- .github/workflows/nightly-main.yml
- .github/workflows/nightly-rainforest.yml
- .github/workflows/release-mas.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecards-analysis.yml
- Upgrade all reusable github actions versions to latest 
- Attempt to fix supply chain scorecard pipeline
https://mattermost.atlassian.net/browse/CLD-7346
```release-note
NONE
```
> Upgrade Reusable GitHub actions version

- .github/workflows/compatibility-matrix-testing.yml
- Introduced proper matrix for CMT testing
```release-note
NONE
```
> Minor fixes for the Compatibility Matrix Test

- package-lock.json
Just a quick package update - fixes a vulnerability highlighted by NPM
```release-note
NONE
```
> Small package update

- src/main/windows/mainWindow.ts
On Windows, when the window is maximized, and we restore the window from minimized using the `restore()` command, we often get into a case where the window will not return to its maximized state. This gets the app into a weird state where sometimes users will not be able to re-maximize or may see some whitespace where the app should be.
This PR forces the app to keep track of the maximized state of the main window, and re-enter the maximized state on restore if it was supposed to be there before.
https://mattermost.atlassian.net/browse/MM-57736
```release-note
Fixed an issue where restoring the window from the tray icon could cause a strange state if the window was previously maximized
```
> [MM-57736] Force maximize state when restoring the window

- e2e/specs/focus.test.js
> Fix focus test cases

- .github/workflows/nightly-main.yml
- .github/workflows/nightly-rainforest.yml
- .github/workflows/release.yaml
Migrate to new upload/download action functionality 
```release-note
NONE
```
> fix: Upgrade upload/download actions

- src/main/app/utils.test.js
- src/main/app/utils.ts
Cherry pick of #3017 on release-5.8.
```release-note
NONE
```
> Automated cherry pick of #3017

- package-lock.json
- package.json
> Bump version to v5.9

- electron-builder.json
- scripts/beforepack.js
Cherry pick of #3022 on release-5.8.
```release-note
NONE
```
> Automated cherry pick of #3022

- scripts/beforepack.js
The MAS build has been failing for about a week due to the changes made to make the DEB build work again. This PR should fix that.
```release-note
NONE
```
> Fix script to make directories recursively

- scripts/beforepack.js
Cherry pick of #3027 on release-5.8.
```release-note
NONE
```
> Automated cherry pick of #3027

- src/main/permissionsManager.test.js
- src/main/permissionsManager.ts
Cherry pick of #3032 on release-5.8.
```release-note
NONE
```
> Automated cherry pick of #3032

- src/main/notifications/index.ts
The logging we have for each step of the notification process is insufficient, as we are missing every step where the app might trip up and decide not to show a notification.
This PR beefs up the amount of logging in debug mode (and removes the logging that showed message content).
```release-note
NONE
```
> Improve notification logging

- src/main/app/initialize.test.js
- src/main/app/initialize.ts
- src/main/notifications/index.test.ts
- src/main/notifications/index.ts
Cherry pick of #3053 on release-5.8.
```release-note
NONE
```
> Automated cherry pick of #3053

- src/common/Validator.ts
- src/main/windows/mainWindow.test.js
- src/main/windows/mainWindow.ts
Cherry pick of #3045 on release-5.8.
```release-note
NONE
```
> Automated cherry pick of #3045

- src/main/notifications/index.ts
Cherry pick of #3040 on release-5.8.
```release-note
NONE
```
> Automated cherry pick of #3040

- src/main/notifications/dnd-windows.test.js
- src/main/notifications/dnd-windows.ts
- src/main/notifications/index.ts
Cherry pick of #3060 on release-5.8.
```release-note
NONE
```
> Automated cherry pick of #3060

- api-types/package-lock.json
- api-types/package.json
> Bump api-types and publish

- src/common/config/index.ts
- Update incorrect JSDoc comment in `src/common/config/index.ts`
N/A
N/A
N/A
N/A
```release-note
NONE
```
> Fix outdated JSDoc comment

- package-lock.json
- package.json
Bump to version v5.10
```release-note
NONE
```
> Bump to version v5.10

- .github/workflows/release.yaml
Cherry pick of #3100 on release-5.9.
```release-note
NONE
```
> Automated cherry pick of #3100

- src/main/windows/mainWindow.ts
Cherry pick of #3104 on release-5.9.
```release-note
NONE
```
> Automated cherry pick of #3104

- src/main/windows/mainWindow.ts
Cherry pick of #3108 on release-5.9.
```release-note
NONE
```
> Automated cherry pick of #3108

- src/renderer/css/components/LoadingScreen.css
- src/renderer/css/components/WelcomeScreen.scss
I changed the completely wrong file to fix the issue with the Welcome Screen button hiding, causing the loading screen to look wrong, this PR changes the right file.
https://mattermost.atlassian.net/browse/MM-59252
```release-note
NONE
```
> [MM-59252] Fix loading screen CSS

- src/main/downloadsManager.ts
Cherry pick of #3147 on release-5.9.
```release-note
NONE
```
> Automated cherry pick of #3147

- src/renderer/components/MainPage.tsx
- src/types/window.ts
Cherry pick of #3148 to `release-5.9`
```release-note
NONE
```
> [MM-60605] Cherrypick of (#3148) to `release-5.9`

- .github/workflows/snyk-sbom.yml
Generate SBOM on release
https://mattermost.atlassian.net/browse/SEC-6363
```release-note
NONE
```
> SBOM generation on release

- .github/workflows/snyk-sbom.yml
Cherry pick of #3156 on release-5.9.
/cc  @enzowritescode
```release-note
NONE
```
> Automated cherry pick of #3156

- package-lock.json
- package.json
Bump to version 5.11
```release-note
NONE
```
> Bump to version 5.11

- package-lock.json
- package.json
- src/common/log.ts
Cherry pick of #3173 on release-5.10.
```release-note
NONE
```
> Automated cherry pick of #3173

- src/app/serverViewState.ts
- src/renderer/components/NewServerModal.tsx
- src/renderer/dropdown.tsx
Cherry pick of #3175 on release-5.10.
```release-note
NONE
```
> Automated cherry pick of #3175

- package-lock.json
- package.json
Cherry pick of #3183 on release-5.10.
```release-note
NONE
```
> Automated cherry pick of #3183

- src/main/app/app.ts
- src/main/app/utils.ts
- src/main/views/viewManager.ts
Cherry pick of #3201 on release-5.10.
```release-note
NONE
```
> Automated cherry pick of #3201

- src/main/app/app.ts
- src/main/app/initialize.ts
Cherry pick of #3214 on release-5.10.
```release-note
NONE
```
> Automated cherry pick of #3214

- package-lock.json
- package.json
- patches/electron+33.2.0.patch
Cherry pick of #3232 on release-5.10.
```release-note
NONE
```
> Automated cherry pick of #3232

- src/main/utils.ts
- src/main/windows/mainWindow.test.js
- src/main/windows/mainWindow.ts
Cherry pick of #3157 on release-5.10.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #3157

- electron-builder.json
- patches/app-builder-lib+24.13.3.patch
Manual cherry-pick of #3237, #3238, #3239 to `release-5.10`
Done manually to avoid `patch-package` issues.
```release-note
NONE
```
> Cherry-pick of #3237, #3238, #3239 to `release-5.10`

- .github/workflows/build-for-pr.yml
- .github/workflows/ci.yaml
- .github/workflows/nightly-builds.yaml
- .github/workflows/nightly-main.yml
- .github/workflows/nightly-rainforest.yml
- .github/workflows/release-mas.yaml
- .github/workflows/release.yaml
Cherry pick of #3226 on release-5.9.
```release-note
NONE
```
> Automated cherry pick of #3226

- patches/app-builder-lib+24.13.3.patch
Cherry pick of #3249 on release-5.10.
```release-note
NONE
```
> Automated cherry pick of #3249

- .github/workflows/snyk-sbom.yml
Cherry pick of #3257 on release-5.10.
/cc  @enzowritescode
```release-note
NONE
```
> Automated cherry pick of #3257

- .github/workflows/build-for-pr.yml
- .github/workflows/nightly-main.yml
- .github/workflows/nightly-rainforest.yml
- .github/workflows/release.yaml
- .gitignore
- electron-builder.json
Fix mac build again :cry:
```release-note
NONE
```
> Fix mac build again :sob:

- .github/workflows/e2e-functional.yml
Fix reporting for E2E Functional tests
https://mattermost.atlassian.net/browse/MM-62431
```release-note
NONE
```
> Fix reporting for E2E Functional tests

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/crash_report.yml
Updating the issue template to clarify that reporters should check closed issues as well.
```release-note
NONE
```
> Update issue template to include closed issues

- package-lock.json
- package.json
Bump to version v5.12
```release-note
NONE
```
> Bump to version v5.12

- package-lock.json
- package.json
- patches/electron+34.0.1.patch
Upgrade to Electron v34.0.1
https://mattermost.atlassian.net/browse/MM-62740
```release-note
Upgrade to Electron v34.0.1
```
> [MM-62740] Upgrade to Electron v34.0.1

- package-lock.json
- package.json
- patches/electron+34.0.1.patch
Cherry pick of #3297 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3297

- patches/electron-context-menu+4.0.4.patch
- src/main/contextMenu.ts
Cherry pick of #3291 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3291

- src/renderer/css/components/Input.scss
Cherry pick of #3306 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3306

- src/main/views/viewManager.ts
Cherry pick of #3303 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3303

- patches/electron-context-menu+4.0.4.patch
Cherry pick of #3310 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3310

- e2e/package-lock.json
- package-lock.json
Need to update `cross-spawn` for internal reasons.
https://mattermost.atlassian.net/browse/MM-62859
```release-note
NONE
```
> [MM-62589] Push cross-spawn to v7.0.6

- .github/dependabot.yaml
- Add dependabot configuration for gha 
https://mattermost.atlassian.net/browse/CLD-8903
```release-note
NONE
```
> feat: Add dependabot for gha

- .gitignore
Add aider files to `.gitignore`
NA
```release-note
NONE
```
> Add aider to gitignore

- src/renderer/dropdown.tsx
Cherry pick of #3320 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3320

- scripts/patch_updater_yml.sh
Cherry pick of #3314 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3314

- e2e/package-lock.json
- package-lock.json
Cherry pick of #3319 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3319

- src/main/views/MattermostWebContentsView.test.js
- src/main/views/MattermostWebContentsView.ts
Cherry pick of #3356 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3356

- src/main/views/MattermostWebContentsView.ts
Cherry pick of #3365 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3365

- package-lock.json
- package.json
> Bump to version 5.13

- .github/workflows/build-for-pr.yml
- .github/workflows/nightly-main.yml
- .github/workflows/nightly-rainforest.yml
- .github/workflows/release-mas.yaml
- .github/workflows/release.yaml
> Fix mac build again

- .github/workflows/snyk-sbom.yml
- Allow manual trigger of SBOM generation
https://mattermost.atlassian.net/browse/SEC-7811
```release-note
NONE
```
> Manual SBOM trigger

- .github/workflows/snyk-sbom.yml
- Bump Snyk SBOM version (minor fix)
NA
```release-note
NONE
```
> Bump sbom version

- src/main/views/viewManager.ts
Cherry pick of #3409 on release-5.12.
```release-note
NONE
```
> Automated cherry pick of #3409

- scripts/generate_release_post.sh
Cherry pick of #3411 on release-5.12.
```release-note
NONE
```
> Automated cherry pick of #3411

- src/renderer/components/SettingsModal/components/ServerSetting.tsx
Cherry pick of #3430 on release-5.12.
```release-note
NONE
```
> Automated cherry pick of #3430

- src/main/views/viewManager.ts
Cherry pick of #3429 on release-5.12.
```release-note
NONE
```
> Automated cherry pick of #3429

- .github/workflows/ci.yaml
Cherry pick of #3394 on release-5.11.
/cc  @yasserfaraazkhan
```release-note
NONE
```
> Automated cherry pick of #3394

- .github/workflows/build-for-pr.yml
- .github/workflows/nightly-main.yml
- .github/workflows/nightly-rainforest.yml
- .github/workflows/release-mas.yaml
- .github/workflows/release.yaml
Cherry pick of #3400 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3400

- scripts/patch_updater_yml.sh
Cherry pick of #3436 on release-5.11.
```release-note
NONE
```
> Automated cherry pick of #3436

- patches/electron-context-menu+4.0.4.patch
Cherry pick of #3441 on release-5.12.
```release-note
NONE
```
> Automated cherry pick of #3441

- NOTICE.txt
Cherry pick of #3464 on release-5.13.
/cc  @unified-ci-app[bot]
```release-note
NONE
```
> Automated cherry pick of #3464

- package-lock.json
- package.json
Bump to version v6.0
```release-note
NONE
```
> Bump to version v6.0

- src/main/tray/tray.test.js
- src/main/views/loadingScreen.test.js
- src/main/views/loadingScreen.ts
Cherry pick of #3477 on release-5.13.
```release-note
NONE
```
> Automated cherry pick of #3477

- i18n/en.json
- src/main/views/webContentEvents.test.js
- src/main/views/webContentEvents.ts
Cherry pick of #3476 on release-5.13.
```release-note
NONE
```
> Automated cherry pick of #3476
